### ISSUE TITLE
Test Drive/standalone GoCD fails to start when commit GPG signing is enabled at system/user level

### ISSUE THREAD

**Issue by outsideris** [gocd/gocd#10086]
##### Issue Type

- Bug Report

##### Summary
When I run Test Drive 21.4.0 (`gocd-21.4.0-13469-1477-osx`) which is current stable version, GoCD server couldn't be started.

##### Environment

On my macbook

###### Basic environment details

* Go Version: `21.4.0`
* JAVA Version: `openjdk 15.0.4`
* OS: `macOS 11.6`

##### Steps to Reproduce

1. Run `curl -fsSL 'https://www.gocd.org/test-drive-gocd/try.sh' | bash -s 'https://download.gocd.org/test-drive/installers/21.4.0/13469/gocd-21.4.0-13469-1477-osx.zip'` 
2. Server hung with `Wating for the GoCD server to finish initializing.....`

##### Expected Results
GoCD Server launched

##### Actual Results
Starting server failed.

##### Log snippets
```
org.eclipse.jgit.api.errors.ServiceUnavailableException: Signing service is not available
	at org.eclipse.jgit.api.CommitCommand.sign(CommitCommand.java:290)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:247)
	at com.thoughtworks.go.service.ConfigRepository$1.run(ConfigRepository.java:125)
	at com.thoughtworks.go.util.VoidThrowingFn.call(VoidThrowingFn.java:25)
	at com.thoughtworks.go.service.ConfigRepository.doLocked(ConfigRepository.java:136)
	at com.thoughtworks.go.service.ConfigRepository.checkin(ConfigRepository.java:121)
	at com.thoughtworks.go.config.FullConfigSaveFlow.checkinToConfigRepo(FullConfigSaveFlow.java:79)
	at com.thoughtworks.go.config.FullConfigSaveNormalFlow.execute(FullConfigSaveNormalFlow.java:67)
	at com.thoughtworks.go.config.GoConfigMigrator.upgradeConfigFile(GoConfigMigrator.java:110)
	at com.thoughtworks.go.config.GoConfigMigrator.upgrade(GoConfigMigrator.java:96)
	at com.thoughtworks.go.config.GoConfigMigrator.migrate(GoConfigMigrator.java:87)
	at com.thoughtworks.go.config.CachedGoConfig.upgradeConfig(CachedGoConfig.java:149)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:112)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1067)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:996)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:517)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:157)
	at com.thoughtworks.go.server.Jetty9Server.startHandlers(Jetty9Server.java:179)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:129)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:62)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:54)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.thoughtworks.gocd.Boot.run(Boot.java:90)
	at com.thoughtworks.gocd.Boot.main(Boot.java:56)
2022-01-14 20:54:16,934 WARN  [main] GoConfigMigrator:98 - Error upgrading config file, trying to upgrade using the versioned config file.
2022-01-14 20:54:16,935 WARN  [main] ConfigRepository:196 - [CONFIG REPOSITORY] No head exists in the config repository.
2022-01-14 20:54:16,935 WARN  [main] GoConfigMigrator:116 - There is no versioned configuration to fallback for migration.
2022-01-14 20:54:16,944 ERROR [main] GoConfigMigrator:64 - There are errors in the Cruise config file.  Please read the error message and correct the errors.
Once fixed, please restart GoCD.
Error: Signing service is not available
```

**Comment by chadlwilson** [comment]
Ahh yes - thanks for reporting this. I think this is the same problem that can happen with local development work on GoCD too, but it hadn't occurred to me that it'd be an issue with test drive, or running GoCD.

The root of the problem is most likely that you have GPG signing of commits enabled globally in your Git configuration. (`commit.gpgsign=true`). Is that right?

GoCD uses git internally to maintain versions of its configuration to allow for rollbacks, history etc. JGit (java git implementation) picks up global Git config by default and tries to use it, but is not configured to know how to sign its own commits internally (the "Signing service" it refers to).

What is probably needed is ensure that the internal git config repo disables commit signing. I have contemplated this before, but never been sure if appropriate.

In the meantime, as a workaround for now, you might be able to get past this locally by overriding it for GoCD's internal repo in the folder where the test driver server is unpacked to. Would you be willing to try
```shell
cd gocd-21.4.0-13469-1477/data/server/db/config.git
git config commit.gpgsign false
cd -
gocd-21.4.0-13469-1477/run-gocd
```

if you're just looking to play around as a once-off, it may also work to turn it off globally first with `git config --global commit.gpgsign false`, start gocd, and then turn it back on globally. If I recall correctly GoCD/jGit only reads this once at startup.

**Comment by outsideris** [comment]
> The root of the problem is most likely that you have GPG signing of commits enabled globally in your Git configuration. (commit.gpgsign=true). Is that right?

Yesss! I've understood what happened. Thank you for your kind explanation.

**Comment by chadlwilson** [comment]
> Yesss! I've understood what happened. Thank you for your kind explanation.

Thanks for confirming, I have a fix to the underlying problem to avoid this issue in future, hopefully can be sorted out for the next release.

**Comment by outsideris** [comment]
Anyway, the workaround works for me. Thank you.
