### ISSUE TITLE
plugins update failed on agent

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#1015]
happened once. the next update worked.

```
2015-04-09 01:37:24,949 [main     ] WARN  thoughtworks.go.agent.AgentPluginsInitializer:66 - could not extract plugin zip
java.io.IOException: Unable to delete directory plugins.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1541)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at com.thoughtworks.go.agent.AgentPluginsInitializer.onApplicationEvent(AgentPluginsInitializer.java:60)
	at com.thoughtworks.go.agent.AgentPluginsInitializer.onApplicationEvent(AgentPluginsInitializer.java:35)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.thoughtworks.go.agent.AgentMain.main(AgentMain.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
```

---
Edit: happened again. saw this error on agent when pipeline ran. restart works.

```
02:23:51.903 [go] Start to execute task: Plugin with ID: script-executor.
02:23:51.903 Error: Associated plugin 'script-executor' not found. Please contact the Go admin to install the plugin.
02:23:51.950 [go] Current job status: failed.
```

**Comment by arikagoyal** [comment]
Not been reproducible so far. Closing this issue for now

**Comment by fabriciocduarte** [comment]
This just came up for me. Go Server version 16.3. Plug-in is installed and listed in go admin page under plug-ins. Pipeline fails everytime with error message: 

`Error: Associated plugin 'script-executor' not found`

**Comment by fabriciocduarte** [comment]
**More information:**
-OS: Windows 2008 R2 Server
-Go Server version: 16.3

**Workaround solution: restart go server windows service.**
