### ISSUE TITLE
gocd-issue

### ISSUE THREAD

**Issue by Veenareddygaddam19** [gocd/gocd#10289]
Hi , I'm deploying a gocd plotform on my kubernetes cluster.The deployment is successfull and is running fine but when i build the job its throwing an gradle dependency error
Exception in thread "main" java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:288)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)

I'm very new to kubernetes. Can anyone help me how to resolve this?

**Comment by chadlwilson** [comment]
It doesn't look like this is a GoCD issue if the stack trace comes from running a build within Gradle, however it's a bit difficult to tell from what you have included.

If you can include the fuller stack trace which shows what Gradle is doing at the time, and which "host" is unreachable, I might be able to point you in the right direction, however.

I'm not sure where your Kubernetes cluster is deployed, but it's possible your Gradle build is trying to pull dependencies from the internet, and the networking rules for yourr cluster don't allow it. Or that the Gradle build is pointing to some special internal server that your cluster doesn't have network level access to.

**Comment by chadlwilson** [comment]
Hiya - going to close this now, as it seems to be a networking issue with your environment rather than a GoCD issue. Let me know if you you can supply any more information as above.
