### ISSUE TITLE
[performance] server freezes when put under load

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#1034]
bunch of:
```
2015-04-16 04:49:07,656  WARN [qtp749610025-36-acceptor-0@69a0f3fb-ServerConnector@115fae6{SSL-HTTP/1.1}{0.0.0.0:8154}] ServerConnector:505 - 
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.$$YJP$$accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept0(ServerSocketChannelImpl.java)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:226)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:377)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:500)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:722)
```

**Comment by srinivasupadhya** [comment]
netstat -a | grep blrstdgoprf02.thoughtw:8153 | wc -l
3088
tcp      105      0 xxx.thoughtw:8153 yyy.thought:38153 CLOSE_WAIT

**Comment by srinivasupadhya** [comment]
This went away after we turned off the yourkit agent on server. (ulimit is set to 1024 & could be causing issues) there are still a few requests timing out but the numbers are looking similar to 14.1 - 14.3.

**Comment by ketan** [comment]
@jyotisingh - is this resolved?

**Comment by jyotisingh** [comment]
This did not show up anytime while running performance tests with jetty 9.2.11, is I guess we can call it resolved.
