### ISSUE TITLE
Issue in shine backgroundstageloader

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#111]
## Description
When multiple stages complete at the same time, shine loader throws up below exception. This however does not effect Go. Need to find a way around this

```
2013-10-14 01:17:50,061 ERROR [291607518@qtp-763030760-239] GRDDLTransformer:39 - Could not convert to a graph. The document was:

<?xml version="1.0" encoding="UTF-8"?>

<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:java="http://xml.apache.org/xalan/java" xmlns:cruise="http://studios.thoughtworks.com/ontologies/2009/12/07-cruise#">urn:x-go.studios.thoughtworks.com:job-id:FsaComplianceDb-ToSIT:8:generateSQLReport:1:generateSQLReport<cruise:jobResult><cruise:PassedResult/></cruise:jobResult>Completed<cruise:hasArtifacts><cruise:Artifacts rdf:about="urn:uuid:7d382f42-7188-40ce-b0c3-4b4053929512"><cruise:artifactsBaseURL rdf:datatype="http://www.w3.org/2001/XMLSchema#string">https://localhost:8154/go/files/FsaComplianceDb-ToSIT/8/generateSQLReport/1/generateSQLReport</cruise:artifactsBaseURL><cruise:pathFromArtifactRoot rdf:datatype="http://www.w3.org/2001/XMLSchema#string">pipelines\FsaComplianceDb-ToSIT\8\generateSQLReport\1\generateSQLReport</cruise:pathFromArtifactRoot><cruise:hasArtifact><cruise:Artifact rdf:about="urn:uuid:c15bc9e2-084a-4962-93ce-485da12b070a"><cruise:artifactPath rdf:datatype="http://www.w3.org/2001/XMLSchema#string"/><cruise:artifactType rdf:datatype="http://www.w3.org/2001/XMLSchema#string">file</cruise:artifactType></cruise:Artifact></cruise:hasArtifact></cruise:Artifacts></cruise:hasArtifacts></rdf:RDF>

com.thoughtworks.studios.shine.ShineRuntimeException: Could not create graph from XML RDF!

at com.thoughtworks.studios.shine.semweb.sesame.SesameGraph.addTriplesFromRDFXMLAbbrev(SesameGraph.java:270)

at com.thoughtworks.studios.shine.semweb.grddl.GRDDLTransformer.transform(GRDDLTransformer.java:36)

at com.thoughtworks.studios.shine.cruise.CruiseGRDDLResourceRDFizer.importFile(CruiseGRDDLResourceRDFizer.java:36)

at com.thoughtworks.studios.shine.cruise.CruiseGRDDLResourceRDFizer.importDocumentUsingGRDDL(CruiseGRDDLResourceRDFizer.java:54)

at com.thoughtworks.studios.shine.cruise.CruiseGRDDLResourceRDFizer.importURIUsingGRDDL(CruiseGRDDLResourceRDFizer.java:45)

at com.thoughtworks.studios.shine.cruise.stage.details.JobResourceImporter.importJob(JobResourceImporter.java:52)

at com.thoughtworks.studios.shine.cruise.stage.details.StageResourceImporter.importJobs(StageResourceImporter.java:95)

at com.thoughtworks.studios.shine.cruise.stage.details.StageResourceImporter.load(StageResourceImporter.java:55)

at com.thoughtworks.studios.shine.cruise.BackgroundStageLoader.handle(BackgroundStageLoader.java:55)

at com.thoughtworks.studios.shine.cruise.stage.feeds.StageAtomFeedsReader.readFromLatest(StageAtomFeedsReader.java:35)

at com.thoughtworks.studios.shine.cruise.BackgroundStageLoader.load(BackgroundStageLoader.java:45)
```

*Old Tracking ID : 12751*

**Comment by arvindsv** [comment]
@ketan: Can this be closed, now that #2201 is in?
