### ISSUE TITLE
Starting agent with GO_SERVER_PORT=80 gives bad URL

### ISSUE THREAD

**Issue by tomas-forsman** [gocd/gocd#1114]
Trying to start the agent with environment variable GO_SERVER_PORT=80 produces URL with missing slash between hostname and context path.

Using port that is not 80 produces url https://my.domain.net:8080/go/admin/agent-launcher.jar while using port 80 produces https://my.domain.netgo/admin/agent-launcher.jar

```
ERROR com.thoughtworks.go.agent.launcher.ServerCall  - Couldn't access Go Server with base url: https://my.domain.netgo/admin/agent-launcher.jar: java.net.UnknownHostException: my.domain.netgo
java.lang.Exception: Couldn't access Go Server with base url: https://my.domain.netgo/admin/agent-launcher.jar: java.net.UnknownHostException: my.domain.netgo
        at com.thoughtworks.go.agent.launcher.ServerCall.invoke(ServerCall.java:70)
        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.headers(ServerBinaryDownloader.java:128)
        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:105)
        at com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:78)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:74)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:306)
        at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.net.UnknownHostException: my.domain.netgo
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
        at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:451)
        at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:140)
        at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:81)
        at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$1.doit(ControllerThreadSocketFactory.java:90)
        at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$SocketTask.run(ControllerThreadSocketFactory.java:157)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by wojtek-oledzki** [comment]
When I use port 80 it get's translated to `https://...:8144` :(
My gocd server is running behind AWS loadbalancer (with single instance) on port 80, and I would like to use that loadbalancer DNS on port 80 from my agents.

```
[Fri Jun 12 15:24:52 UTC 2015] Starting Go Agent Bootstrapper with command: /usr/lib/jvm/java-7-oracle/jre/bin/java -jar "/usr/share/go-agent-1/agent-bootstrapper.jar" managemen-gocdserv-1gdl4ot8g8lkf-1242094387.eu-west-1.elb.amazonaws.com 80
...
Launching Agent with command: /usr/lib/jvm/java-7-oracle/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Dagent.launcher.version=15.1.0 -Dagent.plugins.md5=20eaad1f2e9f649dfbff3dbdc5b4afae -Dagent.binary.md5=WrfXrfz5zYtW7MeCdAotvg== -Dagent.launcher.md5=2SJZgbpIe30D+DTnq691bA== -jar agent.jar https://managemen-gocdserv-1gdl4ot8g8lkf-1242094387.eu-west-1.elb.amazonaws.com:8154/go/
```

**Comment by arvindsv** [comment]
Some changes in #2236 changes startup parameters. Closing this. Can re-open once that is done, if needed.
