### ISSUE TITLE
java.net.NoRouteToHostException: No route to host

### ISSUE THREAD

**Issue by xlw712** [gocd/gocd#11325]
I'am deployment k8s(1.18.20) exec pipeline task , but agent status pending. take agent pod log , below 
```
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Standard Edition 64-bit 3.5.50
wrapper  |   Copyright (C) 1999-2022 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |   Licensed to ThoughtWorks for GoCD Agent
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | [Wed Feb 22 09:22:23 GMT 2023] Starting process:
jvm 1    | [Wed Feb 22 09:22:23 GMT 2023]   Working directory    : /go
jvm 1    | [Wed Feb 22 09:22:23 GMT 2023]   Application arguments: [-serverUrl, http://gocd-server:8153/go]
jvm 1    | [Wed Feb 22 09:22:23 GMT 2023]            GoCD Version: 22.3.0-15301
jvm 1    | [Wed Feb 22 09:22:23 GMT 2023]            Java Version: 17.0.5
jvm 1    | [Wed Feb 22 09:22:23 GMT 2023]        Operating System: Linux(3.10.0-693.2.2.el7.x86_64)
jvm 1    | Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:onejar:lib/agent-bootstrapper-22.3.0-15301-classes.jar!/config/agent-bootstrapper-logback.xml'.
jvm 1    | 2023-02-22 09:22:23,591 INFO  [WrapperJarAppMain] DefaultAgentLauncherCreatorImpl:67 - Attempting to load com.thoughtworks.go.agent.launcher.AgentLauncherImpl as specified by manifest key Go-Agent-Launcher-Class
jvm 1    | 2023-02-22 09:22:23,614 INFO  [WrapperJarAppMain] ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLauncher using java.net.URLClassLoader
jvm 1    | SLF4J: Class path contains multiple SLF4J bindings.
jvm 1    | SLF4J: Found binding in [jar:onejar:lib/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: Found binding in [jar:file:/go/data/deps-19c8ad3597c6585e-agent-launcher.jar/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
jvm 1    | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
jvm 1    | 2023-02-22 09:22:23,638 INFO  [WrapperJarAppMain] AgentBootstrapper:74 - Attempting create and start launcher...
jvm 1    | 2023-02-22 09:22:23,642 INFO  [WrapperJarAppMain] ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLaunchDescriptor using java.net.URLClassLoader
jvm 1    | Could not find file `config/agent-launcher-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:file:/go/data/deps-19c8ad3597c6585e-agent-launcher.jar/agent-launcher-22.3.0-15301-classes.jar!/config/agent-launcher-logback.xml'.
jvm 1    | 2023-02-22 09:22:23,697 INFO  [TouchLoopThread-1] Lockfile:103 - Using lock file: /go/.agent-bootstrapper.running
jvm 1    | 2023-02-22 09:22:27,022 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:22:27,022 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:22:30,027 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:22:30,027 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:22:33,033 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:22:33,033 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:22:36,041 ERROR [WrapperJarAppMain] ServerBinaryDownloader:88 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error:
jvm 1    | java.net.NoRouteToHostException: No route to host
jvm 1    | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
jvm 1    | 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
jvm 1    | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
jvm 1    | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
jvm 1    | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
jvm 1    | 	at java.base/java.net.Socket.connect(Unknown Source)
jvm 1    | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
jvm 1    | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
jvm 1    | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
jvm 1    | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
jvm 1    | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
jvm 1    | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
jvm 1    | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.fetchUpdateCheckHeaders(ServerBinaryDownloader.java:104)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:80)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:86)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
jvm 1    | 	at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:76)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:57)
jvm 1    | 	at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:57)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 	at com.thoughtworks.gocd.Boot.run(Boot.java:90)
jvm 1    | 	at com.thoughtworks.gocd.Boot.main(Boot.java:56)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 	at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | 2023-02-22 09:23:39,095 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:23:39,095 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:23:42,101 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:23:42,101 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:23:45,107 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:23:45,107 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:23:48,113 ERROR [WrapperJarAppMain] ServerBinaryDownloader:88 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error:
jvm 1    | java.net.NoRouteToHostException: No route to host
jvm 1    | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
jvm 1    | 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
jvm 1    | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
jvm 1    | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
jvm 1    | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
jvm 1    | 	at java.base/java.net.Socket.connect(Unknown Source)
jvm 1    | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
jvm 1    | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
jvm 1    | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
jvm 1    | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
jvm 1    | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
jvm 1    | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
jvm 1    | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.fetchUpdateCheckHeaders(ServerBinaryDownloader.java:104)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:80)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:86)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
jvm 1    | 	at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:76)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:57)
jvm 1    | 	at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:57)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 	at com.thoughtworks.gocd.Boot.run(Boot.java:90)
jvm 1    | 	at com.thoughtworks.gocd.Boot.main(Boot.java:56)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 	at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | 2023-02-22 09:24:51,123 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:24:51,123 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:24:54,129 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:24:54,129 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:24:57,135 INFO  [WrapperJarAppMain] RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://gocd-server:8153: No route to host
jvm 1    | 2023-02-22 09:24:57,135 INFO  [WrapperJarAppMain] RetryExec:113 - Retrying request to {}->http://gocd-server:8153
jvm 1    | 2023-02-22 09:25:00,141 ERROR [WrapperJarAppMain] ServerBinaryDownloader:88 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error:
jvm 1    | java.net.NoRouteToHostException: No route to host
jvm 1    | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
jvm 1    | 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
jvm 1    | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
jvm 1    | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
jvm 1    | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
jvm 1    | 	at java.base/java.net.Socket.connect(Unknown Source)
jvm 1    | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
jvm 1    | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
jvm 1    | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
jvm 1    | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
jvm 1    | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
jvm 1    | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
jvm 1    | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.fetchUpdateCheckHeaders(ServerBinaryDownloader.java:104)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:80)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:86)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
jvm 1    | 	at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:76)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:57)
jvm 1    | 	at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)

```
what should i do ?

**Comment by xlw712** [comment]
![image](https://user-images.githubusercontent.com/10722207/220584803-86295969-d9b9-4515-985e-52138687c8f7.png)
