### ISSUE TITLE
Getting error while building pipeline for kubernetes elastic agent

### ISSUE THREAD

**Issue by arcis123umair** [gocd/gocd#11332]
Issue Type

- Bug Report

Summary

Kubernetes elastic agent get connection refused error while building pipeline

Environment

* Go Version: gocd/gocd-server:v22.3..0

Kubernetes Elastic Agent Pod Configuration

apiVersion: v1
kind: Pod
metadata:
  name: gocd-pod1
  labels:
    app: gocd
spec:
  containers:
    - name: gocd-agent-container-1
      image: gocd-agent-img
      securityContext:
        privileged: true
      volumeMounts:
        - name: ssh-secrets
          readOnly: true
          mountPath: /home/go/.ssh
  volumes:
    - name: ssh-secrets
      secret: 
        defaultMode: 420
        secretName: gocd-agent-ssh
  imagePullSecrets:
    - my-image

Kubernetes Elastic Agent's Pod logs 

Running go-agent...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Standard Edition 64-bit 3.5.50
wrapper  |   Copyright (C) 1999-2022 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |   Licensed to ThoughtWorks for GoCD Agent
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | [Fri Feb 24 10:40:45 UTC 2023] Starting process:
jvm 1    | [Fri Feb 24 10:40:45 UTC 2023]   Working directory    : /go
jvm 1    | [Fri Feb 24 10:40:45 UTC 2023]   Application arguments: [-serverUrl, http://server:port/go]
jvm 1    | [Fri Feb 24 10:40:45 UTC 2023]            GoCD Version: 22.3.0-15301
jvm 1    | [Fri Feb 24 10:40:45 UTC 2023]            Java Version: 17.0.5
jvm 1    | [Fri Feb 24 10:40:45 UTC 2023]        Operating System: Linux(3.10.0-1160.81.1.el7.x86_64)
jvm 1    | Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:onejar:lib/agent-bootstrapper-22.3.0-15301-classes.jar!/config/agent-bootstrapper-logback.xml'.
jvm 1    | 2023-02-24 10:40:47,107 INFO  [WrapperJarAppMain] DefaultAgentLauncherCreatorImpl:67 - Attempting to load com.thoughtworks.go.agent.launcher.AgentLauncherImpl as specified by manifest key Go-Agent-Launcher-Class
jvm 1    | 2023-02-24 10:40:47,166 INFO  [WrapperJarAppMain] ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLauncher using java.net.URLClassLoader
jvm 1    | SLF4J: Class path contains multiple SLF4J bindings.
jvm 1    | SLF4J: Found binding in [jar:onejar:lib/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: Found binding in [jar:file:/go/data/deps-3f6039f9c4d7cb6f-agent-launcher.jar/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
jvm 1    | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
jvm 1    | 2023-02-24 10:40:47,237 INFO  [WrapperJarAppMain] AgentBootstrapper:74 - Attempting create and start launcher...
jvm 1    | 2023-02-24 10:40:47,247 INFO  [WrapperJarAppMain] ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLaunchDescriptor using java.net.URLClassLoader
jvm 1    | Could not find file `config/agent-launcher-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:file:/go/data/deps-3f6039f9c4d7cb6f-agent-launcher.jar/agent-launcher-22.3.0-15301-classes.jar!/config/agent-launcher-logback.xml'.
jvm 1    | 2023-02-24 10:40:47,403 INFO  [TouchLoopThread-1] Lockfile:103 - Using lock file: /go/.agent-bootstrapper.running
jvm 1    | 2023-02-24 10:40:48,319 ERROR [WrapperJarAppMain] ServerBinaryDownloader:88 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error:
jvm 1    | org.apache.http.conn.HttpHostConnectException: Connect to server:port [/server] failed: Connection refused
jvm 1    |      at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
jvm 1    |      at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
jvm 1    |      at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
jvm 1    |      at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
jvm 1    |      at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
jvm 1    |      at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
jvm 1    |      at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
jvm 1    |      at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
jvm 1    |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
jvm 1    |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
jvm 1    |      at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.fetchUpdateCheckHeaders(ServerBinaryDownloader.java:104)
jvm 1    |      at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:80)
jvm 1    |      at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:86)
jvm 1    |      at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
jvm 1    |      at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
jvm 1    |      at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
jvm 1    |      at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:76)
jvm 1    |      at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:57)
jvm 1    |      at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
jvm 1    |      at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:57)
jvm 1    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    |      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    |      at com.thoughtworks.gocd.Boot.run(Boot.java:90)
jvm 1    |      at com.thoughtworks.gocd.Boot.main(Boot.java:56)
jvm 1    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    |      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    |      at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
jvm 1    |      at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | Caused by: java.net.ConnectException: Connection refused
jvm 1    |      at java.base/sun.nio.ch.Net.pollConnect(Native Method)
jvm 1    |      at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
jvm 1    |      at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
jvm 1    |      at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
jvm 1    |      at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
jvm 1    |      at java.base/java.net.Socket.connect(Unknown Source)
jvm 1    |      at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
jvm 1    |      at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
jvm 1    |      ... 31 common frames omitted

**Comment by chadlwilson** [comment]
It looks like you have configured something incorrectly, your agent is trying to connect to `http://server:port/go` rather than your actual server.

Try going to Admin > Server Config and setting the URLs properly. If that doesn't work check what you have set in the Cluster Profile for "Go Server URL".

https://github.com/gocd/kubernetes-elastic-agents/blob/master/docs/configure_cluster_profile.md

**Comment by arcis123umair** [comment]
Hello Sir @chadlwilson 

I follow the instructions mention in the kubernetes elastic agent docs.
Here is my cluster configuration for k8s elastic agent
{
  "id" : "cluster1",
  "plugin_id" : "cd.go.contrib.elasticagent.kubernetes",
  "properties" : [ {
    "key" : "go_server_url",
    "value" : "http://ip:port/go"
  }, {
    "key" : "auto_register_timeout",
    "value" : "5"
  }, {
    "key" : "pending_pods_count",
    "value" : "10"
  }, {
    "key" : "kubernetes_cluster_url",
    "value" : "https://ip:port"
  }, {
    "key" : "namespace",
    "value" : "default"
  }, {
    "key" : "security_token",
    "encrypted_value" : "service-account-secret-token"
  }, {
    "key" : "kubernetes_cluster_ca_cert",
    "encrypted_value" : "cluster-ca-cert"
  } ]
}

**Comment by chadlwilson** [comment]
Your log file above says

```
jvm 1    | [Fri Feb 24 10:40:45 UTC 2023]   Application arguments: [-serverUrl, http://server:port/go]
```

I'm not sure if you _redacted_ the actual values from the actual log for privacy reasons, but either 
- the `go_server_url` or the values in https://docs.gocd.org/current/installation/configuring_server_details.html#configure-site-urls are not correct
- there is something in your Kubernetes cluster preventing the connection.
- if your agents are in a different namespace to the server, you will need to change the `go_server_url` to reflect the namespace as part of the hostname 

Create a test pod in the same namespace as the agents (looks like `default` from the above) and see if you can `curl` the server.
