### ISSUE TITLE
Could not fetch artifact (again)

### ISSUE THREAD

**Issue by bormotov** [gocd/gocd#1144]
Server Info
Go Server Version: 	15.1.0(1863-42e58c22aefd03)
JVM version: 	1.7.0_79
OS Information: 	Linux 3.19.7-200.fc21.x86_64

go-agent-15.1.0-1863-setup.exe on Windows 7, with bundled jre 1.7.0_09

====== server log  ======
2015-05-21 23:17:13,120  INFO [2042445103@qtp-1742546142-14] ArtifactsController:264 - [Artifact Download] Trying to resolve 'cruise-output/md5.checksum' for 'ICM-Pack/518/Package/1/Package'
2015-05-21 23:17:13,184  INFO [2042445103@qtp-1742546142-14] ArtifactsController:282 - [Artifact Download] Successfully resolved 'cruise-output/md5.checksum' for 'ICM-Pack/518/Package/1/Package'. It took: 63ms
2015-05-21 23:17:13,186  INFO [2042445103@qtp-1742546142-14] FileView:108 - [Artifact Download] About to download: /var/lib/go-server/artifacts/pipelines/ICM-Pack/518/Package/1/Package/cruise-output/md5.checksum. ShouldZip? = false
2015-05-21 23:17:13,191  INFO [2042445103@qtp-1742546142-14] FileView:114 - [Artifact Download] Finished downloading: /var/lib/go-server/artifacts/pipelines/ICM-Pack/518/Package/1/Package/cruise-output/md5.checksum. ShouldZip? = false. The time taken is: 4ms
2015-05-21 23:17:13,215  INFO [2042445103@qtp-1742546142-14] ArtifactsController:264 - [Artifact Download] Trying to resolve 'trunk/ICM-setup-0.15.04.exe' for 'ICM-Pack/518/Package/1/Package'
2015-05-21 23:17:13,218  INFO [2042445103@qtp-1742546142-14] ArtifactsController:282 - [Artifact Download] Successfully resolved 'trunk/ICM-setup-0.15.04.exe' for 'ICM-Pack/518/Package/1/Package'. It took: 2ms
2015-05-21 23:17:31,289  INFO [2042445103@qtp-1742546142-14] ArtifactsController:264 - [Artifact Download] Trying to resolve 'trunk/ICM-setup-0.15.04.exe' for 'ICM-Pack/518/Package/1/Package'
2015-05-21 23:17:31,292  INFO [2042445103@qtp-1742546142-14] ArtifactsController:282 - [Artifact Download] Successfully resolved 'trunk/ICM-setup-0.15.04.exe' for 'ICM-Pack/518/Package/1/Package'. It took: 2ms
2015-05-21 23:17:56,452  INFO [1874050317@qtp-1742546142-17] ArtifactsController:264 - [Artifact Download] Trying to resolve 'trunk/ICM-setup-0.15.04.exe' for 'ICM-Pack/518/Package/1/Package'
2015-05-21 23:17:56,455  INFO [1874050317@qtp-1742546142-17] ArtifactsController:282 - [Artifact Download] Successfully resolved 'trunk/ICM-setup-0.15.04.exe' for 'ICM-Pack/518/Package/1/Package'. It took: 1ms
2015-05-21 23:18:34,625  INFO [1874050317@qtp-1742546142-17] ArtifactsController:264 - [Artifact Download] Trying to resolve 'trunk/ICM-setup-0.15.04.exe' for 'ICM-Pack/518/Package/1/Package'
2015-05-21 23:18:34,628  INFO [1874050317@qtp-1742546142-17] ArtifactsController:282 - [Artifact Download] Successfully resolved 'trunk/ICM-setup-0.15.04.exe' for 'ICM-Pack/518/Package/1/Package'. It took: 2ms
2015-05-21 23:18:34,638  INFO [1874050317@qtp-1742546142-17] BuildRepositoryRemoteImpl:104 - [Agent [python, 192.168.109.232, 1c360ee1-fc68-46ba-ae8b-2ff486e29320, 3c84f136-1813-42aa-894f-02daa2c35c04]] is reporting result [Failed] for [Build [ICM-Test/508/Test-Install/1/Test-Install/8376]]
2015-05-21 23:18:34,680  INFO [1874050317@qtp-1742546142-17] BuildRepositoryRemoteImpl:104 - [Agent [python, 192.168.109.232, 1c360ee1-fc68-46ba-ae8b-2ff486e29320, 3c84f136-1813-42aa-894f-02daa2c35c04]] is reporting status [Completing] for [Build [ICM-Test/508/Test-Install/1/Test-Install/8376]]
2015-05-21 23:18:34,702  INFO [1874050317@qtp-1742546142-17] BuildRepositoryRemoteImpl:104 - [Agent [python, 192.168.109.232, 1c360ee1-fc68-46ba-ae8b-2ff486e29320, 3c84f136-1813-42aa-894f-02daa2c35c04]] is reporting status and result [Completed, Failed] for [Build [ICM-Test/508/Test-Install/1/Test-Install/8376]]
2015-05-21 23:18:34,773  INFO [1874050317@qtp-1742546142-17] Stage:218 - Stage is being completed by transition id: 39841
====== server log  ======

====== agent log  ======
2015-05-22 00:16:17,381 [loopThread] INFO  thoughtworks.go.util.HttpService:129 - Got back 200 from server
2015-05-22 00:16:17,382 [loopThread] INFO  thoughtworks.go.util.PerfTimer:53 - Performance: Downloading from url [https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/cruise-output/md5.checksum] took 82ms
2015-05-22 00:16:17,384 [loopThread] INFO  thoughtworks.go.domain.ChecksumFileHandler:58 - [Agent Fetch Artifact] Saved checksum property file [pipelines\ICM-Test\ICM-Pack_Package_Package_md5.checksum]
2015-05-22 00:16:17,411 [loopThread] INFO  thoughtworks.go.util.HttpService:129 - Got back 404 from server
2015-05-22 00:16:17,411 [loopThread] INFO  thoughtworks.go.util.PerfTimer:53 - Performance: Downloading from url [https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe] took 26ms
2015-05-22 00:16:17,411 [loopThread] WARN  thoughtworks.go.domain.DownloadAction:69 - Could not fetch artifact https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe. Pausing 18 seconds to retry. Error was : Unsuccessful response '404' from the server
2015-05-22 00:16:35,429 [loopThread] INFO  thoughtworks.go.util.HttpService:129 - Got back 404 from server
2015-05-22 00:16:35,430 [loopThread] INFO  thoughtworks.go.util.PerfTimer:53 - Performance: Downloading from url [https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe] took 17ms
2015-05-22 00:16:35,430 [loopThread] WARN  thoughtworks.go.domain.DownloadAction:69 - Could not fetch artifact https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe. Pausing 25 seconds to retry. Error was : Unsuccessful response '404' from the server
2015-05-22 00:17:00,451 [loopThread] INFO  thoughtworks.go.util.HttpService:129 - Got back 404 from server
2015-05-22 00:17:00,452 [loopThread] INFO  thoughtworks.go.util.PerfTimer:53 - Performance: Downloading from url [https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe] took 22ms
2015-05-22 00:17:00,452 [loopThread] WARN  thoughtworks.go.domain.DownloadAction:69 - Could not fetch artifact https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe. Pausing 38 seconds to retry. Error was : Unsuccessful response '404' from the server
2015-05-22 00:17:38,470 [loopThread] INFO  thoughtworks.go.util.HttpService:129 - Got back 404 from server
2015-05-22 00:17:38,470 [loopThread] INFO  thoughtworks.go.util.PerfTimer:53 - Performance: Downloading from url [https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe] took 18ms
2015-05-22 00:17:38,470 [loopThread] ERROR thoughtworks.go.domain.DownloadAction:57 - Giving up fetching resource 'https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe'. Tried 4 times and failed.
2015-05-22 00:17:38,471 [loopThread] ERROR thoughtworks.go.publishers.GoArtifactsManipulator:187 - Failed to save artifact [trunk/ICM-setup-0.15.04.exe] to []
java.lang.RuntimeException: Giving up fetching resource 'https://build.bregis.ru:8154/go/remoting/files/ICM-Pack/518/Package/1/Package/trunk/ICM-setup-0.15.04.exe'. Tried 4 times and failed.
	at com.thoughtworks.go.domain.DownloadAction.perform(DownloadAction.java:58)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.pullArtifact(FetchArtifactBuilder.java:73)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.downloadArtifact(FetchArtifactBuilder.java:64)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.fetch(FetchArtifactBuilder.java:59)
	at com.thoughtworks.go.publishers.GoArtifactsManipulator.fetch(GoArtifactsManipulator.java:183)
	at com.thoughtworks.go.work.DefaultGoPublisher.fetch(DefaultGoPublisher.java:77)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.build(FetchArtifactBuilder.java:54)
	at com.thoughtworks.go.domain.builder.Builder.build(Builder.java:51)
	at com.thoughtworks.go.remote.work.Builders.build(Builders.java:63)
	at com.thoughtworks.go.remote.work.BuildWork.execute(BuildWork.java:208)
	at com.thoughtworks.go.remote.work.BuildWork.buildJob(BuildWork.java:183)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:145)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
2015-05-22 00:17:38,471 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:101 - Agent [python, 192.168.109.232, 1c360ee1-fc68-46ba-ae8b-2ff486e29320] is reporting build result [Failed] to Go Server for Build [ICM-Test/508/Test-Install/1/Test-Install/8376]
2015-05-22 00:17:38,505 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:95 - Agent [python, 192.168.109.232, 1c360ee1-fc68-46ba-ae8b-2ff486e29320] is reporting status [Completing] to Go Server for Build [ICM-Test/508/Test-Install/1/Test-Install/8376]
2015-05-22 00:17:38,525 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:107 - Agent [python, 192.168.109.232, 1c360ee1-fc68-46ba-ae8b-2ff486e29320] is reporting build result [Failed] to Go Server for Build [ICM-Test/508/Test-Install/1/Test-Install/8376]
2015-05-22 00:17:38,974 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:90 - Stopping Transmission for Build [ICM-Test/508/Test-Install/1/Test-Install/8376]
====== agent log  ======

**Comment by bormotov** [comment]
oops, sorry - job configration problem: try to fetch resource with wrong name.
