### ISSUE TITLE
Can't get v23.1.0 agent to connect to server following installation

### ISSUE THREAD

**Issue by vernonr3** [gocd/gocd#11533]
##### Issue Type
Bug Report
##### Summary
v23.1.0 Docker Go Server installed and dashboard appears on http://localhost:8153/go
v23.1.0 go-agent for ubuntu 22.04 installed - but doesn't connect successfully to http://localhost:8153

###### Basic environment details
Go 23.1.0 (16079-21e78c998e1eb35d8d489c1d3e3e9813dc18233a)
Java 17.0.6
OS Linux 5.19.0-41-generic
Browser Firefox 112.02 (64 bit) Mozilla Snap for Ubuntu.

##### Steps to Reproduce

1. Install Docker v23.1.0 go-server container. Run it
2. download deb package v23.1.0 and install
3. Add config/agent-bootstrapper-logback.xml & config/agent-launcher-logback.xml from repository which appear to be missing from package. 
4. Configure wrapper-properties.conf with:
wrapper.app.parameter.100=-serverUrl
wrapper.app.parameter.101=http://localhost:8153/go
wrapper.app.parameter.102=-sslVerificationMode
wrapper.app.parameter.103=NONE
5. Copied auto register key from server config.xml into agent.auto.register.key in autoregister.properties file in /usr/share/go-agent/config
6. Start Agent sudo ./go-agent console.
7. Inspect logs when client doesn't appear in dashboard

##### Expected Results
Agent connects and appears in server dashboard

##### Actual Results
Agent never connects. Fails to appear

##### Log snippets
go-agent.log
```
2023-05-03 19:19:10,513 INFO  [scheduler-1] AgentHTTPClientController:121 - [Agent Loop] Registered, but need new agent cookie - about to get cookie from the server.
2023-05-03 19:19:10,515 ERROR [scheduler-1] RemotingClient:162 - Server responded to action `get_cookie` with: status[403 Forbidden], body[]
2023-05-03 19:19:10,516 ERROR [scheduler-1] AgentController:99 - [Agent Loop] Error occurred during loop: 
java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: The server returned status code 403. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
	at com.thoughtworks.go.agent.RemotingClient.post(RemotingClient.java:117)
	at com.thoughtworks.go.agent.RemotingClient.getCookie(RemotingClient.java:104)
	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveCookieIfNecessary(AgentHTTPClientController.java:122)
	at com.thoughtworks.go.agent.AgentHTTPClientController.tryDoWork(AgentHTTPClientController.java:115)
	at com.thoughtworks.go.agent.AgentController.performWork(AgentController.java:89)
	at com.thoughtworks.go.agent.AgentWorkRetrievalScheduler.run(AgentWorkRetrievalScheduler.java:60)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.client.ClientProtocolException: The server returned status code 403. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
	at com.thoughtworks.go.agent.RemotingClient.validateResponse(RemotingClient.java:140)
	at com.thoughtworks.go.agent.RemotingClient.post(RemotingClient.java:113)
	... 13 common frames omitted
2023-05-03 19:19:12,228 ERROR [scheduler-2] RemotingClient:162 - Server responded to action `ping` with: status[403 Forbidden], body[]
2023-05-03 19:19:12,229 ERROR [scheduler-2] AgentHTTPClientController:102 - Error occurred when agent tried to ping server: 
java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: The server returned status code 403. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
	at com.thoughtworks.go.agent.RemotingClient.post(RemotingClient.java:117)
	at com.thoughtworks.go.agent.RemotingClient.ping(RemotingClient.java:73)
	at com.thoughtworks.go.agent.AgentHTTPClientController.ping(AgentHTTPClientController.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.client.ClientProtocolException: The server returned status code 403. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
	at com.thoughtworks.go.agent.RemotingClient.validateResponse(RemotingClient.java:140)
	at com.thoughtworks.go.agent.RemotingClient.post(RemotingClient.java:113)
	... 14 common frames omitted


```
-->

**Comment by vernonr3** [comment]
Fixed it. If an install/launch fails for some reason it is likely to leave behind a guid.txt and token in /var/lib/go-agent/config. These need to be deleted.
