### ISSUE TITLE
Login fails with 500 error on invalid LDAP configuration

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1186]
On Experimental *release15.2.0-2019 (2358016d368f9069c48c8c6800dde93874f1cf04)*
Related to #851 (edit: might not be)

Steps to reproduce

* Admin -> Server Settings
* Enter an invalid LDAP configuration (fuzz the url)
* Save

Login with any username password

Stare with horror at

HTTP ERROR 500

Problem accessing /go/api/support. Reason:

    Server Error

Caused by:

```java
java.lang.RuntimeException: Invalid or empty ldap config, Error creating DefaultSpringSecurityContextSource
	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:40)
	at com.thoughtworks.go.server.security.LdapContextFactory.initializeDelegator(LdapContextFactory.java:68)
	at com.thoughtworks.go.server.security.LdapContextFactory.delegator(LdapContextFactory.java:50)
	at com.thoughtworks.go.server.security.LdapContextFactory.getReadOnlyContext(LdapContextFactory.java:81)
	at org.springframework.ldap.core.LdapTemplate.executeReadOnly(LdapTemplate.java:770)
	at org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForSingleEntry(SpringSecurityLdapTemplate.java:190)
	at org.springframework.security.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:118)
```

Expected to not login and display error message on the login screen.

**Comment by arvindsv** [comment]
Should fix [this](https://github.com/gocd/gocd/issues/900) too, when this is fixed?

**Comment by zabil** [comment]
This issue also exists on supported release14.4.0-1356 (86064ef5ee28e0d0d12911f46fd603d15246fdd5)

**Comment by chopraapooja** [comment]
Picking up for QA

**Comment by rajiesh** [comment]
This issue verified on 15.3.0-2559 and working as expected. Exception is handled and user friendly message shown on browser rather than the entire stack trace.

This issue only addressed the exception handling, does not address #900
