### ISSUE TITLE
GoCD agent on Java 20 can't talk to server on Java 17 - Exception parsing modifiedTime

### ISSUE THREAD

**Issue by jprogin** [gocd/gocd#11969]
##### Issue Type

- Bug Report

##### Summary

Hi team, 
I have recently updated my GoCD-Agent docker image using the latest softwares version and since then I have the problem that the GoCD-Agent can't parse the *modifiedTime* Git field and causes an exception. It is running into an Arch Linux Docker container (source below).

##### Environment

The GoCD server is running into a Docker container hosted on a QNAP NAS.

The GoCD-Agent causing the problem is running into a new Docker container hosted on a Windows 11 computer. However, a previous version of the Docker image of the GoCD-Agent runs without problem.

###### Basic environment details

* Go Version: `23.3.0 (16991-f38981e8aa684d63ac96f517996cd888eff37640)`
* JAVA Version: `17.0.8`
* OS: `Linux 5.10.60-qnap`

###### Additional Environment Details

_Dockerfile_ used to build the agent container image:

```
FROM archlinux:base-devel-20230723.0.166908

RUN pacman-key --init \
    && echo NoExtract = user/include/* >> /etc/pacman.conf \
    && echo NoExtract = user/share/* >> /etc/pacman.conf \
    && echo NoExtract = user/lib/*.a >> /etc/pacman.conf \
    && echo NoExtract = user/lib/libLLVM* >> /etc/pacman.conf \
    && echo NoExtract = user/lib/libgphobos* >> /etc/pacman.conf \
    && pacman -Syyu --noconfirm \
    && pacman -S --noconfirm \
        qt5-base \
        ffmpeg \
        glew \
        git \
        unzip \
        wget \
        eigen \
        hdf5 \
        libjpeg \
        libjpeg-turbo \
        libpng \
        libtiff \
        openssl \
        poco \
        freetype2 \
        pugixml \
        vtk \
        opencv \
        embree \
        libgit2 \
        jsoncpp \
        openmpi \
        fmt \
        vi \
        cmake \
        zip \
        go \
        gcc \
        gdb \
        gtest \
        jre-openjdk \
        extra/nodejs-lts-gallium \
        yarn \
        asciidoctor \
        extra/ansible-core \
        libpng \
        libjpeg-turbo \
        python-pip \
    && pacman --noconfirm -Sc \
    && rm -rf /var/cache/pacman/pkg

RUN yarn global add @quasar/cli node-gyp

RUN wget -O /tmp/go-agent.zip https://download.gocd.org/binaries/23.3.0-16991/generic/go-agent-23.3.0-16991.zip \
    && unzip -d /opt /tmp/go-agent.zip \
    && mv /opt/go-agent* /opt/go-agent \
    && rm /tmp/go-agent.zip \
    && sed -i "/#wrapper.lang=en_US/s/^#//g" /opt/go-agent/wrapper-config/wrapper.conf \
    && sed -i 's/localhost/gocd-server.local/g' /opt/go-agent/wrapper-config/wrapper-properties.conf

COPY entry.sh /entry.sh

CMD [ "/entry.sh" ]
```

The _entry.sh_ file content:

```
#!/bin/sh

rm -f /opt/go-agent/.agent-bootstrapper.running
/opt/go-agent/bin/go-agent console
```

##### Steps to Reproduce

1. Build the docker agent image from above source (replace the _gocd-server.local_)
2. Start the agent container (volumes on _/opt/go-agent/pipelines_, _/opt/go-agent/config_ and _/root/.ssh_ are mounted in my case)
3. Assign a pipeline with a Git material on the agent
4. Start a job

##### Actual Results

The agent cannot start the job and produces the logs below

##### Possible Fix

No workaround found until now:

* tried to set *LANG* variable to *en_US* in the container
* tried to force Java locale properties with _-Duser.country=US_ and _-Duser.language=en_

##### Log snippets

These logs are extracted from the _/opt/go-agent/logs/go-agent.log_:

```
2023-09-08 09:05:49,895 ERROR [scheduler-1] AgentController:99 - [Agent Loop] Error occurred during loop:
com.google.gson.JsonSyntaxException: Failed parsing 'Sep 2, 2023, 11:09:23 AM' as Date; at path $.assignment.materialRevisions.revisions[0].modifications[0].modifiedTime
        at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:90)
        at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:75)
        at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:46)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:299)
        at com.thoughtworks.go.remote.adapter.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:258)
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204)
        at com.google.gson.Gson.fromJson(Gson.java:1227)
        at com.google.gson.Gson.fromJson(Gson.java:1137)
        at com.google.gson.Gson.fromJson(Gson.java:1047)
        at com.google.gson.Gson.fromJson(Gson.java:982)
        at com.thoughtworks.go.agent.RemotingClient.getWork(RemotingClient.java:77)
        at com.thoughtworks.go.agent.AgentHTTPClientController.doWork(AgentHTTPClientController.java:133)
        at com.thoughtworks.go.agent.AgentHTTPClientController.tryDoWork(AgentHTTPClientController.java:116)
        at com.thoughtworks.go.agent.AgentController.performWork(AgentController.java:89)
        at com.thoughtworks.go.agent.AgentWorkRetrievalScheduler.run(AgentWorkRetrievalScheduler.java:60)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.text.ParseException: Failed to parse date ["Sep 2, 2023, 11:09:23 AM"]: Invalid number: Sep
        at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:279)
        at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:88)
        ... 43 common frames omitted
Caused by: java.lang.NumberFormatException: Invalid number: Sep
        at com.google.gson.internal.bind.util.ISO8601Utils.parseInt(ISO8601Utils.java:316)
        at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:133)
        ... 44 common frames omitted
...
```

**Comment by jprogin** [comment]
### Investigation
By remote debugging the GoCD-Agent in the docker container, I have observed that the **DateTypeAdapter.deserializeToDate** method tries to parse the string with a list of date formats. 

It looks that the format **MMM d, y, h:mm:ss a** is in the list and should be able to parse the date. But the pattern contains an hidden character, the _NNBSP_, between the **ss** and the **a**, instead of the normal white space. If I replace the pattern character with a white space, the date can be parsed.

Googling around this character and **SimpleDateFormat** gave me this result: https://bugs.openjdk.org/browse/JDK-8304925

And that's my situation: the GoCD server run on Java 17 and the agent on Java 20.02.

Any chance to find a fix in GoCD?

**Comment by jprogin** [comment]
### Solution

As announced previously, the problem appeared because the GoCD server run on Java 17 and the GoCD agent on Java 20.

The solution for me was to downgrade the Java version of the agent, by adding the following lines in the _Dockerfile_:

```
RUN pacman -Syyu --noconfirm \
    && pacman -R --noconfirm jre-openjdk jre-openjdk-headless \
    && pacman -S --noconfirm jre17-openjdk \
    && pacman -Sc --noconfirm \
    && rm -rf /var/cache/pacman/pkg
```

**Comment by chadlwilson** [comment]
Thanks for the digging, that's super helpful and is broadly what I was expecting the issue to be (aside from the root cause being a Java change).

Note that Java 20 is neither validated nor supported. GoCD is not tested on non-LTS versions of Java any longer.

But probably this whole serialisation approach should not be locale dependent or indeterministic in a way that this issue exposes, so that should probably be addressed with use of ISO8601 formats.
