### ISSUE TITLE
Agent has no cookie set / AgentNoCookieSetException after updating GUID

### ISSUE THREAD

**Issue by MassiveHiggsField** [gocd/gocd#1233]
GO-Server: 15.1.0
GO-Agent: 15.1.0

Our setup is a little bit weird, but it works something like this:
1. Pipelines:
   - Deploy-To-Test
   - Deploy-Fix-To-Stage
   - Deploy-Fix-To-Live
   - Move-From-Test-To-Stage
   - Move-From-Stage-To-Live
   - Move-From-Live-To-Silent
2. Agents:
   - Agent-Test
   - Agent-Stage
   - Agent-Live
   - Agent-Silent
3. Environments:
   - Env-Test (Deploy-To-Test, Move-From-Test-To-Stage; Agent-Test)
   - Env-Stage (Deploy-Fix-To-Stage, Move-From-Stage-To-Live, Agent-Stage)
   - Env-Live (Deploy-Fix-To-Live, Move-From-Stage-To-Live; Agent-Live)
   - Env-Silent (Agent-Silent)

The workflow is as follows:
1. Install Agent-Test on a new vm
2. Run Deploy-To-Test
3. Then we get an OK from our client on this system
4. Run Move-From-Test-To-Stage (basically just updates the guid.txt with the GUID for Agent-Stage and changes the hostname to "Agent-Stage")
5. Our client now gets an OK for this system from their clients for the new version
6. Run Move-From-Stage-To-Live (same as before)
7. System runs for a period of time
8. Run Move-From-Live-To-Silent when it is no longer needed

So it updates the guid.txt between every move and restarts the go-agent. Most of the time, this works, but in ~3/10 runs, the agent doesn't come back up and i get these errors:

```
2015-06-16 14:07:22,458 [loopThread] INFO  thoughtworks.go.agent.AgentController:152 - About to get cookie from the server.
2015-06-16 14:07:22,467 [loopThread] ERROR thoughtworks.go.agent.AgentController:145 - [Agent Loop] Error occurred during loop: 
org.springframework.remoting.RemoteAccessException: Could not deserialize result from HTTP invoker remote service [https://example.com/go/remoting/remoteBuildRepository]; nested exception is java.lang.ClassNotFoundException: org.hibernate.exception.DataException
    at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:208)

2015-06-16 14:07:22,964 [pingThread] ERROR thoughtworks.go.agent.AgentController:116 - Error occurred when agent tried to ping server: 
org.springframework.remoting.RemoteAccessException: Agent [Agent [Agent-Stage, 192.168.124.202, 70s98f52-c0h3-4r32-9b88-dw435SERVRwgasdfq3, null]] has no cookie set; nested exception is com.thoughtworks.go.server.service.AgentNoCookieSetException: Agent [Agent [Agent-Stage, 192.168.124.202, 70s98f52-c0h3-4r32-9b88-dw435SERVRwgasdfq3, null]] has no cookie set
    at com.thoughtworks.go.remote.BuildRepositoryRemoteImpl.wrappedException(BuildRepositoryRemoteImpl.java:125)
```

Every time this happens, my only solution so far was to completely remove the config directory, restart the client so it generates a new one and then updating our repository with the new guid. But since normally our client starts the pipelines via our custom backend through the api and cannot interfere when the agent doesn't come back up, this is not really what we want. 

So to recap, problem occurs while trying to update the GUID from a fixed set of GUIDs and restarting the agent. I don't see a better way to change the workflow to meet our requirements, so is there even a right way to update the GUID on an agent so after the restarts it registers as another agent?

Or maybe the workflow is bs and there is a better way. Our requirements are basically as follows:
- everytime we start a cycle, we want to start with a freshly installed agent, this agent gets installed directly by us
- the freshly installed has to run through four tstages; test, stage, live and silent
- there can be more than one cycle running at any given time, but never in the same stage (although we might have a future requirement to change that, so for example there could be more than one "Agent-Test", but that is not decided yet)
- our client can initiate moves/deploys through our custom backend

I've thought about more like a "one agent per cycle" approach, but i can't think of a way to control which pipeline should run on which agent dynamically. It always fails with this scenario:
1. Develop software version 1.1
2. Install new agent with software v1.1, no fix guid, enable agent manually in the backend
3. Update environments Env-\* to use this agent
4. Move agent via Move-From-Test-To-Stage
5. Now developing for the next release has finished, v1.2
6. Install new agent with software v1.2, no fix guid, enable agent manually in the backend
7. Update environments Env-\* to use this agent....

Now i run into problems, the agent with v1.1 is configured for every environment and is still running in stage. So for now, i can only safely update the Env-Test. But that would mean, that when it comes to moving the new agent with v1.2 to stage, again i have to update it manually and our client cannot move the agent with our custom backend (which basically just triggers the pipeline). Maybe there is a way to do this via the go api, so everytime after a Move-\* pipeline is run, a certain environment gets updated or maybe there is a possibility to force a pipeline to run on a given agent via the api. 

Sorry for the long text, it is a little hard to describe. Any advice appreciated.

**Comment by apsey** [comment]
I am having a similar problem, not the same use case but the same symptom:

```
2016-10-27 20:01:21,624 [pingThread] ERROR thoughtworks.go.agent.AgentController:161 - Error occurred when agent tried to ping server:
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://goserver/go/remoting/remoteBuildRepository]; nested exception is org.apache.http.NoHttpResponseException: Did not receive successful HTTP response: status code = 403, status message = [Access Denied]
       	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:212)
       	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:145)
       	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
       	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
       	at com.sun.proxy.$Proxy6.ping(Unknown Source)
       	at com.thoughtworks.go.agent.AgentController.ping(AgentController.java:157)
       	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
       	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
       	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
       	at java.util.TimerThread.mainLoop(Timer.java:555)
       	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.apache.http.NoHttpResponseException: Did not receive successful HTTP response: status code = 403, status message = [Access Denied]
```

**Comment by ujjwalvns** [comment]
` 2021-09-27 12:14:12,145 [stdout] - 2021-09-27 12:14:12,144 ERROR [scheduler-2] AgentHTTPClientController:114 - Error occurred when agent tried to ping server:
jvm 1    | 2021-09-27 12:14:12,146 [stdout] - java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: The server returned status code 422. Possible reasons include:
jvm 1    | 2021-09-27 12:14:12,146 [stdout] -    - This agent has been deleted from the configuration
jvm 1    | 2021-09-27 12:14:12,146 [stdout] -    - This agent is pending approval`

While I was trying to update the password of the bitbucket config repo, the GoCD pipeline is failing and when I investigated further, it seems as it is still is taking the last password.
