### ISSUE TITLE
Convariance and Java Cross-compile

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1248]
I happened to build GoCD using java8. The source and target in the build scripts is set to 1.7, one would expect the resultant app to work fine with java7. However, I'm seeing the following issue because of covariance -

```java
Exception in thread "71@MessageListener for WorkFinder" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.thoughtworks.go.domain.activity.JobStatusCache.clearOldJobs(JobStatusCache.java:59)
	at com.thoughtworks.go.domain.activity.JobStatusCache.cache(JobStatusCache.java:55)
	at com.thoughtworks.go.domain.activity.JobStatusCache.jobStatusChanged(JobStatusCache.java:49)
	at com.thoughtworks.go.server.service.JobInstanceService$4.afterCommit(JobInstanceService.java:182)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCommit(TransactionSynchronizationUtils.java:133)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerAfterCommit(TransactionSynchronizationUtils.java:121)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCommit(AbstractPlatformTransactionManager.java:950)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:796)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:147)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
	at com.thoughtworks.go.server.service.BuildAssignmentService$2.surrounding(BuildAssignmentService.java:196)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.transactionSurrounding(TransactionTemplate.java:71)
	at com.thoughtworks.go.server.service.BuildAssignmentService.createWork(BuildAssignmentService.java:181)
	at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:106)
	at com.thoughtworks.go.server.messaging.scheduling.BuildAssignmentServiceAssigner.assignWorkToAgent(BuildAssignmentServiceAssigner.java:44)
	at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:56)
	at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:30)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by srinivasupadhya** [comment]
@ketan - is this done? i think the PR was accepted for this?

**Comment by ketan** [comment]
Yes, I think this specific issue can be marked done. I'm not aware of any other issues of the same type if there are any.
