### ISSUE TITLE
100% CPU and Memory utilisation when creating a fetch artifact task in a template

### ISSUE THREAD

**Issue by dmcniven** [gocd/gocd#1256]
Number of pipelines: 552
Number of agents: 12
Number of environments: 0
Number of unique materials: 820
Number of schedulable materials: 820

[full api support information captured during fault](https://gist.github.com/dmcniven/d28e136dc4ef59a8d0be)

We are encountering an issue with the latest nightly build of GO server (15.2)

Using [this sanitised config.xml](https://gist.github.com/dmcniven/b339db3f342e56809b94), when editing a template, if we attempt to add a 'fetch artifact' task (as shown below) the GO server becomes unresponsive, CPU load increases and memory utilisation reaches 100%.
![template_fetch_artifact](https://cloud.githubusercontent.com/assets/12992523/8299264/78733a2a-19b9-11e5-8259-77aebecf516e.png)

system load:
![load](https://cloud.githubusercontent.com/assets/12992523/8299244/49068440-19b9-11e5-9c10-9028eadc6561.png)

The only way to recover is to kill the GO server and restart it.

**Comment by srinivasupadhya** [comment]
Thank your for trying out experimental build (v15.2). We use it on build.go.cd & couple of other instances for dog-fooding & faster feedback. We will try our best to resolve this fast, so you are unblocked.

Now, I doubt the CPU/Memory usage is by Fetch Artifact UI action.

From the API support page:

```java
75, 75@MessageListener for ScheduleCheckListener, RUNNABLE
Locked Monitors:
org.h2.engine.Database@47205c77 at org.h2.command.Command.executeQuery(Command.java:185)org.h2.engine.Session@3533d6e9 at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)java.lang.String@2a498650 at com.thoughtworks.go.server.persistence.MaterialRepository.findMaterialInstance(MaterialRepository.java:530)Locked Synchronizers:
Stacktrace:
  org.h2.command.Command.executeQuery(Command.java:185)
  org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
  org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
  org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
  org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:208)
  org.hibernate.loader.Loader.getResultSet(Loader.java:1812)
  org.hibernate.loader.Loader.doQuery(Loader.java:697)
  org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
  org.hibernate.loader.Loader.doList(Loader.java:2232)
  org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2129)
  org.hibernate.loader.Loader.list(Loader.java:2124)
  org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:118)
  org.hibernate.impl.SessionImpl.list(SessionImpl.java:1597)
  org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:306)
  org.springframework.orm.hibernate3.HibernateTemplate$36.doInHibernate(HibernateTemplate.java:1056)
  org.springframework.orm.hibernate3.HibernateTemplate$36.doInHibernate(HibernateTemplate.java:1)
  org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:406)
  org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:374)
  org.springframework.orm.hibernate3.HibernateTemplate.findByCriteria(HibernateTemplate.java:1046)
  org.springframework.orm.hibernate3.HibernateTemplate.findByCriteria(HibernateTemplate.java:1039)
  com.thoughtworks.go.server.persistence.MaterialRepository.firstResult(MaterialRepository.java:580)
  com.thoughtworks.go.server.persistence.MaterialRepository.findMaterialInstance(MaterialRepository.java:530)
  com.thoughtworks.go.server.persistence.MaterialRepository.findLatestModification(MaterialRepository.java:796)
  com.thoughtworks.go.server.materials.MaterialChecker.findLatestRevisions(MaterialChecker.java:82)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:184)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:160)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:122)
  com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:45)
  com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:24)
  com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
  com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
  java.lang.Thread.run(Thread.java:745)
```

which is blocking all other DB queries like:

```java
74, 74@MessageListener for ScheduleCheckListener, BLOCKED
Locked Monitors:
org.h2.engine.Session@411103e0 at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)java.lang.String@4415887f at com.thoughtworks.go.server.persistence.MaterialRepository.findMaterialInstance(MaterialRepository.java:530)Locked Synchronizers:
Stacktrace:
  org.h2.command.Command.executeQuery(Command.java:185)
  org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:109)
  org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
  org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
  org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:208)
  org.hibernate.loader.Loader.getResultSet(Loader.java:1812)
  org.hibernate.loader.Loader.doQuery(Loader.java:697)
  org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
  org.hibernate.loader.Loader.doList(Loader.java:2232)
  org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2129)
  org.hibernate.loader.Loader.list(Loader.java:2124)
  org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:118)
  org.hibernate.impl.SessionImpl.list(SessionImpl.java:1597)
  org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:306)
  org.springframework.orm.hibernate3.HibernateTemplate$36.doInHibernate(HibernateTemplate.java:1056)
  org.springframework.orm.hibernate3.HibernateTemplate$36.doInHibernate(HibernateTemplate.java:1)
  org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:406)
  org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:374)
  org.springframework.orm.hibernate3.HibernateTemplate.findByCriteria(HibernateTemplate.java:1046)
  org.springframework.orm.hibernate3.HibernateTemplate.findByCriteria(HibernateTemplate.java:1039)
  com.thoughtworks.go.server.persistence.MaterialRepository.firstResult(MaterialRepository.java:580)
  com.thoughtworks.go.server.persistence.MaterialRepository.findMaterialInstance(MaterialRepository.java:530)
  com.thoughtworks.go.server.persistence.MaterialRepository.findLatestModification(MaterialRepository.java:796)
  com.thoughtworks.go.server.materials.MaterialChecker.findLatestRevisions(MaterialChecker.java:82)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:184)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:160)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:122)
  com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:45)
  com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:24)
  com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
  com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
  java.lang.Thread.run(Thread.java:745)
```

which im suspecting is making the server unresponsive. Need to dig deeper there i suppose.

What release were you on before upgrade? The database queries have not changed in any of the recent releases so i doubt there is any problem there, but we have turned on jetty 9 by default in 15.2 & will keep it turned on if we dont find any performance issues with it (all unit/integration/functional tests are green so no problem there).  There seems to be a performance issue with the latest Jetty 9 with connection pools.

Suggesion: You could try switching to Jetty 6 for now to make make sure Jetty 9 is not the problem. To switch to Jetty 6 add system property `-Dapp.server=com.thoughtworks.go.server.Jetty6Server` & restart Go Server.

**Comment by dmcniven** [comment]
If it helps, we noticed this problem on the official 15.1 release.

We just ran this test against the latest code to ensure that the problem wasn't already fixed before creating the issue on GitHub.

I'll try to switch to jetty 6 and report the findings

Thanks

**Comment by srinivasupadhya** [comment]
If you have already tried it with 15.1 it looks like an existing issue. Thanks for taking the pain to verify on the latest build.

We are using the sample config you gave & saw that the fetch artifact pop-up takes a long time to open, but eventually opens with no spike in CPU/memory). Can you tell us which pipeline in the sanitized config will reproduce the issue.

On the side note, if would be great if you could open-source the config sanitizer code so other users could use that as well. Was thinking of writing one myself, couldn't find time.

**Comment by srinivasupadhya** [comment]
Looks like the graph is very dense & the Fetch Artifact UI tries to compute all possible paths to all its upstream pipelines for auto-suggest. Ideal solution is to move auto-suggest computation logic to JS using APIs which will take sometime to get it right. Putting a flag to turn off auto-suggest in Fetch Artifact UI so you are unblocked for now.

**Comment by dmcniven** [comment]
Thankyou for the prompt reply, a flag would be ideal.

For reference [here is the api support info with jetty 6](https://gist.github.com/dmcniven/639ce12a64fd2d0113fa). There was no noticeable difference in behaviour, so Jetty 9 can probably be ruled out as a contributing factor

**Comment by vinasoni** [comment]
While we need to re-look at the whole interaction of drilling down to tasks and accessing the fetch artefact, here is a quick fix to the overlay screen where they search. The auto-suggest can be improved to-
- Displaying only downstream pipelines
- Highlight the text which we are suggesting (this is a general UX best practise we can borrow)

![auto-suggest](https://cloud.githubusercontent.com/assets/12891016/8567601/5ddea81c-2584-11e5-9c04-2af177de4c62.png)

**Comment by dimitri-koussa** [comment]
> On the side note, if would be great if you could open-source the config sanitizer code so other users
> could use that as well. Was thinking of writing one myself, couldn't find time.

Finally got around to doing this. Source available here: https://github.com/dimitri-koussa/gocd-config-cleaner.

**Comment by srinivasupadhya** [comment]
my patch for re-writing fetch artifact UI:

```javascript
FetchTaskEditorNew: function () {
        function init() {
        }

        function pipelineList(pipeline_groups) {
            var pipelines = new Array();
            for (i = 0; i < pipeline_groups.length; i++) {
                pipelines = pipelines.concat(pipeline_groups[i].pipelines);
            }
            return pipelines;
        }

        function getPipeline(currentPipelineName) {
            for (i = 0; i < pipelines.length; i++) {
                if (pipelines[i].name == currentPipelineName) {
                    return pipelines[i];
                }
            }
            return null;
        }

        function downstreamPipelineList(pipelineName) {
            var downstream_pipelines = new Array();
            for (i = 0; i < pipelines.length; i++) {
                for (j = 0; j < pipelines[i].materials.length; j++) {
                    if (pipelines[i].materials[j].type == 'pipeline' && pipelines[i].materials[j]['pipeline-configuration']['pipeline-name'] == pipelineName) {
                        downstream_pipelines = downstream_pipelines.concat(pipelines[i]);
                    }
                }
            }
            return downstream_pipelines;
        }

        function updatePipelineAutoCompleteWithDownstreamPipelines(pipeline_name, pipeline_box) {
            var pipeline = getPipeline(pipeline_name);
            var downstream_pipelines = downstreamPipelineList(pipeline.name);

            updatePipelineAutoCompleteOptions(pipeline_box, downstream_pipelines);
        }

        function updatePipelineAutoCompleteOptions(pipeline_box, pipelines) {
            pipeline_box.setOptions({
                data: pipelines
            });
        }

        function updateStageAutoCompleteOptions(stage_box, stages) {
            stage_box.setOptions({
                data: stages
            });
        }

        function updateJobAutoCompleteOptions(job_box, jobs) {
            job_box.setOptions({
                data: jobs
            });
        }

        function wireInPipelineAutoComplete(pipeline_box, stage_box, job_box, pipelines) {
            pipeline_box.removeData('events').autocomplete(pipelines, {
                multiple: true,
                multipleSeparator: "/",
                minChars: 0,
                width: 400,
                matchContains: "word",
                cacheLength: 0,
                formatItem: function (row, i, max) {
                    return row.name;
                },
                formatMatch: function (row, i, max) {
                    return row.name;
                },
                formatResult: function (row) {
                    return row.name;
                }
            }).result(function (event, pipelineEntry) {
                updatePipelineAutoCompleteWithDownstreamPipelines(pipelineEntry.name, pipeline_box);

                var pipeline_path = pipeline_box.val();
                var pipelines_in_path = pipeline_path.split('/');
                var source_pipeline_name = pipelines_in_path[0];

                if (source_pipeline_name != current_auto_suggest_pipeline_name) {
                    var source_pipeline = getPipeline(source_pipeline_name);

                    updateStageAutoCompleteOptions(stage_box, source_pipeline.stages);

                    stage_box.val("");
                    job_box.val("");

                    current_auto_suggest_pipeline_name = source_pipeline.name;
                }
            });
        }

        function wireInStageAutoComplete(stage_box, job_box, pipelineEntry) {
            var stages = pipelineEntry == null ? new Array() : pipelineEntry.stages;
            stage_box.removeData('events').autocomplete(stages, {
                minChars: 0,
                width: 400,
                matchContains: "word",
                cacheLength: 0,
                formatItem: function (row, i, max) {
                    return row.name;
                },
                formatMatch: function (row, i, max) {
                    return row.name;
                },
                formatResult: function (row) {
                    return row.name;
                }
            }).result(function (event, stageEntry) {
                if (stageEntry.name != current_auto_suggest_stage_name) {
                    updateJobAutoCompleteOptions(job_box, stageEntry.jobs);

                    job_box.val("");

                    current_auto_suggest_stage_name = stageEntry.name;
                }
            });
        }

        function wireInJobAutoComplete(job_box, stageEntry) {
            var jobs = stageEntry == null ? new Array() : stageEntry.jobs;
            job_box.removeData('events').autocomplete(jobs, {
                minChars: 0,
                width: 400,
                matchContains: "word",
                cacheLength: 0,
                formatItem: function (row, i, max) {
                    return row.name;
                },
                formatMatch: function (row, i, max) {
                    return row.name;
                },
                formatResult: function (row) {
                    return row.name;
                }
            });
        }

        function deleteLastPipeline(pipeline_box) {
            var pipeline_path = pipeline_box.val();
            var is_full_pipeline = pipeline_path.trim().endsWith("/");
            var pipelines_in_path = pipeline_path.split('/');

            pipelines_in_path.pop();
            if (is_full_pipeline) {
                pipelines_in_path.pop();
            }

            var new_pipelines_in_path = "";
            for (i = 0; i < pipelines_in_path.length; i++) {
                new_pipelines_in_path += pipelines_in_path[i] + "/";
            }
            pipeline_box.val(new_pipelines_in_path);

            if (pipelines_in_path.length > 0) {
                updatePipelineAutoCompleteWithDownstreamPipelines(pipelines_in_path[pipelines_in_path.length - 1], pipeline_box);
            } else {
                updatePipelineAutoCompleteOptions(pipeline_box, pipelines);
            }
        }

        init.prototype.wireInAutoComplete = function (pipeline_box, stage_box, job_box, currentPipelineName) {
            jQuery.ajax({
                type: "GET",
                url: "/go/api/config/pipeline_groups",
                success: function (pipeline_groups) {
                    pipelines = pipelineList(pipeline_groups);
                    current_pipeline_name = currentPipelineName;
                    current_auto_suggest_pipeline_name = current_pipeline_name;
                    current_auto_suggest_stage_name = "";

                    var currentPipeline = getPipeline(current_pipeline_name);

                    pipeline_box.keydown(function (event) {
                        var keycode = (event.keyCode ? event.keyCode : event.which);
                        if (keycode == 8) {
                            event.preventDefault();

                            deleteLastPipeline(pipeline_box);
                        }
                    });

                    wireInPipelineAutoComplete(pipeline_box, stage_box, job_box, pipelines);

                    wireInStageAutoComplete(stage_box, job_box, currentPipeline);

                    wireInJobAutoComplete(job_box, null);
                },
                error: function (data) {
                    // handle
                }
            });
        };

        return init;
    }(),
```

**Comment by zabil** [comment]
This will done as a part of #1494
