### ISSUE TITLE
GoCD Dashboard is loading forever

### ISSUE THREAD

**Issue by mintughosh** [gocd/gocd#12785]
##### Issue Type
After the Restart of GoCD Service, the dashboard page is not loading. We can access the pipelines if we have the pipelines and run the pipelines but landing page or main page does not load any pipelines. Not just the Default view but any other view as well

##### Summary

Post Restart of the Gocd service. I am getting the following error. The Dashboard are not loading.
Dashboard is being processed, this may take a few seconds. Please check back later.

GoCD Version: 21.2.0

**Comment by chadlwilson** [comment]
The issue description asks for you to supply information necessary to help you. If you'd like help, please follow the issue description rather than deciding you won't supply the requested information and follow your own format.

Anyway, look at your server logs and see what it says. There is obviously something wrong with your installation or database so you need to start with the logs to figure out why.

**Comment by mintughosh** [comment]
Hi @chadlwilson 
We have goCD running for over 3 years. We faced several issues but have been able to resolve by our own.
This is not a new installation. This happened after we restarted the gocd service. It was working fine before restart. the pipelines which are in hundreds were populating on the dashboard. Post restart, we are getting loading error.

On the go-server.log files - We find the following errors -

024-05-20 11:59:28,947 ERROR [121@MessageListener for ScheduleCheckListener] BuildCauseProducerService:220 - Error while scheduling pipeline: prod-frontend
com.thoughtworks.go.server.service.dd.MaxBackTrackLimitReachedException: Maximum Backtracking limit reached while trying to resolve revisions for material DependencyMaterialConfig{pipelineName='sit-tops-mdc-build-integrated', stageName='build-code'}
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.hasMoreInstances(DependencyFanInNode.java:233)
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.fillNextRevisions(DependencyFanInNode.java:128)
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.handleNeedMoreRevisions(DependencyFanInNode.java:83)
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.initRevision(DependencyFanInNode.java:75)
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.populateRevisions(DependencyFanInNode.java:61)
        at com.thoughtworks.go.server.service.dd.FanInGraph.initChildren(FanInGraph.java:310)
        at com.thoughtworks.go.server.service.dd.FanInGraph.computeRevisions(FanInGraph.java:173)
        at com.thoughtworks.go.server.service.PipelineService.getRevisionsBasedOnDependencies(PipelineService.java:220)
        at com.thoughtworks.go.server.service.AutoBuild.fanInOn(AutoBuild.java:108)
        at com.thoughtworks.go.server.service.AutoBuild.onModifications(AutoBuild.java:67)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:191)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:148)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:110)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:44)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:24)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
        at java.base/java.lang.Thread.run(Unknown Source)
        
        024-05-20 12:01:56,803 ERROR [qtp1634794671-38] BuildRepositoryRemoteImpl:59 - Error occurred in com.thoughtworks.go.server.service.ElasticAgentRuntimeInfo@7769a36c[elasticAgentId=gocd-8f425d85-f238-4ae0-9e69-404425909f47,elasticPluginId=cd.go.contrib.elasticagent.kubernetes,agentBootstrapperVersion=21.2.0-12498,agentVersion=21.2.0-12498,buildingInfo=AgentBuildingInfo[, ],cookie=<null>,identifier=Agent [8f425d85-f238-4ae0-9e69-404425909f47, 10.200.4.234, ebeccff0-563a-4204-9ebd-9e959704eaff],location=/go,operatingSystemName=Alpine Linux v3.19,runtimeStatus=Idle,usableSpace=76701691904] ping.
        
        2024-05-20 12:05:19,134 ERROR [126@MessageListener for ScheduleCheckListener] BuildCauseProducerService:220 - Error while scheduling pipeline: build-prod
com.thoughtworks.go.server.service.dd.MaxBackTrackLimitReachedException: Maximum Backtracking limit reached while trying to resolve revisions for material DependencyMaterialConfig{pipelineName='build-prod', stageName='build-code'}

**Comment by chadlwilson** [comment]
There's nothing unusual there unfortunately.

If you could make a call via your browser to `/go/api/support`, **carefully review the output for anything sensitive** and share it here, that would be useful. That will capture stack traces and show us where it is stuck for the dashboard load, as well as capture the necessary environment information to help you.

If you're not comfortable sharing that, you may need to fall back to my suggestions above to review any changes to the config from before you restarted it, and/or restore an earlier database version (if using H2database, not external postgres/mysql).
