### ISSUE TITLE
Port over backup API

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1319]
#1292

**Comment by zabil** [comment]
on experimental release15.2.0-2237 (2fd095a561193826f445f9627cf6861c8983f0dc)

The new back up api reports 500 for a successful backup

To replicate try the old api
```
/T/go-server-15.2.0 curl -X POST http://localhost:8153/go/api/admin/start_backup -v
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8153 (#0)
> POST /go/api/admin/start_backup HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:8153
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 09 Jul 2015 11:46:36 GMT
< Set-Cookie: JSESSIONID=2ncubs4ownqn1gaargg4mj5s4;Path=/go;Expires=Thu, 23-Jul-2015 11:46:36 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-UA-Compatible: chrome=1
< Content-Type: text/html; charset=UTF-8
< ETag: "6bafc8b96cf6034afea1b77a7a41570f"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: a258f8be-f46d-4012-8c2c-78bd4fb4bf36
< X-Runtime: 0.079000
< Transfer-Encoding: chunked
* Server Jetty(9.2.z-SNAPSHOT) is not blacklisted
< Server: Jetty(9.2.z-SNAPSHOT)
< 
Backup completed successfully.
* Connection #0 to host localhost left intact
~/T/go-server-15.2.0 
```

and then the new API

```
curl -X POST -H 'Accept: application/vnd.go.cd.v1+json' http://localhost:8153/go/api/backups -v
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8153 (#0)
> POST /go/api/backups HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:8153
> Accept: application/vnd.go.cd.v1+json
> 
< HTTP/1.1 500 Server Error
< Date: Thu, 09 Jul 2015 11:47:40 GMT
< Set-Cookie: JSESSIONID=143lijxwa4pcx148ojuvukk08v;Path=/go;Expires=Thu, 23-Jul-2015 11:47:40 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Content-Type: text/html; charset=UTF-8
< X-Request-Id: 25b28385-768a-40de-8048-92aaee90d6c2
< X-Runtime: 0.113000
< Content-Length: 1266
* Server Jetty(9.2.z-SNAPSHOT) is not blacklisted
< Server: Jetty(9.2.z-SNAPSHOT)
....
<body>
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <h1>We're sorry, but something went wrong.</h1>
  </div>
  <p>If you are the application owner check the logs for more information.</p>
</body>
</html>
* Connection #0 to host localhost left intact
```

Here's what's reported on the logs

```
2015-07-09 17:20:58,732  INFO [qtp377311812-12] H2EventListener:82 - Backing up cruise.h2.db 0%
2015-07-09 17:20:58,735  INFO [qtp377311812-12] H2EventListener:82 - Backing up cruise.h2.db 0%
2015-07-09 17:20:58,757 ERROR [Thread-1196] GoSmtpMailSender:103 - Sending failed for email [Server Backup Completed Successfully] to [null]
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:514)
	at com.thoughtworks.go.config.GoSmtpMailSender.mailProperties(GoSmtpMailSender.java:133)
	at com.thoughtworks.go.config.GoSmtpMailSender.send(GoSmtpMailSender.java:86)
	at com.thoughtworks.go.config.BackgroundMailSender$1.run(BackgroundMailSender.java:47)
	at java.lang.Thread.run(Thread.java:745)
2015-07-09 17:20:58,780 FATAL [qtp377311812-12] Rails:? - 
ActionController::UrlGenerationError (No route matches {:action=>"update", :controller=>"api_v1/users", :login_name=>""} missing required keys: [:login_name]):
  app/presenters/api_v1/user_representer.rb:27:in `UserRepresenter'
  app/presenters/api_v1/base_representer.rb:36:in `to_hash'
  app/presenters/api_v1/base_representer.rb:36:in `to_hash'
  app/controllers/api_v1/backups_controller.rb:27:in `create'
```
