### ISSUE TITLE
Update to 15.2 - Lots of agents went "missing"

### ISSUE THREAD

**Issue by paulclarkin** [gocd/gocd#1350]
Following an upgrade to 15.2 about 50% of agents went "missing".

Resolved by backing up the agent guid.txt, and then reinstalling the agent with the latest agent download, then restore the guid.txt.

Error log
```
2015-07-15 09:00:22,566 [loopThread] ERROR go.agent.service.AgentUpgradeService:64 - [Agent Upgrade] Couldn't connect to: https://myserver.8154/go/admin/latest-agent.status: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
2015-07-15 09:00:22,566 [loopThread] ERROR thoughtworks.go.agent.AgentController:145 - [Agent Loop] Error occurred during loop: 
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:808)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1112)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:623)
	at com.sun.net.ssl.internal.ssl.AppOutputStream.write(AppOutputStream.java:59)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:827)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1525)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:1975)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:993)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:54)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:47)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:129)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:333)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:789)
	... 24 more
2015-07-15 09:00:24,173 [pingThread] ERROR thoughtworks.go.agent.AgentController:116 - Error occurred when agent tried to ping server: 
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://myserver:8154/go/remoting/remoteBuildRepository]; nested exception is javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:212)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:145)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at $Proxy5.ping(Unknown Source)
	at com.thoughtworks.go.agent.AgentController.ping(AgentController.java:112)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:808)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1112)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:623)
	at com.sun.net.ssl.internal.ssl.AppOutputStream.write(AppOutputStream.java:59)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:502)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:1973)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:993)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
	at org.springframework.remoting.httpinvoker.CommonsHttpInvokerRequestExecutor.executePostMethod(CommonsHttpInvokerRequestExecutor.java:205)
	at org.springframework.remoting.httpinvoker.CommonsHttpInvokerRequestExecutor.doExecuteRequest(CommonsHttpInvokerRequestExecutor.java:140)
	at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:136)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:192)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:174)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:142)
	... 12 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:333)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:789)
	... 30 more
2015-07-15 09:00:29,181 [pingThread] ERROR thoughtworks.go.agent.AgentController:116 - Error occurred when agent tried to ping server: 
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://myserver:8154/go/remoting/remoteBuildRepository]; nested exception is javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:212)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:145)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at $Proxy5.ping(Unknown Source)
	at com.thoughtworks.go.agent.AgentController.ping(AgentController.java:112)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:808)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1112)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:623)
	at com.sun.net.ssl.internal.ssl.AppOutputStream.write(AppOutputStream.java:59)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:502)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:1973)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:993)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
	at org.springframework.remoting.httpinvoker.CommonsHttpInvokerRequestExecutor.executePostMethod(CommonsHttpInvokerRequestExecutor.java:205)
	at org.springframework.remoting.httpinvoker.CommonsHttpInvokerRequestExecutor.doExecuteRequest(CommonsHttpInvokerRequestExecutor.java:140)
	at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:136)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:192)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:174)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:142)
	... 12 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:333)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:789)
	... 30 more
```

**Comment by arvindsv** [comment]
Hello! Which version of the Go Agents was present, before upgrade? Also, on those 50% of agents, was there a common Java version (an older version, maybe)? I'm trying to see what could cause this. Did you try just restarting the agents, instead of upgrading them?

**Comment by arvindsv** [comment]
Can you also provide the agent logs (bootstrapper, launcher and agent logs)? Thank you very much!

**Comment by paulclarkin** [comment]
They were a mix of versions. Some have never been manually upgraded. The documentation says they should auto upgrade - is that right?

I believe they were using "bundled JRE".

Yes, I tried restarting them, but with no luck.

Log files: http://s000.tinyupload.com/?file_id=76557584056432854651

**Comment by arvindsv** [comment]
Thanks for that. I'm suspecting that the old JRE which was in the old agents was incompatible with the one on the server. The 15.2 Go Server uses much more secure ciphers, which were probably unsupported by the older JRE.

**Comment by arvindsv** [comment]
About auto-upgrade. Yes, the version of the Go Agent will auto upgrade to make sure that the correct version is being used for that Go Server, but in this case, the bundled JRE itself was an old version. It won't be able to upgrade that, unless the go-agent EXE is used.

**Comment by paulclarkin** [comment]
OK, that makes sense.
Might need a note adding to the release notes?

**Comment by arvindsv** [comment]
> Might need a note adding to the release notes?

Definitely, and maybe to the download page. I'll need to verify which JRE versions this happens on before that.

**Comment by paulclarkin** [comment]
![jdk](https://cloud.githubusercontent.com/assets/1027095/8702579/7e0b0752-2b10-11e5-88ec-a213376b6e29.jpg)
This is from one of them

**Comment by arvindsv** [comment]
Thank you! That helps. I'm not surprised that Java 7 would not work. We sent some mails to the mailing list, and had a [blog post](http://www.go.cd/2015/04/23/Go_15_1_jdk7_announcement.html) about upgrading to 7, before 15.1 came out.

I'm checking to see if an upgrade from a (15.1 Go Agent + 15.1 Go Server) => to a (15.2 Go Server without any change to agent) works. I have a local copy of the warnings on the download page and release notes ready, in case that fails.

**Comment by paulclarkin** [comment]
No problems when we upgraded to 15.1

**Comment by arvindsv** [comment]
Yes. In 15.1, it was a soft requirement, because the ciphers were not changed. But, we wanted to warn people (in fact, our first warning about Java 7 was in April 2013, I believe). Now, in 15.2, it is a hard requirement. The Java juggernaut is moving a little [quicker](http://www.oracle.com/technetwork/java/eol-135779.html) these days. In fact, updates to Java 7 have already ended.

**Comment by arvindsv** [comment]
Alright, I checked and upgrade from 15.1 server and agent to 15.2 server (keeping the old agent with old JRE) works. I'll add a less severe warning on those two pages, about making sure that Java 7 is used. Thanks again, @paulclarkin.

**Comment by arvindsv** [comment]
I've added a warning to the download page. I'll close this issue for now, @paulclarkin. Let me know if you think it should be reopened.
