### ISSUE TITLE
Investigate why GitMaterialTest fails on newer git versions

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1372]
The following tests fail on the version of git I have - 

```
shouldRemoveSubmoduleFolderFromWorkingDirWhenSubmoduleIsRemovedFromRepo
shouldHaveModificationsWhenSubmoduleIsRemoved
```

I'm not sure if its a bad test or compatibility that git has broken (that could cause go to behave unexpectedly)

**Comment by ketan** [comment]
```
% git --version
git version 2.4.5
```

Test `shouldRemoveSubmoduleFolderFromWorkingDirWhenSubmoduleIsRemovedFromRepo`

```
com.thoughtworks.go.util.command.CommandLineException: Error performing command: --- Command ---
git rm --cached sub1
--- Environment ---
{}
--- INPUT ----


--OUTPUT ---

--- ERROR ---
STDERR: fatal: Please, stage your changes to .gitmodules or stash them to proceed
---

	at com.thoughtworks.go.util.command.CommandLine.runOrBomb(CommandLine.java:498)
	at com.thoughtworks.go.util.command.CommandLine.runOrBomb(CommandLine.java:526)
	at com.thoughtworks.go.domain.materials.SCMCommand.runOrBomb(SCMCommand.java:42)
	at com.thoughtworks.go.domain.materials.git.GitCommand.submoduleRemove(GitCommand.java:319)
	at com.thoughtworks.go.helper.GitSubmoduleRepos.removeSubmodule(GitSubmoduleRepos.java:60)
	at com.thoughtworks.go.config.materials.git.GitMaterialTest.shouldRemoveSubmoduleFolderFromWorkingDirWhenSubmoduleIsRemovedFromRepo(GitMaterialTest.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:107)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:88)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at com.googlecode.junit.ext.JunitExtRunner.invokeTestMethod(JunitExtRunner.java:41)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:61)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:54)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:52)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

```

Test `shouldHaveModificationsWhenSubmoduleIsRemoved` -

```
com.thoughtworks.go.util.command.CommandLineException: Error performing command: --- Command ---
git rm --cached sub1
--- Environment ---
{}
--- INPUT ----


--OUTPUT ---

--- ERROR ---
STDERR: fatal: Please, stage your changes to .gitmodules or stash them to proceed
---

	at com.thoughtworks.go.util.command.CommandLine.runOrBomb(CommandLine.java:498)
	at com.thoughtworks.go.util.command.CommandLine.runOrBomb(CommandLine.java:526)
	at com.thoughtworks.go.domain.materials.SCMCommand.runOrBomb(SCMCommand.java:42)
	at com.thoughtworks.go.domain.materials.git.GitCommand.submoduleRemove(GitCommand.java:319)
	at com.thoughtworks.go.helper.GitSubmoduleRepos.removeSubmodule(GitSubmoduleRepos.java:60)
	at com.thoughtworks.go.config.materials.git.GitMaterialTest.shouldHaveModificationsWhenSubmoduleIsRemoved(GitMaterialTest.java:477)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:107)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:88)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at com.googlecode.junit.ext.JunitExtRunner.invokeTestMethod(JunitExtRunner.java:41)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:61)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:54)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:52)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by arvindsv** [comment]
Took a quick look at `shouldHaveModificationsWhenSubmoduleIsRemoved `. I think it should be renamed `shouldSeeSubmoduleRemovalAsAModification`. The intent looks ok. The implementation is wrong. It's doing this to remove a submodule:

```
git config --remove-section submodule.sub1
git config -f .gitmodules --remove-section submodule.sub1
git rm --cached sub1
```

That is failing. Need to fix `GitCommand#submoduleRemove`. Ideally that shouldn't even be in `GitCommand`. It's used only in tests.

Haven't looked at the other test.

**Comment by arvindsv** [comment]
@ketan, @varshavaradarajan: Can this be closed now?

**Comment by ketan** [comment]
@zabil has already closed this, but the failures were just git error message assertion strings that had changed between git versions. I'd fixed some of them, and we're running green on a fairly new version of git running on windows.
