### ISSUE TITLE
Agents Update & Delete API not usable - responds with 422 Unprocessable Entity

### ISSUE THREAD

**Issue by craiggenner** [gocd/gocd#1375]
I'm trying to disable and then delete agents via the API.

The docs say to update an agent run the following:
```
$ curl 'https://ci.example.com/go/api/agents/adb9540a-b954-4571-9d9b-2f330739d4da' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -H 'Content-Type: application/json' \
      -X PATCH \
      -d '{
            "hostname": "agent02.example.com"
          }'
```
Yet if I call:
```
curl -vX PATCH 'http://localhost:8153/go/api/agents/48063733-e360-497b-9238-41fef0fffdf8'
     -H 'Accept: application/vnd.go.cd.v1+json' \
      -H 'Content-Type: application/json' \
      -u 'username:password' \
      -d '{"hostname": "ip-10-203-8-113"}'
```
I then get:
```
< HTTP/1.1 422 Unprocessable Entity
< Expires: Thu, 01-Jan-1970 00:00:00 GMT
< Set-Cookie: JSESSIONID=1tob8wg915y0d4iwob180ex2z;Path=/go;Expires=Tue, 04-Aug-2015 15:19:26 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< X-Request-Id: 54c815e5-7f2c-460c-a202-0fe26c2de299
< X-Runtime: 0.570000
* Server Jetty() is not blacklisted
< Server: Jetty()
```
The logs then show a stack trace:
```
2015-07-21 15:06:14,274  WARN [1237366370@qtp-1983747920-62] Rails:? - Can't verify CSRF token authenticity
2015-07-21 15:06:14,277 FATAL [1237366370@qtp-1983747920-62] Rails:? - 
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/request_forgery_protection.rb:166:in `handle_unverified_request'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/request_forgery_protection.rb:173:in `handle_unverified_request'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/request_forgery_protection.rb:180:in `verify_authenticity_token'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:380:in `_run__87216347__process_action__callbacks'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in `run_callbacks'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:31:in `process_action'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:19:in `instrument'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/base.rb:136:in `process'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/rendering.rb:44:in `process'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal.rb:195:in `dispatch'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal.rb:231:in `action'
  org/jruby/RubyProc.java:271:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:48:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:71:in `call'
  org/jruby/RubyArray.java:1613:in `each'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:674:in `call'
  vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
  vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/flash.rb:241:in `call'
  file:/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-1.1.14.jar!/jruby/rack/session_store.rb:79:in `context'
  vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/cookies.rb:486:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/callbacks.rb:29:in `call'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:376:in `_run__2080675632__call__callbacks'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in `run_callbacks'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/rack/logger.rb:22:in `call'
  vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/engine.rb:511:in `call'
  vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/application.rb:97:in `call'
  file:/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-1.1.14.jar!/rack/handler/servlet.rb:22:in `call'
```

The same happens when trying to delete the agent, or when no parameters to curl other then the url and and `-X PATCH`.

Some thing clearly isn't right, any ideas?

Running GO 15.1.0-1863, Ubuntu 14.04, openjdk-8-jdk 8u40-b27-1~14.04

**Comment by ketan** [comment]
This API is only available starting with 15.2.0. We have a [pull request](https://github.com/gocd/api.go.cd/pull/37) pending to improve the API documentation to point users to the correct documentation version.

In the meanwhile, may I suggest using the old API documentation for 15.1 instead (http://www.go.cd/documentation/user/15.1.0/api/agent_api.html)

**Comment by xxfelixxx** [comment]
I am seeing the same problem, using 15.2.0(2248-c1f90a6aa3192a).

**Comment by ketan** [comment]
@xxfelixxx - can you provide provide the curl command (use `curl -v`) and the output you get?

**Comment by xxfelixxx** [comment]
Nevermind, I got it to work by changing the Accept header.  Thanks!
