### ISSUE TITLE
Better log output for failure to upload artifact

### ISSUE THREAD

**Issue by gaqzi** [gocd/gocd#1377]
I just had an issue where a pipeline failed to upload the artifacts and there's nothing in the output in the pipeline to help me debug at all. I did find what I needed in the agent log. But it would be nice if more of the information could be exposed in the pipeline log, as I believe it's a bit harsh to expect normal users to look for this information in the agent log. :)

The pipeline console view:

> 09:20:59.543 [go] Start to create properties Sandbox/734/prepare_for_deploy/4/prepare on name-deployer-2.shared [/var/lib/go-agent1]
> 09:20:59.543 [go] Start to upload Sandbox/734/prepare_for_deploy/4/prepare on name-deployer-2.shared [/var/lib/go-agent1]
> 09:20:59.543 [go] Uploading artifacts from /var/lib/go-agent1/pipelines/Sandbox/infra/script/name/verify_smoke_test.sh to [defaultRoot]
> **09:20:59.961 [go] Failed to upload /var/lib/go-agent1/pipelines/Sandbox/infra/ansible**
> **09:21:00.334 [go] Failed to upload /var/lib/go-agent1/pipelines/Sandbox/infra/ansible**
> **09:21:00.704 [go] Failed to upload /var/lib/go-agent1/pipelines/Sandbox/infra/ansible**
> 09:21:00.706 [go] Uploading artifacts from /var/lib/go-agent1/pipelines/Sandbox/infra/ansible/deploy-manifest.yml to [defaultRoot]
> 09:21:00.718 [go] Uploading artifacts from /var/lib/go-agent1/pipelines/Sandbox/infra/script/name/verify_deployment.sh to [defaultRoot]
> **09:21:00.733 [go] Uploading finished. Failed to upload [infra/ansible]**
> 09:21:00.794 [go] Job completed Sandbox/734/prepare_for_deploy/4/prepare on name-deployer-2.shared [/var/lib/go-agent1]

Agent log:

```
2015-07-22 09:21:00,718 [loopThread] INFO  thoughtworks.go.util.HttpService:69 - Uploading file [/tmp/cruise-f737c8cf-c9f0-48c7-aa2b-e0db744ebaab/14f10926-9e4c-4a99-8868-8b6f237ee050/verify_deployment.sh.zip] to url [https://172.16.2.23:8154/go/remoting/files/Sandbox/734/prepare_for_deploy/4/prepare/?attempt=1&buildId=374588]
2015-07-22 09:21:00,733 [loopThread] INFO  thoughtworks.go.util.HttpService:129 - Got back 201 from server
2015-07-22 09:21:00,794 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:90 - Stopping Transmission for Build [Sandbox/734/prepare_for_deploy/4/prepare/374588]
(END)
        at com.thoughtworks.go.util.ZipUtil.addDirectory(ZipUtil.java:83)
        at com.thoughtworks.go.util.ZipUtil.addFolderToZip(ZipUtil.java:72)
        at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:94)
        at com.thoughtworks.go.util.ZipUtil.addDirContents(ZipUtil.java:88)
        at com.thoughtworks.go.util.ZipUtil.addDirectory(ZipUtil.java:83)
        at com.thoughtworks.go.util.ZipUtil.addFolderToZip(ZipUtil.java:72)
        at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:94)
        at com.thoughtworks.go.util.ZipBuilder.done(ZipBuilder.java:57)
        at com.thoughtworks.go.util.ZipUtil.zipContents(ZipUtil.java:64)
        at com.thoughtworks.go.util.ZipUtil.zip(ZipUtil.java:42)
        at com.thoughtworks.go.publishers.GoArtifactsManipulator.publish(GoArtifactsManipulator.java:83)
        at com.thoughtworks.go.work.DefaultGoPublisher.upload(DefaultGoPublisher.java:73)
        at com.thoughtworks.go.config.ArtifactPlan.publishWithProperties(ArtifactPlan.java:127)
        at com.thoughtworks.go.config.ArtifactPlan.publish(ArtifactPlan.java:118)
        at com.thoughtworks.go.domain.DefaultJobPlan.publishArtifacts(DefaultJobPlan.java:105)
        at com.thoughtworks.go.remote.work.BuildWork.completeJob(BuildWork.java:198)
        at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:146)
        at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
        at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
        at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2015-07-22 09:21:00,704 [loopThread] ERROR thoughtworks.go.publishers.GoArtifactsManipulator:113 - Failed to upload /var/lib/go-agent1/pipelines/Sandbox/infra/ansible
java.io.FileNotFoundException: pipelines/Sandbox/infra/ansible/roles/name-automation/files/rpmbuild.expect (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:99)
        at com.thoughtworks.go.util.ZipUtil.addDirContents(ZipUtil.java:88)
        at com.thoughtworks.go.util.ZipUtil.addDirectory(ZipUtil.java:83)
        at com.thoughtworks.go.util.ZipUtil.addFolderToZip(ZipUtil.java:72)
        at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:94)
        at com.thoughtworks.go.util.ZipUtil.addDirContents(ZipUtil.java:88)
        at com.thoughtworks.go.util.ZipUtil.addDirectory(ZipUtil.java:83)
        at com.thoughtworks.go.util.ZipUtil.addFolderToZip(ZipUtil.java:72)
        at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:94)
        at com.thoughtworks.go.util.ZipUtil.addDirContents(ZipUtil.java:88)
        at com.thoughtworks.go.util.ZipUtil.addDirectory(ZipUtil.java:83)
        at com.thoughtworks.go.util.ZipUtil.addFolderToZip(ZipUtil.java:72)
        at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:94)
        at com.thoughtworks.go.util.ZipUtil.addDirContents(ZipUtil.java:88)
        at com.thoughtworks.go.util.ZipUtil.addDirectory(ZipUtil.java:83)
        at com.thoughtworks.go.util.ZipUtil.addFolderToZip(ZipUtil.java:72)
        at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:94)
        at com.thoughtworks.go.util.ZipBuilder.done(ZipBuilder.java:57)
        at com.thoughtworks.go.util.ZipUtil.zipContents(ZipUtil.java:64)
        at com.thoughtworks.go.util.ZipUtil.zip(ZipUtil.java:42)
        at com.thoughtworks.go.publishers.GoArtifactsManipulator.publish(GoArtifactsManipulator.java:83)
        at com.thoughtworks.go.work.DefaultGoPublisher.upload(DefaultGoPublisher.java:73)
        at com.thoughtworks.go.config.ArtifactPlan.publishWithProperties(ArtifactPlan.java:127)
        at com.thoughtworks.go.config.ArtifactPlan.publish(ArtifactPlan.java:118)
        at com.thoughtworks.go.domain.DefaultJobPlan.publishArtifacts(DefaultJobPlan.java:105)
        at com.thoughtworks.go.remote.work.BuildWork.completeJob(BuildWork.java:198)
        at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:146)
        at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
        at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
        at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

The `java.io.FileNotFoundException` exception got me in the right direction, and it turns out the problem was a stale symlink. When the symlink was corrected the pipeline was able to artifact and continue. :)

**Comment by birchb1024** [comment]
We see the identical issue. Go Version: 16.8.0 (3929-4d871a65f9a14b157006236d8fda3460bcafcadb).

Actually I had assumed the agent would ignore symlinks to non-existent files when downloading. I guessed wrong, but it would be better if the console has a message about the symlink case (or any other   issue with the artefacts on the agent).

**Comment by tomzo** [comment]
I've ran into similar problem. Symlink to non-existing file is causing entire upload to fail.

```
2019-12-16 14:37:32,087 [stdout] - 2019-12-16 14:37:32,087 ERROR [scheduler-2] GoArtifactsManipulator:114 - Failed to upload /var/lib/go-agent/pipelines/prm-gp2gp-dashboard/node_modules
2019-12-16 14:37:32,088 [stdout] - java.io.FileNotFoundException: pipelines/prm-gp2gp-dashboard/node_modules/.bin/strip-indent (No such file or directory)
2019-12-16 14:37:32,088 [stdout] - 	at java.io.FileInputStream.open0(Native Method)
2019-12-16 14:37:32,088 [stdout] - 	at java.io.FileInputStream.open(FileInputStream.java:195)
2019-12-16 14:37:32,088 [stdout] - 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
2019-12-16 14:37:32,088 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:97)
2019-12-16 14:37:32,088 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addDirContents(ZipUtil.java:88)
2019-12-16 14:37:32,088 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addDirectory(ZipUtil.java:83)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addFolderToZip(ZipUtil.java:72)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:94)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addDirContents(ZipUtil.java:88)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addDirectory(ZipUtil.java:83)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addFolderToZip(ZipUtil.java:72)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.addToZip(ZipUtil.java:94)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipBuilder.done(ZipBuilder.java:57)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.zipContents(ZipUtil.java:64)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.util.ZipUtil.zip(ZipUtil.java:42)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.publishers.GoArtifactsManipulator.publish(GoArtifactsManipulator.java:84)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.work.DefaultGoPublisher.upload(DefaultGoPublisher.java:76)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.domain.ArtifactPlan.uploadArtifactFile(ArtifactPlan.java:167)
2019-12-16 14:37:32,089 [stdout] - 	at com.thoughtworks.go.domain.ArtifactPlan.publishBuildArtifact(ArtifactPlan.java:141)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.domain.ArtifactPlan.publishBuiltInArtifacts(ArtifactPlan.java:129)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.remote.work.artifact.ArtifactsPublisher.publishArtifacts(ArtifactsPublisher.java:76)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.remote.work.BuildWork.completeJob(BuildWork.java:198)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:129)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:79)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:54)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveWork(AgentHTTPClientController.java:144)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.agent.AgentHTTPClientController.work(AgentHTTPClientController.java:116)
2019-12-16 14:37:32,090 [stdout] - 	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:85)
2019-12-16 14:37:32,090 [stdout] - 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
2019-12-16 14:37:32,090 [stdout] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-12-16 14:37:32,090 [stdout] - 	at java.lang.reflect.Method.invoke(Method.java:498)
2019-12-16 14:37:32,090 [stdout] - 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
2019-12-16 14:37:32,091 [stdout] - 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
2019-12-16 14:37:32,091 [stdout] - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2019-12-16 14:37:32,091 [stdout] - 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2019-12-16 14:37:32,091 [stdout] - 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2019-12-16 14:37:32,091 [stdout] - 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2019-12-16 14:37:32,091 [stdout] - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-12-16 14:37:32,091 [stdout] - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-12-16 14:37:32,091 [stdout] - 	at java.lang.Thread.run(Thread.java:748)
```

I think, the right thing to do is warn about the empty symlink, but not fail entirely.
