### ISSUE TITLE
Agent cannot register due to javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by JamesMGreene** [gocd/gocd#1381]
**Go Server version:** `15.1.0-1863`

**Go Server Java version:**
```
java version "1.7.0_79"
OpenJDK Runtime Environment (amzn-2.5.5.1.59.amzn1-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Go Agent version:** `15.1.0-1863`

**Go Agent Java version:**
```
java version "1.7.0_85"
OpenJDK Runtime Environment (amzn-2.6.1.3.61.amzn1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

---

### Logs

**Tail of `/var/log/go-agent-bootstrapper.log`:**

```
[Fri Jul 24 17:12:52 CDT 2015] Starting Go Agent Bootstrapper with command: /usr/lib/jvm/java-1.7.0/bin/java -jar "/usr/share/go-agent/agent-bootstrapper.jar" 123.45.67.89 8153
[Fri Jul 24 17:12:52 CDT 2015] Starting Go Agent Bootstrapper in directory: /var/lib/go-agent
[Fri Jul 24 17:12:52 CDT 2015] AGENT_STARTUP_ARGS=-Dcruise.console.publish.interval=10 -Xms128m -Xmx256m
logFile Environment Variable= /var/log/go-agent/go-agent-bootstrapper.log
Logging to /var/log/go-agent/go-agent-bootstrapper.log
2015-07-24 22:12:52,813 [main     ] INFO  agent.common.util.JarUtil:68 - Attempting to load Go-Agent-Launcher-Class from 225a66c6-9726-4d4b-b22c-f334b36bd15fagent-launcher.jar File:
2015-07-24 22:12:52,815 [main     ] INFO  agent.common.util.JarUtil:77 - manifestLibDirKey: Go-Agent-Launcher-Lib-Dir: libs
2015-07-24 22:12:52,835 [main     ] INFO  agent.common.util.JarUtil:83 - manifestClassKey: Go-Agent-Launcher-Class: com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl
2015-07-24 22:12:52,836 [main     ] INFO  agent.common.util.ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLauncher using com.simontuffs.onejar.JarClassLoader
2015-07-24 22:12:52,872 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:72 - Attempting create and start launcher...
2015-07-24 22:12:52,907 [main     ] INFO  agent.common.util.ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLaunchDescriptor using com.simontuffs.onejar.JarClassLoader
0 [TouchLoopThread-2] INFO com.thoughtworks.go.agent.launcher.Lockfile  - Using lock file: /var/lib/go-agent/.agent-bootstrapper.running
270 [main] INFO com.thoughtworks.go.agent.common.util.JarUtil  - Attempting to load Go-Agent-Bootstrap-Class from agent.jar File:
271 [main] INFO com.thoughtworks.go.agent.common.util.JarUtil  - manifestClassKey: Go-Agent-Bootstrap-Class: com.thoughtworks.go.agent.AgentProcessParentImpl
273 [main] INFO com.thoughtworks.go.agent.AgentProcessParentImpl  - Agent is version: 15.1.0
391 [main] INFO com.thoughtworks.go.agent.launcher.ServerBinaryDownloader  - download started at Fri Jul 24 22:12:53 UTC 2015
396 [main] INFO com.thoughtworks.go.agent.launcher.ServerBinaryDownloader  - got server response at Fri Jul 24 22:12:53 UTC 2015
421 [main] INFO com.thoughtworks.go.agent.launcher.ServerBinaryDownloader  - pipe the stream to admin/agent-plugins.zip at Fri Jul 24 22:12:53 UTC 2015
422 [main] INFO com.thoughtworks.go.util.PerfTimer  - Performance: Downloading new admin/agent-plugins.zip with md5 signature: 20eaad1f2e9f649dfbff3dbdc5b4afae took 36ms
426 [main] INFO com.thoughtworks.go.agent.AgentProcessParentImpl  - Launching Agent with command: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.85.x86_64/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Dagent.launcher.version=15.1.0 -Dagent.plugins.md5=20eaad1f2e9f649dfbff3dbdc5b4afae -Dagent.binary.md5=WrfXrfz5zYtW7MeCdAotvg== -Dagent.launcher.md5=2SJZgbpIe30D+DTnq691bA== -jar agent.jar https://123.45.67.89:8154/go/
```

**Tail of `/var/log/go-agent-launcher.log`:**

```
2015-07-24 22:12:52,911 [TouchLoopThread-2] INFO  go.agent.launcher.Lockfile:102 - Using lock file: /var/lib/go-agent/.agent-bootstrapper.running
2015-07-24 22:12:53,181 [main     ] INFO  agent.common.util.JarUtil:68 - Attempting to load Go-Agent-Bootstrap-Class from agent.jar File:
2015-07-24 22:12:53,182 [main     ] INFO  agent.common.util.JarUtil:83 - manifestClassKey: Go-Agent-Bootstrap-Class: com.thoughtworks.go.agent.AgentProcessParentImpl
2015-07-24 22:12:53,184 [main     ] INFO  thoughtworks.go.agent.AgentProcessParentImpl:49 - Agent is version: 15.1.0
2015-07-24 22:12:53,302 [main     ] INFO  go.agent.launcher.ServerBinaryDownloader:175 - download started at Fri Jul 24 22:12:53 UTC 2015
2015-07-24 22:12:53,307 [main     ] INFO  go.agent.launcher.ServerBinaryDownloader:181 - got server response at Fri Jul 24 22:12:53 UTC 2015
2015-07-24 22:12:53,332 [main     ] INFO  go.agent.launcher.ServerBinaryDownloader:184 - pipe the stream to admin/agent-plugins.zip at Fri Jul 24 22:12:53 UTC 2015
2015-07-24 22:12:53,333 [main     ] INFO  thoughtworks.go.util.PerfTimer:53 - Performance: Downloading new admin/agent-plugins.zip with md5 signature: 20eaad1f2e9f649dfbff3dbdc5b4afae took 36ms
2015-07-24 22:12:53,337 [main     ] INFO  thoughtworks.go.agent.AgentProcessParentImpl:60 - Launching Agent with command: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.85.x86_64/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Dagent.launcher.version=15.1.0 -Dagent.plugins.md5=20eaad1f2e9f649dfbff3dbdc5b4afae -Dagent.binary.md5=WrfXrfz5zYtW7MeCdAotvg== -Dagent.launcher.md5=2SJZgbpIe30D+DTnq691bA== -jar agent.jar https://123.45.67.89:8154/go/
```

**Tail of `/var/log/go-agent.log`:**

```
...
2015-07-24 22:39:57,749 [loopThread] ERROR go.agent.service.AgentUpgradeService:64 - [Agent Upgrade] Couldn't connect to: https://123.45.67.89:8154/go/admin/latest-agent.status: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
2015-07-24 22:39:57,750 [loopThread] ERROR thoughtworks.go.agent.AgentController:145 - [Agent Loop] Error occurred during loop:
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:965)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:721)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:827)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1525)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:1975)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:993)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:54)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:47)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:129)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:482)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
	... 24 more
```

**Comment by JamesMGreene** [comment]
I'm guessing this is a cipher suite list mismatch between the Server and Agent but I have no idea how to resolve it.

**Comment by jyotisingh** [comment]
You will know for sure after some ssl debugging on server side. You may go through the following steps to capture debug level ssl logs:

(i) Open `/etc/default/go-server` and add this line to it: 
`GO_SERVER_SYSTEM_PROPERTIES="$GO_SERVER_SYSTEM_PROPERTIES -Djavax.net.debug=ssl:record"`
(ii) Restart go server.
(iii) Wait for the agent to connect to the server
(iv) The debug logs would go to go-server.log. 

The logs should give the exact reason for failure.

**Comment by ketan** [comment]
what are the go and jvm versions on your server and agent machines?

Do you think this is a dup of #1350

**Comment by jyotisingh** [comment]
@ketan - He already mentioned that on top. Its Go 15.1 with openjdk7 on both server and agent

**Comment by JamesMGreene** [comment]
**Snippet from `/var/log/go-server.log`:**

```
...
Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for SSLv2Hello
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
1229114783@qtp-203163727-11, READ: TLSv1 Handshake, length = 63
*** ClientHello, TLSv1
RandomCookie:  GMT: 1421234812 bytes = { 125, 228, 8, 247, 0, 249, 57, 3, 87, 128, 11, 253, 192, 117, 14, 244, 181, 182, 116, 33, 223, 165, 239, 15, 0, 148, 23, 90 }
Session ID:  {}
Cipher Suites: [TLS_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
Compression Methods:  { 0 }
***
%% Initialized:  [Session-11, SSL_NULL_WITH_NULL_NULL]
1229114783@qtp-203163727-11, fatal error: 40: no cipher suites in common
javax.net.ssl.SSLHandshakeException: no cipher suites in common
%% Invalidated:  [Session-11, SSL_NULL_WITH_NULL_NULL]
1229114783@qtp-203163727-11, SEND TLSv1 ALERT:  fatal, description = handshake_failure
1229114783@qtp-203163727-11, WRITE: TLSv1 Alert, length = 2
1229114783@qtp-203163727-11, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLHandshakeException: no cipher suites in common
2015-07-27 15:47:08,285  WARN [1229114783@qtp-203163727-11] log:76 - javax.net.ssl.SSLHandshakeException: no cipher suites in common
1229114783@qtp-203163727-11, called closeOutbound()
1229114783@qtp-203163727-11, closeOutboundInternal()
...
```

**Comment by JamesMGreene** [comment]
FYI, downgrading my Go Agent instance's Java version to match the Go Server instance's Java version resolved the issue for now.

Presumably, upgrading the Go Server instance's Java version to match the Go Agent instance's Java version also would have worked.

So, it seems the root cause is that Java 1.7.0_85 deprecated/disabled a bunch of SSL ciphers (by default?) such that it makes it incompatible with Java 1.7.0_79 (or other lower versions).  Nasty business.

I would love to see a recommended proposed fix from the Go team, perhaps in the form of a description of how to enable the old ciphers on the new Java version (or enable the new ciphers on the old Java version). The alternative appears to be having to upgrade all the Agents' and the Server's Java versions to 1.7.0_85 simultaneously, which would be unpleasant but reasonable given this latest Java version release is very recent and also out of your direct control.

**Comment by cz8s** [comment]
debians openjdk security update also breaks ssl here. 7u79-2.5.5-1~deb7u1 still works, but 7u79-2.5.6-1~deb8u1 creates this error in the server.log:
```
2015-07-28 08:10:31,143  WARN [1278313939@qtp-558049888-16] log:76 - javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suite
s are inappropriate)
1278313939@qtp-558049888-16, called closeOutbound()
1278313939@qtp-558049888-16, closeOutboundInternal()
Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
No available cipher suite for SSLv2Hello
No available cipher suite for SSLv3
No available cipher suite for TLSv1
No available cipher suite for TLSv1.1
No available cipher suite for TLSv1.2
```

I

**Comment by JamesMGreene** [comment]
FYI, the version that I downgraded to on Amazon Linux (basically RHEL) is equivalent to the extended version number (package release) that @cz8ss mentioned working for him:  `1:1.7.0.79-2.5.5.1.59.amzn1.x86_64`

**Comment by DrStrangepork** [comment]
I experienced this same issue on Ubuntu 14.04 LTS. After upgrading to openjdk-7-jre-headless_7u79-2.5.6-0ubuntu1.14.04.1, my go-agent experienced these same errors. Downgrading to openjdk-7-jre-headless_7u51-2.4.6-1ubuntu4 resolved my issue.

**Comment by JamesMGreene** [comment]
Any updates, @jyotisingh @ketan et al?

**Comment by wilb** [comment]
Upgrading to go-agent & go-server 15.2.0-2248 resolves the issue for me on Debian Wheezy.

**Comment by JamesMGreene** [comment]
@wilb: What are the `java -version` outputs on your agents and server?

**Comment by wilb** [comment]
Server:
```java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)```

Wheezy Agent:
```java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)```

Jessie Agent:
```java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)```

**Comment by rouanw** [comment]
Thanks @wilb. Upgrading to 15.2.0-2248 worked for me too.

**Comment by cz8s** [comment]
15.2.0-2248 works for me. great.

**Comment by jyotisingh** [comment]
Some context first: Go 15.1.0 server uses jetty6 by default which fails if the communication involves any cipher other than : `SSL_RSA_WITH_RC4_128_SHA`, `SSL_RSA_EXPORT_WITH_RC4_40_MD5`, and `SSL_RSA_WITH_RC4_128_MD5`. 15.2.0 on the other hand uses jetty9 by default which can handle all ciphers. 

If you go through the [logs](https://github.com/gocd/gocd/issues/1381#issuecomment-125251041) shared by @JamesMGreene closely, the error message is `no cipher suites in common`. This basically means the server and the client(go-agent) could not agree on any common cipher suite for communication. Agent runs using java 7u85. As @JamesMGreene mentioned earlier, a bunch of SSL ciphers were disabled by default on [7u85](http://www.oracle.com/technetwork/java/javase/7u85-relnotes-2587591.html), specifically the RC4 ones. For this communication, agent presents the ciphers that it would like to use (ie. `TLS_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV`). The only ciphers that Go 15.1.0(jetty6) will work with are `SSL_RSA_WITH_RC4_128_SHA, SSL_RSA_EXPORT_WITH_RC4_40_MD5, SSL_RSA_WITH_RC4_128_MD5`. Hence they cannot agree on a common cipher. If you switch the java version on agent to 7u79, and try ssl-debugging again, you would see that the RC4 ciphers are being sent by the agent and hence the communication succeeds. We have seen similar issue happening when agent runs on oracle java 7 but the server uses openjdk7. The workaround here is basically trying to get a version of java on your agent that can support the RC4 ciphers that this version of Go can work with.

Moving on to 15.2.0. While Go (being powered by jetty9) can now work with stronger ciphers, if the java version installed on server does not support them, not much changes. For instance, openjdk8 does not support ECC yet and if your Go server runs on this, whereas the Go agent runs on say oracle java7, then you would again come across no-common-cipher error. 

Be it on 15.1 or 15.2, if the version of java version and make(ie. openjdk, oracle etc) installed is the same on both server and agent, the communication should normally succeed. However, If it fails, then ssl-debugging should help understand the real issue.

**Comment by marcelboettcher** [comment]
Upgrading to go-server 15.2.0-2248 resolves the issue for me on Ubuntu 14.
Make sure to backup your files before updating via backup function in admin section. My cipher file was gone and I needed the old one to get the server up and running.

**Comment by zhmocean** [comment]
```
2016-01-04 21:30:38,014 [loopThread] INFO  apache.commons.httpclient.HttpMethodDirector:444 - Retrying request
2016-01-04 21:30:38,085 [loopThread] ERROR go.agent.service.AgentUpgradeService:64 - [Agent Upgrade] Couldn't connect to: https://10.130.130.81:8154/go/admin/latest-agent.status: javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
2016-01-04 21:30:38,086 [loopThread] ERROR thoughtworks.go.agent.AgentController:164 - There has been a problem with one of Go's SSL certificates. This can be caused by a man-in-the-middle attack, or by pointing the agent to a new server, or by deleting and re-installing Go Server. Go will ask for a new certificate. If this fails to solve the problem, try deleting config/trust.jks in Go Agent's home directory.
javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
```

I have the connect error with agent at CentOS 6.5 to server at Ubuntu 12(both openjdk-1.7.0_91), even clear all of agent data.
But have no error at Ubuntu 12(agent) to Ubuntu 12(server) , both openjdk-1.7.0_91 too.
Any SSL issue with different OS?
Agent and server both 15.3.1-2777.
thx

**Comment by zhmocean** [comment]
resolve the error with keyException when install latest nss...- -!

**Comment by ketan** [comment]
Java depends on NSS to provide security capabilities including ssl/tls and ciphers. I'm going to mark this issue as closed since it does not appear to be a go issue, but a misconfiguration between the JVM capabilities (part of which is provided by NSS).

We should encourage users to simply upgrade Java and NSS to the latest versions to mitigate this issue.

Please post a comment if you think otherwise, and I'll re-open the issue.
