### ISSUE TITLE
"Configuration file is not valid : This field is required" when trying to save configuration of custom JSON API plugin

### ISSUE THREAD

**Issue by jmnarloch** [gocd/gocd#1518]
The problem originated from here: https://github.com/gocd/sample-plugins/issues/4#issuecomment-142682746

I've installed the curl-task-plugin and I've tried to add it's task to the pipeline, as a result when I clicked "Save" I've got message "Save failed, see errors below" and saw error in server logs:

```
2015-09-23 19:57:02,192 ERROR [540585569@qtp-117244645-17] GoConfigDataSource:214 - Configuration file is not valid : This field is required
com.thoughtworks.go.config.exceptions.GoConfigInvalidException: This field is required
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:142)
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:115)
	at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:86)
	at com.thoughtworks.go.config.GoConfigDataSource.configAsXml(GoConfigDataSource.java:313)
	at com.thoughtworks.go.config.GoConfigDataSource.getModifiedConfig(GoConfigDataSource.java:244)
	at com.thoughtworks.go.config.GoConfigDataSource.writeWithLock(GoConfigDataSource.java:201)
	at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:97)
	at com.thoughtworks.go.config.GoConfigFileDao.updateConfig(GoConfigFileDao.java:222)
	at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:260)
	at com.thoughtworks.go.server.service.GoConfigService.updateConfigFromUI(GoConfigService.java:305)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Any ideas?

**Comment by zabil** [comment]
Answers here https://github.com/gocd/sample-plugins/issues/4#issuecomment-142682746

Closing this a duplicate.
