### ISSUE TITLE
Repositories with a `git` folder + complex submodules still generate errors

### ISSUE THREAD

**Issue by gajwani** [gocd/gocd#152]
# Steps to reproduce
- Create a new Pipeline (optionally in a new pipeline group).
- Add the material [CF-Release](https://github.com/cloudfoundry/cf-release) using the SSH (`git@github.com:cloudfoundry/cf-release.git`) or HTTPS (`git@github.com:cloudfoundry/cf-release.git`) retrieval links.
- Add a default job/task which does something inconsequential, such as `ls -la`
- Attempt to start the pipeline.
- **_Note**_: This repository contains submodules within submodules. This is another edge case to consider.
# Expected Result
- The pipeline runs, and the `ls` shows the presence of a `cf-release` folder.
# Actual Result
- The pipeline is never scheduled. The following errors/warnings are in the go-server.log file:

```
2014-04-29 22:13:04,629  WARN [87@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:117 - [Material Update] Modification check failed for material: URL: https://github.com/cloudfoundry/cf-release.git, Branch: master
java.lang.RuntimeException:
    at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:82)
    at com.thoughtworks.go.domain.materials.git.GitCommand.latestModification(GitCommand.java:66)
    at com.thoughtworks.go.config.materials.git.GitMaterial.latestModification(GitMaterial.java:104)
    at com.thoughtworks.go.server.service.materials.GitPoller.latestModification(GitPoller.java:31)
    at com.thoughtworks.go.server.service.materials.GitPoller.latestModification(GitPoller.java:27)
    at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:107)
    at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
    at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
    at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:72)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:171)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:130)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:46)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:92)
    at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
    at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:89)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.thoughtworks.go.util.command.CommandLineException: Working directory "/var/vcap/store/gocd/pipelines/flyweight/6badd25c-53bf-440f-a768-b40c91e24795/src/router" does not exist!
    at com.thoughtworks.go.util.command.CommandLine.checkWorkingDir(CommandLine.java:343)
    at com.thoughtworks.go.util.command.CommandLine.setWorkingDir(CommandLine.java:334)
    at com.thoughtworks.go.util.command.CommandLine.withWorkingDir(CommandLine.java:417)
    at com.thoughtworks.go.domain.materials.git.GitCommand.cleanUnversionedFiles(GitCommand.java:183)
    at com.thoughtworks.go.domain.materials.git.GitCommand.cleanAllUnversionedFiles(GitCommand.java:140)
    at com.thoughtworks.go.domain.materials.git.GitCommand.fetchAndReset(GitCommand.java:129)
    at com.thoughtworks.go.domain.materials.git.GitCommand.fetchAndResetToHead(GitCommand.java:166)
    at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:79)
    ... 22 more
```

And...

```
2014-04-29 22:15:45,916  WARN [materialUpdateThread] MaterialUpdateService:146 - [Material Update] Skipping update of material GitMaterial{url=https://github.com/cloudfoundry/cf-release.git, branch='master', submoduleFolder='null'} which has been in-progress since Tue Apr 29 22:15:15 UTC 2014
```

In an earlier run of the same pipeline, we witnessed something slightly different, although we are having some difficulty recreating this particular message:

```
2014-04-29 01:53:14,541  WARN [78@MessageListener for ScheduleCheckListener] BuildCauseProducerService:189 - Error while scheduling pipeline: cf-release Possible Reasons: (1) Upstream pipelines have not been built yet. (2) Materials do not match between configuration and build-cause.
```

**Comment by arvindsv** [comment]
Related PRs are: #278, #282, #285.

**Comment by vhasus** [comment]
GO's git extension faces problems when git submodule url changes over the lifetime of a project
If the submodule config (i.e .gitmodules) contains:

[submodule "a"]
        path = b
        url = git-repo-url

If a != b. Checkout on agent/server will fail with an error along the lines of 'Could not find pipelines/flyweights/<some-uuid>/a'

The simplest solution was to set a=b.

**Comment by lorijoan** [comment]
We saw this as well.  We had a submodule that was listed in the .gitmodules config, but was subsequently removed.  The submodule however was not removed from the project itself only the .gitmodules.  When GOCD was running, it naturally got very confused and complained about this submodule.

We decided to do a delete of the flyweight folder (as originally we didn't realise what the exact issue was) which then upset it even more.  So we put back the flyweight folder that was missing, recloned the project and then properly removed the submodule.

The flyweight folder was still upset until we did a hacky fix that was seen elsewhere of just changing the capitalisation of the git material.  This caused a new flyweight folder to be created and then a successful run.  Now, reverting the capitalisation hack, we have gotten the original flyweight folder working.

We're all stable now again, but I just thought it'd be interesting to add this case of what went wrong should you guys be looking at this kind of stuff.

**Comment by prisamuel** [comment]
We are seeing a similar issue with cloning repos with complex submodules.

From GoCD the error is 
```
Modification check failed for material: URL: https://xxx@github.com/org/repo.git, Branch: master [Feb-23 15:48:02]
Working directory: pipelines/flyweight/c58ddf2e-25e0-4708-bb61-bc5aa25b0e24
```

The go-cd logs show this:
```
2016-02-23 15:37:32,267  WARN [93@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:121 - [Material Update] Modification check failed for material: URL: https://5f6a1723884cc736494fcfcc76bccee2eb686890@github.com/EconomistDigitalSolutions/mt-content-blogs.git, Branch: master
java.lang.RuntimeException: Working directory: pipelines/flyweight/c58ddf2e-25e0-4708-bb61-bc5aa25b0e24

	at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:82)
	at com.thoughtworks.go.domain.materials.git.GitCommand.modificationsSince(GitCommand.java:70)
	at com.thoughtworks.go.config.materials.git.GitMaterial.modificationsSince(GitMaterial.java:110)
	at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:36)
	at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:27)
	at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:110)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:57)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:155)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:147)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:110)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:51)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:31)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.thoughtworks.go.util.command.CommandLineException: Working directory "/var/lib/go-server/pipelines/flyweight/c58ddf2e-25e0-4708-bb61-bc5aa25b0e24/vendor/github.com/org/submodule-repo" does not exist!
	at com.thoughtworks.go.util.command.CommandLine.checkWorkingDir(CommandLine.java:343)
	at com.thoughtworks.go.util.command.CommandLine.setWorkingDir(CommandLine.java:334)
	at com.thoughtworks.go.util.command.CommandLine.withWorkingDir(CommandLine.java:417)
	at com.thoughtworks.go.domain.materials.git.GitCommand.cleanUnversionedFiles(GitCommand.java:192)
	at com.thoughtworks.go.domain.materials.git.GitCommand.cleanAllUnversionedFiles(GitCommand.java:141)
	at com.thoughtworks.go.domain.materials.git.GitCommand.fetchAndReset(GitCommand.java:123)
	at com.thoughtworks.go.domain.materials.git.GitCommand.fetchAndResetToHead(GitCommand.java:167)
	at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:79)
	... 19 more
```

**Comment by phylake** [comment]
Seeing this issue as well. I assumed a material fetch was a simple `git clone` or `git fetch` equivalent command and that I would have to support submodules explicitly. In a job I have a command `git submodule update --init --recursive` to do that and was surprised by this behavior.

Perhaps submodules need explicit support in GoCD for some reason but otherwise I the hidden & surprising git submodule commands should be removed. I would never expect a CI/CD system to manage those for me and now that's it's blocking me from using git submodules in a normal way I'm really not happy about it.

Is there a known workaround?

> The simplest solution was to set a=b.

:point_up: Did not work for me

**Comment by prisamuel** [comment]
Fixed my issue with this 'workaround' that mentioned in the post above.

'The flyweight folder was still upset until we did a hacky fix that was seen elsewhere of just changing the capitalisation of the git material. This caused a new flyweight folder to be created and then a successful run.'

**Comment by jswetzen** [comment]
I had a similar issue, but the problem arose from assuming that `git submodule update --init --recursive` was actually called by GoCD. The surprising submodule commands can be found in [GitMaterialUpdater.updateSubmodules()](https://github.com/gocd/gocd/blob/8a2e663e6faf0eb25054530ea7da5e94f51190e7/common/src/com/thoughtworks/go/domain/materials/git/GitMaterialUpdater.java#L69).
To me it seems reasonable to either do no submodule clone, do it recursively or have an option for recursive clone on the website. In any case the actual behaviour needs to be documented.

**Comment by elboletaire** [comment]
Same problem here, but for a removed submodule. After removing the submodule (the project remain without any submodule) it started crashing with the above mentioned error (cannot find the submodule path).

**Comment by trinitronx** [comment]
In case it helps, I've got some observations about how this can occur.
After running into corrupted flyweight directory issues, my team has noticed a couple cases where this can happen:

1. Removing a git submodule
2. Disk space on agent full - corrupt or incomplete flyweight bare repo clone
3. Moving the intended `origin` for a Git repo to a new location - causes GoCD to get confused, as the old flyweight `origin` points to the old remote repo.

Usually our fix has been to make sure the agent host has free disk space and then remove the flyweight directory that GoCD complains about, then things start working fine again.

Perhaps a way GoCD could cope with this issue is to allow cleaning out the workspace / flyweight directory for a pipeline & start from a fresh git clone?

**Comment by cattz** [comment]
In any case, it would be useful to have an option to ignore the submodules: 
- It will allow you to handle them with your own scripts/commands
- It will allow you to clone them just when needed (eg: you only need the promote/deploy/publish scripts that are in your superproject)
