### ISSUE TITLE
Downstream pipelines failing to automatically trigger

### ISSUE THREAD

**Issue by codemonkeycode** [gocd/gocd#1529]
I use version 14.2 of GoCD, a central set-up with 9 agent servers.

Up until fairly recently everything was running smoothly. At some point downstream pipelines stopped automatically triggering after the upstream pipelines completed successfully. This behavior was seen across the board. All other functionality (to my knowledge) stayed the same. We are trying to determine what happened and how to fix our GoCD instance. Going through the process of re-creating pipelines allowed us to get back the downstream pipeline automation, but the functionality broke again a couple weeks later.

One theory is directly editing the config XML somehow caused this issue. To troubleshoot more verbose logging for go-server was enabled. There were many of these error messages in the logs:

```
2015-09-23 17:11:42,985 DEBUG [66@MessageListener for WorkFinder] GoCache:93 - transaction active during cache put for com.thoughtworks.go.server.dao.JobInstanceSqlMapDao_jobInstanceWithTranistionIds_33696 = JobInstance{stageId=16695, name='RNTData', state=Scheduled, result=Unknown, agentUuid='null', stateTransitions=[com.thoughtworks.go.domain.JobStateTransition@65367f53[currentState=Scheduled,stateChangeTime=Wed Sep 23 17:11:39 EDT 2015,jobId=33696,stageId=16695,id=194192]], scheduledDate=Wed Sep 23 17:11:39 EDT 2015, timeProvider=com.thoughtworks.go.util.TimeProvider@5ce1560e, ignored=false, matcher=com.thoughtworks.go.domain.BuildOutputMatcher@4dd8e0c5, log=com.thoughtworks.go.domain.NullJobInstanceLog@598ccd70, identifier=JobIdentifier[Rightnow-RunUpdate-PROD, 32, 32, RunUpdates, 1, RNTData, 33696], plan=null, runOnAllAgents=false}
java.lang.IllegalStateException
    at com.thoughtworks.go.server.cache.GoCache.put(GoCache.java:93)
    at com.thoughtworks.go.server.cache.GoCache.put(GoCache.java:86)
    at com.thoughtworks.go.server.dao.JobInstanceSqlMapDao.buildByIdWithTransitions(JobInstanceSqlMapDao.java:85)
    at com.thoughtworks.go.server.service.JobInstanceService.buildByIdWithTransitions(JobInstanceService.java:101)
    at com.thoughtworks.go.server.service.ScheduleService.updateAssignedInfo(ScheduleService.java:672)
    at com.thoughtworks.go.server.service.BuildAssignmentService$2$1.doInTransaction(BuildAssignmentService.java:198)
    at com.thoughtworks.go.server.transaction.TransactionTemplate$2.doInTransaction(TransactionTemplate.java:39)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
    at com.thoughtworks.go.server.service.BuildAssignmentService$2.surrounding(BuildAssignmentService.java:196)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.transactionSurrounding(TransactionTemplate.java:71)
    at com.thoughtworks.go.server.service.BuildAssignmentService.createWork(BuildAssignmentService.java:181)
    at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:106)
    at com.thoughtworks.go.server.messaging.scheduling.BuildAssignmentServiceAssigner.assignWorkToAgent(BuildAssignmentServiceAssigner.java:44)
    at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:56)
    at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:30)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
```

We may have been getting these error messages all along, but unfortunately there is no way to go back in time and determine that.

Any help would be appreciated. Please let me know if I can provide more detail. Thanks

**Comment by zabil** [comment]
@codemonkeycode I don't think this error is associated to the problem you are facing.
Here's the piece of code that does the logging
```
        if (predicate.isTrue()) {
            if (LOGGER.isDebugEnabled()) {
                LOGGER.debug(String.format("transaction active during cache put for %s = %s", key, value), new IllegalStateException());
            }
            return;
        }
        ehCache.put(new Element(key, value));
```

It's an instruction not put anything onto the cache when there's a running transaction. 
It comes frequently on your logs because the debug messages are on.

Ignore these messages for now and look out anything else that's related to the pipeline that's not getting triggered.

**Comment by codemonkeycode** [comment]
@zabil went through the exercise of tracing through the logs, between the time the upstream pipeline/stage reached a finished status, and looking for reference to the downstream pipeline that should but doesn't trigger

We tried two different log levels and ran the exact same scenario to see if there was any more information in one over the other. Our upstream pipeline is **Rightnow-RunUpdate-PROD**, when the **RunUpdates** stage finishes it *should* kick off the downstream pipeline **Rightnow-RunCRDB-PROD**

In the one log we see a fair few of the following, and nothing else really useful:
```
2015-09-23 17:16:57,812 DEBUG [76@MessageListener for ScheduleCheckListener] BuildCauseProducerService:205 - Repository for [Rightnow-RunCRDB-PROD] modified; scheduling...
2015-09-23 17:16:57,818 DEBUG [76@MessageListener for ScheduleCheckListener] AutoBuild:129 - [Revision Resolution] Fan-In Resolution is active for pipeline Rightnow-RunCRDB-PROD
```


In the other log covers when the pipeline/stage finishes, and the first time when the downstream pipeline is shown as busy

Upstream pipeline is competing:
```
2015-09-23 16:29:05,007  INFO [1762492324@qtp-1787265837-14] BuildRepositoryRemoteImpl:104 - [Agent [wdciagtl03.cfpb.local, 10.95.79.179, 3e817931-f583-4617-9850-d72d86edf089, 415e7c8f-4ddb-40e6-8fdc-6a19213ab5b5]] is reporting status [Completing] for [Build [Rightnow-RunUpdate-PROD/31/RunUpdates/1/RNTData/33690]]
2015-09-23 16:29:05,008 DEBUG [1762492324@qtp-1787265837-14] BuildRepositoryService:54 - Changing status of job instance with identifier JobIdentifier[Rightnow-RunUpdate-PROD, 31, 31, RunUpdates, 1, RNTData, 33690] to Completing from agent[3e817931-f583-4617-9850-d72d86edf089]
```

```
2015-09-23 16:29:05,018 DEBUG [61@MessageListener for MessageLogger] MessageLogger:35 - [JobStatusMessage: 3e817931-f583-4617-9850-d72d86edf089 JobIdentifier[Rightnow-RunUpdate-PROD, 31, 31, RunUpdates, 1, RNTData, 33690] Completing]
2015-09-23 16:29:05,023  INFO [1762492324@qtp-1787265837-14] BuildRepositoryRemoteImpl:104 - [Agent [wdciagtl03.cfpb.local, 10.95.79.179, 3e817931-f583-4617-9850-d72d86edf089, 415e7c8f-4ddb-40e6-8fdc-6a19213ab5b5]] is reporting status and result [Completed, Passed] for [Build [Rightnow-RunUpdate-PROD/31/RunUpdates/1/RNTData/33690]]
```

First reference to the downstream pipeline trying to schedule after the upstream pipeline completes:
```
2015-09-23 16:29:12,333 DEBUG [77@MessageListener for ScheduleCheckListener] ScheduleCheckListener:40 - ScheduleCheckMessage for Rightnow-RunCRDB-PROD is received
2015-09-23 16:29:12,333 DEBUG [73@MessageListener for ScheduleCheckListener] Modifications:133 - Checking Ignore filters for GitMaterialConfig{url=https://github.cfpb.gov/ConsumerResponse/schemas.git, branch='master', submoduleFolder='null'}
2015-09-23 16:29:12,336 DEBUG [73@MessageListener for ScheduleCheckListener] Modifications:134 - Ignored files : [testrunner.py, report_runner.py]
2015-09-23 16:29:12,336 DEBUG [73@MessageListener for ScheduleCheckListener] Modifications:135 - Changed files : [crdw/tables/3_ADDRESSES.sql]
2015-09-23 16:29:12,333 TRACE [produceBuildCausesThread] PipelineScheduler:? - try to schedule pipeline Rightnow-RunCRDB-PROD, current pipeline state: {ReplicateSchemas-PROD=BUSY, Replicate-STG=BUSY, Narrative-Alert-Report=BUSY, Run-Healthchecks-STG=BUSY, Rightnow-RunUpdate-PROD=BUSY, Rightnow-Setup-STG=BUSY, Rightnow-RunCRDB-PROD=BUSY, Rightnow-BuildCoreCRDB-DEV=IDLE, RightNow-NarrativeScrub-Specific-PROD=IDLE, marketlend=IDLE, Singhydemo=IDLE, CaseETL-DEV=IDLE, CCDB-SocrataPush-STG=IDLE, Rightnow-SetupEnv-PROD=IDLE, Rightnow-BryanExtCRDB-STG=IDLE, -RNTNarrativeScrubber-DEV=IDLE, Rightnow-BuildExtCRDB-DEV=IDLE, Rightnow-BuildExtCRDB-PROD=IDLE, Rightnow-UpgradeTesting-Bootstrap-STG=IDLE, TestEnvVar=IDLE, Rightnow-GrantAccess-DEV=IDLE, Rightnow-BootstrapDataParrallel-PROD=IDLE, RightNow-NarrativeScrub-3-DEV=IDLE, Replicate-DEV=IDLE, ComplaintModelSetup-DEV=IDLE, RightNow-NarrativeScrubSetup-UPGRADE-DEV=IDLE, Rightnow-Setup-DEV=IDLE, Rightnow-UpdateData-STG=IDLE, Clean-Agent-Directories=IDLE, Test1=IDLE, Rightnow-Setup-PROD=IDLE, Rightnow-BryanCCDBHealth-STG=IDLE, Demo-STG=IDLE, Rightnow-QueryLinter-PROD=IDLE, NonsenseScraper=IDLE, Rightnow-BootstrapDataParrallel-STG=IDLE, RightNow-NarrativeScrubSetup-1.3-PROD=IDLE, Complaint-Elasticsearch-Load=IDLE, ComplaintModelRunner-DEV=IDLE, Rightnow-RunCoreCRDB-STG=IDLE, Rightnow-QueryLinter-STG=IDLE, Rightnow-BuildCoreCRDB-STG=IDLE, RightNow-NarrativeScrubSetup-STAGING=IDLE, Rightnow-ReplicateData-PROD=IDLE, DownloadAttachments=IDLE, Rightnow-UpdateData-DEV=IDLE, Rightnow-BootstrapDataParrallel-DEV=IDLE, Socrata-Push-DEV=IDLE, Rightnow-UpdateData-PROD=IDLE, Rightnow-BuildExtCRDB-STG=IDLE, RightNow-NarrativeScrubSetup-PROD=IDLE, RightNow-NarrativeScrubSetup-3-DEV=IDLE, Demo=IDLE, Rightnow-BootstrapData-PROD=IDLE, Rightnow-Setup-DEV-COPY=IDLE, TestShell=IDLE, Rightnow-BryanBuildCoreOnlyCRDB-STG=IDLE, Healthchecks-DEV-Al=IDLE, CRDB-Topline-PROD=IDLE, Rightnow-BuildCoreCRDB-PROD=IDLE, Run-Healthchecks=IDLE, Rightnow-UpgradeTesting-Setup-STG=IDLE, Rightnow-GrantAccess-STG=IDLE, RightNow-NarrativeScrub-UPGRADE-DEV=IDLE, Elasticsearch_CreateIndices=IDLE, Rightnow-RunExtCRDB-PROD=IDLE, RightNow-NarrativeScrub-PROD=IDLE, Rightnow-BryanBuildCoreCRDB-STG=IDLE, RightNow-NarrativeScrub-STAGING=IDLE, Rightnow-RunExtendedCRDB-STG=IDLE}
```

Then later the downstream pipeline becomes idle without any type of explanation I could see in the logs:
```

2015-09-23 16:29:12,483 TRACE [98@MessageListener for PipelineScheduler] PipelineScheduler:? - marked pipeline Rightnow-RunCRDB-PROD as IDLE, current pipelines state: {ReplicateSchemas-PROD=BUSY, Replicate-STG=BUSY, Narrative-Alert-Report=IDLE, Run-Healthchecks-STG=IDLE, Rightnow-RunUpdate-PROD=BUSY, Rightnow-Setup-STG=IDLE, Rightnow-RunCRDB-PROD=IDLE, Rightnow-BuildCoreCRDB-DEV=BUSY, RightNow-NarrativeScrub-Specific-PROD=BUSY, marketlend=BUSY, Singhydemo=BUSY, CaseETL-DEV=BUSY, CCDB-SocrataPush-STG=BUSY, Rightnow-SetupEnv-PROD=BUSY, Rightnow-BryanExtCRDB-STG=BUSY, -RNTNarrativeScrubber-DEV=BUSY, Rightnow-BuildExtCRDB-DEV=BUSY, Rightnow-BuildExtCRDB-PROD=BUSY, Rightnow-UpgradeTesting-Bootstrap-STG=BUSY, TestEnvVar=BUSY, Rightnow-GrantAccess-DEV=BUSY, Rightnow-BootstrapDataParrallel-PROD=BUSY, RightNow-NarrativeScrub-3-DEV=BUSY, Replicate-DEV=BUSY, ComplaintModelSetup-DEV=BUSY, RightNow-NarrativeScrubSetup-UPGRADE-DEV=BUSY, Rightnow-Setup-DEV=BUSY, Rightnow-UpdateData-STG=BUSY, Clean-Agent-Directories=BUSY, Test1=BUSY, Rightnow-Setup-PROD=BUSY, Rightnow-BryanCCDBHealth-STG=BUSY, Demo-STG=BUSY, Rightnow-QueryLinter-PROD=BUSY, NonsenseScraper=BUSY, Rightnow-BootstrapDataParrallel-STG=BUSY, RightNow-NarrativeScrubSetup-1.3-PROD=BUSY, Complaint-Elasticsearch-Load=BUSY, ComplaintModelRunner-DEV=BUSY, Rightnow-RunCoreCRDB-STG=BUSY, Rightnow-QueryLinter-STG=BUSY, Rightnow-BuildCoreCRDB-STG=BUSY, RightNow-NarrativeScrubSetup-STAGING=BUSY, Rightnow-ReplicateData-PROD=BUSY, DownloadAttachments=BUSY, Rightnow-UpdateData-DEV=BUSY, Rightnow-BootstrapDataParrallel-DEV=BUSY, Socrata-Push-DEV=BUSY, Rightnow-UpdateData-PROD=BUSY, Rightnow-BuildExtCRDB-STG=BUSY, RightNow-NarrativeScrubSetup-PROD=BUSY, RightNow-NarrativeScrubSetup-3-DEV=BUSY, Demo=BUSY, Rightnow-BootstrapData-PROD=BUSY, Rightnow-Setup-DEV-COPY=BUSY, TestShell=BUSY, Rightnow-BryanBuildCoreOnlyCRDB-STG=BUSY, Healthchecks-DEV-Al=BUSY, CRDB-Topline-PROD=BUSY, Rightnow-BuildCoreCRDB-PROD=BUSY, Run-Healthchecks=BUSY, Rightnow-UpgradeTesting-Setup-STG=BUSY, Rightnow-GrantAccess-STG=BUSY, RightNow-NarrativeScrub-UPGRADE-DEV=BUSY, Elasticsearch_CreateIndices=BUSY, Rightnow-RunExtCRDB-PROD=BUSY, RightNow-NarrativeScrub-PROD=BUSY, Rightnow-BryanBuildCoreCRDB-STG=BUSY, RightNow-NarrativeScrub-STAGING=BUSY, Rightnow-RunExtendedCRDB-STG=BUSY}
```
