### ISSUE TITLE
Internal Server Error 500 on installing GO server 15.3.0-2559 on go02.thoughworks.com

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#1561]
Steps:

Upgrade go02.thoughworks.com from 15.2.0-2246 to 15.3.0-2559 using the go02 pipeline in go05.thoughtworks.com
The pipeline passed but accessing the url http://go02.thoughworks.com:8153/go returns Http error 500 - Internal server error 

Below is the exception trace shown on the browser and in logs

```
Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/execjs-2.6.0/lib/execjs/runtimes.rb:47:in `autodetect'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/execjs-2.6.0/lib/execjs.rb:5:in `ExecJS'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/execjs-2.6.0/lib/execjs.rb:4:in `(root)'
from org/jruby/RubyKernel.java:1085:in `require'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/mithril_rails-0.0.7/lib/mithril_rails/msx.rb:1:in `(root)'
from org/jruby/RubyKernel.java:1085:in `require'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/mithril_rails-0.0.7/lib/mithril_rails/msx.rb:1:in `(root)'
from org/jruby/RubyKernel.java:1085:in `require'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/mithril_rails-0.0.7/lib/mithril_rails.rb:1:in `(root)'
from org/jruby/RubyArray.java:1613:in `each'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/mithril_rails-0.0.7/lib/mithril_rails.rb:1:in `(root)'
from org/jruby/RubyArray.java:1613:in `each'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/runtime.rb:1:in `(root)'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/runtime.rb:76:in `require'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/runtime.rb:72:in `require'
from org/jruby/RubyKernel.java:1085:in `require'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/runtime.rb:61:in `require'
from org/jruby/RubyKernel.java:1085:in `require'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler.rb:134:in `require'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/config/application.rb:8:in `(root)'
from /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/config/environment.rb:1:in `(root)'
```

**Comment by ketan** [comment]
Suggested way to fix this is to add the following line to the file [`gocd/server/webapp/WEB-INF/init.rb`](https://github.com/gocd/gocd/blob/01e406aa4eb821a425288adbe62ecce5acdb56ca/server/webapp/WEB-INF/init.rb)

```ruby
ENV['EXECJS_RUNTIME'] = 'Disabled'
```

See [this](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/execjs-2.6.0/lib/execjs/runtimes.rb#L56-L64) for this "hack"

**Comment by rajiesh** [comment]
This issue verified on go-server 15.3.0-2597. go02.thoughworks.com and go05.thoughworks.com are upgraded to 15.3.0-2597
