### ISSUE TITLE
OSGi agent extra packages

### ISSUE THREAD

**Issue by jmnarloch** [gocd/gocd#1571]
I've been facing an issue when I tried to start the Project Reactor task in Go Agent. Project reactor uses sun.mics.Unsafe for some low level memory management. I was able to install plugin, add the task to the pipeline, but when I run the build I can see an exception:

```
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
    at reactor.jarjar.com.lmax.disruptor.util.Util$1.run(Util.java:102)
    at reactor.jarjar.com.lmax.disruptor.util.Util$1.run(Util.java:99)
    at java.security.AccessController.doPrivileged(Native Method)
    at reactor.jarjar.com.lmax.disruptor.util.Util.<clinit>(Util.java:108)
    at reactor.jarjar.com.lmax.disruptor.RingBufferFields.<clinit>(RingBuffer.java:34)
    at reactor.fn.timer.HashWheelTimer.<init>(HashWheelTimer.java:110)
    at reactor.fn.timer.HashWheelTimer.<init>(HashWheelTimer.java:91)
    at reactor.fn.timer.HashWheelTimer.<init>(HashWheelTimer.java:67)
    at reactor.Environment.getTimer(Environment.java:792)
    at reactor.Environment.timer(Environment.java:184)
    at reactor.rx.Streams.period(Streams.java:405)
```

All the dependencies are in the /lib dir and they also correctly define the import packages in their OSGi complaint manifest: sun.mics. Unfortunately this does not work. Is there a way how can I define extra system packages to be loaded by Apache Felix? How can I do that?

I try to specify the org.osgi.framework.bootdelegation or org.osgi.framework.system.packages.extra without result.

http://stackoverflow.com/questions/32840584/go-cd-agent-apache-felix-settings
https://github.com/reactor/reactor/issues/553

**Comment by arvindsv** [comment]
You should try specifying that property on the Go Agent side, not on the Go Server side. Maybe [this thread](https://groups.google.com/d/topic/go-cd/tpq3SZYxhlA/discussion) gives you some ideas.

It nothing works, you might be able to change the boot delegated packages [here](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-infra/src/com/thoughtworks/go/plugin/infra/FelixGoPluginOSGiFramework.java#L182-L183) and try building an installer locally and try with it.

**Comment by arvindsv** [comment]
Closing. Haven't heard back from issue author.
