### ISSUE TITLE
MaxBackTrackLimitReachedException : getting this exception repeatedly

### ISSUE THREAD

**Issue by lethaldose** [gocd/gocd#1583]
- We recently started getting `MaxBackTrackLimitReachedException` from a pipeline which depends on 3 materials - a git repo, and artifacts from 2 pipelines. 
- Checked the code and it seems the exception depends on this env variable `SystemEnvironment.RESOLVE_FANIN_MAX_BACK_TRACK_LIMIT` which defaults to value 100
- Also it would be helpful to know what is a _MaterialRevision_ ?
- we are using go version - go-server-15.2.0-2248.noarch

Not sure what this error is. any insights would be helpful. thanks

_Stacktrace_

``` Stacktrace
2015-10-28 05:00:18,514 ERROR [81@MessageListener for ScheduleCheckListener] BuildCauseProducerService:244 - Error while scheduling pipeline: Smoke-Tests
com.thoughtworks.go.server.service.dd.MaxBackTrackLimitReachedException: Maximum Backtracking limit reached while trying to resolve revisions for material DependencyMaterialConfig{pipelineName='Web-Deployment', stageName='UAT'}
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.hasMoreInstances(DependencyFanInNode.java:233)
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.fillNextRevisions(DependencyFanInNode.java:122)
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.handleNeedMoreRevisions(DependencyFanInNode.java:83)
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.initRevision(DependencyFanInNode.java:75)
        at com.thoughtworks.go.server.service.dd.DependencyFanInNode.populateRevisions(DependencyFanInNode.java:61)
        at com.thoughtworks.go.server.service.dd.FanInGraph.initChildren(FanInGraph.java:314)
        at com.thoughtworks.go.server.service.dd.FanInGraph.computeRevisions(FanInGraph.java:177)
        at com.thoughtworks.go.server.service.PipelineService.getRevisionsBasedOnDependencies(PipelineService.java:235)
        at com.thoughtworks.go.server.service.AutoBuild.fanInOn(AutoBuild.java:131)
        at com.thoughtworks.go.server.service.AutoBuild.onModifications(AutoBuild.java:74)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:207)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:161)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:123)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:45)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:24)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by piotrekjanisz** [comment]
We have the same issue with 15.3.1. It produces a lot of error messages in the log file. 

What is the cause of this error? Is there a way we can fix our pipelines to avoid this error?

**Comment by srinivasupadhya** [comment]
When Go checks if a pipeline can be scheduled it tries to resolve the latest revisions of upstream dependencies available for that pipeline to consistent revisions. In the process of doing this it looks at 'x' number of older revisions of upstream dependencies. It might so happen that even after considerable number of older revisions Go is still unable to resolve upstream dependencies to consistent revisions & this could cause performance problems by hogging the CPU. To avoid this we put a limit for 'x' which is `SystemEnvironment.RESOLVE_FANIN_MAX_BACK_TRACK_LIMIT`. But this sometimes causes `MaxBackTrackLimitReachedException`, i.e. Go has looked at 'x' instances of upstream materials & was unable to resolve them to consistent revisions.

Solutions:
* Manually trigger the pipeline with consistent revisions of upstream pipelines once & Go should be ok from there on
* If Go Server is on a beefy box with enough memory & CPUs then you can bump up `RESOLVE_FANIN_MAX_BACK_TRACK_LIMIT`
* Turn off the fan-in feature altogether

**Comment by piotrekjanisz** [comment]
@srinivasupadhya Thank you for a quick response. It was very useful.

**Comment by xko** [comment]
@srinivasupadhya , we see this exception quite often.
I'm not sure if I get an algorythm behind it right. Could you please see if below is correct?

* Problem
   * Pipeline `Release` depends on manually triggered stage `approve-release` and git material `dev-git`. `approve-release` has the same git material several steps upstream
   * We're getting `Error while scheduling pipeline: Release` ... `limit reached while trying to resolve revisions for material DependencyMaterialConfig{pipelineName='Approve' , stageName='approve-release'}`
* Analysis
   * It tries to schedule `Release` every time `dev-git` changes, and tries to find corresponding `approve-release`
   * When `dev-git` is 100 revisions ahead we start to see this error
* The solution is to turn off `poll for new changes` in `dev-git` material in `Release`

**Comment by ccampanale** [comment]
@xko Slightly unrelated to your problem but to touch on the `Material of type Git (ssh://...) is specified more than once in the configuration...` error; GoCD essentially stores a single configuration for - or representation of - every material that is referenced in any pipeline. If that material is referenced again it's essentially just a pointer to that material's configuration in a way. Therefore, a git material can either be configured to be polled for changes, or not, but when it is set to poll GoCD polls for changes and then notifies any dependent pipelines that the material has been updated and provides the revision.

This is why you can't have the material polled in one pipeline and not in another pipeline. If you want to setup the git material and either turn on or off polling the setting needs to be changed on every pipeline that references the material (at least from my experience). This is that part that to me is frustrating. To do this, you'll need to manually modify the XML configuration file using an administrative account. Once changed in each location, you can save the config without getting errors.
