### ISSUE TITLE
"Modification check failed for material" due to git repository with invalid submodule commit

### ISSUE THREAD

**Issue by henriquegemignani** [gocd/gocd#1586]
Hello,

The Go Server was reporting the following error:

```
Modification check failed for material: URL: git@bitbucket.org:*snip*.git, Branch: master [Oct-29 19:39:02]
Working directory: pipelines\flyweight\83463146-cc07-4bde-ad7f-10cbfe24991d
```

Checking the go-server.log, we have the following:

```
2015-10-29 18:27:04,645  WARN [90@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:121 - [Material Update] Modification check failed for material: URL: git@bitbucket.org:*snip*.git, Branch: master
java.lang.RuntimeException: Working directory: pipelines\flyweight\83463146-cc07-4bde-ad7f-10cbfe24991d

    at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:82)
    at com.thoughtworks.go.domain.materials.git.GitCommand.modificationsSince(GitCommand.java:70)
    at com.thoughtworks.go.config.materials.git.GitMaterial.modificationsSince(GitMaterial.java:104)
    at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:36)
    at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:27)
    at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:110)
    at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:155)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:147)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:110)
    at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
    at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.thoughtworks.go.util.command.CommandLineException: Error performing command: --- Command ---
git submodule update
--- Environment ---
{}
--- INPUT ----


--OUTPUT ---

--- ERROR ---
STDERR: fatal: reference is not a tree: b51d6eb27d75637e3486d12c7e96f0b000ea96bc
STDERR: Unable to checkout 'b51d6eb27d75637e3486d12c7e96f0b000ea96bc' in submodule path 'src/lib'

---
```

The error message available in the log is way more helpful.

**Comment by arvindsv** [comment]
Is this a duplicate of [this](https://github.com/gocd/gocd/issues/152#issuecomment-146754575)?

**Comment by henriquegemignani** [comment]
No.
In this case the error is correct: running ```git submodule update``` causes an error, because the commit does not exist.
The issue is that the actual error message appears only in the server log, and not in the interface.

(One could say that the Go Server has no business dealing with submodules at all if it only plans to track new commits in the repository)
