### ISSUE TITLE
CCTray RSS feed in Go is empty

### ISSUE THREAD

**Issue by m1ndful** [gocd/gocd#1592]
Hello, we are experiencing an issue with Go's RSS feed for CCTray.
It doesn't show any projects. The content we got from https://go.site.com/go/cctray.xml is listed below.

```
<?xml version="1.0" encoding="utf-8"?>
<Projects>
</Projects>
```

The only thing I have found in logs related to 'rss' or 'cctray' are warning messages.

```
root@goserverhostname:/var/log/go-server# grep -ri 'cctray' ./*
./go-server.log.1:2015-11-04 10:14:32,974  WARN [CCTray-Queue-Processor] CcTrayActivityListener:111 - Failed to handle action in CCTray queue
./go-server.log.1:2015-11-04 10:16:06,672  WARN [CCTray-Queue-Processor] CcTrayActivityListener:111 - Failed to handle action in CCTray queue
```

Go details:

```
Go Server Version:  15.2.0(2248-c1f90a6aa3192a)
JVM version:    1.7.0_55
OS Information:     Linux 3.2.0-23-generic
```

**Comment by arvindsv** [comment]
Just after those lines, there should be some information (a stack trace). Is it there?

**Comment by m1ndful** [comment]
There are messages, but I don't think they are related to CCTray.
```
2015-11-04 07:46:41,527  WARN [CCTray-Queue-Processor] CcTrayActivityListener:111 - Failed to handle action in CCTray queuejava.lang.NullPointerException
2015-11-04 07:46:41,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:42,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:43,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:44,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:45,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:46,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:47,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:48,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:49,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
2015-11-04 07:46:50,437  WARN [materialUpdateThread] MaterialUpdateService:155 - [Material Update] Skipping update of material GitMaterial{url=https://user%40domain.com:******@another.git.domain.com:7990/scm/QQQ/project-name.git, branch='develop', submoduleFolder='null'} which has been in-progress since Wed Nov 04 07:36:50 GMT 2015
2015-11-04 07:46:50,586  INFO [consumeBuildCausesThread] ScheduleService:175 - [Pipeline Schedule] Scheduling pipeline Pipeline_NAME_NDA with build cause [ModificationBuildCause: modified by User name <users@email.com>]
Later there is an exception which relates to git pull error, due to unknow hostname...
```

**Comment by arvindsv** [comment]
No stack trace. Damn. Can you please paste the whole log somehere? Maybe in a gist.

**Comment by arvindsv** [comment]
Does this happen across restarts?

**Comment by arvindsv** [comment]
Can you also try one more thing? Change the config once. Make some small change. Does that change the cctray output?

**Comment by m1ndful** [comment]
So,
1) It will take some time, because there are a lot of corporate details, which will take me some time to replace as 'dummy' data. Also I am googling where to increase log-level, so hope to post more detailed log.
2) Yes, it does.
3) No, we are having this issue several months already. We have changes configs, restarted Go, nothing helps at this point.

**Comment by arvindsv** [comment]
> It will take some time ...

Ok, then don't do that.

> About 2) and 3)

That's good in a way (that it happens across restarts). It means we should be able to reproduce it and find the issue. I don't know why the stack trace is not showing up in the logs. The [code](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/domain/cctray/CcTrayActivityListener.java#L111) should log the stack trace as well.

**Comment by arvindsv** [comment]
I've added some more logging around this, but that will only be going forward, obviously. Won't help find out what's going on in your case.

**Comment by birchb1024** [comment]
We have the same problem on one of our GoCD servers.  We use the CCTRAY for monitoring pipeline failures and forwarding emails to mobile (cell) phones. Sadly the cctray is now empty. So no more notifications :-(  

The log files have these NPEs. Yes thats right NPE. Occuring maybe ten times daily:

```
2017-05-12 14:37:44,931  WARN [CCTray-Queue-Processor] CcTrayActivityListener:137 - Failed to handle action in CCTray queue
java.lang.NullPointerException
        at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
        at com.thoughtworks.go.domain.cctray.CcTrayViewAuthority.namesOf(CcTrayViewAuthority.java:79)
        at com.thoughtworks.go.domain.cctray.CcTrayViewAuthority.access$000(CcTrayViewAuthority.java:32)
        at com.thoughtworks.go.domain.cctray.CcTrayViewAuthority$1.visit(CcTrayViewAuthority.java:56)
        at com.thoughtworks.go.domain.PipelineGroups.accept(PipelineGroups.java:115)
        at com.thoughtworks.go.domain.cctray.CcTrayViewAuthority.groupsAndTheirViewers(CcTrayViewAuthority.java:47)
        at com.thoughtworks.go.domain.cctray.CcTrayConfigChangeHandler.findAllProjectStatusesForStagesAndJobsIn(CcTrayConfigChangeHandler.java:58)
        at com.thoughtworks.go.domain.cctray.CcTrayConfigChangeHandler.call(CcTrayConfigChangeHandler.java:45)
        at com.thoughtworks.go.domain.cctray.CcTrayActivityListener$4.call(CcTrayActivityListener.java:120)
        at com.thoughtworks.go.domain.cctray.CcTrayActivityListener$5.run(CcTrayActivityListener.java:135)


```

My hunch is this is related to the content of the config. I have tried many many variations of the config but cannot seem to fix it. Also looked in h2 but cannot see anything cctray related there. 

We would be stoked if someone solves this.

**Comment by arvindsv** [comment]
@birchb1024:

1. Do you have GoCD System Administrators set up? I mean, do you have the `<admins>` tag in your config?

2. I've found one instance where this can happen. I'll need you to see whether that's happening to you. The instance is when you have a role defined in the `<security>` tag with a case which is different from the case when it is used in a pipeline. Something like this:

```
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="90">
  <server artifactsdir="artifacts" agentAutoRegisterKey="1ad10917-dd4b-4118-96f2-170e81ccd0f2" commandRepositoryLocation="default" serverId="dev-id">
    <security>
      <passwordFile path="/path/to/password.properties" />
      <roles>
        <role name="role1">
          <users>
            <user>view</user>
          </users>
        </role>
      </roles>
      <admins>
        <user>admin</user>
      </admins>
    </security>
  </server>
  <pipelines group="defaultGroup">
    <authorization>
      <view>
        <role>ROLE1</role>
      </view>
    </authorization>
    <pipeline name="Test">
      <materials>
        <git url="/tmp/test.git" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
</cruise>
```

See the usage of `role1` vs `ROLE1`. This is a valid config.

**Comment by arvindsv** [comment]
For my notes: If there is no system admin, it looks like everyone is admin (or something like that). That needs to be taken care of. Also, if the case of the role is different, this NPE can happen.

**Comment by jyotisingh** [comment]
Yes, that's correct

**Comment by birchb1024** [comment]
Yes from memory (I am at home now) we have a role which people spell with different case in the leading character (e.g. **S**aladrole vs **s**aladrole). I will confirm this tomorrow and do some experiments with changing the case.....

**Comment by arvindsv** [comment]
Ok, thanks. Try and make the case the same and see if it helps. If it does, https://github.com/gocd/gocd/pull/3516, once merged, should fix the issue. Thanks for the stack trace.

**Comment by birchb1024** [comment]
This seems to be a fix for the issue. After I changed the roles to have matching case, cctray started working. Thankyou @arvindsv !

**Comment by arvindsv** [comment]
Good to know. The PR is merged and should be in 17.5.

**Comment by jyotisingh** [comment]
Reopened the issue for testing

**Comment by rajiesh** [comment]
Verified on 17.5.0 (5094-facde1c814310d1f9c463c8945c5145a994d0f39)
