### ISSUE TITLE
Get All Users API returns 500 response when a user has space in the login name

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#1650]
the get all users API returns a 500 if there is a space in the login name, below exception seen in the log,

```
2015-11-26 14:08:57,331 FATAL [qtp1453889274-29] Rails:? -
ActionController::UrlGenerationError (No route matches {:action=>"update", :controller=>"api_v1/users", :login_name=>"test !"} missing required keys: [:login_name]):
  app/controllers/application_controller.rb:200:in `url_for'
  app/presenters/api_v1/user_summary_representer.rb:27:in `UserSummaryRepresenter'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/controllers/api_v1/users_controller.rb:23:in `index'
  lib/jetty_weak_etag_middleware.rb:13:in `call'
  lib/catch_json_parse_errors.rb:8:in `call'
```

**Comment by rajiesh** [comment]
verified it on 15.3.0-2753(7aa885fe5c2d71de7544ed776f2c6e16ccc9a79a). GET all users returns user details with details of users with space in the login name. However we cannot do a single user GET with login name containing space(other commonly used special chars works fine - dot(.), &, colon(:) , lt(<) gt(>), ! , @). GET / DELETE / PATCH API cannot be invoked on users with login name containing space.

**Comment by rajiesh** [comment]
created the issue #1706 for the login name with space, so this issue can be closed for other special chars
