### ISSUE TITLE
NullPointerException on LDAPUserSearch.toUser

### ISSUE THREAD

**Issue by patrick92100** [gocd/gocd#1768]
under tab
ADMIN/User Summary/ADD USER
I type a valid LDAP user name, and clic SEARCH button

get an error message "Ldap search failed, please contact the administrator."

in the server side, in go-server.log get

 ERROR [qtp26002038-30] UserSearchService:83 - User search for xxxxxx on ldap failed with Exception.
java.lang.NullPointerException
        at com.thoughtworks.go.server.security.LdapUserSearch.toUser(LdapUserSearch.java:163)
        at com.thoughtworks.go.server.security.LdapUserSearch.buildUserList(LdapUserSearch.java:150)
        at com.thoughtworks.go.server.security.LdapUserSearch.search(LdapUserSearch.java:133)
        at com.thoughtworks.go.server.security.LdapUserSearch.search(LdapUserSearch.java:106)
        at com.thoughtworks.go.server.security.UserSearchService.searchLdap(UserSearchService.java:78)
        at com.thoughtworks.go.server.security.UserSearchService.search(UserSearchService.java:65)

**Comment by patrick92100** [comment]
LDAP config setup correctly for login, I mean login is activated and works fine.

**Comment by patrick92100** [comment]
in server/src/com/thoughtworks/go/server/security/LdapUserSearch.java
line 167
loginName = samAccName != null ? samAccName.get().toString() : attributes.get(UID).get().toString();
when samAccName is null and attributes.get(UID) is null the exception is raisen ( attributes.get(UID).get() ). 
In my case the LDAP records do no have UID attributes...

**Comment by arvindsv** [comment]
Closing. LDAP functionality has been moved out to a plugin and rewritten completely.
