### ISSUE TITLE
Issue while adding a role to a go template

### ISSUE THREAD

**Issue by sriharibobilla** [gocd/gocd#1821]
While I am trying to assign a new role on a template, it's not allowing me to save changes Even the same role is added on top of pipeline group.

Gocd is running on version 15.3.1

Error I am seeing in logs:

2016-01-21 16:39:32,529  INFO [qtp668998501-18238666] GoConfigDao:195 - Config update request by sbobil001c is in queue - com.thoughtworks.go.config.update.UiBasedConfigUpdateCommand@180504e6
2016-01-21 16:39:32,531  INFO [qtp668998501-18238666] GoConfigDao:199 - Config update request by sbobil001c is being processed
2016-01-21 16:39:33,177  WARN [qtp668998501-18238666] GoFileConfigDataSource:251 - Configuration file is invalid: Role "esp-master-admin" who is not authorized to operate pipeline group can not be authorized to approve stage
com.thoughtworks.go.config.exceptions.GoConfigInvalidException: Role "esp-master-admin" who is not authorized to operate pipeline group can not be authorized to approve stage
        at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:143)
        at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:116)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:94)
        at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:344)
        at com.thoughtworks.go.config.GoFileConfigDataSource.getModifiedConfig(GoFileConfigDataSource.java:275)
        at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:241)
        at com.thoughtworks.go.config.CachedFileGoConfig.writeWithLock(CachedFileGoConfig.java:139)
        at com.thoughtworks.go.config.MergedGoConfig.writeWithLock(MergedGoConfig.java:145)
        at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:207)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:257)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfigFromUI(GoConfigService.java:302)
        at sun.reflect.GeneratedMethodAccessor823.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:425)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:292)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:44)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
        at rubyjit.AdminController$$save_8a402cbd83c411bb7273bed78fcb64966767894f1417007275.__file__(/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/app/controllers/admin_controller.rb:107)
        at rubyjit.AdminController$$save_8a402cbd83c411bb7273bed78fcb64966767894f1417007275.__file__(/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/app/controllers/admin_controller.rb)
        at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:101)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:90)

**Comment by arvindsv** [comment]
Linking to mailing list [post](https://groups.google.com/d/topic/go-cd/zGq_Iok0AWs/discussion). @sriharibobilla, you'll need to verify whether this is still an issue on 16.1.0. Thanks!

**Comment by zabil** [comment]
No response from the reporter. 
Closing this for now as it's fixed on the latest release. please feel free to open it if's not yet resolved.
