### ISSUE TITLE
"Modification check failed for material" during 'git config remote.origin.url'

### ISSUE THREAD

**Issue by henriquegemignani** [gocd/gocd#1845]
Hello,

I'm having a material check failure and Go isn't giving any clear reason for it.

On the Go interface we have the following:

```
Modification check failed for material: URL: git@bitbucket.org:teamname/repository.git, Branch: topic [Jan-27 16:52:03]
Error performing command: --- Command --- git config remote.origin.url --- Environment --- {} --- INPUT ---- --OUTPUT --- --- ERROR --- ---
```

And on the log files:

```
2016-01-27 16:36:33,858  WARN [89@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:121 - [Material Update] Modification check failed for material: URL: git@bitbucket.org:teamname/repository.git, Branch: topic
java.lang.RuntimeException: Error performing command: --- Command ---
git config remote.origin.url
--- Environment ---
{}
--- INPUT ----


--OUTPUT ---

--- ERROR ---

---
 
    at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:40)
    at com.thoughtworks.go.config.materials.git.GitMaterial.getGit(GitMaterial.java:189)
    at com.thoughtworks.go.config.materials.git.GitMaterial.modificationsSince(GitMaterial.java:109)
    at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:36)
    at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:27)
    at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:110)
    at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:57)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:155)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:147)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:110)
    at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
    at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:51)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:31)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.thoughtworks.go.util.command.CommandLineException: Error performing command: --- Command ---
git config remote.origin.url
--- Environment ---
{}
--- INPUT ----


--OUTPUT ---

--- ERROR ---

---

    at com.thoughtworks.go.util.command.CommandLine.runOrBomb(CommandLine.java:498)
    at com.thoughtworks.go.util.command.CommandLine.runOrBomb(CommandLine.java:526)
    at com.thoughtworks.go.domain.materials.SCMCommand.runOrBomb(SCMCommand.java:42)
    at com.thoughtworks.go.domain.materials.git.GitCommand.workingRepositoryUrl(GitCommand.java:217)
    at com.thoughtworks.go.config.materials.git.GitMaterial.isRepositoryChanged(GitMaterial.java:232)
    at com.thoughtworks.go.config.materials.git.GitMaterial.git(GitMaterial.java:199)
    at com.thoughtworks.go.config.materials.git.GitMaterial.getGit(GitMaterial.java:187)
    ... 18 more
```

The repository/branch exists, and is accessible by the Go server. Pressing 'Check Connection' results in success.

**Comment by juhijariwala** [comment]
Hello,

It looks like origin is not set for your repository and GO expects origin to be set. 

Could you try to clone  ```git@bitbucket.org:teamname/repository.git  Branch: topic``` and run ```git config remote.origin.url``` locally?

 If output is blank then run the following command to set the remote origin.
```git remote add origin git@bitbucket.org:teamname/repository.git```

However, check connection runs the following command for which remote origin is not needed.
```git ls-remote git@bitbucket.org:teamname/repository.git```

**Comment by arvindsv** [comment]
It's not just empty, it also seems to be returning a non-zero exit code. Hmm.

**Comment by henriquegemignani** [comment]
I logged as the go user on the machine running Go Server and ran ```git clone git@bitbucket.org:teamname/repository.git -b topic```, and the clone was successful. Then, inside the just cloned repository, running ```git config remote.origin.url``` returns ```git@bitbucket.org:teamname/repository.git``` as expected.

I'm not sure it helps, but I tried running this command on each repository inside the flyweight directory, and none failed.

**Comment by zabil** [comment]
@arvindsv it returns a non-zero exit code when empty too

```
$ git remote rm origin
$ git config remote.origin.url
$ echo $?
1
```

@henriquegemignani can you do a ```echo $?``` to check the status code after a clone or ```git config remote.origin.url```

**Comment by henriquegemignani** [comment]
```
go@84b528f336fc:~$ git clone git@bitbucket.org:teamname/repository.git -b topic        
Cloning into 'repository'...
remote: Counting objects: 13150, done.        
remote: Compressing objects: 100% (6386/6386), done.        
remote: Total 13150 (delta 7879), reused 11157 (delta 6284)        
Receiving objects: 100% (13150/13150), 405.37 MiB | 20.87 MiB/s, done.
Resolving deltas: 100% (7879/7879), done.
Checking connectivity... done.
go@84b528f336fc:~$ echo $?
0
go@84b528f336fc:~$ cd repository/
go@84b528f336fc:~/repository$ git config remote.origin.url
git@bitbucket.org:teamname/repository.git
go@84b528f336fc:~/repository$ echo $?
0
```

**Comment by zabil** [comment]
@henriquegemignani do you still see this?

**Comment by henriquegemignani** [comment]
I've since deleted the Pipeline that used this material, and the whole flyweight directory during a server migration.
So, no, I don't have this error right now.

**Comment by zabil** [comment]
Closing this for now.
Will re-open if we see this again.

**Comment by mushycode** [comment]
I am facing the same issue. Was there any fix found for this problem?

**Comment by varshavaradarajan** [comment]
@mushycode , which version of git and GoCD are you using?

**Comment by mushycode** [comment]
I am running GOCD server as a docker container ( gocd/gocd-server:v17.7.0).
Git version is 2.13.0 
I ended up fixing it by deleting the flyweight directory of the particular repository in question. I am assuming it might have been caused during a restart of the gocd server container while it was still performing some operation.

**Comment by varshavaradarajan** [comment]
@mushycode , yes, it is because the flyweight directory end up being corrupted. We may not to add a check to delete and reclone the flyweight directory in such a case.

**Comment by flewid-cd** [comment]
I just removed the project dir in pipelines and started all over again. However this was after I changed from https to ssh for cloning github repos.

**Comment by erIamshivani** [comment]
I am not able to locate pipelines/flyweight directory. Can someone help me?
I am new to GoCD by the way.

**Comment by adityasood** [comment]
@erIamshivani the location pipelines/flyweight directory will differ based on your installation mechanism and OS.

For e.g, if you are using an RPM/deb package on Linux box you should be able to see it in /var/lib/go-server.

You can read through the documentation [here](https://docs.gocd.org/current/installation/install/server/linux.html) to know more.

**Comment by erIamshivani** [comment]
@adityasood Thanks!
I keep getting this error:
`Modification check failed for material: URL: http://<myhost>:8081/a/myrepo, Branch: master`

It was working fine till yesterday. I did not change anything in code or configuration or in the git repo. 
I even deleted flyweight folder and tried triggering the pipeline. It keeps giving me same error. Are there any other settings I should be aware of?
I have given my repo url, username, password correctly.

**Comment by badbort** [comment]
I've been encountering this problem frequently with my config repository.

The repository is being used as a config repository, as well as a material source for pipeines defined in that repo. To explain this, the repo looks like:

root/Fred/Content/file1
root/Fred/Content/file2
root/Fred/ReferencingFile
root/Fred/fred.gocd.yaml <- Contains pipelines that use the above content files

This works fine at first, but after making changes and committing to the repo I end up with the following error:

> Modification check failed for material: URL: http://<local on premises repo>, Branch: master
> Affected pipelines are <all pipelines in that repo>.

I can't be certain but I think becomes an issue after every commit to that repo.

And having a look at the server log:

> 2020-07-27 15:35:27,680 WARN  [153@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:127 - [Material Update] Modification check failed for material: URL: http://192.168.20.39/FMG/fmg.christmascreek.models.git, Branch: master
> java.lang.RuntimeException: Error performing command: --- Command ---
> git config remote.origin.url
> --- Environment ---
> {}
> --- INPUT ----
> 
> 
> --- EXIT CODE (1) ---
> --- STANDARD OUT ---
> 
> --- STANDARD ERR ---
> 
> ---
>  
> 	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:41)
> 	at com.thoughtworks.go.config.materials.git.GitMaterial.getGit(GitMaterial.java:207)
> 	at com.thoughtworks.go.config.materials.git.GitMaterial.modificationsSince(GitMaterial.java:130)
> 	at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:35)
> 	at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:26)
> 	at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:128)
> 	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:56)
> 	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:157)
> 	<yadda yadda yadda>

My workaround lately is to stop gocd, delete everything in the flyweight folder, and start it again. It will work fine after this, until the next commit.

My local gocd server is in this state currently. I've gone through the flyweight directories and found the associated directory. I've run the following commands:

> git config remote.origin.url
> (Blank)

> git fsck --full
> fatal: not a git repository (or any of the parent directories): .git

I'm not sure how to proceed. Something is causing the flyweight repo to corrupt?

I have other existing repos that have content of the same type but different client, and they have no issues yet. I have yet to turn them into config repositories due to the problems I'm currently having with this one.

**Comment by AnkitSinha-Git** [comment]
> I am not able to locate pipelines/flyweight directory. Can someone help me?
> I am new to GoCD by the way.

Answer : if you are using windows server then you would find in C:\Program Files (x86)\Go Server\pipelines\flyweight
