### ISSUE TITLE
Job Timeout should apply even when the job could not be assigned to an agent

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#1926]
We encountered this scenario in build.go.cd where the pipeline `installer-testing` was pending for assignment for over 18 hours since the agent was missing. Even though the job timeout on build.go.cd is setup to 180 mins, it do not apply in this scenario where the job assignment is not completed.

I think its good to apply the timeout on non-assigned jobs too since a job waiting for 18 hrs do not have any value. Better we timeout and fail the job so that it can be notified to take action.

Another observation was when the agent came up, the job `installer-testing` failed after having waited for 18 hours, and below exception seen in the logs,

```
2016-02-11 22:22:01,683  INFO [qtp399573350-130769] BuildRepositoryRemoteImpl:133 - [Agent Cookie] Agent [Agent [blrstdgoprf02.thoughtworks.com, 10.4.7.1, 1bdd029e-3c33-4928-a6a8-f3bd46d30c7e]] at location [/var/lib/go-agent] asked for a new cookie, assigned [4258312b-3fdf-4b72-874b-049af41253ce]
2016-02-11 22:22:02,008  INFO [67@MessageListener for WorkFinder] Stage:218 - Stage is being completed by transition id: 887554
2016-02-11 22:22:02,061 ERROR [67@MessageListener for WorkFinder] StageService:235 - error notifying listener for stage <Stage id='15283' name='fresh-install' stageCounter='1' createdTime='2016-02-11 04:23:57.133' result='Failed'>
java.lang.RuntimeException: Multiple independent transactions are not permitted inside single transaction surrounding.
        at com.thoughtworks.go.server.transaction.TransactionContext.transactionPushed(TransactionContext.java:47)
        at com.thoughtworks.go.server.transaction.TransactionTemplate$2.doInTransaction(TransactionTemplate.java:37)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
        at com.thoughtworks.go.server.dao.EnvironmentVariableSqlMapDao.load(EnvironmentVariableSqlMapDao.java:60)
        at com.thoughtworks.go.server.dao.JobInstanceSqlMapDao.loadJobPlanAssociatedEntities(JobInstanceSqlMapDao.java:208)
        at com.thoughtworks.go.server.dao.JobInstanceSqlMapDao.loadPlan(JobInstanceSqlMapDao.java:200)
        at com.thoughtworks.go.server.service.JobInstanceService.loadOriginalJobPlan(JobInstanceService.java:208)
        at com.thoughtworks.go.domain.XmlWriterContext.planFor(XmlWriterContext.java:62)
        at com.thoughtworks.go.server.domain.xml.JobXmlViewModel.toXml(JobXmlViewModel.java:81)
        at com.thoughtworks.go.server.service.XmlApiService.write(XmlApiService.java:49)
        at com.thoughtworks.studios.shine.cruise.GoGRDDLResourceRDFizer.importURIUsingGRDDL(GoGRDDLResourceRDFizer.java:60)
        at com.thoughtworks.studios.shine.cruise.stage.details.JobResourceImporter.importJob(JobResourceImporter.java:69)
        at com.thoughtworks.studios.shine.cruise.stage.details.StageResourceImporter.importJobs(StageResourceImporter.java:124)
        at com.thoughtworks.studios.shine.cruise.stage.details.StageResourceImporter.load(StageResourceImporter.java:84)
        at com.thoughtworks.studios.shine.cruise.BackgroundStageLoader.handle(BackgroundStageLoader.java:71)
        at com.thoughtworks.studios.shine.cruise.stage.feeds.StageAtomFeedsReader.readFromLatest(StageAtomFeedsReader.java:51)
        at com.thoughtworks.studios.shine.cruise.BackgroundStageLoader.load(BackgroundStageLoader.java:61)
        at com.thoughtworks.studios.shine.cruise.BackgroundStageLoaderStageStatusListener.stageStatusChanged(BackgroundStageLoader.java:104)
        at com.thoughtworks.go.server.service.StageService$4.afterCommit(StageService.java:233)
        at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCommit(TransactionSynchronizationUtils.java:133)
        at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerAfterCommit(TransactionSynchronizationUtils.java:121)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCommit(AbstractPlatformTransactionManager.java:950)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:796)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:147)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
        at com.thoughtworks.go.server.service.StageService.changeJob(StageService.java:468)
2016-02-11 22:22:02,064  INFO [67@MessageListener for WorkFinder] BuildAssignmentService:115 - [Agent Assignment] Assigned job [JobIdentifier[installer_testing, 46, 46, fresh-install, 1, run, 158509]] to agent [Agent [blrstdgoprf02.thoughtworks.com, 10.4.7.1, 1bdd029e-3c33-4928-a6a8-f3bd46d30c7e]]
```

**Comment by chrislovsund** [comment]
This is important in other scenarios as well. 
We have a scenario where a job should run on all agents every 10 minutes matching some resources. If an agent is `missing` or `lostcontact` the job will "never" fail nor pass, hindering the other agents from getting a new job every 10 minutes. The way to make the job run again is to either repair the missing agent or cancel the job. But cancelling the job will only work once I believe.

**Comment by cfontes** [comment]
Just got bitten by this as well.

Any news on it? It's pretty old

**Comment by kritika-singh3** [comment]
Proposal: The current `jobTimeout` is considered when we the job has been inactive for a while. Currently this meant while executing tasks. We should also consider agent non-assignment has part of inactivity.

Meaning: If the `jobTimout` is set to `x` minutes, the job will be cancelled in the following scenarios:

1. If the job hasn't been assigned as agent for last `x` minutes, or
2. The job is executing but has not shown any activity for the last `x` minutes.

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd/pull/8585
