### ISSUE TITLE
Recursive symlinks prevent artifact generation

### ISSUE THREAD

**Issue by wendorf** [gocd/gocd#20]
# Steps to Reproduce

1. Create a pipeline with an job whose artifact is generated from a directory that includes a recursive symlink (e.g. `directory1/directory2/directory3/my_symlink` points to `../../..`).
  - The [Duckburg/launchpad](https://github.com/Duckburg/launchpad) repository is already set up with such a symlink.
1. Run the pipeline such that Go will attempt to generate the artifact from `really/*`
1. Look in the go-agent.log to see that the artifact has failed to generate due to a `File name too long` error

The following config can be used to create a pipeline that will generate this error:

```
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="69">
  <server artifactsdir="artifacts" commandRepositoryLocation="default" serverId="639da549-ba01-4e69-8bcd-5186f166bae7" />
  <pipelines group="Duckburg">
    <pipeline name="launchpadMcQuack">
      <materials>
        <git url="git@github.com:Duckburg/launchpad.git" autoUpdate="false" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="pwd`" />
            </tasks>
            <artifacts>
              <artifact src="really/*" dest="really" />
            </artifacts>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
  <agents>
    <agent hostname="money-bin" ipaddress="127.0.0.1" uuid="91e7e456-5810-4c0a-b986-e0e7bf307bbc">
      <resources>
        <resource>ruby-1.9.3</resource>
      </resources>
    </agent>
  </agents>
</cruise>
```

# Expected Result

The build succeeds and gives us an artifact.

# Actual Result

The build fails and gives the following stacktrace in go-agent.log:

```
014-03-11 16:33:45,492 [loopThread] ERROR thoughtworks.cruise.publishers.CruiseArtifactsManipulator:99 - Failed to upload /Volumes/Biggie/workspace/thoughtworks-go-cd/go_agent.app/pipelines/launchpadMcQuack/really/long
java.io.FileNotFoundException: pipelines/launchpadMcQuack/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/really/long/path/really_long_file_name/.git/objects/pack/pack-ee96781dbc3bcadfd7f8a90615a0ff8f7e1adbe3.idx (File name too long)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:120)
        at com.thoughtworks.cruise.util.ZipUtil.addToZip(ZipUtil.java:100)
        at com.thoughtworks.cruise.util.ZipUtil.addDirContents(ZipUtil.java:89)
        at com.thoughtworks.cruise.util.ZipUtil.addDirectory(ZipUtil.java:84)
        at com.thoughtworks.cruise.util.ZipUtil.addFolderToZip(ZipUtil.java:73)
        at com.thoughtworks.cruise.util.ZipUtil.addToZip(ZipUtil.java:95)
        at com.thoughtworks.cruise.util.ZipUtil.addDirContents(ZipUtil.java:89)
        at com.thoughtworks.cruise.util.ZipUtil.addDirectory(ZipUtil.java:84)
        at com.thoughtworks.cruise.util.ZipUtil.addFolderToZip(ZipUtil.java:73)
        at com.thoughtworks.cruise.util.ZipUtil.addToZip(ZipUtil.java:95)
        at com.thoughtworks.cruise.util.ZipUtil.addDirContents(ZipUtil.java:89)
        [...long recursive stack omitted for brevity]
        at com.thoughtworks.cruise.util.ZipUtil.addDirectory(ZipUtil.java:84)
        at com.thoughtworks.cruise.util.ZipUtil.addFolderToZip(ZipUtil.java:73)
        at com.thoughtworks.cruise.util.ZipUtil.addToZip(ZipUtil.java:95)
        at com.thoughtworks.cruise.util.ZipUtil.addDirContents(ZipUtil.java:89)
        at com.thoughtworks.cruise.util.ZipUtil.addDirectory(ZipUtil.java:84)
        at com.thoughtworks.cruise.util.ZipUtil.addFolderToZip(ZipUtil.java:73)
        at com.thoughtworks.cruise.util.ZipUtil.addToZip(ZipUtil.java:95)
        at com.thoughtworks.cruise.util.ZipUtil.addDirContents(ZipUtil.java:89)
        at com.thoughtworks.cruise.util.ZipUtil.addDirectory(ZipUtil.java:84)
        at com.thoughtworks.cruise.util.ZipUtil.addFolderToZip(ZipUtil.java:73)
        at com.thoughtworks.cruise.util.ZipUtil.addToZip(ZipUtil.java:95)
        at com.thoughtworks.cruise.util.ZipUtil.zipContents(ZipUtil.java:55)
        at com.thoughtworks.cruise.util.ZipUtil.zip(ZipUtil.java:33)
        at com.thoughtworks.cruise.publishers.CruiseArtifactsManipulator.publish(CruiseArtifactsManipulator.java:69)
        at com.thoughtworks.cruise.work.DefaultCruisePublisher.upload(DefaultCruisePublisher.java:57)
        at com.thoughtworks.cruise.config.ArtifactPlan.publishWithProperties(ArtifactPlan.java:110)
        at com.thoughtworks.cruise.config.ArtifactPlan.publish(ArtifactPlan.java:101)
        at com.thoughtworks.cruise.domain.DefaultJobPlan.publishArtifacts(DefaultJobPlan.java:89)
        at com.thoughtworks.cruise.remote.work.BuildWork.completeJob(BuildWork.java:175)
        at com.thoughtworks.cruise.remote.work.BuildWork.build(BuildWork.java:127)
        at com.thoughtworks.cruise.remote.work.BuildWork.doWork(BuildWork.java:75)
        at com.thoughtworks.cruise.agent.JobRunner.run(JobRunner.java:34)
        at com.thoughtworks.cruise.agent.AgentController.retrieveWork(AgentController.java:153)
        at com.thoughtworks.cruise.agent.AgentController.loop(AgentController.java:99)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:512)
        at java.util.TimerThread.run(Timer.java:462)
```

**Comment by wendorf** [comment]
I haven't used GoCD since shortly after filing this issue, and it doesn't look like it's interesting to anyone who's currently using GoCD, so I'm closing this issue.
