### ISSUE TITLE
Can't set server port in Mac OS X agent

### ISSUE THREAD

**Issue by janfabry** [gocd/gocd#2032]
##### Issue Type

- Bug Report
- Documentation Report

##### Summary

I could not find a way to set the server port in the agent for Mac OS X.

##### Environment

I am running our Go server behind an Apache proxy on port 443, with port 80 forwarding there. I could configure an agent running on Linux to connect to this server by setting the `GO_SERVER_PORT` environment variable, however this does not seem to work on Mac OS X. Assume the server is running on `go.example.com` for this report.

###### Basic environment details

Go Version: 16.2.1.3027
JAVA Version: 1.8.0_40
OS: Max OS X 11.1

##### Steps to Reproduce
I tried modifying the settings in three places:
 - The interface
 - `~/Library/Application Support/Go Agent/overrides.env`
 - `~/Library/Preferences/com.thoughtworks.studios.cruise.agent.properties`

What I tried to modify:
 - In the interface: setting it to `go.example.com:80` or `go.example.com 80`.
 - In `overrides.env`:
  - Setting `$EXTRA_JVM_ARGUMENTS` to `go.example.com 80` or `go.example.com`
  - Setting `-Dcruise.server.port=80` and `-Dcruise.server.host=go.example.com`
  - Setting the `GO_SERVER_HOST` and `GO_SERVER_PORT` environment variables
 - In `com.thoughtworks.studios.cruise.agent.properties`: set the `server` and `port` variables to `go.example.com` and `80` respectively.

##### Expected Results
The agent connects over HTTP to `go.example.com` port 80, and then can connect via HTTPS to `go.example.com` port 443.

##### Actual Results
The agent kept trying to append port 8153 to the address, resulting in either invalid URLs or failures to connect.

##### Log snippets
(I only included the relevant parts)

```
Tue Mar  8 11:35:02 CET 2016: Final environment variables after sourcing overrides.env are:
AGENT_STARTUP_ARGS=-Xms128m -Xmx256m
GO_SERVER_HOST=go.example.com
GO_SERVER_PORT=80

Tue Mar  8 11:35:02 CET 2016: Running:
Tue Mar  8 11:35:02 CET 2016:   /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java
Tue Mar  8 11:35:02 CET 2016:   -cp
Tue Mar  8 11:35:02 CET 2016:   /Applications/Go Agent.app/Contents/Resources/agent-bootstrapper.jar
Tue Mar  8 11:35:02 CET 2016:   -Xdock:icon=/Applications/Go Agent.app/Contents/Resources/go-agent.icns
Tue Mar  8 11:35:02 CET 2016:   -Xdock:name=Go Agent
Tue Mar  8 11:35:02 CET 2016:   -Dgo.application.name=Go Agent
Tue Mar  8 11:35:02 CET 2016:   -Dgo.java.to.use=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java
Tue Mar  8 11:35:02 CET 2016:   -Dcruise.server.port=80 -Dcom.apple.mrj.application.apple.menu.about.name=Go Agent -Dapple.laf.useScreenMenuBar=true -Done-jar.main.class=com.thoughtworks.go.agent.bootstrapper.osx.AgentMacWindow -Dcruise.server.host=go.example.com
Tue Mar  8 11:35:02 CET 2016:   com.simontuffs.onejar.Boot
Tue Mar  8 11:35:02 CET 2016:   go.example.com

logFile Environment Variable= null
Logging to go-agent-bootstrapper.log
5145 [main] ERROR com.thoughtworks.go.agent.launcher.ServerCall  - Couldn't access Go Server with base url: http://go.example.com:8153/go/admin/agent-launcher.jar: org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 5000 ms
java.lang.Exception: Couldn't access Go Server with base url: http://go.example.com:8153/go/admin/agent-launcher.jar: org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 5000 ms
        at com.thoughtworks.go.agent.launcher.ServerCall.invoke(ServerCall.java:70)
        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.headers(ServerBinaryDownloader.java:128)
        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:105)
        at com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:78)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:74)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.simontuffs.onejar.Boot.run(Boot.java:306)
        at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 5000 ms
        at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:154)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:124)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:706)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:386)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
        at com.thoughtworks.go.agent.launcher.ServerCall.invoke(ServerCall.java:49)
        ... 11 more
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:139)
        ... 18 more
5146 [main] ERROR com.thoughtworks.go.agent.launcher.ServerBinaryDownloader  - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error: java.lang.Exception: Couldn't access Go Server with base url: http://go.example.com:8153/go/admin/agent-launcher.jar: org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 5000 ms
```

**Comment by arvindsv** [comment]
When I set the values properly in `com.thoughtworks.studios.cruise.agent.properties`, I was able to get it to connect to that port. Here's what I see in the logs:

```
223 [MacBootstrapperThread-0 go.example.com:32769] INFO com.thoughtworks.go.agent.AgentProcessParentImpl  - Agent is version: 16.2.1
327 [MacBootstrapperThread-0 go.example.com:32769] INFO com.thoughtworks.go.agent.launcher.ServerBinaryDownloader  - download started at Tue Mar 08 07:07:38 EST 2016
332 [MacBootstrapperThread-0 go.example.com:32769] INFO com.thoughtworks.go.agent.launcher.ServerBinaryDownloader  - got server response at Tue Mar 08 07:07:38 EST 2016
358 [MacBootstrapperThread-0 go.example.com:32769] INFO com.thoughtworks.go.agent.launcher.ServerBinaryDownloader  - pipe the stream to admin/agent-plugins.zip at Tue Mar 08 07:07:38 EST 2016
365 [MacBootstrapperThread-0 go.example.com:32769] INFO com.thoughtworks.go.util.PerfTimer  - Performance: Downloading new admin/agent-plugins.zip with md5 signature: f71759343f3ab1e91647a1bd7aadefc0 took 40ms
371 [MacBootstrapperThread-0 go.example.com:32769] INFO com.thoughtworks.go.agent.AgentProcessParentImpl  - Launching Agent with command: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java -Xms128m -Xmx256m -Dagent.launcher.version=Unknown -Dagent.plugins.md5=f71759343f3ab1e91647a1bd7aadefc0 -Dagent.binary.md5=/HAoz6UGrGbuuLS61z0yJg== -Dagent.launcher.md5=zrOukW6CVDdd/+26yUF1Tg== -jar agent.jar https://go.example.com:8154/go/
```

The contents of `com.thoughtworks.studios.cruise.agent.properties` for me, are:

```
#Tue Mar 08 06:53:17 EST 2016
port=32769
server=go.example.com
```

It failed because it tried to connect to 8154 after that, and failed because the TLS port was not 8154. But, if it gets this far, it should work for you, as long as port 8154 is accessible.

**Comment by janfabry** [comment]
Ok, setting it there got me through the first part, but then indeed the SSL port is not running at 8154, but on 443 (via the Apache proxy). I believe this SSL port number is passed from the agent to the server, but can I tell the server that the public SSL port is 443 instead of 8154? I only see the Site URLs in the server settings, but changing them has no effect.

Once this question is resolved I'll create a PR for the docs.

**Comment by arvindsv** [comment]
Unfortunately, you can't tell the agent to use 443, because the server insists of terminating TLS connections itself. This is because the each agent is provided a different TLS certificate, which is has to use, to communicate with the server. So, as mentioned in [this comment](https://github.com/gocd/gocd/issues/1459#issuecomment-135396398), you'll need to make sure that 8154 is available to the agents. Users can use 443.

**Comment by zabil** [comment]
Closing this for now. please feel free to open it if's not yet resolved.
