### ISSUE TITLE
OAuth is not working as expected

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2038]
##### Issue Type

- Bug Report

##### Summary

As documented [here](https://docs.go.cd/current/faq/oauth_overview.html) OAuth is not working as expected

###### Basic environment details

Go Version: Go Version: 16.3.0(3160-e86fcdf55ce237a53586e91b380f0271e7c3d5ac)

##### Log snippets

```
2016-03-09 11:59:24,250 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,250 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /rails/cas_errors/**; matched=false
2016-03-09 11:59:24,250 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,251 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /remoting/**; matched=false
2016-03-09 11:59:24,251 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,251 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /agent-websocket/**; matched=false
2016-03-09 11:59:24,251 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,251 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /api/feeds/**; matched=false
2016-03-09 11:59:24,251 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,251 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /api/pipelines.xml; matched=false
2016-03-09 11:59:24,251 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,252 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /api/*/*.xml; matched=false
2016-03-09 11:59:24,252 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,252 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /api/pipelines/*/*.xml; matched=false
2016-03-09 11:59:24,252 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,252 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /gadgets/**; matched=false
2016-03-09 11:59:24,252 DEBUG [qtp2115235807-33] FilterChainProxy:194 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,253 DEBUG [qtp2115235807-33] FilterChainProxy:201 - Candidate is: '/cctray.xml'; pattern is /cctray.xml; matched=true
2016-03-09 11:59:24,253 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 1 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.PerformanceLoggingFilter@790ffaa9'
2016-03-09 11:59:24,253 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 2 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.ModeAwareFilter@811ab57'
2016-03-09 11:59:24,253 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 3 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.web.i18n.LocaleResolver@4007e0e4'
2016-03-09 11:59:24,253 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 4 of 17 in additional filter chain; firing Filter: 'org.springframework.security.context.HttpSessionContextIntegrationFilter[ order=200; ]'
2016-03-09 11:59:24,253 DEBUG [qtp2115235807-33] HttpSessionContextIntegrationFilter:213 - Obtained a valid SecurityContext from SPRING_SECURITY_CONTEXT to associate with SecurityContextHolder: 'org.springframework.security.context.SecurityContextImpl@fcc2ffcc: Authentication: com.thoughtworks.go.server.security.OauthAuthenticationToken@fcc2ffcc: Principal: org.springframework.security.userdetails.User@0: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_OAUTH_USER; Password: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_OAUTH_USER'
2016-03-09 11:59:24,254 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 5 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.web.ApiSessionFilter[ order=201; ]'
2016-03-09 11:59:24,254 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 6 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.GoLogoutFilter[ order=300; ]'
2016-03-09 11:59:24,254 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 7 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.RemoveAdminPermissionFilter[ order=999; ]'
2016-03-09 11:59:24,255 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 8 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.CasProcessingFilter[ order=600; ]'
2016-03-09 11:59:24,255 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 9 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.OauthAuthenticationFilter[ order=999; ]'
2016-03-09 11:59:24,255 DEBUG [qtp2115235807-33] OauthAuthenticationFilter:48 - Oauth authorization header: Token token="71d587b2dfc654e49aea1adbaa9b2ac40c24c57c10b822e2803ed68a7eb6d0a5"
2016-03-09 11:59:24,256 DEBUG [qtp2115235807-33] ProviderManager:190 - Authentication attempt using com.thoughtworks.go.server.security.providers.GoAuthenticationProvider
2016-03-09 11:59:24,265 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 10 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.BasicAuthenticationFilter[ order=1000; ]'
2016-03-09 11:59:24,265 DEBUG [qtp2115235807-33] BasicAuthenticationFilter:114 - Authorization header: Token token="71d587b2dfc654e49aea1adbaa9b2ac40c24c57c10b822e2803ed68a7eb6d0a5"
2016-03-09 11:59:24,266 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 11 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.AuthenticationProcessingFilter[ order=700; ]'
2016-03-09 11:59:24,266 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 12 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.UserEnabledCheckFilter[ order=701; ]'
2016-03-09 11:59:24,267 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 13 of 17 in additional filter chain; firing Filter: 'com.thoughtworks.go.server.security.AnonymousProcessingFilter[ order=1300; ]'
2016-03-09 11:59:24,267 DEBUG [qtp2115235807-33] AnonymousProcessingFilter:98 - SecurityContextHolder not populated with anonymous token, as it already contained: 'com.thoughtworks.go.server.security.OauthAuthenticationToken@fcc2ffcc: Principal: org.springframework.security.userdetails.User@0: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_OAUTH_USER; Password: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_OAUTH_USER'
2016-03-09 11:59:24,268 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 14 of 17 in additional filter chain; firing Filter: 'org.springframework.security.ui.ExceptionTranslationFilter[ order=1400; ]'
2016-03-09 11:59:24,268 DEBUG [qtp2115235807-33] FilterChainProxy:366 - /cctray.xml at position 15 of 17 in additional filter chain; firing Filter: 'org.springframework.security.intercept.web.FilterSecurityInterceptor@218e0333'
2016-03-09 11:59:24,268 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:196 - Converted URL to lowercase, from: '/cctray.xml'; to: '/cctray.xml'
2016-03-09 11:59:24,269 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /auth/login; matched=false
2016-03-09 11:59:24,269 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /auth/logout; matched=false
2016-03-09 11:59:24,269 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /auth/security_check; matched=false
2016-03-09 11:59:24,270 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/server.xml; matched=false
2016-03-09 11:59:24,270 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /shine/sparql.xml; matched=false
2016-03-09 11:59:24,270 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /compressed/*; matched=false
2016-03-09 11:59:24,270 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /assets/**; matched=false
2016-03-09 11:59:24,271 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /static/backup_in_progress.html; matched=false
2016-03-09 11:59:24,271 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /is_backup_finished.json; matched=false
2016-03-09 11:59:24,271 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /images/cruise.ico; matched=false
2016-03-09 11:59:24,272 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/agent; matched=false
2016-03-09 11:59:24,272 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/latest-agent.status; matched=false
2016-03-09 11:59:24,272 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/agent-launcher.jar; matched=false
2016-03-09 11:59:24,272 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/agent-plugins.zip; matched=false
2016-03-09 11:59:24,273 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /tab/admin/**; matched=false
2016-03-09 11:59:24,273 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/configuration/file/**; matched=false
2016-03-09 11:59:24,273 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/configuration/**; matched=false
2016-03-09 11:59:24,273 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/restful/configuration/**; matched=false
2016-03-09 11:59:24,274 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/pipelines/**; matched=false
2016-03-09 11:59:24,274 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/pipeline_group/**; matched=false
2016-03-09 11:59:24,274 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/templates/**; matched=false
2016-03-09 11:59:24,274 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/commands/**; matched=false
2016-03-09 11:59:24,275 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/plugins; matched=false
2016-03-09 11:59:24,275 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/pipeline/**; matched=false
2016-03-09 11:59:24,275 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/materials/**; matched=false
2016-03-09 11:59:24,276 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/package_repositories/**; matched=false
2016-03-09 11:59:24,276 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/package_definitions/**; matched=false
2016-03-09 11:59:24,276 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/admin/**; matched=false
2016-03-09 11:59:24,277 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/jobs/scheduled.xml; matched=false
2016-03-09 11:59:24,277 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /admin/**; matched=false
2016-03-09 11:59:24,278 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /**/addresources.json; matched=false
2016-03-09 11:59:24,278 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /**/registeragent.json; matched=false
2016-03-09 11:59:24,279 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/feeds/**; matched=false
2016-03-09 11:59:24,279 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/support; matched=false
2016-03-09 11:59:24,279 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/pipelines.xml; matched=false
2016-03-09 11:59:24,279 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/*/*.xml; matched=false
2016-03-09 11:59:24,280 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/pipelines/*/*.xml; matched=false
2016-03-09 11:59:24,280 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/agents/**; matched=false
2016-03-09 11:59:24,280 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/users/**; matched=false
2016-03-09 11:59:24,281 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/material_test/**; matched=false
2016-03-09 11:59:24,281 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /api/version_infos/**; matched=false
2016-03-09 11:59:24,281 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /*/environments/*; matched=false
2016-03-09 11:59:24,281 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /oauth/admin/**; matched=false
2016-03-09 11:59:24,282 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /oauth/token; matched=false
2016-03-09 11:59:24,282 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /oauth/authorize; matched=false
2016-03-09 11:59:24,283 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /oauth/user_tokens; matched=false
2016-03-09 11:59:24,283 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /oauth/user_tokens/revoke/**; matched=false
2016-03-09 11:59:24,284 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /gadgets/pipeline.xml; matched=false
2016-03-09 11:59:24,284 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /gadgets/pipeline/**; matched=false
2016-03-09 11:59:24,285 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /gadgets/remote_materials.xml; matched=false
2016-03-09 11:59:24,285 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /gadgets/remote_materials/**; matched=false
2016-03-09 11:59:24,286 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /plugin/interact/**; matched=false
2016-03-09 11:59:24,286 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /agents/*/job_run_history*; matched=false
2016-03-09 11:59:24,286 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /agents/*/job_run_history/*; matched=false
2016-03-09 11:59:24,287 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /metrics; matched=false
2016-03-09 11:59:24,287 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /metrics/*; matched=false
2016-03-09 11:59:24,287 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /config_view/templates/*; matched=false
2016-03-09 11:59:24,288 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /add-on/*/admin/**; matched=false
2016-03-09 11:59:24,288 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /add-on/*/api/**; matched=false
2016-03-09 11:59:24,288 DEBUG [qtp2115235807-33] DefaultFilterInvocationDefinitionSource:224 - Candidate is: '/cctray.xml'; pattern is /**; matched=true
2016-03-09 11:59:24,289 DEBUG [qtp2115235807-33] AbstractSecurityInterceptor:250 - Secure object: FilterInvocation: URL: /cctray.xml; ConfigAttributes: [ROLE_USER]
2016-03-09 11:59:24,289 DEBUG [qtp2115235807-33] AbstractSecurityInterceptor:313 - Previously Authenticated: com.thoughtworks.go.server.security.OauthAuthenticationToken@fcc2ffcc: Principal: org.springframework.security.userdetails.User@0: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_OAUTH_USER; Password: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_OAUTH_USER
2016-03-09 11:59:24,292 DEBUG [qtp2115235807-33] ExceptionTranslationFilter:167 - Access is denied (user is not anonymous); delegating to AccessDeniedHandler
org.springframework.security.AccessDeniedException: Access is denied
	at org.springframework.security.vote.AffirmativeBased.decide(AffirmativeBased.java:68)
	at org.springframework.security.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:262)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:106)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.providers.anonymous.AnonymousProcessingFilter.doFilterHttp(AnonymousProcessingFilter.java:105)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.UserEnabledCheckFilter.doFilterHttp(UserEnabledCheckFilter.java:64)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:173)
	at com.thoughtworks.go.server.security.BasicAuthenticationFilter.doFilterHttp(BasicAuthenticationFilter.java:54)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.OauthAuthenticationFilter.doFilterHttp(OauthAuthenticationFilter.java:65)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.RemoveAdminPermissionFilter.doFilterHttp(RemoveAdminPermissionFilter.java:73)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
	at com.thoughtworks.go.server.security.GoLogoutFilter.doFilterHttp(GoLogoutFilter.java:48)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.web.ApiSessionFilter.doFilterHttp(ApiSessionFilter.java:47)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.ModeAwareFilter.doFilter(ModeAwareFilter.java:48)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.PerformanceLoggingFilter.doFilter(PerformanceLoggingFilter.java:50)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:174)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
2016-03-09 11:59:24,293 DEBUG [qtp2115235807-33] HttpSessionContextIntegrationFilter:255 - SecurityContextHolder now cleared, as request processing completed
```

**Comment by ketan** [comment]
False alarm — it seems that OAuth is only enabled for certain URLs (`ROLE_OAUTH_USER` in acegi.xml), and accessing one of those URLs seems to work.
