### ISSUE TITLE
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify

### ISSUE THREAD

**Issue by parksfamily** [gocd/gocd#2043]
##### Issue Type

- Bug Report

##### Summary
It is a problem when excute agent.
how can i do?

###### Basic environment details
Go Version: 
server : 15.1.0
agent : 15.1.0

JAVA Version : jdk1.7.0_80
OS : windows server 2012 r2

##### Actual Results(agent error log)
[loopThread] ERROR thoughtworks.go.agent.AgentController:145 - [Agent Loop] Error occurred during loop: 
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
 at com.rsa.sslj.x.aH.d(Unknown Source)
 at com.rsa.sslj.x.ap.a(Unknown Source)
 at com.rsa.sslj.x.ap.a(Unknown Source)
 at com.rsa.sslj.x.ap.a(Unknown Source)
 at com.rsa.sslj.x.ap.a(Unknown Source)
 at com.rsa.sslj.x.am.write(Unknown Source)
 at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
 at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
 at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:827)
 at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1525)
 at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:1975)
 at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:993)
 at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:397)
 at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
 at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
 at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
 at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:54)
 at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:47)
 at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:129)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
 at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
 at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
 at java.util.TimerThread.mainLoop(Timer.java:555)
 at java.util.TimerThread.run(Timer.java:505)

**Comment by arvindsv** [comment]
There seems to be something wrong here. I don't think com.rsa is a package used by anything in GoCD. This probably has something to do with custom modifications made to the Java instance being used. Closing this, since it doesn't seem to be related to GoCD. Happy to reopen if proven wrong. :)
