### ISSUE TITLE
Exceptions in server logs post upgrade 

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#2088]
##### Issue Type

- Bug Report

Accessing dashboard post Upgrade of Go Server returns a 500 response. This error response was returned only once, upon refreshing the page things were as expected.

Upon inspecting the go-server logs, found the following exceptions,

```
RuntimeError (Circular dependency detected while autoloading constant Spring):
lib/services.rb:5:in `get_service'
lib/services.rb:18:in `server_health_service'
app/controllers/application_controller.rb:88:in `populate_health_messages'
lib/jetty_weak_etag_middleware.rb:13:in `call'
lib/catch_json_parse_errors.rb:8:in `call'
```

and

```
java.io.InvalidClassException: com.thoughtworks.go.server.service.AgentRuntimeInfo; local class incompatible: stream classdesc serialVersionUID = -7574538669713700830,
   at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:617)
   at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1622)
   at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
   at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
   at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1706)
   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1344)
   at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
   at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
   at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
   at org.springframework.remoting.rmi.RemoteInvocationSerializingExporter.doReadRemoteInvocation(RemoteInvocationSerializingExporter.java:141)
   at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:116)
   at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95)
   at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72)
   at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:49)
   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
   at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
   at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
   at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:359)
   at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
   at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
   at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
   at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
   at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
```
- Go Version: From '14.4' to `16.3`
- JAVA Version: `Java &`
- Agent Bootstrap Version: '13.4'

**Comment by arvindsv** [comment]
Closing. Let's reopen this if it happens again. And fix it.
