### ISSUE TITLE
Broken package - org.eclipse.jgit.api.errors.RefNotFoundException

### ISSUE THREAD

**Issue by sriprasanna** [gocd/gocd#2133]
**Bug Report**:
I am trying to provision go-server on a Vagrant box. But the server cannot start and throws an exception(stracktrace below).

**Environment**
Vagrant box: bento/centos-7.1
Provisioned with https://supermarket.chef.io/cookbooks/gocd
Stacktrace:

`````` plain
2016-04-22 14:07:00,784  INFO [main] ServerVersion:72 - [Startup] Environment Variables: {TERM=xterm-256color, OLDPWD=/var/go, SHELL=/bin/bash, HISTSIZE=1000, JAVA_HOME=/usr/lib/jvm/java-1.7.0, SHLVL=1, SERVER_WORK_DIR=/var/lib/go-server, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/go/.local/bin:/var/go/bin, SERVER_MAX_MEM=2048m, MAIL=/var/spool/mail/go, USER=go, HOSTNAME=localhost.localdomain, PWD=/var/lib/go-server, GO_SERVER_PORT=8153, SERVER_MAX_PERM_GEN=400m, HISTCONTROL=ignoredups, HOME=/var/go, LOGNAME=go, LESSOPEN=||/usr/bin/lesspipe.sh %s, XDG_SESSION_ID=4, GO_SERVER_SSL_PORT=8154, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, SERVER_MEM=1024m, LANG=en_US.UTF-8}
2016-04-22 14:07:19,229 ERROR [main] ConfigRepository:380 - [CONFIG_MERGE] Checkout to branch master failed
org.eclipse.jgit.api.errors.RefNotFoundException: Ref master can not be resolved
    at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:243)
    at com.thoughtworks.go.service.ConfigRepository.checkout(ConfigRepository.java:378)
    at com.thoughtworks.go.service.ConfigRepository.cleanAndResetToMaster(ConfigRepository.java:388)
    at com.thoughtworks.go.service.ConfigRepository.initialize(ConfigRepository.java:79)
    at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:101)
    at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:48)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
    at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:89)
    at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
    at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
    at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.simontuffs.onejar.Boot.run(Boot.java:306)
    at com.simontuffs.onejar.Boot.main(Boot.java:159)
2016-04-22 14:07:19,258 ERROR [main] ConfigRepository:393 - Error while trying to clean up config repository, CurrentBranch: master```

Let me know if you need more information.
``````

**Comment by malytic** [comment]
I've encountered the same error message:
```
ERROR [main] ConfigRepository:380 - [CONFIG_MERGE] Checkout to branch master failed
org.eclipse.jgit.api.errors.RefNotFoundException: Ref master can not be resolved
```
For me it was solved by moving `config-repos` to after `repositories` in `cruise-config.xml`.
Initially I had the following config:
```xml
<cruise>
  <server>...</server>
  <config-repos>...</config-repos>
  <repositories>...</repositories>
</cruise>
```
When I moved `config-repos` to after `repositories` the error disappeared:
```xml
<cruise>
  <server>...</server>
  <repositories>...</repositories>
  <config-repos>...</config-repos>
</cruise>
```

**Comment by varshavaradarajan** [comment]
@malytic, @sriprasanna  - The error `org.eclipse.jgit.api.errors.RefNotFoundException: Ref master can not be resolved`  is for the internal git repository that gocd maintains for the `cruise-config.xml`. The location for this is `<server_installation_directory>/db/config.git`. Please check if you can execute `git checkout master` there. In all likelihood, the error is because the server got abruptly stopped while the git repository was being created. You can move the config.git directory and start the server properly.
