### ISSUE TITLE
Websocket based communication with Shine enabled does not play well

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#2249]
##### Issue Type
- Bug Report

##### Summary

* Enable websockets for agent-server communication
* Enable Shine
* When a job completion causes a stage to get completed, it sends a callback to shine(check [this](https://github.com/gocd/gocd/blob/23aad62d61ebdbb2eeb57cd7d11a9fc7dac462f1/server/src/com/thoughtworks/go/server/service/ScheduleService.java#L527) and follow through [this](https://github.com/gocd/gocd/blob/23aad62d61ebdbb2eeb57cd7d11a9fc7dac462f1/server/src/com/thoughtworks/go/server/service/StageService.java#L284), then [this](https://github.com/gocd/gocd/blob/23aad62d61ebdbb2eeb57cd7d11a9fc7dac462f1/server/src/com/thoughtworks/go/server/service/StageService.java#L233), then [this](https://github.com/gocd/gocd/blob/23aad62d61ebdbb2eeb57cd7d11a9fc7dac462f1/server/src/com/thoughtworks/studios/shine/cruise/BackgroundStageLoader.java#L103))
* For some reason, shine fails to find `GoDateTime` class which is used for the xslt transformation and fails with the following stacktrace:
```
java.lang.RuntimeException: Cannot call method public void com.thoughtworks.go.server.websocket.AgentRemoteSocket#onMessage(java.io.InputStream) with args: [org.eclipse.jetty.websocket.common.message.MessageInputStream]
    at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.unwrapRuntimeException(CallableMethod.java:93)
    at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:75)
    at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)
    at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$1.run(JettyAnnotatedEventDriver.java:91)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/thoughtworks/studios/shine/cruise/GoDateTime
    at GregorSamsa.template$dot$5()
    at GregorSamsa.applyTemplates()
    at GregorSamsa.template$dot$1()
    at GregorSamsa.applyTemplates()
    at GregorSamsa.template$dot$0()
    at GregorSamsa.applyTemplates()
    at GregorSamsa.transform()
    at com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet.transform(AbstractTranslet.java:620)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:739)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:351)
    at com.thoughtworks.studios.shine.semweb.grddl.GRDDLTransformer.transform(GRDDLTransformer.java:46)
    at com.thoughtworks.studios.shine.cruise.GoGRDDLResourceRDFizer.importFile(GoGRDDLResourceRDFizer.java:52)
    at com.thoughtworks.studios.shine.cruise.GoGRDDLResourceRDFizer.importDocumentUsingGRDDL(GoGRDDLResourceRDFizer.java:70)
    at com.thoughtworks.studios.shine.cruise.GoGRDDLResourceRDFizer.importURIUsingGRDDL(GoGRDDLResourceRDFizer.java:61)
    at com.thoughtworks.studios.shine.cruise.stage.details.StageResourceImporter.loadIsolatedStageGraph(StageResourceImporter.java:96)
    at com.thoughtworks.studios.shine.cruise.stage.details.StageResourceImporter.load(StageResourceImporter.java:82)
    at com.thoughtworks.studios.shine.cruise.BackgroundStageLoader.handle(BackgroundStageLoader.java:70)
    at com.thoughtworks.studios.shine.cruise.stage.feeds.StageAtomFeedsReader.readFromLatest(StageAtomFeedsReader.java:51)
    at com.thoughtworks.studios.shine.cruise.BackgroundStageLoader.load(BackgroundStageLoader.java:61)
    at com.thoughtworks.studios.shine.cruise.BackgroundStageLoaderStageStatusListener.stageStatusChanged(BackgroundStageLoader.java:103)
    at com.thoughtworks.go.server.service.StageService$4.afterCommit(StageService.java:233)
    at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCommit(TransactionSynchronizationUtils.java:133)
    at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerAfterCommit(TransactionSynchronizationUtils.java:121)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCommit(AbstractPlatformTransactionManager.java:950)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:796)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:147)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
    at com.thoughtworks.go.server.service.ScheduleService.updateJobStatus(ScheduleService.java:508)
```

**Comment by djrice** [comment]
If it helps, this issue did not exist in 16.5

**Comment by zabil** [comment]
Think it's this line that's started it.

https://github.com/gocd/gocd/blob/5feec49c4413035f71e8c0646502ee85287ad5d5/server/src/com/thoughtworks/studios/shine/semweb/grddl/XSLTTransformerRegistry.java#L64

The stylesheets gets [compiled](https://xml.apache.org/xalan-j/xsltc/xsltc_native_api.html) to translets, and can't load some extension java functions used in them.

Strangely, this happens only while using websockets.
From the internal implementation of Xalan you can set a property to pass a class loader.

```
        xsltc.setProperty(XalanConstants.JDK_EXTENSION_CLASSLOADER, _extensionClassLoader);
        xsltc.init();
```

**Comment by arvindsv** [comment]
The only commit that could do something around it is [this](https://github.com/gocd/gocd/commit/a71182c8da4bc0b73f2755babd9f067481dc1cf2), which looks ok to me.

> Strangely, this happens only while using websockets.

That is strange. I wouldn't expect websockets to cause any such classloader related issues on the server. Instead of changing the classloader, should we spend a little more time trying to see why it happens only with websockets?

**Comment by arvindsv** [comment]
Unless, of course, you saw that the classloader changed between 16.4 and 16.5.

**Comment by ketan** [comment]
Could be because the websocket classes are inside go.jar which does not
have access to the shine classes inside the war? Not sure how the websocket
classloaders work.

**Comment by zabil** [comment]
> Instead of changing the classloader, should we spend a little more time trying to see why it happens only with websockets

Trying to do that, not able replicate it on ```DevelopmentServer``` because the setup is different. 
It wasn't happening earlier because the transformer was cached and now it's the compiled template, so it looks up ```GoDateTime```.

The difference between [spring-cruise-remoting](https://github.com/gocd/gocd/blob/5feec49c4413035f71e8c0646502ee85287ad5d5/server/webapp/WEB-INF/web.xml#L145) loading as a spring servlet while [agent-websocket](https://github.com/gocd/gocd/blob/5feec49c4413035f71e8c0646502ee85287ad5d5/server/webapp/WEB-INF/web.xml#L151) loading as a websocket servlet is something to look at too.

**Comment by arvindsv** [comment]
Yeah, don't use the dev server for finding classloader issues. As you know, it completely changes it to make it work within IntelliJ.

I'd build a 16.4 server and a server off of HEAD and check for any differences in the classloader chain between the old one and the new (when it is evaluating or transforming using the templates, not compiling them). My guess is that one has the webappclassloader (WAC). I don't know what the other has.
