### ISSUE TITLE
[websocket] Agents not opening websocket sessions

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2263]
##### Issue Type
- Bug Report
##### Summary

Almost all agents running on windows went missing.
###### Basic environment details
- JAVA Version: `1.8.0_66-b18`
- Windows Server 2008 R2

This is the only trace I could find on one of the agents —

<img width="1088" alt="screen shot 2016-06-05 at 12 24 12 pm" src="https://cloud.githubusercontent.com/assets/10598/15804062/3b416240-2b19-11e6-8fb6-f4ed3cdd45e1.png">

**Comment by zabil** [comment]
16.7+ The following error is reported on the logs and the agents do not connect to the server when websockets are enabled.

```
2016-09-23 17:43:43,467 [loopThread] ERROR thoughtworks.go.agent.AgentController:270 - Error occurred when agent tried to ping server:
java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.FuturePromise.get(FuturePromise.java:123)
	at com.thoughtworks.go.agent.service.AgentWebsocketService.start(AgentWebsocketService.java:148)
	at com.thoughtworks.go.agent.AgentController.websocketPing(AgentController.java:262)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:482)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:109)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:116)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.close(SslConnection.java:913)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:667)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:841)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:364)
	at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:98)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```
