### ISSUE TITLE
Invalid entries in cruise-config.xml break the login mechanism

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#2348]
##### Issue Type
- Bug Report

##### Summary
If the cruise-config.xml is edited manually and a user introduces a role definition within a pipeline, all authentication mechanisms break and a login into the server is not possible anymore.
As soon as the erroneous XML segment is removed, login works again.

Details:
 - The role with its members is not defined in the correct global position but within the pipeline. Thus the pipeline does not reference a role for a given authorization but attempts to define it in-place.
- There is no useful logging using the standard logging configuration that would hint to this issue.

##### Environment
- Go 16.1
- CentOS 7
- OpenJDK 7

##### Steps to Reproduce
See above. 
Additional details will be provided soon.

##### Expected Results
- The server should complain about invalid config XML upon starting / config reload in the log.
- It would also be nice to see the offending line.
- Login should either work aside from this issue or the login screen should present a warning that hints to the logs. 

##### Actual Results
The logs only show
```
2016-06-22 11:27:30,474 ERROR [qtp57730642-30] BasicAuthenticationFilter:56 -
```
The login stops working with all authentication backends.

##### Log snippets
```
2016-06-22 11:27:30,282 DEBUG [qtp57730642-25] AnonymousProcessingFilter:93 - Populated SecurityContextHolder with anonymous token: 'org.springframework.security.providers.anonymous.AnonymousAuthenticationToken@6fa8940c: Principal: anonymousUser; Password: [PROTECTED]; Authenticated: true; Details: org.springframework.security.ui.WebAuthenticationDetails@fffde5d4: RemoteIpAddress: 1.2.3.4; SessionId: xxx; Granted Authorities: ROLE_ANONYMOUS'
2016-06-22 11:27:30,283 DEBUG [qtp57730642-25] GoExceptionTranslationFilter:104 - Chain processed normally
2016-06-22 11:27:30,474 ERROR [qtp57730642-30] BasicAuthenticationFilter:56 -
2016-06-22 11:27:30,474 DEBUG [qtp57730642-30] BasicAuthenticationFilter:57 -
java.lang.NullPointerException
    at com.thoughtworks.go.config.AdminRole.isSameAs(AdminRole.java:45)
    at com.thoughtworks.go.config.AdminsConfig.isAdmin(AdminsConfig.java:42)
    at com.thoughtworks.go.config.TemplatesConfig.canViewAndEditTemplate(TemplatesConfig.java:102)
    at com.thoughtworks.go.server.service.GoConfigService.isAuthorizedToViewAndEditTemplates(GoConfigService.java:1096)
    at com.thoughtworks.go.server.service.SecurityService.isAuthorizedToViewAndEditTemplates(SecurityService.java:196)
    at com.thoughtworks.go.server.security.AuthorityGranter.checkAndAddTemplateAdmin(AuthorityGranter.java:49)
    at com.thoughtworks.go.server.security.AuthorityGranter.authorities(AuthorityGranter.java:43)
    at com.thoughtworks.go.server.security.GoLdapAuthoritiesPopulator.getGrantedAuthorities(GoLdapAuthoritiesPopulator.java:33)
    at org.springframework.security.providers.ldap.LdapAuthenticationProvider.loadUserAuthorities(LdapAuthenticationProvider.java:243)
    at org.springframework.security.providers.ldap.LdapAuthenticationProvider.authenticate(LdapAuthenticationProvider.java:231)
    at com.thoughtworks.go.server.security.providers.GoAuthenticationProvider.authenticate(GoAuthenticationProvider.java:38)
    at org.springframework.security.providers.ProviderManager.doAuthentication(ProviderManager.java:195)
    at org.springframework.security.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:46)
    at org.springframework.security.ui.webapp.AuthenticationProcessingFilter.attemptAuthentication(AuthenticationProcessingFilter.java:82)
    at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:252)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:173)
    at com.thoughtworks.go.server.security.BasicAuthenticationFilter.doFilterHttp(BasicAuthenticationFilter.java:54)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.security.OauthAuthenticationFilter.doFilterHttp(OauthAuthenticationFilter.java:65)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.security.RemoveAdminPermissionFilter.doFilterHttp(RemoveAdminPermissionFilter.java:60)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
    at com.thoughtworks.go.server.security.GoLogoutFilter.doFilterHttp(GoLogoutFilter.java:48)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
    at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.security.ModeAwareFilter.doFilter(ModeAwareFilter.java:48)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at com.thoughtworks.go.server.security.PerformanceLoggingFilter.doFilter(PerformanceLoggingFilter.java:50)
    at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
    at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:174)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by sadovnikov** [comment]
@lenucksi I'm resolving this issue in https://github.com/JV-ration/gocd/pull/1. It's easy to prevent ```NullPointerException``` and this will restore login mechanism. However I don't expect anything to start complaining about invalid XML. Could you provide wrong XML example, so I can check its loading too?
