### ISSUE TITLE
Pending agent shows a misleading stack trace

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#2464]
Mentioned here: https://groups.google.com/d/topic/go-cd/zLqeECge1t4/discussion

* Server gets an agent [registration request](https://github.com/gocd/gocd/blob/d87f6242bb52541cf20b01226c0a5fc994474a2e/server/src/com/thoughtworks/go/server/service/AgentService.java#L325).
* Since the agent should be pending, it returns a [null private key](https://github.com/gocd/gocd/blob/d87f6242bb52541cf20b01226c0a5fc994474a2e/common/src/com/thoughtworks/go/domain/AgentInstance.java#L220) to [here](https://github.com/gocd/gocd/blob/d87f6242bb52541cf20b01226c0a5fc994474a2e/server/src/com/thoughtworks/go/server/controller/AgentRegistrationController.java#L233).
* This gets [serialized](https://github.com/gocd/gocd/blob/d87f6242bb52541cf20b01226c0a5fc994474a2e/server/src/com/thoughtworks/go/server/controller/AgentRegistrationController.java#L249) and goes over with no key.
* Agent tries to deserialize it and fails.

Log with more context than the one in the mailing list, courtesy @dudadornelles:

```
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - >> "GET /go/admin/latest-agent.status HTTP/1.1[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - >> "User-Agent: Jakarta Commons-HttpClient/3.0.1[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - >> "Host: delivery.sonicdrivein.digital:8154[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - >> "Cookie: $Version=0; JSESSIONID=1lhi0tydld2weamt53xuxwzle; $Path=/go[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - >> "[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - << "HTTP/1.1 200 OK[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - << "Date: Wed, 20 Jul 2016 22:05:38 GMT[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - << "Agent-Content-MD5: fz/hrJeCNFIbFznCD2owjw==[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - << "Agent-Launcher-Content-MD5: iOKsTCPCubjkr0UseSnMkA==[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - << "Agent-Plugins-Content-MD5: da4343018be5c3cdfa589b95fd82f3b4[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - << "Cruise-Server-Ssl-Port: 8154[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] DEBUG httpclient.wire.header:69 - << "Content-Length: 0[\r][\n]"
2016-07-20 22:05:37,112 [loopThread] INFO  go.agent.service.SslInfrastructureService:93 - [Agent Registration] Starting to register agent
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - >> "POST /go/admin/agent HTTP/1.1[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - >> "User-Agent: Jakarta Commons-HttpClient/3.0.1[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - >> "Host: delivery.sonicdrivein.digital:8154[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - >> "Cookie: $Version=0; JSESSIONID=w1spncspt4wl1vwkcwkwtzrp1; $Path=/go[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - >> "Content-Length: 321[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - >> "Content-Type: application/x-www-form-urlencoded[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - >> "[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.content:83 - >> "hostname=WIN-7E0370BVVAM&uuid=9d09b09d-72ca-40f4-9105-51be7b841a1f&location=C%3A%5CProgram+Files+%28x86%29%5CGo+Agent&usablespace=25613254656&operatingSystem=Windows+Server+2012+R2&agentAutoRegisterKey=&agentAutoRegisterResources=&agentAutoRegisterEnvironments=&agentAutoRegisterHostname=&elasticAgentId=&elasticPluginId="
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - << "HTTP/1.1 200 OK[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - << "Date: Wed, 20 Jul 2016 22:05:38 GMT[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - << "Content-Language: en-US[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.header:69 - << "Content-Length: 108[\r][\n]"
2016-07-20 22:05:37,127 [loopThread] DEBUG httpclient.wire.content:83 - << "{"agentPrivateKey":"-----BEGIN RSA PRIVATE KEY-----\n-----END RSA PRIVATE KEY-----\n","agentCertificate":""}"
2016-07-20 22:05:37,127 [loopThread] ERROR go.agent.service.SslInfrastructureService:112 - [Agent Registration] There was a problem registering with the go server.
java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.lang.String.charAt(Unknown Source)
	at org.bouncycastle.util.encoders.Base64Encoder.decode(Unknown Source)
	at org.bouncycastle.util.encoders.Base64.decode(Unknown Source)
	at org.bouncycastle.util.io.pem.PemReader.loadObject(Unknown Source)
	at org.bouncycastle.util.io.pem.PemReader.readPemObject(Unknown Source)
	at com.thoughtworks.go.security.Registration.fromJson(Registration.java:49)
	at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.readResponse(SslInfrastructureService.java:202)
	at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.requestRegistration(SslInfrastructureService.java:195)
	at com.thoughtworks.go.agent.service.SslInfrastructureService.register(SslInfrastructureService.java:110)
	at com.thoughtworks.go.agent.service.SslInfrastructureService.registerIfNecessary(SslInfrastructureService.java:94)
	at com.thoughtworks.go.agent.AgentController.rpcLoop(AgentController.java:173)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:165)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
```

**Comment by arvindsv** [comment]
Solution is to just enable the agent, but the error message on the agent is misleading. Knowing what happens, it can easily provide a nice message about pending agents.

**Comment by dharapvj** [comment]
As a complete newbie.. I spent almost half an hour trying to figure out what's wrong.. looking at this error.

Also, after the agent was enabled on server, the console did not show any log (at INFO level) that the agent is now enabled (/launched). Last message continues to be "Launching..." The log file showed that the registration was successful. We can change the log level so that the enablement shows up in the log.

**Comment by ketan** [comment]
We have identified the problem and have a fix for the problem — #2558 will be merged as soon as 16.8 is out (probably today or tomorrow)

**Comment by tomzo** [comment]
I am seeing this error on few new agents on 16.8.0 and **autoregistration seems broken**. Agents re-attempts to register every few seconds and fails.

This problem exists on all new agents since I deployed 16.8.0 version.  I do deployments with chef and go-cookbook, always the same way, so I am quite confident there is some gocd problem, not my setup.

For these agents o register, I had to remove `/var/lib/go-agent/0/config/guid.txt` and restart agent. Only restarting a new agent does not help - double checked that.

I tried `/etc/default/go-agent` with
```
export GO_SERVER=go.ai-traders.com
export GO_SERVER_PORT=8153
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export AGENT_WORK_DIR=/var/lib/go-agent/0
DAEMON=Y
VNC=N
```
Also with `export GO_SERVER_URL=https://go.ai-traders.com:8154/go`

Agent has auto-register config `/var/lib/go-agent/0/config/autoregister.properties`
```
#
# File autogenerated by chef. All changes will be lost
#

agent.auto.register.key          = something
agent.auto.register.hostname     = msq-stage


agent.auto.register.environments = stage

agent.auto.register.resources    = admin, stc_msq_vm
```

### Agent logs
```
2016-09-05 14:54:48,982 [loopThread] INFO  go.agent.service.SslInfrastructureService:85 - [Agent Registration] Starting to register agent
2016-09-05 14:54:49,202 [loopThread] ERROR go.agent.service.SslInfrastructureService:104 - [Agent Registration] There was a problem registering with the go server.
java.lang.StringIndexOutOfBoundsException: String index out of range: -4
        at java.lang.String.charAt(String.java:658)
        at org.bouncycastle.util.encoders.Base64Encoder.decode(Unknown Source)
        at org.bouncycastle.util.encoders.Base64.decode(Unknown Source)
        at org.bouncycastle.util.io.pem.PemReader.loadObject(Unknown Source)
        at org.bouncycastle.util.io.pem.PemReader.readPemObject(Unknown Source)
        at com.thoughtworks.go.security.Registration.fromJson(Registration.java:43)
        at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.readResponse(SslInfrastructureService.java:186)
        at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.requestRegistration(SslInfrastructureService.java:178)
        at com.thoughtworks.go.agent.service.SslInfrastructureService.register(SslInfrastructureService.java:102)
        at com.thoughtworks.go.agent.service.SslInfrastructureService.registerIfNecessary(SslInfrastructureService.java:86)
        at com.thoughtworks.go.agent.AgentController.rpcLoop(AgentController.java:181)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:173)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2016-09-05 14:54:49,203 [loopThread] ERROR thoughtworks.go.agent.AgentController:192 - [Agent Loop] Error occurred during loop: 
java.lang.StringIndexOutOfBoundsException: String index out of range: -4
        at java.lang.String.charAt(String.java:658)
        at org.bouncycastle.util.encoders.Base64Encoder.decode(Unknown Source)
        at org.bouncycastle.util.encoders.Base64.decode(Unknown Source)
        at org.bouncycastle.util.io.pem.PemReader.loadObject(Unknown Source)
        at org.bouncycastle.util.io.pem.PemReader.readPemObject(Unknown Source)
        at com.thoughtworks.go.security.Registration.fromJson(Registration.java:43)
        at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.readResponse(SslInfrastructureService.java:186)
        at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.requestRegistration(SslInfrastructureService.java:178)
        at com.thoughtworks.go.agent.service.SslInfrastructureService.register(SslInfrastructureService.java:102)
        at com.thoughtworks.go.agent.service.SslInfrastructureService.registerIfNecessary(SslInfrastructureService.java:86)
        at com.thoughtworks.go.agent.AgentController.rpcLoop(AgentController.java:181)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:173)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**Comment by rajiesh** [comment]
Verified on GoCD version 16.10.0 (4129-e51ab2ff4bc66d88a93254c209ee60e42a1112bc), working as expected
