### ISSUE TITLE
Idle agent uses a lot of memory

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2502]
##### Issue Type
- Bug Report
##### Summary

When running a 16.7.0 agent it uses around **460MB** memory when idle after just starting up. In version 16.3.0 it used around **285MB**.
##### Environment

It runs on **debian jessie** using **openjdk-8-jre-headless**. With following envvars:
- AGENT_MEM=128m
- AGENT_MAX_MEM=256m
##### Steps to Reproduce

Run the following and check docker stats. For GO_SERVER_URL use the correct address, otherwise the agent is in a waiting loop, before starting the agent process.

**16.7.0**

```
> docker run -d -p 8153:8153 -p 8154:8154 -e "AGENT_KEY=abc" travix/gocd-server:16.7.0
> docker run -d -e "GO_SERVER_URL=https://192.168.99.100:8154/go" -e "AGENT_KEY=abc" travix/gocd-agent:16.7.0
```

**16.3.0**

```
> docker run -d -p 8153:8153 -p 8154:8154 -e "AGENT_KEY=abc" travix/gocd-server:16.3.0
> docker run -d -e "GO_SERVER=192.168.99.100" -e "AGENT_KEY=abc" travix/gocd-agent:16.3.0
```

**Comment by JorritSalverda** [comment]
In 16.6.0 it uses around **300MB**, so the big change happened between version 16.6.0 and 16.7.0.

```
docker run -d -p 8153:8153 -p 8154:8154 -e "AGENT_KEY=abc" travix/gocd-server:16.6.0
docker run -d -e "GO_SERVER=192.168.99.100" -e "AGENT_KEY=abc" travix/gocd-agent:16.6.0
```

**Comment by JorritSalverda** [comment]
@ketan when I'm trying to get the memory dump you asked for jmap fails.

Inside the docker container I have the following java processes running.

```
go          22  5.8  8.4 2477312 173500 ?      Sl   14:40   0:03 java -jar /usr/share/go-agent/agent-bootstrapper.jar -serverUrl https://192.168.99.100:8154/go -sslVerificationMode NONE
go          50 12.3 10.8 2237112 222056 ?      Sl   14:40   0:06 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Djava.security.egd=file:/dev/./u
```

When trying to run `jmap -dump:format=b,file=FILENAME.BIN 50` it gives the following error:

```
50: Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding
```

When using the suggested option (`jmap -F -dump:format=b,file=FILENAME.BIN 50`) it gives the following stacktrace:

```
Attaching to process ID 50, please wait...
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.execute(LinuxDebuggerLocal.java:163)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:278)
        at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
        at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
        at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
        at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
        at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.HeapDumper.main(HeapDumper.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jmap.JMap.runTool(JMap.java:201)
        at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.access$100(LinuxDebuggerLocal.java:62)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1AttachTask.doit(LinuxDebuggerLocal.java:269)
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.run(LinuxDebuggerLocal.java:138)
```

To make sure I had the jmap tool in the first place I ran a different version of our go.cd agent with JDK installed:

```
docker run -d -p 8153:8153 -p 8154:8154 -e "AGENT_KEY=abc" travix/gocd-server:16.7.0
docker run -d -e "GO_SERVER_URL=https://192.168.99.100:8154/go" -e "AGENT_KEY=abc" travix/gocd-agent-gcloud-jdk-8:16.7.0
```

Any idea on how to get the memory dump?

**Comment by JorritSalverda** [comment]
In 16.8.0 it's down to **407MB**. Still not anywhere near the 300MB of 16.6.0.

```
> docker run -d -p 8153:8153 -p 8154:8154 -e "AGENT_KEY=abc" travix/gocd-server:16.8.0
> docker run -d -e "GO_SERVER_URL=https://192.168.99.100:8154/go" -e "AGENT_KEY=abc" travix/gocd-agent:16.8.0

```

**Comment by JorritSalverda** [comment]
In 16.9.0 it hasn't improved with **419MB** of memory usage.

```
> docker run -d -p 8153:8153 -p 8154:8154 -e "AGENT_KEY=abc" travix/gocd-server:16.9.0
> docker run -d -e "GO_SERVER_URL=https://192.168.99.100:8154/go" -e "AGENT_KEY=abc" travix/gocd-agent:16.9.0
```

**Comment by zabil** [comment]
We are looking into this. Here's some initial stats from docker

```
Version     Process                     Memory  JDK
----------------------------------------------------
16.3.0      Bootstrapper and launcher   116 MB  1.7
16.3.0      Bootstrapper and agent      462 MB  1.7
16.6.0      Bootstrapper and launcher   145 MB  1.7
16.6.0      Bootstrapper and agent      488 MB  1.7
16.7.0      Bootstrapper and launcher   135 MB  1.7
16.7.0      Bootstrapper and agent      546 MB  1.7
```

**Comment by zabil** [comment]
Heap dump of agent.jar recorded on 16.6
```
Heap
 PSYoungGen      total 58368K, used 18515K [0x00000000faa80000, 0x0000000100000000, 0x0000000100000000)
  eden space 29184K, 34% used [0x00000000faa80000,0x00000000fb43fd10,0x00000000fc700000)
  from space 29184K, 29% used [0x00000000fc700000,0x00000000fcf552e8,0x00000000fe380000)
  to   space 29184K, 0% used [0x00000000fe380000,0x00000000fe380000,0x0000000100000000)
 ParOldGen       total 112640K, used 73689K [0x00000000f0000000, 0x00000000f6e00000, 0x00000000faa80000)
  object space 112640K, 65% used [0x00000000f0000000,0x00000000f47f64a8,0x00000000f6e00000)
 PSPermGen       total 21504K, used 20959K [0x00000000e5a00000, 0x00000000e6f00000, 0x00000000f0000000)
  object space 21504K, 97% used [0x00000000e5a00000,0x00000000e6e77e50,0x00000000e6f00000)
```

vs 16.7

```
Heap
 PSYoungGen      total 58368K, used 24895K [0x00000000faa80000, 0x0000000100000000, 0x0000000100000000)
  eden space 29184K, 45% used [0x00000000faa80000,0x00000000fb75f918,0x00000000fc700000)
  from space 29184K, 40% used [0x00000000fe380000,0x00000000feef0468,0x0000000100000000)
  to   space 29184K, 0% used [0x00000000fc700000,0x00000000fc700000,0x00000000fe380000)
 ParOldGen       total 109056K, used 75642K [0x00000000f0000000, 0x00000000f6a80000, 0x00000000faa80000)
  object space 109056K, 69% used [0x00000000f0000000,0x00000000f49de9a8,0x00000000f6a80000)
 PSPermGen       total 22528K, used 22255K [0x00000000e5a00000, 0x00000000e7000000, 0x00000000f0000000)
  object space 22528K, 98% used [0x00000000e5a00000,0x00000000e6fbbd68,0x00000000e7000000)

```

**Comment by zabil** [comment]
Results from profiling the bootstrapper and agent.
The results were recorded on an Ubuntu 16.04 bare metal machine with Java 8.
There's a 10MB increase in heap size for both the agent and boot strapper. And that means a total overhead of around 20-25MB
 
```
                                        16.7   16.3 
Bootstrapper
  Used heap space (MB)                  82    66
  GC'd heap space (MB)                  18    18
  Total Size      (MB)                  176   162
  Max             (MB)                  207   207

Agent
  Used heap space (MB)                  118   108 
  GC'd heap space (MB)                  91    79
  Total Size      (MB)                  250   240
  Max             (MB)                  268   268
  Total loaded classes                  4366  3999
  Loop thread (% of memory)             32%   21%
  Ping thread (% of memory)             31%   11.5%
```

**Comment by zabil** [comment]
The increase in memory is due to increase in size byte code and code cache while migrating from httpclient3 to httpclient4.

We've also tested this by rebuilding the docker images (16.3, 16.4) using the latest dockerfile at https://github.com/gocd/gocd-docker/blob/master/centos/agent/Dockerfile

The only way to reduce the memory is migrating to a lightweight http client library like http://www.eclipse.org/jetty/documentation/9.3.x/http-client.html or by making web sockets work to reduce memory overhead of the ping and loop thread.

**Comment by JorritSalverda** [comment]
Ah, this nice blog post touched on the 'virtues' of the code cache as well.

http://engineering.indeedblog.com/blog/2016/09/job-search-web-app-java-8-migration/

It doesn't make java a strong contester amongst the likes of golang. Speaking of which how is the golang agent coming along? :)

**Comment by zabil** [comment]
The golang agent works. 
We don't support it officially though.

vs battling jvm issues we'll probably be shifting to golang agents once all priority items are sorted.
