### ISSUE TITLE
OAuth gadgets tab very confusing

### ISSUE THREAD

**Issue by savaki** [gocd/gocd#2504]
##### Issue Type
- Bug Report
##### Summary

Attempted to configure the google oauth plugin and instead configured the oauth gadget.
##### Environment

Happens in all environments
###### Basic environment details

n/a
###### Additional Environment Details

n/a
##### Steps to Reproduce
1. install the google-oauth-plugin
2. set a password file
3. you should be required to login at this point
4. login 
5. go to the admin page
6. Notice that there are two tabs labeled oauth
7. Note that the oauth gadgets tab seems to have the properties that need to be set for the oauth plugin
##### Expected Results
1. hoped documentation would provide step by step illustrated steps.  docs assumed knowledge i didn't have and consequently was difficult to follow
2. expected some explanation of what a gadget was.  i assumed it was another error in documentation and it should have been called plugins.  even now, I don't really understand the difference between gadget and plugin
3. input appears to be accepted and G+ button is available from the home screen
4. expected the G+ button to not appear until the plugin was properly configured
##### Actual Results

I entered all the oauth settings into the oauth gadgets tab and was unable to login.  The error message was a non informative stack trace.
##### Possible Fix

Mostly a documentation and comprehension issue.  Need to make clear that a gadget is not a plugin and that this is not the place to configure oauth.  Perhaps it would be useful to describe what this does configure.
##### Log snippets

==> plugin-google.oauth.login.log <==
2016-07-30 10:02:44,844 ERROR [qtp1334729950-24] OAuthLoginPlugin:77 - Error occurred while OAuth setup.
java.lang.RuntimeException: plugin is not configured. please provide plugin settings.
    at com.tw.go.plugin.OAuthLoginPlugin.getPluginSettings(OAuthLoginPlugin.java:232)
    at com.tw.go.plugin.OAuthLoginPlugin.handleSetupLoginWebRequest(OAuthLoginPlugin.java:206)
    at com.tw.go.plugin.OAuthLoginPlugin.handle(OAuthLoginPlugin.java:99)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
    at com.thoughtworks.go.server.plugin.controller.PluginController.handlePluginInteractRequest(PluginController.java:59)
##### Code snippets/Screenshots

n/a

**Comment by ketan** [comment]
Closing there are no oauth tabs anymore.
