### ISSUE TITLE
`encryptedPassword` attribute can be overwritten without the server performing any validations

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2568]
##### Issue Type

- Bug Report

##### Summary

It is currently possible to directly edit the XML and change the `encryptedPassword` attribute of SCM materials to a value that can't be decrypted using the cipher. This causes issues during material update checks and prevents the server from starting up in case the server is restarted.

##### Steps to Reproduce

1. Create a new pipeline

    ```xml
    <pipeline name="up42">
      <materials>
        <svn url="http://localhost/foo/bar" username="bob" password="p@ssw0rd" />
      </materials>
      <stage name="up42_stage">
        <jobs>
          <job name="up42_job">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
    ```

2. Save the pipeline, the password should now be encrypted (the `encryptedPassword` may differ for you)

    ```xml
    <svn url="http://localhost/foo/bar" username="bob" encryptedPassword="rw8RZMOKOqI=" />
    ```

3. Edit the pipeline again, and set the `encryptedPassword` to a bad cipher text —

    ```xml
    <svn url="http://localhost/foo/bar" username="bob" encryptedPassword="ThisShouldBomb" />
    ```

4. The config is saved without any warnings — this needs fixing.
5. Restart the server. The following exception shows up.

    ```
    Failed to start Go server. Exception:
    java.lang.RuntimeException: Failed to start Go server.
    	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:78)
    	at com.thoughtworks.go.server.DevelopmentServer.main(DevelopmentServer.java:71)
    Caused by: java.lang.RuntimeException: org.bouncycastle.crypto.DataLengthException: last block incomplete in decryption
    	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:146)
    	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:51)
    	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
    	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
    	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
    	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
    	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
    	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
    	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
    	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
    	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
    	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
    	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
    	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
    	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
    	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    	at org.eclipse.jetty.server.Server.start(Server.java:387)
    	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
    	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
    	... 1 more
    Caused by: org.bouncycastle.crypto.DataLengthException: last block incomplete in decryption
    	at org.bouncycastle.crypto.paddings.PaddedBufferedBlockCipher.doFinal(Unknown Source)
    	at com.thoughtworks.go.security.GoCipher.decipher(GoCipher.java:68)
    	at com.thoughtworks.go.security.GoCipher.decrypt(GoCipher.java:48)
    	at com.thoughtworks.go.config.materials.svn.SvnMaterialConfig.currentPassword(SvnMaterialConfig.java:157)
    	at com.thoughtworks.go.config.materials.svn.SvnMaterialConfig.getPassword(SvnMaterialConfig.java:147)
    	at com.thoughtworks.go.config.materials.svn.SvnMaterial.<init>(SvnMaterial.java:93)
    	at com.thoughtworks.go.config.materials.Materials.convertToMaterial(Materials.java:246)
    	at com.thoughtworks.go.config.materials.Materials.<init>(Materials.java:72)
    	at com.thoughtworks.go.server.service.MaterialConfigConverter.toMaterial(MaterialConfigConverter.java:63)
    	at com.thoughtworks.go.server.service.MaterialConfigConverter.toMaterials(MaterialConfigConverter.java:80)
    	at com.thoughtworks.go.server.materials.MaterialUpdateService.updateSchedulableMaterials(MaterialUpdateService.java:257)
    	at com.thoughtworks.go.server.materials.MaterialUpdateService.onConfigChange(MaterialUpdateService.java:217)
    	at com.thoughtworks.go.config.CachedGoConfig.registerListener(CachedGoConfig.java:200)
    	at com.thoughtworks.go.config.GoConfigDao.registerListener(GoConfigDao.java:136)
    	at com.thoughtworks.go.server.service.GoConfigService.register(GoConfigService.java:412)
    	at com.thoughtworks.go.server.materials.MaterialUpdateService.initialize(MaterialUpdateService.java:104)
    	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:125)
    	... 30 more

    ```

**Comment by ketan** [comment]
Here is another (slightly different) exception that was reported by a customer —

```
2016-08-15 09:32:47,193 ERROR [WrapperJarAppMain] GoServer:77 - ERROR: Failed to start Go server.
java.lang.RuntimeException: java.lang.RuntimeException: Could not decrypt the password to get the real password
at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:146)
at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:51)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.server.Server.start(Server.java:387)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.server.Server.doStart(Server.java:354)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:90)
at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.simontuffs.onejar.Boot.run(Boot.java:306)
at com.simontuffs.onejar.Boot.main(Boot.java:159)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:352)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not decrypt the password to get the real password
at com.thoughtworks.go.config.materials.tfs.TfsMaterialConfig.getPassword(TfsMaterialConfig.java:128)
at com.thoughtworks.go.config.materials.tfs.TfsMaterial.<init>(TfsMaterial.java:77)
at com.thoughtworks.go.config.materials.Materials.convertToMaterial(Materials.java:256)
at com.thoughtworks.go.config.materials.Materials.<init>(Materials.java:72)
at com.thoughtworks.go.server.service.MaterialConfigConverter.toMaterial(MaterialConfigConverter.java:63)
at com.thoughtworks.go.server.service.MaterialConfigConverter.toMaterials(MaterialConfigConverter.java:80)
at com.thoughtworks.go.server.materials.MaterialUpdateService.updateSchedulableMaterials(MaterialUpdateService.java:257)
at com.thoughtworks.go.server.materials.MaterialUpdateService.onConfigChange(MaterialUpdateService.java:217)
at com.thoughtworks.go.config.CachedGoConfig.registerListener(CachedGoConfig.java:200)
at com.thoughtworks.go.config.GoConfigDao.registerListener(GoConfigDao.java:136)
at com.thoughtworks.go.server.service.GoConfigService.register(GoConfigService.java:414)
at com.thoughtworks.go.server.materials.MaterialUpdateService.initialize(MaterialUpdateService.java:104)
at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:125)
... 43 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: pad block corrupted
at org.bouncycastle.crypto.paddings.PKCS7Padding.padCount(Unknown Source)
at org.bouncycastle.crypto.paddings.PaddedBufferedBlockCipher.doFinal(Unknown Source)
at com.thoughtworks.go.security.GoCipher.decipher(GoCipher.java:68)
at com.thoughtworks.go.security.GoCipher.decrypt(GoCipher.java:48)
at com.thoughtworks.go.config.materials.tfs.TfsMaterialConfig.getPassword(TfsMaterialConfig.java:126)
... 55 more
```

**Comment by rajiesh** [comment]
#2569

**Comment by rajiesh** [comment]
verified on 16.9.0 (3981-aa488f618ca6c06932d605bf99dded2ffd604e9e) and works as expected
