### ISSUE TITLE
golang agent breaks UI Agent tab

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#2668]
##### Summary

golang agent which registers with server will make it impossible to render the Agents UI tab.

##### Environment

Go server 16.8.0

##### Steps to Reproduce

1.  Start go server
2. Start golang agent - in other host
4. Build some pipeline
3. Go to Agent UI tab

UI Agents tab fails to render. Says `Something went wrong`.

Server log:
```
ActionView::Template::Error (undefined method `empty?' for nil:NilClass):
    237:             <% end -%>
    238: 
    239:             <% unless scope[:exclude_columns].include?('operating_system') -%>
    240:                 <%== cell_with_title( agent_in_agent_table.getOperatingSystem(), 'operating_system') %>
    241:             <% end -%>
    242: 
    243:             <% unless scope[:exclude_columns].include?('ip_address') -%>
  app/helpers/agents_helper.rb:68:in `lostcontact'
  app/helpers/agents_helper.rb:47:in `agent_status_cell'
  app/views/agents/index.html.erb:240:in `_app_views_agents_index_html_erb___2027224728_66874'
  app/views/agents/index.html.erb:206:in `_app_views_agents_index_html_erb___2027224728_66874'
  lib/jetty_weak_etag_middleware.rb:16:in `call'
  lib/catch_json_parse_errors.rb:8:in `call'
```

#### Possible fix

@ketan says changing `empty?` to `blank?` might fix it, but it probably not the right way to fix it.
Also
> Could you add a breakpoint in AgentInstance#getBuildLocator and AgentBuildingInfo#getBuildLocator() and see if they’re really null

Yes it is null. I managed to reproduce this in development server

#### Previous conversation

https://gitter.im/gocd/gocd?at=57d32f5c83c1556511b4b591

**Comment by tomzo** [comment]
Changing that like to `blank` is not good really. It fixes tab only when agent is not building. Then if agent is building another failure because buildLocator is null
```
app/helpers/agents_helper.rb:62:in `has_view_or_operate_permission_on_pipeline?'
app/helpers/agents_helper.rb:49:in `agent_status_cell'
app/views/agents/_agents_table.html.erb:121:in `_app_views_agents__agents_table_html_erb__1140227770_26438'
app/views/agents/_agents_table.html.erb:87:in `_app_views_agents__agents_table_html_erb__1140227770_26438'
app/views/agents/index.html.erb:85:in `_app_views_agents_index_html_erb___482818861_26370'
lib/jetty_weak_etag_middleware.rb:16:in `call'
lib/catch_json_parse_errors.rb:8:in `call'
```

**Comment by tomzo** [comment]
I think I found it. By pure guessing, these 2 structures seem to be data contracts -
In [Go lang agent](https://github.com/gocd-contrib/gocd-golang-agent/blob/0c2ee247d85a3abc7ac03e82840fe6a223725b7d/protocol/agent_runtime_info.go#L27)
```
type AgentBuildingInfo struct {
	BuildingInfo string `json:"buildingInfo"`
	BuildLocator string `json:"buildingLocator"`
}
```

In [server](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/server/service/AgentBuildingInfo.java)
```
public class AgentBuildingInfo implements Serializable {
    @Expose
    private final String buildingInfo;
    @Expose
    private final String buildLocator;
```

See the naming `buildingLocator` vs `buildLocator`.
I temporarily changed it in server and problem seems gone, but the final fix should be in agent really.

**Comment by tomzo** [comment]
This was solved by fixing golang agent
