### ISSUE TITLE
go-server does not want to install on Ubuntu 12.04

### ISSUE THREAD

**Issue by lilianmoraru** [gocd/gocd#2768]
##### Issue Type

- Bug Report

##### Summary

go-server does not want to install on Ubuntu 12.04:
Log attached lower.

###### Basic environment details

* Go Version: `16.10.0-4131`
* JAVA Version: `1.7.0_111`
* OS: `Ubuntu 12.04.5 LTS, Linux 3.13.0-95-generic, x86_64`

##### Steps to Reproduce

1. Run these instructions to setup: https://docs.go.cd/current/installation/install/server/linux.html#debian-based-distributions-ie-ubuntu

##### Expected Results
To install cleanly.

##### Actual Results
Fails to install.

##### Log snippets

```
sudo apt-get install go-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  go-server
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/140 MB of archives.
After this operation, 140 MB of additional disk space will be used.
Selecting previously unselected package go-server.
(Reading database ... 186390 files and directories currently installed.)
Unpacking go-server (from .../go-server_16.10.0-4131_all.deb) ...
invoke-rc.d: unknown initscript, /etc/init.d/go-server not found.
Processing triggers for ureadahead ...
Setting up go-server (16.10.0-4131) ...
 Adding system startup for /etc/init.d/go-server ...
   /etc/rc0.d/K99go-server -> ../init.d/go-server
   /etc/rc1.d/K99go-server -> ../init.d/go-server
   /etc/rc6.d/K99go-server -> ../init.d/go-server
   /etc/rc2.d/S99go-server -> ../init.d/go-server
   /etc/rc3.d/S99go-server -> ../init.d/go-server
   /etc/rc4.d/S99go-server -> ../init.d/go-server
   /etc/rc5.d/S99go-server -> ../init.d/go-server
[Fri Oct  7 16:20:05 EEST 2016] using default settings from /etc/default/go-server
Error starting Go Server.
dpkg: error processing go-server (--configure):
 subprocess installed post-installation 
```

**Comment by rajiesh** [comment]
@lilianmoraru, we could not reproduce this issue, we could successfully install GoCD version 16.10.0-4131 on Ubuntu-12.04. Could you check if there is any error logs available at `/var/log/go-server`. If any logs available please share

**Comment by lilianmoraru** [comment]
This is my mistake.

The log if filled with these:
```
[Fri Oct 14 11:26:23 EEST 2016] Starting Go Server with command: java -server -Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=256m -Duser.language=en -Djruby.rack.request.size.threshold.bytes=30000000 -Duser.country=US -Dcruise.config.dir=/etc/go -Dcruise.config.file=/etc/go/cruise-config.xml -Dcruise.server.port=8153 -Dcruise.server.ssl.port=8154 -jar /usr/share/go-server/go.jar
[Fri Oct 14 11:26:23 EEST 2016] Starting Go Server in directory: /var/lib/go-server
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/thoughtworks/go/server/util/GoLauncher : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:648)
	at com.simontuffs.onejar.JarClassLoader.defineClass(JarClassLoader.java:693)
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:599)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:325)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:270)
	at com.simontuffs.onejar.Boot.run(Boot.java:300)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
```

I did `javac -version` and got `1.7.0_111`, so I thought that it is ok.
Now I did `java -version` and I get:
```
java version "1.6.0_40"
OpenJDK Runtime Environment (IcedTea6 1.13.12) (6b40-1.13.12-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 23.40-b40, mixed mode)
```

The Java version is to old...
