### ISSUE TITLE
Unable to register Windows Agent to Linux server.

### ISSUE THREAD

**Issue by fire** [gocd/gocd#2769]
##### Issue Type

- Bug Report

##### Summary
Unable to register Windows Agent to Linux server.

###### Basic environment details

Go Agent: Same version
OS: Windows Server 2012

Go Server Version:	16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d)
JVM version:	1.8.0_102
OS Information:	Linux 3.10.0-327.36.1.el7.x86_64
Usable space in artifacts repository:	490 GB
Database schema version:	1610001

##### Steps to Reproduce

1. Download gocd https://download.go.cd/binaries/16.10.0-4131/win/go-agent-16.10.0-4131-setup.exe
2. Input gocd server addr
3. Agent fails to register

##### Expected Results
Agent is able to be seen and registered.
##### Actual Results

Agent is not seen.

##### Possible Fix
...

##### Log snippets

```
2016-10-07 23:18:46,836 [loopThread] ERROR thoughtworks.go.agent.AgentController:192 - [Agent Loop] Error occurred during loop: 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:822)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at com.thoughtworks.go.security.RegistrationJSONizer.fromJson(RegistrationJSONizer.java:49)
	at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.readResponse(SslInfrastructureService.java:190)
	at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.requestRegistration(SslInfrastructureService.java:182)
	at com.thoughtworks.go.agent.service.SslInfrastructureService.register(SslInfrastructureService.java:103)
	at com.thoughtworks.go.agent.service.SslInfrastructureService.registerIfNecessary(SslInfrastructureService.java:87)
	at com.thoughtworks.go.agent.AgentController.rpcLoop(AgentController.java:181)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:173)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	... 18 more
2016-10-07 23:18:56,825 [loopThread] INFO  go.agent.service.SslInfrastructureService:86 - [Agent Registration] Starting to register agent
2016-10-07 23:18:56,826 [loopThread] ERROR go.agent.service.SslInfrastructureService:105 - [Agent Registration] There was a problem registering with the go server.
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:822)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at com.thoughtworks.go.security.RegistrationJSONizer.fromJson(RegistrationJSONizer.java:49)
	at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.readResponse(SslInfrastructureService.java:190)
	at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.requestRegistration(SslInfrastructureService.java:182)
	at com.thoughtworks.go.agent.service.SslInfrastructureService.register(SslInfrastructureService.java:103)
	at com.thoughtworks.go.agent.service.SslInfrastructureService.registerIfNecessary(SslInfrastructureService.java:87)
	at com.thoughtworks.go.agent.AgentController.rpcLoop(AgentController.java:181)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:173)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	... 18 more
2016-10-07 23:18:56,826 [loopThread] ERROR thoughtworks.go.agent.AgentController:192 - [Agent Loop] Error occurred during loop: 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:822)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at com.thoughtworks.go.security.RegistrationJSONizer.fromJson(RegistrationJSONizer.java:49)
	at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.readResponse(SslInfrastructureService.java:190)
	at com.thoughtworks.go.agent.service.SslInfrastructureService$RemoteRegistrationRequester.requestRegistration(SslInfrastructureService.java:182)
	at com.thoughtworks.go.agent.service.SslInfrastructureService.register(SslInfrastructureService.java:103)
	at com.thoughtworks.go.agent.service.SslInfrastructureService.registerIfNecessary(SslInfrastructureService.java:87)
	at com.thoughtworks.go.agent.AgentController.rpcLoop(AgentController.java:181)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:173)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	... 18 more
```
-->

**Comment by padmam** [comment]
We were unable to reproduce the issue you have been facing. The agent in windows server 2012 was connected and registered to go-server in Linux OS. 

Can you specific the Java version you have been using in Windows server 2012 where the agent is installed?

**Comment by fire** [comment]
In the go agent directory D:\g\jre the release file says:
```
JAVA_VERSION="1.7.0"
OS_NAME="Windows"
OS_VERSION="5.1"
OS_ARCH="i586"
SOURCE=" .:127bfeeddc9c corba:59faa5249393 deploy:19f9d3c1ce63 hotspot:78dcbf58e349 hotspot/make/closed:2506a0848a86 hotspot/src/closed:69033fdf2743 hotspot/test/closed:74a7b688d797 install:d20733adfc0a jaxp:6abf26813c3b jaxws:4ed47474a15a jdk:ea77b684d424 jdk/make/closed:af7aa2f49416 jdk/src/closed:fc5a7a474f5d jdk/test/closed:e51e5f32324e langtools:e5e807700ff8 pubs:6e03d0e27bd9 sponsors:e9d372c43b8f"
BUILD_TYPE=commercial
```

**Comment by fire** [comment]
Is there a way to get the broken json document from my go server?

**Comment by fire** [comment]
I tried restoring the gocd system via backup and restore and this error appears on a new system. The default works.

**Comment by fire** [comment]
By wiping the database and only copying the cipher and the xml configuration I was able to reset the system so that agents can be added...

**Comment by ketan** [comment]
We think this issue is likely because of an error on the gocd server. Do you happen to have the logs from the server when this issue happened, could you paste any snippets of the log (`/var/log/go-server/go-server.log.*`) containing the string `AgentRegistrationController`.

**Comment by fire** [comment]
This is the only error I can find and it's not related. It's an error with logging in and checking with the /etc/go/passwd. 

`2016-10-16 00:43:34,652 ERROR [qtp1334729950-23] BasicAuthenticationFilter:56 - java.lang.NumberFormatException: For input string: "3000000000"`

**Comment by fire** [comment]
Since I don't actually use the failing system anymore and the workaround of starting a new server and copying the xml configuration works. I'm not sure how I can debug this more.

Maybe in the new releases if it happens again I can try it.
