### ISSUE TITLE
An agent running backup on the server behaves weirdly

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#2838]
##### Issue Type

- Bug Report

##### Summary

When an agent of a GoCD server calls the backup API using curl to run a backup on the server, log messages from that curl process are mostly lost. During the backup, there are also some exceptions shown on the agent side.

###### Basic environment details

* Go Version: 16.12.0
* JAVA Version: 1.8.0_65
* OS: Linux

##### Steps to Reproduce

1. Setup a task which calls back to the server and does a [backup](https://api.go.cd/current/#create-a-backup) using curl.
2. Check agent logs.

##### Expected Results

The whole curl output should be in the console log, once the task finishes successfully.

##### Actual Results

Some of it is missing. Especially the part where it says: "Starting to execute ..." (the early parts).

##### Possible Fix

Something around [here](https://github.com/gocd/gocd/blob/fb1a6a7071d891cd5a5ce2744aa5bccf5cd8abc3/common/src/com/thoughtworks/go/remote/work/ConsoleOutputTransmitter.java#L87)?

##### Log snippets

Found this exception in the logs, but that's the ping thread, not the console log updating thread.

```
2016-11-02 23:34:03,784 [pingThread] ERROR thoughtworks.go.agent.AgentController:161 - Error occurred when agent tried to ping server:
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://build.go.cd:8154/go/remoting/remoteBuildRepository]; nested exception
 is java.io.StreamCorruptedException: invalid stream header: 3F3C2144
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:212)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:145)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
        at com.sun.proxy.$Proxy6.ping(Unknown Source)
        at com.thoughtworks.go.agent.AgentController.ping(AgentController.java:157)
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.StreamCorruptedException: invalid stream header: 3F3C2144
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:807)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:302)
        at org.springframework.core.ConfigurableObjectInputStream.<init>(ConfigurableObjectInputStream.java:64)
        at org.springframework.core.ConfigurableObjectInputStream.<init>(ConfigurableObjectInputStream.java:50)
        at org.springframework.remoting.rmi.CodebaseAwareObjectInputStream.<init>(CodebaseAwareObjectInputStream.java:81)
        at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.createObjectInputStream(AbstractHttpInvokerRequestExecutor.java:271)
        at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.readRemoteInvocationResult(AbstractHttpInvokerRequestExecutor.java:239)
        at com.thoughtworks.go.agent.GoHttpClientHttpInvokerRequestExecutor.doExecuteRequest(GoHttpClientHttpInvokerRequestExecutor.java:66)
        at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:136)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:192)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:174)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:142)
        ... 12 more
```

**Comment by nathanbabin** [comment]
I've also seen this behavior on an agent (exact same error message)  when go-server is performing a backup.  It resulted in the go-agent process crashing.
go-server-17.2.0-4587
java-1.8.0-openjdk-1.8.0.121
Linux
