### ISSUE TITLE
BuildCauseProducerServer: NullPointerException

### ISSUE THREAD

**Issue by dpsenner** [gocd/gocd#2903]
##### Issue Type

- Bug Report

##### Summary

Go server reports a null pointer exception while scheduling a pipeline.

```plain
2016-11-28 13:56:03,538  INFO [consumeBuildCausesThread] PipelineRepository:92 - Pipeline timeline updated
2016-11-28 13:56:03,553 ERROR [79@MessageListener for ScheduleCheckListener] BuildCauseProducerService:237 - Error while scheduling pipeline: XXXXX
java.lang.NullPointerException
	at com.thoughtworks.go.server.service.dd.FanInGraph.createFinalRevisionsForScmChildren(FanInGraph.java:246)
	at com.thoughtworks.go.server.service.dd.FanInGraph.computeRevisions(FanInGraph.java:185)
	at com.thoughtworks.go.server.service.PipelineService.getRevisionsBasedOnDependencies(PipelineService.java:235)
	at com.thoughtworks.go.server.service.AutoBuild.fanInOn(AutoBuild.java:129)
	at com.thoughtworks.go.server.service.AutoBuild.onModifications(AutoBuild.java:74)
	at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:198)
	at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:152)
	at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:114)
	at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:45)
	at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:24)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:69)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Unknown Source)
```
###### Basic environment details

* Go Version: 16.11.0 (4185-e7acc53aac8bb5ad2a7f306ca8f3e752855d844b).
* JAVA Version: 1.7.0_79
* OS: Windows 8.1 6.3

**Comment by zabil** [comment]
Were any of the upstream or downstream pipeline(s) for this pipeline deleted/renamed?

**Comment by NachbarsLumpi** [comment]
Correct. Not a direct upstream pipeline, but one that a downstream pipeline depends on. Please note, too that this operation was done about a week ago and the pipeline in question has run already more than 50 times in the meanwhile.

**Comment by bgehman** [comment]
Bumping this old ticket.  We are seeing this problem intermittently, but frequently.
GoCD Version: *Go Version: 18.3.0 (6540-1e79bb6dc4f01f6ccd71c2b5aa0fbefa0b3eb92d).*

```
2018-05-01 14:17:53,527 ERROR [78@MessageListener for ScheduleCheckListener] BuildCauseProducerService:220 - Error while scheduling pipeline: Consume-QA-QA4
java.lang.NullPointerException: null
        at com.thoughtworks.go.server.service.dd.FanInGraph.createFinalRevisionsForScmChildren(FanInGraph.java:246)
        at com.thoughtworks.go.server.service.dd.FanInGraph.computeRevisions(FanInGraph.java:185)
        at com.thoughtworks.go.server.service.PipelineService.getRevisionsBasedOnDependencies(PipelineService.java:232)
        at com.thoughtworks.go.server.service.AutoBuild.fanInOn(AutoBuild.java:105)
        at com.thoughtworks.go.server.service.AutoBuild.onModifications(AutoBuild.java:67)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:191)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:148)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:110)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:44)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:25)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
2018-05-01 14:17:53,529 INFO  [qtp1301664418-19] 
```

```
2018-05-01 14:18:31,868 ERROR [81@MessageListener for ScheduleCheckListener] BuildCauseProducerService:220 - Error while scheduling pipeline: Consume-QA-USERMGMT
java.lang.NullPointerException: null
        at com.thoughtworks.go.server.service.dd.FanInGraph.createFinalRevisionsForScmChildren(FanInGraph.java:246)
        at com.thoughtworks.go.server.service.dd.FanInGraph.computeRevisions(FanInGraph.java:185)
        at com.thoughtworks.go.server.service.PipelineService.getRevisionsBasedOnDependencies(PipelineService.java:232)
        at com.thoughtworks.go.server.service.AutoBuild.fanInOn(AutoBuild.java:105)
        at com.thoughtworks.go.server.service.AutoBuild.onModifications(AutoBuild.java:67)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:191)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:148)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:110)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:44)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:25)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
```

```
2018-05-01 14:19:19,775 ERROR [86@MessageListener for ScheduleCheckListener] BuildCauseProducerService:220 - Error while scheduling pipeline: CAM-Development-Data-Ingestion2
java.lang.NullPointerException: null
        at com.thoughtworks.go.server.service.dd.FanInGraph.createFinalRevisionsForScmChildren(FanInGraph.java:246)
        at com.thoughtworks.go.server.service.dd.FanInGraph.computeRevisions(FanInGraph.java:185)
        at com.thoughtworks.go.server.service.PipelineService.getRevisionsBasedOnDependencies(PipelineService.java:232)
        at com.thoughtworks.go.server.service.AutoBuild.fanInOn(AutoBuild.java:105)
        at com.thoughtworks.go.server.service.AutoBuild.onModifications(AutoBuild.java:67)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:191)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:148)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:110)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:44)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:25)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
```
