### ISSUE TITLE
Large folder in artifact upload causes failure

### ISSUE THREAD

**Issue by fire** [gocd/gocd#2998]
##### Issue Type

- Bug Report
##### Summary

Using a large folder in artifact upload causes this message and failure. The data is 16GB uncompressed.

##### Environment

```
Go Server Version:	16.12.0 (4352-018c65856d46007240cc75577e9cc8535b44148d)
JVM version:	1.8.0_111
OS Information:	Linux 3.10.0-327.36.3.el7.x86_64
Usable space in artifacts repository:	528 GB
Database schema version:	1610001
```

* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

* Chrome

##### Steps to Reproduce

1. Have an artifact upload a folder collection that is 16 GB.
2. Transfer it to a different stage.
3. Have the archive fail on fetch on the second stage

##### Expected Results

1. Archive should fetch and continue
##### Actual Results

Errors.

##### Possible Fix

???

##### Log snippets

```
02:39:20.908 [go] Could not fetch artifact https://test.example.com:8154/go/remoting/files/example/xxx/defaultStage/latest/defaultJob/xxx.zip. Pausing 33 seconds to retry. Error was : Caught an exception 'SSL peer shut down incorrectly'
```

**Comment by fire** [comment]
Client is the newest .12 client on windows with 64bit Java.

**Comment by ketan** [comment]
Are there any exceptions that are logged in either the server or the client logs at around the time this happens?

**Comment by fire** [comment]
In the console there's the above 'SSL peer shut down incorrectly'. Which logs are you looking for?

**Comment by fire** [comment]
There seems to be a 8 GB file in the folder.

**Comment by ketan** [comment]
The agent logs are in `/var/log/go-agent/go-agent.log` and the server logs in `/var/log/go-server/go-server.log`

Depending on the amount of logs that get generated, these logs may be rotated with suffix `.0`, `.1` etc, so you may need to look for the logs with the right timestamps in the correct file.

**Comment by fire** [comment]
```java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30007/30000 ms
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:234)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:141)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:355)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
        at com.thoughtworks.go.server.web.FileView.setOutput(FileView.java:68)
        at com.thoughtworks.go.server.web.FileView.handleFile(FileView.java:60)
        at com.thoughtworks.go.server.web.FileView.handleFileWithLogging(FileView.java:111)
        at com.thoughtworks.go.server.web.FileView.render(FileView.java:104)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1180)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:950)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:72)
        at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.web.FlashLoadingFilter.doFilter(FlashLoadingFilter.java:43)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
        at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.ui.x509.X509ProcessingFilter.doFilter(X509ProcessingFilter.java:137)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.ArtifactSizeEnforcementFilter.doFilter(ArtifactSizeEnforcementFilter.java:76)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.ModeAwareFilter.doFilter(ModeAwareFilter.java:48)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.PerformanceLoggingFilter.doFilter(PerformanceLoggingFilter.java:50)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:174)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
``` 

Do I need more of the stack?

**Comment by fire** [comment]
```2016-12-13 02:33:12,578  WARN [qtp2040495657-23] HttpChannel:396 - /go/remoting/files/xxx/nnn/defau$
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30007/30000 ms
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:234)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:141)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:355)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
        at com.thoughtworks.go.server.web.FileView.setOutput(FileView.java:68)
        at com.thoughtworks.go.server.web.FileView.handleFile(FileView.java:60)
        at com.thoughtworks.go.server.web.FileView.handleFileWithLogging(FileView.java:111)
        at com.thoughtworks.go.server.web.FileView.render(FileView.java:104)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1180)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:950)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
...
```

**Comment by fire** [comment]
This seems related. http://stackoverflow.com/q/25548341

**Comment by fire** [comment]
How would I set this to 5 minutes or 30 minutes?

**Comment by jyotisingh** [comment]
Jetty idle timeout can be set using JVM arg `-Didle.timeout=30000`, the value is specified in millisecs, default being 30seconds. Update this in `/etc/default/go-server` and restart server.

**Comment by fire** [comment]
For future reference that's `GO_SERVER_SYSTEM_PROPERTIES="-Didle.timeout=1800000"` in `/etc/default/go-server`

**Comment by fire** [comment]
Workinging. Thank you.

**Comment by fire** [comment]
This should be a ui option though..

**Comment by jyotisingh** [comment]
This value for this timeout is passed along to jetty which needs to be restarted for the updated timeout to be picked. Even if there was an option to update this from the UI, a restart of Go server process would be required for the changes to take effect, making the UI option seem pointless.
