### ISSUE TITLE
SSL endpoint fails to load (port 8154), after upgrading to 17.1.0.

### ISSUE THREAD

**Issue by rvypandey** [gocd/gocd#3123]
##### Issue Type Bug
- Bug Report

##### Summary

Cannot navigate to https://IP:8154/go after starting go-server service (GoCD v17.1.0)

##### Environment

```
"Environment Variables": {
"AWS_AUTO_SCALING_HOME": "/opt/aws/apitools/as",
"AWS_CLOUDWATCH_HOME": "/opt/aws/apitools/mon",
"AWS_ELB_HOME": "/opt/aws/apitools/elb",
"AWS_PATH": "/opt/aws",
"CVS_RSH": "ssh",
"EC2_AMITOOL_HOME": "/opt/aws/amitools/ec2",
"EC2_HOME": "/opt/aws/apitools/ec2",
"HISTCONTROL": "ignoredups",
"HISTSIZE": "1000",
"HOME": "/var/go",
"HOSTNAME": "ip-address-of-instance",
"JAVA_HOME": "/usr/lib/jvm/jre",
"LANG": "en_US.UTF-8",
"LESSOPEN": "||/usr/bin/lesspipe.sh %s",
"LESS_TERMCAP_mb": "\u001b[01;31m",
"LESS_TERMCAP_md": "\u001b[01;38;5;208m",
"LESS_TERMCAP_me": "\u001b[0m",
"LESS_TERMCAP_se": "\u001b[0m",
"LESS_TERMCAP_ue": "\u001b[0m",
"LESS_TERMCAP_us": "\u001b[04;38;5;111m",
"LOGNAME": "go",
"MAIL": "/var/spool/mail/go",
"NLSPATH": "/usr/dt/lib/nls/msg/%L/%N.cat",
"OLDPWD": "/var/go",
"PATH": "/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/var/go/.local/bin:/var/go/bin",
"PWD": "/var/lib/go-server",
"SHELL": "/bin/bash",
"SHLVL": "1",
"TERM": "xterm-256color",
"USER": "go",
"XFILESEARCHPATH": "/usr/dt/app-defaults/%L/Dt"
}
```

###### Basic environment details

* Go Version: `17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69).`
* JAVA Version: `1.8.0_111`
* OS: `Linux 4.4.35-33.55.amzn1.x86_64`
* Browser vendor and version (if relevant): `Google Chrome - Version 55.0.2883.95 (64-bit)`

##### Steps to Reproduce

1. In the given OS (AWS EC2 instance), setup Go server as per documentation.
2. Make some required changes as per the new GoCD (17.1.0) version. For example 'major.minor' issue. To fix the major.minor issue update JDK to 1.8.
3. Start server manually with the command /etc/init.d/go-server start. (If any problems are encountered, fix them)
4. Navigate to https://IP.Address.Of.Instance:8154/go.

##### Expected Results

When navigated to https://IP.Address.Of.Instance:8154/go, Go Pipeline UI should load. 

##### Actual Results
This does not work. However, http://IP.Address.Of.Instance:8153/go works fine. But agents are designed to work on 8154 (SSL), so all the agents (if already assigned), lose connection to the server.

##### Possible Fix
No idea.

##### Log snippets
This does not appear in logs.

##### Code snippets/Screenshots
NA

##### Any other info
NA

**Comment by ketan** [comment]
What information do you see in the logs at `/var/log/go-server`. If the file `/etc/default/go-server` contains `JAVA_HOME`, is it pointing to the right java (Java 8).

Also does `java -version` on your command prompt say it's Java 8?

**Comment by rvypandey** [comment]
There is no JAVA_HOME set in the file `/etc/default/go-server`, but the command `java -version` says:
```openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)```

In logs at /var/log/go-server, there were lots of things, but I'm certain that you need the latest log(s). So I restarted the go-server, and the logs created after this restart are:
```
[Wed Jan 25 18:32:13 UTC 2017] Starting Go Server with command: /usr/lib/jvm/jre/bin/java -server -Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1024m -XX:PermSize=128m -XX:MaxMetaspaceSize=256m -Duser.language=en -Djruby.rack.request.size.threshold.bytes=30000000 -Duser.country=US -Dcruise.config.dir=/etc/go -Dcruise.config.file=/etc/go/cruise-config.xml -Dcruise.server.port=8153 -Dcruise.server.ssl.port=8154 -jar /usr/share/go-server/go.jar
[Wed Jan 25 18:32:13 UTC 2017] Starting Go Server in directory: /var/lib/go-server
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /var/log/go-server/go-server.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:395)
	at org.apache.log4j.PropertyWatchdog.doOnChange(PropertyConfigurator.java:955)
	at org.apache.log4j.helpers.FileWatchdog.checkAndConfigure(FileWatchdog.java:89)
	at org.apache.log4j.helpers.FileWatchdog.<init>(FileWatchdog.java:58)
	at org.apache.log4j.PropertyWatchdog.<init>(PropertyConfigurator.java:947)
	at org.apache.log4j.PropertyConfigurator.configureAndWatch(PropertyConfigurator.java:473)
	at org.apache.log4j.PropertyConfigurator.configureAndWatch(PropertyConfigurator.java:455)
	at com.thoughtworks.go.util.validators.LoggingValidator$Log4jConfigReloader.reload(LoggingValidator.java:53)
	at com.thoughtworks.go.util.validators.LoggingValidator.validate(LoggingValidator.java:47)
	at com.thoughtworks.go.server.GoServer.validate(GoServer.java:128)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:60)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /var/log/go-server/go-server.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:262)
	at org.apache.commons.logging.impl.Log4JLogger.<init>(Log4JLogger.java:108)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:1025)
	at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:844)
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:541)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:269)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Reading change scripts from directory /var/lib/go-server/db/h2deltas...
dbdeploy v2.11
Creating index SYS:SYS_ID 0%
Creating index SYS:SYS_ID 0%
Changes currently applied to database:
  1..90, 221001, 230001..230009, 240001, 240002, 300001..300011, 1202001..1202003, 1203002..1203005, 1301001, 1302001, 1303001..1303004, 1304001, 1401001, 1403001, 1403002, 1501001..1501003, 1502001, 1503001, 1503002, 1606001, 1606002, 1607001, 1610001, 1701001
Scripts available:
  1..90, 221001, 230001..230009, 240001, 240002, 300001..300011, 1202001..1202003, 1203002..1203005, 1301001, 1302001, 1303001..1303004, 1304001, 1401001, 1403001, 1403002, 1501001..1501003, 1502001, 1503001, 1503002, 1606001, 1606002, 1607001, 1610001, 1701001
To be applied:
  (none)
Creating index SYS:SYS_ID 0%
Creating index SYS:SYS_ID 0%
Warning: org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
DEPRECATION WARNING: Filter object with #filter method is deprecated. Define method corresponding to filter type (#before, #after or #around). (called from transaction_actions at /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/engines/oauth2_provider/lib/oauth2_provider/transaction_helper.rb:18)
DEPRECATION WARNING: Filter object with #filter method is deprecated. Define method corresponding to filter type (#before, #after or #around). (called from transaction_actions at /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/engines/oauth2_provider/lib/oauth2_provider/transaction_helper.rb:18)
DEPRECATION WARNING: Filter object with #filter method is deprecated. Define method corresponding to filter type (#before, #after or #around). (called from transaction_actions at /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/engines/oauth2_provider/lib/oauth2_provider/transaction_helper.rb:18)
DEPRECATION WARNING: Filter object with #filter method is deprecated. Define method corresponding to filter type (#before, #after or #around). (called from transaction_actions at /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/vendor/engines/oauth2_provider/lib/oauth2_provider/transaction_helper.rb:18)
```

**Comment by rvypandey** [comment]
@ketan I've moved back to using 16.12.0, and that is working for me. That is, with all the same configurations as I used in 17.1.0.

**Comment by arvindsv** [comment]
Closing. Please reopen if this is still happening with a newer release.
