### ISSUE TITLE
Can't get agent to register with 17.2 Go server

### ISSUE THREAD

**Issue by joel74** [gocd/gocd#3209]
##### Issue Type
- Bug Report

##### Summary
I built a new instance of 17.2 on a Windows server and am trying to get a new agent to register with it. I'm using a self-signed SSL cert (following the instructions [here](https://docs.gocd.io/current/installation/ssl_tls/custom_server_certificate.html) ). I can tell the Go server is using the SSL cert in the keystore correctly because the site's address registers as secure.

However, when the agent service starts, SSL verification fails. In the launcher log is written:
("WARN  go.agent.common.AgentBootstrapperBackwardCompatibility:53 - SslVerificationMode could not parsed. Disabling SSL verification.")

I tried debugging on the Go server to see if I could catch any SSL-related issues, but I haven't seen any in the logs.

##### Environment

```
  "Go Server Information": {
    "Version": "17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45)"
  },
```

###### Basic environment details

* Go Version: 17.2.0
* JAVA Version: 8.121
* OS: Windows Server 2012r2
* Browser vendor and version (if relevant): (n/a)

##### Steps to Reproduce

1. Start the Go agent service 
2. Examine the logs

##### Expected Results
1. The Go agent successfully negotiates an SSL connection and registers with the Go server

##### Actual Results
1. The Go agent fails to attempt to connect to the Go server via SSL and does not register with the Go server.

##### Log snippets
```
2017-02-27 15:40:51,705 [loopThread] ERROR thoughtworks.go.agent.AgentController:84 - [Agent Loop] Error occurred during loop: 
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.thoughtworks.go.agent.common.ssl.GoAgentServerHttpClient.execute(GoAgentServerHttpClient.java:49)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:71)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:65)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:76)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(Unknown Source)
	... 28 more
```

**Comment by varshavaradarajan** [comment]
@joel74 , what is the java version on the go agent? If you are using GoCD 17.2.0, the Go Server and the Go Agent's java home should point to Java 8.

**Comment by joel74** [comment]
@varshavaradarajan, sorry I just saw this comment. I've been using the JRE version 8.0.121. I found out that I have to uninstall the old agent and then after a fresh install of the 17.2 agent, it could successfully talk to the 17.2 server. Performing an upgrade from the 16.3 agent was what wasn't working.

**Comment by varshavaradarajan** [comment]
Related to https://github.com/gocd/gocd/issues/2525
