### ISSUE TITLE
Deleting pipeline config via API don't notify scheduleService to cancel job

### ISSUE THREAD

**Issue by kulikov** [gocd/gocd#3390]
##### Issue Type

- Bug Report

##### Summary

When I remove pipeline config via API I've got some repeated errors in gocd server logs:

```
2017-04-12 15:49:25,519 ERROR [86@MessageListener for ScheduleCheckListener] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.scheduling.ScheduleCheckListener@75b61bef
java.lang.RuntimeException: com.thoughtworks.go.config.PipelineNotFoundException: Pipeline 'front-office-table-rendering-fix' not found.
	at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:51)
	at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:24)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
```

This logs repeated each 10 seconds.

API request that I use for deleting:
```
DELETE https://localhost:8154/go/api/admin/pipelines/front-office-table-rendering-fix
200 OK
```

##### Environment
```plain
{
  "Timestamp": "2017-04-12T16:37:26Z",
  "Go Server Information": {
    "Version": "17.3.0 (4704-3c7d8f7e5d78e46f72ff1194bb322c6b5d72a90f)"
  },
  "Config Statistics": {
    "Valid Config": {
      "Number of pipelines": 8,
      "Number of agents": 2,
      "Number of environments": 1,
      "Number of unique materials": 7,
      "Number of schedulable materials": 7
    },
    "Security": {
      "LDAP": false,
      "Password": true
    }
  },
  "Config file locations": {
    "loc.config.dir": "/etc/go",
    "loc.log.root.0": "/var/lib/go-server/.",
    "loc.log.basename.0": "plugin-slack.notifier.log"
  },
  "OS Information": {
    "OS Name": "Linux",
    "OS Version": "4.4.0-64-generic",
    "System Architecture": "amd64",
    "Available Processors": 2,
    "Average System Load": 1.14
  },
  "Runtime Information": {
    "Name": "12@...",
    "Uptime": 23683622,
    "Uptime (in Time Format)": "[About 6 hours, 34 minutes, 43 seconds]",
    "Spec Name": "Java Virtual Machine Specification",
    "Spec Vendor": "Oracle Corporation",
    "Spec Version": "1.8",
    "Input Arguments": [
      "-Djava.security.egd\u003dfile:/dev/./urandom",
      "-Xms512m",
      "-Xmx1024m",
      "-XX:MaxMetaspaceSize\u003d256m",
      "-Dcom.sun.net.ssl.enableECC\u003dfalse",
      "-Duser.language\u003den",
      "-Djruby.rack.request.size.threshold.bytes\u003d30000000",
      "-Duser.country\u003dUS",
      "-Dcruise.config.dir\u003d/etc/go",
      "-Dcruise.config.file\u003d/etc/go/cruise-config.xml",
      "-Dcruise.server.port\u003d8153",
      "-Dcruise.server.ssl.port\u003d8154"
    ],
    "System Properties": {
      "awt.toolkit": "sun.awt.X11.XToolkit",
      "com.sun.net.ssl.enableECC": "false",
      "cruise.config.dir": "/etc/go",
      "cruise.config.file": "/etc/go/cruise-config.xml",
      "cruise.server.port": "8153",
      "cruise.server.ssl.port": "8154",
      "file.encoding": "ANSI_X3.4-1968",
      "file.encoding.pkg": "sun.io",
      "file.separator": "/",
      "java.awt.graphicsenv": "sun.awt.X11GraphicsEnvironment",
      "java.awt.printerjob": "sun.print.PSPrinterJob",
      "java.class.path": "/usr/local/go-server/go.jar",
      "java.class.version": "52.0",
      "java.endorsed.dirs": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/endorsed",
      "java.ext.dirs": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/ext:/usr/java/packages/lib/ext",
      "java.home": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre",
      "java.io.tmpdir": "/tmp",
      "java.library.path": "/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib",
      "java.net.preferIPv4Stack": "true",
      "java.protocol.handler.pkgs": "com.simontuffs",
      "java.runtime.name": "OpenJDK Runtime Environment",
      "java.runtime.version": "1.8.0_121-b13",
      "java.security.egd": "file:/dev/./urandom",
      "java.specification.name": "Java Platform API Specification",
      "java.specification.vendor": "Oracle Corporation",
      "java.specification.version": "1.8",
      "java.vendor": "Oracle Corporation",
      "java.vendor.url": "http://java.oracle.com/",
      "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
      "java.version": "1.8.0_121",
      "java.vm.info": "mixed mode",
      "java.vm.name": "OpenJDK 64-Bit Server VM",
      "java.vm.specification.name": "Java Virtual Machine Specification",
      "java.vm.specification.vendor": "Oracle Corporation",
      "java.vm.specification.version": "1.8",
      "java.vm.vendor": "Oracle Corporation",
      "java.vm.version": "25.121-b13",
      "jdk.tls.ephemeralDHKeySize": "matched",
      "jetty.base": "/var/lib/go-server",
      "jetty.home": "/var/lib/go-server",
      "jetty.xml.file.name": "jetty.xml",
      "jruby.compile.invokedynamic": "false",
      "jruby.ji.objectProxyCache": "false",
      "jruby.management.enabled": "true",
      "jruby.rack.request.size.threshold.bytes": "30000000",
      "line.separator": "\n",
      "net.sf.ehcache.skipUpdateCheck": "true",
      "os.arch": "amd64",
      "os.name": "Linux",
      "os.version": "4.4.0-64-generic",
      "path.separator": ":",
      "rails.use.compressed.js": "true",
      "sun.arch.data.model": "64",
      "sun.boot.class.path": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/jfr.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/classes",
      "sun.boot.library.path": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre/lib/amd64",
      "sun.cpu.endian": "little",
      "sun.cpu.isalist": "",
      "sun.io.unicode.encoding": "UnicodeLittle",
      "sun.java.command": "/usr/local/go-server/go.jar",
      "sun.java.launcher": "SUN_STANDARD",
      "sun.jnu.encoding": "ANSI_X3.4-1968",
      "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
      "sun.os.patch.level": "unknown",
      "user.country": "US",
      "user.dir": "/var/lib/go-server",
      "user.home": "/root",
      "user.language": "en",
      "user.name": "root",
      "user.timezone": "UTC",
      "webapp.root": "/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp"
    },
    "Environment Variables": {
      "HOME": "/root",
      "HOSTNAME": "...",
      "NLSPATH": "/usr/dt/lib/nls/msg/%L/%N.cat",
      "OLDPWD": "/",
      "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "PWD": "/var/lib/go-server",
      "SHLVL": "1",
      "XFILESEARCHPATH": "/usr/dt/app-defaults/%L/Dt"
    }
  },
  "Server Health Information": {
    "Messages Count": 0,
    "Messages": []
  },
  "Cache Information": {
    "Cache configuration information": {
      "name": "cruise",
      "Maximum Elements in Memory": 100000,
      "Maximum Elements on Disk": 0,
      "Memory Store Eviction Policy": {
        "myName": "LRU"
      },
      "Clean or Flush": true,
      "Eternal": true,
      "Time To Idle Seconds": 120,
      "time To Live Seconds": 120,
      "Overflow To Disk": false,
      "Disk Persistent": false,
      "Disk Store Path": null,
      "Disk Spool Buffer Size in MB": 30,
      "Disk Access Stripes": 1,
      "Disk Expiry Thread Interval Seconds": 120,
      "Logging Enabled": false,
      "Cache Event Listener Configurations": [],
      "Cache Extension Configurations": [],
      "Bootstrap Cache Loader Factory Configuration": null,
      "Cache Exception Handler Factory Configuration": null,
      "Terracotta Configuration": null,
      "Cache Writer Configuration": {
        "writeMode": "WRITE_THROUGH",
        "notifyListenersOnException": false,
        "minWriteDelay": 1,
        "maxWriteDelay": 1,
        "rateLimitPerSecond": 0,
        "writeCoalescing": false,
        "writeBatching": false,
        "writeBatchSize": 1,
        "retryAttempts": 0,
        "retryAttemptDelaySeconds": 1,
        "cacheWriterFactoryConfiguration": null
      },
      "Cache Loader Configurations": [],
      "Frozen": false,
      "Transactional Mode": "OFF",
      "Statistics": true
    },
    "Cache runtime information": {
      "Statistics enabled": true,
      "Get Time in milliseconds": {
        "Average": 0.00134261,
        "Minimum": 0,
        "Maximum": 0
      },
      "Cache Size": 799,
      "Accuracy": "Best Effort",
      "Cache Counts": {
        "Hits": 282286,
        "Miss": 4517,
        "Expired": 0,
        "Eviction": 0,
        "Put": 1278,
        "Remove": 2874
      },
      "Cache Size (Disk)": 0,
      "Cache Count (Disk)": 0
    }
  },
  "Config Git Repository": {
    "Number of commits": 119,
    "GC Statistics": {
      "sizeOfPackedObjects": 0,
      "sizeOfLooseObjects": 162265,
      "numberOfPackedObjects": 0,
      "numberOfPackFiles": 0,
      "numberOfPackedRefs": 0,
      "numberOfLooseRefs": 2,
      "numberOfLooseObjects": 253
    }
  },
  "GC Information": {
    "PS Scavenge": {
      "Memory Pool Names": "[PS Eden Space, PS Survivor Space]",
      "Collection Count": 99,
      "Collection Time": 1975
    },
    "PS MarkSweep": {
      "Memory Pool Names": "[PS Eden Space, PS Survivor Space, PS Old Gen]",
      "Collection Count": 4,
      "Collection Time": 1058
    }
  },
  "Memory Information": {
    "Heap": {
      "init": 536870912,
      "used": 358558704,
      "committed": 755499008,
      "max": 954728448
    },
    "Non Heap": {
      "init": 2555904,
      "used": 256418640,
      "committed": 275447808,
      "max": 1593835520
    },
    "Pending Finalization": 0
  },
  "Memory Pool Information": {...},
  "Hibernate Statistics": {},
  "Thread Information": {
    "Thread Count": {
      "Current": 130,
      "Total": 28213,
      "Daemon": 74,
      "Peak": 148
    },
    "DeadLock Threads": {},
    "Stack Trace": {...}
  }
}
```

##### Steps to Reproduce

1. Delete pipeline via API: DELETE /go/api/admin/pipelines/{name}

##### Actual Results
Pipeline successfully deleted from UI, but in server logs comes error.
Restart gocd-server fix it. Save config xml in UI fix it too.

**Comment by rajiesh** [comment]
Verified on 18.8.0 (7425-18b6420935c6d0946d958d9e2e492d9595e57459)
