### ISSUE TITLE
Unable to configure custom SSL certificate in Go Server

### ISSUE THREAD

**Issue by ByteFlinger** [gocd/gocd#3432]
##### Issue Type
- Bug Report
##### Summary

I am trying to apply a custom SSL certificate to a newly installed Go Server following the instructions found here https://docs.gocd.io/current/installation/ssl_tls/custom_server_certificate.html but it does not seem to work
##### Environment
A freshly provisioned AWS EC2 instance running RHEL 7.3
###### Basic environment details

* Go Version: `17.3.0`
* JAVA Version: `1.8.0_131-b11`
* OS: `RHEL 7.3`
###### Additional Environment Details
Using the YUM repository at https://download.gocd.io  
##### Steps to Reproduce

1. Install GOCD from YUM repository following the same steps found here https://github.com/gocd/gocd-cloud/blob/master/go-server-packer.json 
2. Create keystore with custom SSL certificate and replace existing according to steps described here https://docs.gocd.io/current/installation/ssl_tls/custom_server_certificate.html
3. Attempt to start go-server service

##### Expected Results
The go-server should start

##### Actual Results
Go does not start and the logs show seem to indicate the issue is Go not being able to properly understand the keystore. See error snippet below

##### Log snippets
<details> 
  <summary>Click to see ERROR LOGS</summary>
   <pre>
2017-04-26 11:39:33,478  WARN [main] AbstractLifeCycle:212 - FAILED SslContextFactory@73a0353f(/etc/go/keystore,/etc/go/truststore): java.security.UnrecoverableKeyException: Cannot recover key
java.security.UnrecoverableKeyException: Cannot recover key
	at sun.security.provider.KeyProtector.recover(KeyProtector.java:328)
	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:146)
	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:70)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:911)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:300)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2017-04-26 11:39:33,479  WARN [main] AbstractLifeCycle:212 - FAILED SslConnectionFactory@445b84c0{SSL-HTTP/1.1}: java.security.UnrecoverableKeyException: Cannot recover key
java.security.UnrecoverableKeyException: Cannot recover key
	at sun.security.provider.KeyProtector.recover(KeyProtector.java:328)
	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:146)
	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:70)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:911)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:300)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2017-04-26 11:39:33,480  WARN [main] AbstractLifeCycle:212 - FAILED ServerConnector@7c53a9eb{SSL-HTTP/1.1}{0.0.0.0:8154}: java.security.UnrecoverableKeyException: Cannot recover key
java.security.UnrecoverableKeyException: Cannot recover key
	at sun.security.provider.KeyProtector.recover(KeyProtector.java:328)
	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:146)
	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:70)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:911)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:300)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.A1: JavaScriptserver.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2017-04-26 11:39:33,480  WARN [main] AbstractLifeCycle:212 - FAILED org.eclipse.jetty.server.Server@156643d4: java.security.UnrecoverableKeyException: Cannot recover key
java.security.UnrecoverableKeyException: Cannot recover key
	at sun.security.provider.KeyProtector.recover(KeyProtector.java:328)
	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:146)
	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:70)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
	at org.eclipse.jetty.A1: JavaScriptutil.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:911)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:300)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2017-04-26 11:39:33,582  WARN [Thread-35] ServerStatusService:81 - An API support page provider failed.
java.lang.NullPointerException
	at com.thoughtworks.go.server.service.support.ThreadInformationProvider.getThreadInformation(ThreadInformationProvider.java:104)
	at com.thoughtworks.go.server.service.support.ThreadInformationProvider.asJson(ThreadInformationProvider.java:187)
	at com.thoughtworks.go.server.service.support.ServerStatusService.serverInfoAsJson(ServerStatusService.java:78)
	at com.thoughtworks.go.server.service.support.ServerStatusService.access$000(ServerStatusService.java:34)
	at com.thoughtworks.go.server.service.support.ServerStatusService$2.run(ServerStatusService.java:57)
	at java.lang.Thread.run(Thread.java:748) 
</pre>
</details>

##### Other information

I can confirm the issue is the keystore as go starts without any problem if I restore the original keystore created by go on the first start.

SELinux was disabled to rule out any issues with it

**Comment by joel74** [comment]
If you execute the following against your new keystore with the self-signed cert in it, do you see an entry with the alias name 'cruise'?

` keytool -v -list -keystore keystore`

**Comment by ByteFlinger** [comment]
Hi @joel74 

Yes. This is what I get
`# keytool -v -list -keystore /etc/go/keystore`
```

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: cruise
Creation date: Apr 26, 2017
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]: 
```

I should mention that the certificate in it is not self-signed

**Comment by joel74** [comment]
Hi, @ByteFlinger, 
Ok. My next suggestion is to check the password used. In some forums, I found it mentioned that "UnrecoverableKeyException happens because the keymanager isn't using the correct password." When adding the cert to the keystore and updating the alias, I made sure that I was always using the passphrase specified on the [article ](https://docs.gocd.io/current/installation/ssl_tls/custom_server_certificate.html) and that worked for me.

**Comment by ByteFlinger** [comment]
I have been copying and pasting the password exactly from that article every time I needed it, including when I ran the commands above you asked to verify the store.

Just to make sure I am not making some mistake, I'll repeat the procedure here

`serverKeystorepa55w0rd`

And to make it absolutely sure, I did the same against the keystore that is generated by Go the first time I run it and it works as well to list the internal data

**Comment by joel74** [comment]
Does the key have a password associated with it? I did a bit more searching, and all answers I found were related to the key and the keystore having different password values (i.e. [here](https://confluence.atlassian.com/bitbucketserverkb/bitbucket-server-fails-to-start-with-ssl-java-security-unrecoverablekeyexception-cannot-recover-key-814205872.html))

**Comment by ByteFlinger** [comment]
No, nothing I configured.

I have a key and a certificate which I generate the keystore from. This are the list of commands to perform this

```
openssl pkcs12 -inkey /etc/go/mycert.key -in /etc/go/mycert.pem -export -out /etc/go/mycert.pkcs12 -password 'pass:'
keytool -importkeystore -srckeystore /etc/go/mycert.pkcs12 -srcstoretype PKCS12 -destkeystore /etc/go/keystore -srcalias 1 -srcstorepass '' -destalias cruise -deststorepass 'serverKeystorepa55w0rd'
```

Notice that the only different is I specify the passwords in the commands for the sake of automation but I do not specify any key password.
I attempted to create the keystore from the pkcs12 file by hand just now to make sure that it wasnt the issue and it still doesnt work :(

**Comment by ByteFlinger** [comment]
I got it.

I happen to re-read your last post and I thought I had seen different options for specfying keystore pass and key pass in keytool. I have never run into an issue like this but I assumed the key has no password while the store does making them different.

Once I gave the key a password (serverKeystorepa55w0rd) it worked.

Talk about being specific. In 5 years of working with pki in different products I have never run into this issue

Thank you for the help

**Comment by ByteFlinger** [comment]
It might be worth nothing that running the keytool command specified in the documentation and answering the password question *will not* work because keytool will not ask the key pass and it will default to empty (Or at least it seemed to when I tried)

**Comment by joel74** [comment]
Good stuff. I'm glad you were able to get it figured out. Hopefully anyone else who runs into this issue while setting up go to use their own cert will stumble across this post.

**Comment by ketan** [comment]
> It might be worth nothing that running the keytool command specified in the documentation and answering the password question will not work because keytool will not ask the key pass and it will default to empty (Or at least it seemed to when I tried)

Would you like to submit a clarification to [this document](https://github.com/gocd/docs.go.cd/blob/master/installation/ssl_tls/custom_server_certificate.md)?

**Comment by ByteFlinger** [comment]
I added quick PR however there may be further improvements that can be done on that. Point number 1 (Change the original key password) should not really be needed.

**Comment by ketan** [comment]
> Point number 1 (Change the original key password) should not really be needed.

I can see how this was confusing for you. Would it make sense to rephrase it as?

> 1. Ensure that the certificate has a password set to `serverKeystorepa55w0rd` and import it into the `keystore` file which has the password `serverKeystorepa55w0rd`

**Comment by ByteFlinger** [comment]
The PR I pushed does mention pretty much the that in Point 3 and also the
keytool command will fix the password regardless of what the key or the
generates pkcs12 passwords are so I think it is redundant.

I think the extra step to backup the key and set a new password on it is
unnecessary as you can set the proper password on the keytool command
avoiding one step too many but I guess it is a matter of taste really how
each person likes to handle their keys and keystores so I'll leave any
extra revisions to you guys. :)

The issue I had was that I was not aware that keytool will per default use
the password of the pkcs12 file as the password for the key (or maybe
setting the keystore password through the flag does not default the key
password to the same value, I'd need to perform some more tests)

**Comment by arvindsv** [comment]
Closing. Documentation was changed in [this PR](https://github.com/gocd/docs.go.cd/pull/81).
