### ISSUE TITLE
Git Tree parsing fails with exception

### ISSUE THREAD

**Issue by mlaug** [gocd/gocd#3526]
Steps to reproduce:
* Setup a clean installation with Go Agent and Server on MacOs Version 17.4.0
* Setup first pipeline and connect with repository e.g git@github.com:thebulbs/brain-mapper.git
* trigger first build

It will always cause an error as seen in the log excerpt below

```
2017-05-17 17:52:21,262 ERROR [63@MessageListener for MaterialUpdateStatusNotifier] BuildCauseProducerService:349 - not scheduling pipeline mapper after manual-trigger because update of material failed with reason Unable to parse git-diff-tree output line: b8cc4db102ea819efff849eb6a12231c760ba672
From output:
b8cc4db102ea819efff849eb6a12231c760ba672
M	codeship-steps.yml
2017-05-17 17:53:43,691  WARN [96@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:115 - [Material Update] Modification check failed for material: URL: git@github.com:thebulbs/brain-mapper.git, Branch: master
java.lang.RuntimeException: Unable to parse git-diff-tree output line: b8cc4db102ea819efff849eb6a12231c760ba672
From output:
b8cc4db102ea819efff849eb6a12231c760ba672
M	codeship-steps.yml
	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:28)
	at com.thoughtworks.go.domain.materials.git.GitCommand.addModifiedFiles(GitCommand.java:140)
	at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:123)
	at com.thoughtworks.go.domain.materials.git.GitCommand.latestModification(GitCommand.java:97)
	at com.thoughtworks.go.config.materials.git.GitMaterial.latestModification(GitMaterial.java:116)
	at com.thoughtworks.go.server.service.materials.GitPoller.latestModification(GitPoller.java:32)
	at com.thoughtworks.go.server.service.materials.GitPoller.latestModification(GitPoller.java:28)
	at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:105)
	at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:54)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:73)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:166)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:124)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:46)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:89)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:86)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:50)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:30)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mlaug** [comment]
found the issue, the configuration for the log was set to 

```
[log]
  abbrevCommit = false
```
