### ISSUE TITLE
Cannot restore backup - server fails with SQL errors

### ISSUE THREAD

**Issue by schlomo** [gocd/gocd#3534]
##### Issue Type

- Bug Report

##### Summary

Restoring the backup of a Go server leads to the server not starting and crashing with SQL exceptions.

##### Environment

Running Go server and agents in Docker. Take a regular backup via API and move files away. Restoring the files to a fresh data directory (we use `data`) looks like this:

```
/data/
├── [4.0K]  config
│   ├── [3.1K]  agentkeystore
│   ├── [  16]  cipher
│   ├── [2.2K]  cruise-config.xml
│   ├── [ 48K]  cruise-config.xsd
│   ├── [ 799]  go_update_server.pub
│   ├── [3.7K]  jetty.xml
│   ├── [2.1K]  keystore
│   ├── [1.1K]  log4j.properties
│   └── [3.1K]  truststore
└── [4.0K]  db
    ├── [4.0K]  config-git
    │   └── [2.2K]  cruise-config.xml
    └── [4.0K]  h2db
        └── [2.7M]  cruise.h2.db

```

When starting Go it crashes with a large amount of SQL related exceptions (see below). The column `locked` that it complains about actually also doesn't seem to exist in the still running Go server where I took the backups from.

###### Basic environment details

* Go Version: 17.3.0
* JAVA Version: 1.8.0_121
* OS: Linux 4.9.24-coreos

##### Expected Results

Go would start and work as the server where I took the backup.

##### Actual Results

It crashes horribly.

##### Possible Fix

No idea.

###### Log Snippets

End of logs:
```
2017-05-19 11:53:13 ERROR GoServer:75 - ERROR: Failed to start Go server.
java.lang.RuntimeException: org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/thoughtworks/go/server/dao/maps/Pipeline.xml.  
--- The error occurred while executing query.  
--- Check the          SELECT name FROM pipelines WHERE locked = true     .  
--- Check the SQL Statement (preparation failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: Column "LOCKED" not found; SQL statement:
         SELECT name FROM pipelines WHERE locked = true      [42122-168]
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:149)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/thoughtworks/go/server/dao/maps/Pipeline.xml.  
--- The error occurred while executing query.  
--- Check the          SELECT name FROM pipelines WHERE locked = true     .  
--- Check the SQL Statement (preparation failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: Column "LOCKED" not found; SQL statement:
         SELECT name FROM pipelines WHERE locked = true      [42122-168]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.execute(SqlMapClientDaoSupport.java:112)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForList(SqlMapClientTemplate.java:293)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.access$601(SqlMapClientDaoSupport.java:39)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate$5.execute(SqlMapClientDaoSupport.java:105)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate$5.execute(SqlMapClientDaoSupport.java:103)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.executeInternal(SqlMapClientDaoSupport.java:120)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.queryForList(SqlMapClientDaoSupport.java:103)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForList(SqlMapClientTemplate.java:287)
	at com.thoughtworks.go.server.dao.PipelineSqlMapDao.lockedPipelines(PipelineSqlMapDao.java:876)
	at com.thoughtworks.go.server.service.PipelineLockService.onConfigChange(PipelineLockService.java:91)
	at com.thoughtworks.go.config.CachedGoConfig.registerListener(CachedGoConfig.java:221)
	at com.thoughtworks.go.config.GoConfigDao.registerListener(GoConfigDao.java:146)
	at com.thoughtworks.go.server.service.GoConfigService.register(GoConfigService.java:414)
	at com.thoughtworks.go.server.service.PipelineLockService.initialize(PipelineLockService.java:46)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:123)
	... 37 more
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/thoughtworks/go/server/dao/maps/Pipeline.xml.  
--- The error occurred while executing query.  
--- Check the          SELECT name FROM pipelines WHERE locked = true     .  
--- Check the SQL Statement (preparation failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: Column "LOCKED" not found; SQL statement:
         SELECT name FROM pipelines WHERE locked = true      [42122-168]
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForList(MappedStatement.java:139)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:567)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$3.doInSqlMapClient(SqlMapClientTemplate.java:295)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$3.doInSqlMapClient(SqlMapClientTemplate.java:1)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:200)
	... 52 more
Caused by: org.h2.jdbc.JdbcSQLException: Column "LOCKED" not found; SQL statement:
         SELECT name FROM pipelines WHERE locked = true      [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:239)
	at com.sun.proxy.$Proxy17.prepareStatement(Unknown Source)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.prepareStatement(SqlExecutor.java:497)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:175)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 59 more
ERROR: Failed to start Go server. Please check the logs.
java.lang.RuntimeException: Failed to start Go server.
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:76)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.lang.RuntimeException: org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/thoughtworks/go/server/dao/maps/Pipeline.xml.  
--- The error occurred while executing query.  
--- Check the          SELECT name FROM pipelines WHERE locked = true     .  
--- Check the SQL Statement (preparation failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: Column "LOCKED" not found; SQL statement:
         SELECT name FROM pipelines WHERE locked = true      [42122-168]
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:149)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	... 8 more
Caused by: org.springframework.jdbc.BadSqlGrammarException: SqlMapClient operation; bad SQL grammar []; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/thoughtworks/go/server/dao/maps/Pipeline.xml.  
--- The error occurred while executing query.  
--- Check the          SELECT name FROM pipelines WHERE locked = true     .  
--- Check the SQL Statement (preparation failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: Column "LOCKED" not found; SQL statement:
         SELECT name FROM pipelines WHERE locked = true      [42122-168]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.execute(SqlMapClientDaoSupport.java:112)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForList(SqlMapClientTemplate.java:293)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.access$601(SqlMapClientDaoSupport.java:39)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate$5.execute(SqlMapClientDaoSupport.java:105)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate$5.execute(SqlMapClientDaoSupport.java:103)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.executeInternal(SqlMapClientDaoSupport.java:120)
	at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.queryForList(SqlMapClientDaoSupport.java:103)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForList(SqlMapClientTemplate.java:287)
	at com.thoughtworks.go.server.dao.PipelineSqlMapDao.lockedPipelines(PipelineSqlMapDao.java:876)
	at com.thoughtworks.go.server.service.PipelineLockService.onConfigChange(PipelineLockService.java:91)
	at com.thoughtworks.go.config.CachedGoConfig.registerListener(CachedGoConfig.java:221)
	at com.thoughtworks.go.config.GoConfigDao.registerListener(GoConfigDao.java:146)
	at com.thoughtworks.go.server.service.GoConfigService.register(GoConfigService.java:414)
	at com.thoughtworks.go.server.service.PipelineLockService.initialize(PipelineLockService.java:46)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:123)
	... 37 more
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in com/thoughtworks/go/server/dao/maps/Pipeline.xml.  
--- The error occurred while executing query.  
--- Check the          SELECT name FROM pipelines WHERE locked = true     .  
--- Check the SQL Statement (preparation failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: Column "LOCKED" not found; SQL statement:
         SELECT name FROM pipelines WHERE locked = true      [42122-168]
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForList(MappedStatement.java:139)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:567)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$3.doInSqlMapClient(SqlMapClientTemplate.java:295)
	at org.springframework.orm.ibatis.SqlMapClientTemplate$3.doInSqlMapClient(SqlMapClientTemplate.java:1)
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:200)
	... 52 more
Caused by: org.h2.jdbc.JdbcSQLException: Column "LOCKED" not found; SQL statement:
         SELECT name FROM pipelines WHERE locked = true      [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:239)
	at com.sun.proxy.$Proxy17.prepareStatement(Unknown Source)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.prepareStatement(SqlExecutor.java:497)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:175)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
	... 59 more
```

**Comment by ketan** [comment]
Seems like you may restoring the DB on an older version of GoCD.

**Comment by ketan** [comment]
Some more details:

You're restoring the database on version `17.3.0` of GoCD. However it appears that the DB dump was taken on version `17.4.0` of GoCD. The specific column `locked` was dropped in 17.4.0.

You'll need to restore on version 17.4.0 of GoCD.

I'm going to mark this ticket as closed, but if you're unable to restore the DB — let us know and we can re-open the ticket.
