### ISSUE TITLE
PasswordFile doesn't support non-english characters for username

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3550]
##### Issue Type

- Bug Report

##### Summary

User is not recognized (GoCD throws authentication error), if a user is added to PasswordFile with non-english character in its username. 

##### Log snippets

```
2017-05-25 21:47:04,123  INFO [qtp1174361318-25] PasswordFilePlugin:52 - [Authenticate] Authenticating User: пароль using auth_config: af24a380-0264-4bb7-8ee4-81e2b27ef768
2017-05-25 21:47:04,124 ERROR [qtp1174361318-25] PasswordFilePlugin:77 - [Authenticate] Failed to authenticate user: `пароль`
cd.go.authentication.passwordfile.exception.AuthenticationException: Unable to authenticate user, user not found or bad credentials
    at cd.go.authentication.passwordfile.Authenticator.authenticate(Authenticator.java:66)
    at cd.go.authentication.passwordfile.executor.UserAuthenticationExecutor.execute(UserAuthenticationExecutor.java:56)
    at cd.go.authentication.passwordfile.PasswordFilePlugin.handle(PasswordFilePlugin.java:68)
```

###### Basic environment details

* Go Version: All versions

##### Steps to Reproduce

1. Add a user - for example 'пароль'   (htpasswd -c -s passwordfilename пароль).
2. try to login with this user. 

##### Expected Results
User should be added to GoCD and should be able to authenticate just like it is supported through ldap authentication.

##### Possible Fix

Replace [this](https://github.com/gocd/filebased-authentication-plugin/blob/917f095dce3695fac8deb567a67f3fc96c67c4b7/src/main/java/cd/go/authentication/passwordfile/PasswordFileReader.java#L33) part of code with below

```
properties.load(new InputStreamReader(inputStream, "UTF-8”))
```

**Comment by arvindsv** [comment]
Closing. @ankitsri11 - can you log this in: https://github.com/gocd/filebased-authentication-plugin/?

**Comment by ketan** [comment]
opened https://github.com/gocd/filebased-authentication-plugin/issues/20
