### ISSUE TITLE
Catastrophic regex backtracking

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3551]
##### Issue Type

- Bug Report

##### Summary

There's a [catastrophic regex](http://www.regular-expressions.info/catastrophic.html) backtracking issue with a config save.

The regex in question is [here](https://github.com/gocd/gocd/blob/483fdb7a5b6a616e12fc15f46ec38ae4ac099451/config/config-server/resources/cruise-config.xsd#L842-L846).

To reproduce this issue, attempt to perform an update on an `exec` task with the command `c:\coldfusion2016\cfusion\runtime\bin\wsconfig.exe ` note whitespace at the end of the command.

##### Stack trace

```
"qtp934275857-28@2525" prio=5 tid=0x1c nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks cachedGoConfigRefreshExecutorThread@16122
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matches(Unknown Source:-1)
	  at org.apache.xerces.impl.xpath.regex.RegularExpression.matches(Unknown Source:-1)
	  at org.apache.xerces.impl.dv.xs.XSSimpleTypeDecl.getActualValue(Unknown Source:-1)
	  at org.apache.xerces.impl.dv.xs.XSSimpleTypeDecl.validate(Unknown Source:-1)
	  at org.apache.xerces.impl.xs.XMLSchemaValidator.processOneAttribute(Unknown Source:-1)
	  at org.apache.xerces.impl.xs.XMLSchemaValidator.processAttributes(Unknown Source:-1)
	  at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source:-1)
	  at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source:-1)
	  at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source:-1)
	  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source:-1)
	  at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source:-1)
	  at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source:-1)
	  at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source:-1)
	  at org.apache.xerces.parsers.XMLParser.parse(Unknown Source:-1)
	  at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source:-1)
	  at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source:-1)
	  at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	  at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:253)
	  at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1091)
	  at com.thoughtworks.go.util.XmlUtils.buildXmlDocument(XmlUtils.java:57)
	  at com.thoughtworks.go.util.XmlUtils.buildXmlDocument(XmlUtils.java:46)
	  at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.verifyXsdValid(MagicalGoConfigXmlWriter.java:104)
	  at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:81)
	  at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:583)
	  at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:510)
	  at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:494)
	  at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:337)
	  - locked <0x4ebe> (a com.thoughtworks.go.config.GoFileConfigDataSource)
	  at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:151)
	  - locked <0x4ebf> (a com.thoughtworks.go.config.CachedGoConfig)
	  at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:113)
	  - locked <0x1a3b> (a java.lang.Class)
	  at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:243)
	  at com.thoughtworks.go.server.service.GoConfigService.updateConfigFromUI(GoConfigService.java:291)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:421)
	  at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:288)
```

**Comment by rajiesh** [comment]
Verified on 17.5.0 (5095-3130b5ba96f8155ae86fefb261a559d4c7493326)
