### ISSUE TITLE
Go server unable to bind to ports lower 1024

### ISSUE THREAD

**Issue by alethenorio** [gocd/gocd#3580]
##### Issue Type

- Bug Report

##### Summary

Because the way the init scripts for GoCD are written it is not possible to run Gocd directly on ports lower than 1024.

I attempted to bind GoCD to listen on 443 for HTTPS but was not able to and got permission denied.
If you configure GoCD server to run a lower port by changing the port on `/etc/default/go-server` it will not start because you need to allow java the privilege to do so by running something like `setcap cap_net_bind_service=+eip /path/to/java` however this does not seem to work either.

I believe this happpens because the way the init script is calling java, there seems to be some mechanism disallowing processes called in a specific way specifically because it has raised privileges.

This is explained in this stackoverflow answer https://unix.stackexchange.com/a/16670/211368 and I couldn't find any more information that would prove the contrary

###### Basic environment details

* Go Version: `17.3.0`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.10.0-514.21.1.el7.x86_64`

###### Additional Environment Details

* Linux Distribution: `Redhat Linux 7.3`
* Installed via: `Yum repository from https://download.gocd.io`

##### Steps to Reproduce
1. Disable firewalld to make sure it is playing no part in this whole thing
2. Change HTTPS port in `/etc/default/go-server` to something like 443
3. Start Go server and get permission denied in logs `systemctl restart go-server`
4. Get the path to java binary by running ``readlink -f `which java` `` 
5. Allow the binary to bind to lower port by running `sudo setcap cap_net_bind_service=+eip /path/to/java`
6. Restart Go server and get permission denied again `systemctl restart go-server`

##### Expected Results
Go server is able to find to 43

##### Actual Results
Not able to make Go run on 443

##### Possible Fix
A workaround is to use Iptables or firewalld to perform a port forward but I have not been able to find a fix

##### Log snippets
```
2017-06-08 18:31:28,693  INFO [main] GoConfigMigration:216 - Upgrading config file from version 90 to version 90
2017-06-08 18:31:28,762  INFO [main] GoConfigMigration:224 - Finished upgrading config file
2017-06-08 18:31:28,762  INFO [main] GoConfigMigrator:105 - [Config Save] Starting Config Save post upgrade using FullConfigSaveNormalFlow
2017-06-08 18:31:29,051  INFO [main] CachedGoConfig:226 - About to notify config listeners
2017-06-08 18:31:29,052  INFO [main] CachedGoConfig:234 - Finished notifying all listeners
2017-06-08 18:31:29,083  INFO [main] BuildAssignmentService:255 - [Configuration Changed] Removing jobs for pipelines that no longer exist in configuration.
2017-06-08 18:31:29,165  INFO [main] PipelineRepository:85 - Start updating pipeline timeline
2017-06-08 18:31:29,194  INFO [main] PipelineRepository:91 - Pipeline timeline updated
2017-06-08 18:31:29,196  INFO [main] PipelineSqlMapDao:94 - Loading active pipelines into memory.
2017-06-08 18:31:29,196  INFO [main] PipelineSqlMapDao:390 - Retriving Active Pipelines from Database...
2017-06-08 18:31:29,204  INFO [main] PipelineSqlMapDao:96 - Done loading active pipelines into memory.
2017-06-08 18:31:29,258  INFO [main] ConsoleActivityMonitor:67 - Found '0' building jobs. Added them with '2017-06-08T18:31:29.206Z' as the last heard time
2017-06-08 18:31:29,290  INFO [main] RailsAssetsService:66 - Found rails assets manifest file named .sprockets-manifest-081845f20df012fc553ed99c82040e0c.json 
2017-06-08 18:31:29,301  INFO [main] RailsAssetsService:70 - Successfully read rails assets manifest file located at /var/opt/go/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/public/assets/.sprockets-manifest-081845f20df012fc553ed99c82040e0c.json
2017-06-08 18:31:40,712 FATAL [main] Rails:? - reached here
2017-06-08 18:31:45,000  WARN [main] AbstractLifeCycle:212 - FAILED ServerConnector@16f65612{SSL-HTTP/1.1}{0.0.0.0:443}: java.net.SocketException: Permission denied
java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2017-06-08 18:31:45,002  WARN [main] AbstractLifeCycle:212 - FAILED org.eclipse.jetty.server.Server@cac736f: java.net.SocketException: Permission denied
java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:93)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:63)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
```

**Comment by serragnoli** [comment]
Hi @ByteFlinger 
Have you managed to make Go server bind to the <1024 ports?
Thanks.

**Comment by ByteFlinger** [comment]
I have not. I tried everything I could think of as explained above however in the end my workaround was to bind Go to a port above 1024 and use firewalls to redirect 443 to that port

**Comment by akshaydewan** [comment]
I was able to get the Go server to listen on ports 80 and 443 using `setcap` (and additionally `ldconfig`) using the info provided [here](https://confluence.atlassian.com/confkb/permission-denied-error-when-binding-a-port-290750651.html). There are a few other workarounds listed on that link, like `authbind`.

My knowledge is limited, but for a cleaner solution out-of-the-box, maybe we can leverage systemd (#3937).

**Comment by VincenzoDo** [comment]
You can easily use systemd to do so:  https://github.com/gocd/gocd/issues/3937#issuecomment-350253073
