### ISSUE TITLE
Do something about exceptions on server boot

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3754]
##### Issue Type

- Bug Report

##### Summary

This is not a bug per se, but on server startup, we see a bunch of exceptions, all of which can be ignored or logged at a different severity. This always seems gives an impression that something went wrong on startup, and since there are several stacktraces to go through, it makes it particularly bad.

```
2017-08-10 16:33:41,588  INFO [main] ConfigRepository:220 - Upgrading config file from version 81 to version 94
2017-08-10 16:33:41,716  WARN [Thread-75] PluginInfoBuilder:55 - Plugin settings configuration and view could not be retrieved. May be because the plugin doesn't have any plugin settings
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.authentication.ldap' implementing 'authorization' extension failed while requesting for 'go.plugin-settings.get-view'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-view is not supported by plugin.']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:41)
	at com.thoughtworks.go.plugin.access.common.AbstractExtension.getPluginSettingsView(AbstractExtension.java:60)
	at com.thoughtworks.go.plugin.access.common.PluginInfoBuilder.getPluginSettingsAndView(PluginInfoBuilder.java:48)
	at com.thoughtworks.go.plugin.access.authorization.AuthorizationPluginInfoBuilder.pluginInfoFor(AuthorizationPluginInfoBuilder.java:44)
	at com.thoughtworks.go.plugin.access.authorization.AuthorizationPluginInfoBuilder.pluginInfoFor(AuthorizationPluginInfoBuilder.java:29)
	at com.thoughtworks.go.plugin.access.common.MetadataLoader.pluginLoaded(MetadataLoader.java:41)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$FilterChangeListener.pluginLoaded(DefaultPluginManager.java:254)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework$2.execute(FelixGoPluginOSGiFramework.java:354)
	at org.apache.commons.collections.CollectionUtils.forAllDo(CollectionUtils.java:389)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.getBundle(FelixGoPluginOSGiFramework.java:112)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.loadPlugin(FelixGoPluginOSGiFramework.java:98)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:145)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:102)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:68)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners$1.execute(DefaultPluginJarLocationMonitor.java:272)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:303)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:270)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:201)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:192)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:184)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:173)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-view is not supported by plugin.'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
	... 20 more
2017-08-10 16:33:41,729 ERROR [Thread-75] PluginSettingsMetadataLoader:75 - Failed to fetch Plugin Settings metadata for plugin : cd.go.authentication.ldap
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.authentication.ldap' implementing 'authorization' extension failed while requesting for 'go.plugin-settings.get-configuration'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-configuration is not supported by plugin.']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:41)
	at com.thoughtworks.go.plugin.access.common.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:51)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:65)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:45)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$FilterChangeListener.pluginLoaded(DefaultPluginManager.java:254)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework$2.execute(FelixGoPluginOSGiFramework.java:354)
	at org.apache.commons.collections.CollectionUtils.forAllDo(CollectionUtils.java:389)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.getBundle(FelixGoPluginOSGiFramework.java:112)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.loadPlugin(FelixGoPluginOSGiFramework.java:98)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:145)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:102)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:68)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners$1.execute(DefaultPluginJarLocationMonitor.java:272)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:303)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:270)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:201)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:192)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:184)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:173)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-configuration is not supported by plugin.'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
	... 18 more
2017-08-10 16:33:41,976  INFO [main] ConfigRepository:229 - Finished upgrading config file
2017-08-10 16:33:41,977  INFO [main] GoConfigMigrator:105 - [Config Save] Starting Config Save post upgrade using FullConfigSaveNormalFlow
2017-08-10 16:33:42,333 ERROR [main] ConfigRepository:191 - [CONFIG REPOSITORY] Could not fetch latest commit id
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:153)
	at com.thoughtworks.go.service.ConfigRepository.revisions(ConfigRepository.java:137)
	at com.thoughtworks.go.service.ConfigRepository.getCurrentRevCommit(ConfigRepository.java:189)
	at com.thoughtworks.go.service.ConfigRepository$3.call(ConfigRepository.java:176)
	at com.thoughtworks.go.service.ConfigRepository$3.call(ConfigRepository.java:172)
	at com.thoughtworks.go.service.ConfigRepository.doLocked(ConfigRepository.java:127)
	at com.thoughtworks.go.service.ConfigRepository.getCurrentRevision(ConfigRepository.java:172)
	at com.thoughtworks.go.service.ConfigRepository.checkin(ConfigRepository.java:107)
	at com.thoughtworks.go.config.FullConfigSaveFlow.checkinToConfigRepo(FullConfigSaveFlow.java:92)
	at com.thoughtworks.go.config.FullConfigSaveNormalFlow.execute(FullConfigSaveNormalFlow.java:66)
	at com.thoughtworks.go.config.GoConfigMigrator.upgradeConfigFile(GoConfigMigrator.java:109)
	at com.thoughtworks.go.config.GoConfigMigrator.upgrade(GoConfigMigrator.java:95)
	at com.thoughtworks.go.config.GoConfigMigrator.migrate(GoConfigMigrator.java:74)
	at com.thoughtworks.go.config.CachedGoConfig.upgradeConfig(CachedGoConfig.java:143)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:106)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
	at com.thoughtworks.go.server.Jetty9Server.startHandlers(Jetty9Server.java:146)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:104)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2017-08-10 16:33:42,334  INFO [main] ConfigRepository:178 - [CONFIG REPOSITORY] Unable retrieve current cruise config revision
org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:153)
	at com.thoughtworks.go.service.ConfigRepository.revisions(ConfigRepository.java:137)
	at com.thoughtworks.go.service.ConfigRepository.getCurrentRevCommit(ConfigRepository.java:189)
	at com.thoughtworks.go.service.ConfigRepository$3.call(ConfigRepository.java:176)
	at com.thoughtworks.go.service.ConfigRepository$3.call(ConfigRepository.java:172)
	at com.thoughtworks.go.service.ConfigRepository.doLocked(ConfigRepository.java:127)
	at com.thoughtworks.go.service.ConfigRepository.getCurrentRevision(ConfigRepository.java:172)
	at com.thoughtworks.go.service.ConfigRepository.checkin(ConfigRepository.java:107)
	at com.thoughtworks.go.config.FullConfigSaveFlow.checkinToConfigRepo(FullConfigSaveFlow.java:92)
	at com.thoughtworks.go.config.FullConfigSaveNormalFlow.execute(FullConfigSaveNormalFlow.java:66)
	at com.thoughtworks.go.config.GoConfigMigrator.upgradeConfigFile(GoConfigMigrator.java:109)
	at com.thoughtworks.go.config.GoConfigMigrator.upgrade(GoConfigMigrator.java:95)
	at com.thoughtworks.go.config.GoConfigMigrator.migrate(GoConfigMigrator.java:74)
	at com.thoughtworks.go.config.CachedGoConfig.upgradeConfig(CachedGoConfig.java:143)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:106)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
	at com.thoughtworks.go.server.Jetty9Server.startHandlers(Jetty9Server.java:146)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:104)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2017-08-10 16:33:42,415  INFO [main] CachedGoConfig:226 - About to notify config listeners
2017-08-10 16:33:42,415  INFO [main] CachedGoConfig:234 - Finished notifying all listeners
2017-08-10 16:33:42,474  INFO [main] BuildAssignmentService:249 - [Configuration Changed] Removing jobs for pipelines that no longer exist in configuration.
2017-08-10 16:33:42,502  INFO [main] PipelineRepository:86 - Start updating pipeline timeline
2017-08-10 16:33:42,520  INFO [main] PipelineRepository:92 - Pipeline timeline updated
2017-08-10 16:33:42,520  INFO [main] PipelineSqlMapDao:99 - Loading active pipelines into memory.
2017-08-10 16:33:42,520  INFO [main] PipelineSqlMapDao:395 - Retriving Active Pipelines from Database...
2017-08-10 16:33:42,530  INFO [main] PipelineSqlMapDao:101 - Done loading active pipelines into memory.
2017-08-10 16:33:42,617  INFO [main] ConsoleActivityMonitor:68 - Found '0' building jobs. Added them with '2017-08-10T16:33:42.566+05:30' as the last heard time
2017-08-10 16:33:42,662  INFO [main] RailsAssetsService:68 - Found rails assets manifest file named .sprockets-manifest-edc50ba8728b5f4041210551301bb9e2.json
2017-08-10 16:33:42,670  INFO [main] RailsAssetsService:72 - Successfully read rails assets manifest file located at /Users/ketanpadegaonkar/projects/gocd/gocd/installers/target/distributions/zip/go-server-17.9.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/public/assets/.sprockets-manifest-edc50ba8728b5f4041210551301bb9e2.json
2017-08-10 16:33:42,819  WARN [Thread-75] PluginInfoBuilder:55 - Plugin settings configuration and view could not be retrieved. May be because the plugin doesn't have any plugin settings
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.authentication.passwordfile' implementing 'authorization' extension failed while requesting for 'go.plugin-settings.get-view'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-view is not supported by plugin.']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:41)
	at com.thoughtworks.go.plugin.access.common.AbstractExtension.getPluginSettingsView(AbstractExtension.java:60)
	at com.thoughtworks.go.plugin.access.common.PluginInfoBuilder.getPluginSettingsAndView(PluginInfoBuilder.java:48)
	at com.thoughtworks.go.plugin.access.authorization.AuthorizationPluginInfoBuilder.pluginInfoFor(AuthorizationPluginInfoBuilder.java:44)
	at com.thoughtworks.go.plugin.access.authorization.AuthorizationPluginInfoBuilder.pluginInfoFor(AuthorizationPluginInfoBuilder.java:29)
	at com.thoughtworks.go.plugin.access.common.MetadataLoader.pluginLoaded(MetadataLoader.java:41)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$FilterChangeListener.pluginLoaded(DefaultPluginManager.java:254)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework$2.execute(FelixGoPluginOSGiFramework.java:354)
	at org.apache.commons.collections.CollectionUtils.forAllDo(CollectionUtils.java:389)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.getBundle(FelixGoPluginOSGiFramework.java:112)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.loadPlugin(FelixGoPluginOSGiFramework.java:98)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:145)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:102)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:68)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners$1.execute(DefaultPluginJarLocationMonitor.java:272)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:303)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:270)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:201)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:192)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:184)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:173)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-view is not supported by plugin.'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
	... 20 more
2017-08-10 16:33:42,826 ERROR [Thread-75] PluginSettingsMetadataLoader:75 - Failed to fetch Plugin Settings metadata for plugin : cd.go.authentication.passwordfile
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.authentication.passwordfile' implementing 'authorization' extension failed while requesting for 'go.plugin-settings.get-configuration'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-configuration is not supported by plugin.']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:41)
	at com.thoughtworks.go.plugin.access.common.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:51)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:65)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:45)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$FilterChangeListener.pluginLoaded(DefaultPluginManager.java:254)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework$2.execute(FelixGoPluginOSGiFramework.java:354)
	at org.apache.commons.collections.CollectionUtils.forAllDo(CollectionUtils.java:389)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.getBundle(FelixGoPluginOSGiFramework.java:112)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.loadPlugin(FelixGoPluginOSGiFramework.java:98)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:145)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:102)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:68)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners$1.execute(DefaultPluginJarLocationMonitor.java:272)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:303)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:270)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:201)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:192)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:184)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:173)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-configuration is not supported by plugin.'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
	... 18 more
2017-08-10 16:34:00,124  INFO [cachedGoConfigRefreshExecutorThread] GoFileConfigDataSource:146 - Config file changed at 1502363022000
```

**Comment by holms** [comment]
Any plans to fix it?

**Comment by GaneshSPatil** [comment]
Many of these exceptions on server boot were causing due to different kinds of plugins not supporting plugin-settings.
As of today, we don't see any error during server startup.

If these exceptions are seen (again) during server startup, we can reopen this issue or create a separate one for the specific exception.

\cc: @rajiesh
