### ISSUE TITLE
Unable to send Email Notification for gocd pipeline build

### ISSUE THREAD

**Issue by Darshan-shivashankar** [gocd/gocd#3864]
##### Issue Type

- Bug Report

##### Summary

We are currently unable to send email notification configured under admin server configuration settings. The same configuration works through external email notification plugin.

<img width="1294" alt="screen shot 2017-09-17 at 6 45 57 pm" src="https://user-images.githubusercontent.com/1955708/30527084-6b63e8a8-9bd9-11e7-85bf-540f5c16f901.png">

###### Basic environment details

* Go Version: `17.10.0`
* JAVA Version: `1.8.0_77`
* OS: `Mac OS X 10.12.6`
* Browser vendor and version (if relevant): `Chrome Version 60.0.3112.113`

##### Steps to Reproduce

1. Visit Admin->Server Configurations
2. Under Email Notification section configure as attached above.
3. Click on Send test email

##### Expected Results

Test Email notifications to be sent

##### Actual Results

Throws javax.mail.MessagingException

##### Log snippets

2017-09-17 18:06:17,378 ERROR [Thread-143] GoSmtpMailSender:90 - Sending failed for email [Stage [StoreLocator/19/DIT/1] passed] to [*******@gmail.com]
javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2106)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
	at javax.mail.Service.connect(Service.java:366)
	at com.thoughtworks.go.config.GoSmtpMailSender.send(GoSmtpMailSender.java:85)
	at com.thoughtworks.go.config.BackgroundMailSender$1.run(BackgroundMailSender.java:48)
	at java.lang.Thread.run(Thread.java:745)

**Comment by arvindsv** [comment]
Have you tried the "Use SMTPS" option?

As you probably know, gmail has [different ways](https://support.google.com/a/answer/176600?hl=en) of connecting to it. You probably need SMTPS or [enable STARTTLS](https://docs.gocd.org/current/configuration/admin_mailhost_info.html).

gocd/gocd#808 is probably relevant.

I'm closing this issue, till we know for sure that it's an issue. Happy to reopen it, if it is. Thanks.
