### ISSUE TITLE
Problem converting XML pipelines to JSON pipeline-as-code ... need to reset pipeline history

### ISSUE THREAD

**Issue by PredatorVI** [gocd/gocd#3883]
I'm using GoCD 17.10.0 and converting our existing config.xml pipelines to the Git-based JSON pipeline-as-code format.

I presume the issues I'm seeing would not show if I had renamed my pipelines.  However, I do NOT want to change the pipeline names and I'd prefer not to clear the entire database, but I am open to doing so.

Before I committed the new JSON pipelines to GIT, I removed the old XML pipeline definitions from the master config.xml.  My pipelines are now in a weird state.  The label of two of the 3 pipelines reset back to 1, even though it still shows the older 'higher' revisions in the history:

![gocd-error1](https://user-images.githubusercontent.com/1933277/30720289-0fb05632-9ee4-11e7-92eb-9b1846ece54c.png)

Now when I try to view the status of a job or view the graphical Map of a pipeline instance, I get errors such as:

> _Sorry, an unexpected error occurred [SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; Error: executeQueryForObject returned too many results.; nested exception is java.sql.SQLException: Error: executeQueryForObject returned too many results.]. :( Please check the server logs for more information._

Also when I schedule a new head-water pipeline, it does NOT trigger the downstream pipelines.  I presume this is also related to the labels being off.  See the image below and note that the upstream 'filereputationservice' pipeline was built at 3:57pm and the downstream pipeline was manually triggered a few hours earlier and today (almost 17 hours later) the downstream still hasn't triggered:

![image](https://user-images.githubusercontent.com/1933277/30749038-5afdfbb8-9f6f-11e7-9675-67503bc5c4f3.png)

**Is there a way I can just purge the history for these specific pipelines?**  

**If not, how do I clear the database and start from scratch?**

Exceptions from the logs:

```
Last Modified: 2016/06/22 15:22:13
Revision: FileReputationService_ACC/180/Approval/1
UserName: Unknown
EmailAddress: null
Comment: Unknown
PipelineLabel: 180
]
        at com.thoughtworks.go.domain.materials.Modifications.since(Modifications.java:100)
        at com.thoughtworks.go.server.persistence.MaterialRepository.findModificationsSince(MaterialRepository.java:707)
        at com.thoughtworks.go.server.materials.MaterialChecker.findRevisionsSince(MaterialChecker.java:68)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:184)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:147)
        at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:109)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:44)
        at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:25)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
```

AND

```
2017-09-21 10:24:42,237 ERROR [79@MessageListener for ScheduleCheckListener] BuildCauseProducerService:219 - Error while scheduling pipeline: filereputationservice_ACC
org.springframework.jdbc.UncategorizedSQLException: SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; Error: executeQueryForObject returned too many results.; nested exception is java.sql.SQLException: Error: executeQueryForObject returned too many results.
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
        at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
        at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.execute(SqlMapClientDaoSupport.java:112)
        at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:268)
        at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.access$501(SqlMapClientDaoSupport.java:39)
        at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate$4.execute(SqlMapClientDaoSupport.java:97)
        at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.executeInternal(SqlMapClientDaoSupport.java:120)
        at com.thoughtworks.go.server.transaction.SqlMapClientDaoSupport$SqlMapClientTemplate.queryForObject(SqlMapClientDaoSupport.java:95)
        at com.thoughtworks.go.server.dao.PipelineSqlMapDao.loadPipelineInstanceModelByNameAndCounter(PipelineSqlMapDao.java:352)
        at com.thoughtworks.go.server.dao.PipelineSqlMapDao.findPipelineHistoryByNameAndCounter(PipelineSqlMapDao.java:340)
```

**Comment by PredatorVI** [comment]
I should note also that I have dozens of other pipelines I am trying to convert to JSON format in GIT and I don't want to change the naming if I can help it.  

When I try to view the downstream pipeline instance (graphical view of revisions) I see this error:

![image](https://user-images.githubusercontent.com/1933277/30749313-35960acc-9f70-11e7-8497-369bb0ab9e82.png)
