### ISSUE TITLE
Windows Agent cannot connect to gocd Linux Server

### ISSUE THREAD

**Issue by bluesource** [gocd/gocd#3945]
##### Issue Type
Bug
##### Summary
GOCD Windows Agent 17.10.0-5380-jre-64bit cannot connect to gocd Server (Debian 9)

##### Environment
"Go Server Information": {
    "Version": "17.10.0 (5380-05598d88fd4dabdde1184faa4fbffc5f9406d0dc)"

    "OS Name": "Linux",
    "OS Version": "4.9.0-3-amd64",
    "System Architecture": "amd64",
    "Available Processors": 4,
    "Average System Load": 0.03

###### Basic environment details

* Go Version: 17.10.0
* JAVA Version:  1.8.0_131
* OS: Linux 4.9.0-3-amd64

##### Expected Results
Agent should show up in gocd server web GUI

##### Actual Results
nothing happens

##### Log snippets
Log from Agent:

2017-10-18 15:53:23,400 ERROR [WrapperJarAppMain] ServerBinaryDownloader:80 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error: 
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.fetchUpdateCheckHeaders(ServerBinaryDownloader.java:96)
	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:72)
	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:79)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:84)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gocd.Boot.run(Boot.java:58)
	at com.thoughtworks.gocd.Boot.main(Boot.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:427)
	at java.lang.Thread.run(Thread.java:748)

##### Any other info
Same Java Version on both agent and server (1.8.131)

**Comment by arvindsv** [comment]
What is the server hostname you provided, when installing the agent? It should be something like: `https://server:8154/go`. Is it possible you provided `http://` instead?

What is the value of the `GO_SERVER_URL` environment variable on the agent side?

**Comment by bluesource** [comment]
Hi,
Problem fixed! It seems the windows agent cannot connect with IP of the gocd-server.
Provding the gocd-server hostname and voila! - agent connected

It seems the linux / macos agents do not have a problem with ips?

thanks and regards,
Michael

**Comment by arvindsv** [comment]
Glad it is solved. I'll close this, then. There should be no difference. Either IP or hostname should work. Maybe the hostname resolved to a different IP? Anyway, good to know it's alright.
