### ISSUE TITLE
500s when authenticating a user after you delete a <pipelines> tag that was created by a config repo

### ISSUE THREAD

**Issue by dudadornelles** [gocd/gocd#4002]
##### Issue Type

- Bug Report

##### Summary

If you have a config repo that creates a pipeline group and you manually delete that pipeline group tag from the config xml and save it, gocd starts throwing 500s everytime you try to authenticate.-

Edit: the bug will only happen if you have more than one config repo and you define the same pipeline group in pipelines that are in different config repos

##### Environment

Running gocd in docker (17.7), but the same behaviour was observed in 17.7 running in amazon linux

##### Steps to Reproduce
* you will need two config repos that define pipelines and use the *same pipeline group*
* Clone https://github.com/dudadornelles/gocd-reproduce-bug, it has a cruise-config.xml that defines two config_repos that define pipelines in the same pipeline group
* from the cloned folder, run `docker run -d -v $(pwd)/home:/home/go -v $(pwd)/godata:/godata -p8153:8153 -p8154:8154 gocd/gocd-server:v17.7.0`
* once gocd is up, login as admin (admin:admin), wait for the config repos to load - it will create two pipelines under the same pipeline group "pgroup"
* once the pipelines show up, edit the xml and remove the `<pipelines group="pgroup" />` tag
* log out of gocd, try logging in again with admin:admin, it wont be able to login anymore

##### Stack trace
It isnt really printing a full stack trace but the following line gets printed everytime I try to login after gocd gets in the buggy state

```
2017-11-09 21:42:46,792 ERROR [qtp1936628443-26] BasicAuthenticationFilter:62 - java.lang.RuntimeException: No valid configuration part to store authorization
```

**Comment by dudadornelles** [comment]
Hey folks, I wasnt able to reproduce this from a fresh installation, I'm trying to come up with a little repo and some instructions on how to reproduce this, I'll update it here when Im solid with the steps to reproduce.

**Comment by dudadornelles** [comment]
Updated the issue with better steps to reproduce

**Comment by arvindsv** [comment]
```
No valid configuration part to store authorization
  at com.thoughtworks.go.config.merge.MergePipelineConfigs.getAuthorizationPart(MergePipelineConfigs.java:72)
  at com.thoughtworks.go.config.merge.MergePipelineConfigs.getAuthorization(MergePipelineConfigs.java:625)
  at com.thoughtworks.go.config.BasicCruiseConfig$FindPipelineGroupAdminstrator.visit(BasicCruiseConfig.java:1517)
  at com.thoughtworks.go.domain.PipelineGroups.accept(PipelineGroups.java:115)
  at com.thoughtworks.go.config.BasicCruiseConfig.isGroupAdministrator(BasicCruiseConfig.java:1227)
  at com.thoughtworks.go.server.service.GoConfigService.isGroupAdministrator(GoConfigService.java:858)
  at com.thoughtworks.go.server.service.SecurityService.isUserGroupAdmin(SecurityService.java:177)
  at com.thoughtworks.go.server.security.AuthorityGranter.checkAndAddGroupAdmin(AuthorityGranter.java:62)
  at com.thoughtworks.go.server.security.AuthorityGranter.authorities(AuthorityGranter.java:42)
  at com.thoughtworks.go.server.security.providers.PluginAuthenticationProvider.getGoUserPrinciple(PluginAuthenticationProvider.java:167)
  at com.thoughtworks.go.server.security.providers.PluginAuthenticationProvider.retrieveUser(PluginAuthenticationProvider.java:97)
  at org.springframework.security.providers.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:121)
  at com.thoughtworks.go.server.security.providers.GoAuthenticationProvider.authenticate(GoAuthenticationProvider.java:38)
  at org.springframework.security.providers.ProviderManager.doAuthentication(ProviderManager.java:195)
  at org.springframework.security.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:46)
  at org.springframework.security.ui.webapp.AuthenticationProcessingFilter.attemptAuthentication(AuthenticationProcessingFilter.java:82)
  at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:252)
  at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:173)
  at com.thoughtworks.go.server.security.BasicAuthenticationFilter.doFilterHttp(BasicAuthenticationFilter.java:62)
  at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
  at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at com.thoughtworks.go.server.security.WebBasedAuthenticationFilter.doFilterHttp(WebBasedAuthenticationFilter.java:61)
  at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at com.thoughtworks.go.server.security.OauthAuthenticationFilter.doFilterHttp(OauthAuthenticationFilter.java:61)
  at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at com.thoughtworks.go.server.security.RemoveAdminPermissionFilter.doFilterHttp(RemoveAdminPermissionFilter.java:76)
  at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
  at com.thoughtworks.go.server.security.GoLogoutFilter.doFilterHttp(GoLogoutFilter.java:48)
  at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
  at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at com.thoughtworks.go.server.security.ModeAwareFilter.doFilter(ModeAwareFilter.java:49)
  at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
  at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:174)
  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
  at com.thoughtworks.go.server.web.BackupFilter.doFilter(BackupFilter.java:84)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
  at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:34)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
  at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
  at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
  at org.eclipse.jetty.server.Server.handle(Server.java:499)
  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
  at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
  at java.lang.Thread.run(Thread.java:748)
```

/cc @maheshp might be interested too.

**Comment by jyotisingh** [comment]
@dudadornelles , @arvindsv - had a look at this one. [That](https://github.com/gocd/gocd/blob/b9f62428e1f7354cd1bb94cc00a3a7b991ba3b8c/config/config-api/src/com/thoughtworks/go/config/merge/MergePipelineConfigs.java#L72) is the line which throws this exception. Basically, upon a user's login, appropriate user permissions are computed and stored in memory (changes made as a part of authorization extension). The issue happens only when there is more than 1 remote part pointing to a specific pipeline group, as that's the only time when a `MergePipelineConfigs` is created, hence you weren't able to reproduce this with just one config-repo (see [this](https://github.com/gocd/gocd/blob/b9f62428e1f7354cd1bb94cc00a3a7b991ba3b8c/config/config-api/src/com/thoughtworks/go/config/BasicCruiseConfig.java#L378)).

@arvindsv - around your question about why is a pipeline-group always added to the main xml, the reason was to allow an end-user to define authorization from `https://go-server/go/admin/pipelines` since config-repos do not allow this to be defined. For anything defined remotely, the edit links would not work otherwise. So, with a single config-repo, even if the user is allowed to login, hitting the edit pipeline group link `http://localhost:8153/go/admin/pipeline_group/pgroup/edit` throws `404`.

There are two ways to solve this. One would be to ensure that `pgroup` always exists. The other is to make some changes in `MergePipelineConfigs` and making the links work etc. But before trying to make any fixes, I would like to understand if there was a specific reason for you @dudadornelles 
 to delete the entry for `pgroup` from the main xml.

**Comment by dudadornelles** [comment]
@jyotisingh We are using a combination of gomatic and config repos in some of our gocd. However, to ensure correctness, before we run gomatic we remove all pipeline groups and their contents. That ensures that no manual change "survives" a gomatic run, just helps us remain sane.

**Comment by jyotisingh** [comment]
Alright, if that's the intent, then even if GoCD automatically added these pipeline groups to the main xml if it needed to, you remain unaffected. Thanks, that helps.

**Comment by adityasood** [comment]
Renaming a pipeline group ( defined in config-repo) name leads to the creation of a new pipeline-group and the user can no longer edit permissions for the previous one.

for eg.

1. Define a pipeline in config-repo and assign it to a pipeline group (PipelineA -> GroupA). Add this config-repo to GoCD.
2. Rename the group name from GoCD UI to GroupB. 
3. You will now see two groups GroupA with PipeplineA and GroupB with no pipelines associated to it.
4. Try the edit option for GroupA. You will see "Pipeline group 'GroupA' not found.
5. Now change the pipeline group name to GroupB in config repo. This should bring things back to normal or make any changes to the config-repo this should now allow you to edit GroupA->PipelineA and have a separate group GroupB with no pipelines
