### ISSUE TITLE
GoLauncher class not found

### ISSUE THREAD

**Issue by gerardolm** [gocd/gocd#4021]
##### Issue Type

Packaging problem?

##### Summary

Java is unable to find the com.thoughtworks.go.server.util.GoLauncher class although it is located in a lib JAR file inside the go.jar file (java.lang.ClassNotFoundException thrown at start).

##### Environment

3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

##### Steps to Reproduce

1. Download https://download.gocd.org/binaries/17.11.0-5520/deb/go-server_17.11.0-5520_all.deb
2. dpkg -i ...
3. sudo /etc/init.d/go-server start

##### Expected Results
Go server starts properly.

##### Actual Results
Start script outputs "Error starting Go server." Log at /var/log/go-server/go-server.out.log shows a java.lang.ClassNotFoundException for com.thoughtworks.go.server.util.GoLauncher.

**Comment by ketan** [comment]
Could you confirm what the checksum of `/usr/share/go-server/go.jar` is?

**Comment by gerardolm** [comment]
bedc7111c53d46db6f670666fe1c2d88

**Comment by ketan** [comment]
What version of java do you have on PATH. `java -version` should usually tell you. Can you also provide the complete error that you see in the log file?

**Comment by ketan** [comment]
I tried reproducing it on a docker image `ubuntu:14.04` and was able to bring up the server. The packaging is good and I also confirmed that the installer tests which test the installer actually tested version `17.11.0-5520`. I suspect this is something to do with your environment, most likely the java version that the go-server script uses.

**Comment by gerardolm** [comment]
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

[Thu Nov 16 14:00:06 UTC 2017] Starting process: 
[Thu Nov 16 14:00:06 UTC 2017]   Working directory    : /var/lib/go-server
[Thu Nov 16 14:00:06 UTC 2017]   JVM arguments        : [-Dgocd.redirect.stdout.to.file=/var/log/go-server/go-server.out.log, -Djava.security.egd=file:/dev/./urandom, -Xms512m, -Xmx1g, -XX:MaxMetaspaceSize=256m, -Duser.language=en, -Djruby.rack.request.size.threshold.bytes=30000000, -Duser.country=US, -Dcruise.config.dir=/etc/go, -Dcruise.config.file=/etc/go/cruise-config.xml, -Dcruise.server.port=8153, -Dcruise.server.ssl.port=8154]
[Thu Nov 16 14:00:06 UTC 2017]   Application arguments: []
[Thu Nov 16 14:00:06 UTC 2017]            GoCD Version: 17.11.0-5520
[Thu Nov 16 14:00:06 UTC 2017]          JVM properties: {jruby.rack.request.size.threshold.bytes=30000000, java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/usr/lib/jvm/jdk1.8.0_111/jre/lib/amd64, java.vm.version=25.111-b14, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, sun.java.launcher=SUN_STANDARD, user.country=US, sun.os.patch.level=unknown, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/var/lib/go-server, java.runtime.version=1.8.0_111-b14, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, java.endorsed.dirs=/usr/lib/jvm/jdk1.8.0_111/jre/lib/endorsed, os.arch=amd64, java.io.tmpdir=/tmp, line.separator=
, java.vm.specification.vendor=Oracle Corporation, os.name=Linux, cruise.config.dir=/etc/go, sun.jnu.encoding=ANSI_X3.4-1968, java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, java.specification.name=Java Platform API Specification, java.class.version=52.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=3.16.0-77-generic, cruise.server.port=8153, user.home=/var/go, user.timezone=Etc/UTC, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=ANSI_X3.4-1968, java.specification.version=1.8, java.class.path=/usr/share/go-server/go.jar, user.name=go, cruise.config.file=/etc/go/cruise-config.xml, java.vm.specification.version=1.8, sun.java.command=/usr/share/go-server/go.jar, java.home=/usr/lib/jvm/jdk1.8.0_111/jre, sun.arch.data.model=64, user.language=en, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, java.version=1.8.0_111, java.ext.dirs=/usr/lib/jvm/jdk1.8.0_111/jre/lib/ext:/usr/java/packages/lib/ext, sun.boot.class.path=/usr/lib/jvm/jdk1.8.0_111/jre/lib/resources.jar:/usr/lib/jvm/jdk1.8.0_111/jre/lib/rt.jar:/usr/lib/jvm/jdk1.8.0_111/jre/lib/sunrsasign.jar:/usr/lib/jvm/jdk1.8.0_111/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.8.0_111/jre/lib/jce.jar:/usr/lib/jvm/jdk1.8.0_111/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.8.0_111/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.8.0_111/jre/classes, java.vendor=Oracle Corporation, java.security.egd=file:/dev/./urandom, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, gocd.redirect.stdout.to.file=/var/log/go-server/go-server.out.log, cruise.server.ssl.port=8154, sun.cpu.isalist=}
[Thu Nov 16 14:00:06 UTC 2017]   Environment Variables: {LANGUAGE=en_GB:en, PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/lib/android-sdk-linux/tools:/usr/lib/android-sdk-linux/platform-tools:/usr/lib/jvm/jdk1.8.0_111/bin:/usr/lib/jvm/jdk1.8.0_111/jre/bin:/opt/maven/bin, SHELL=/bin/bash, JAVA_HOME=/usr/lib/jvm/jdk1.8.0_111, GO_SERVER_LOG_DIR=/var/log/go-server, OLDPWD=/var/go, TERM=xterm, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, USER=go, LANG=en_GB.UTF-8, XDG_SESSION_ID=14836, ANDROID_HOME=/usr/lib/android-sdk-linux, JRE_HOME=/usr/lib/jvm/jdk1.8.0_111/jre, MAIL=/var/mail/go, LC_ALL=C, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, TS_ENV=devel, LOGNAME=go, XDG_RUNTIME_DIR=/run/user/1017, PWD=/var/lib/go-server, SHLVL=1, HOME=/var/go, NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript}
java.lang.ClassNotFoundException: com.thoughtworks.go.server.util.GoLauncher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.thoughtworks.gocd.Boot.run(Boot.java:103)
	at com.thoughtworks.gocd.Boot.main(Boot.java:55)

Alright, so the issue doesn't seem to be a OSX thing (I assumed this because I only found Mac-specific stuff inside the JAR itself).

It seems the "missing" class is found in server-launcher-17.12.0-5564-main.jar, inside the lib folder. No idea why it's not picking it up, though.

**Comment by ketan** [comment]
> It seems the "missing" class is found in server-launcher-17.12.0-5564-main.jar, inside the lib folder. No idea why it's not picking it up, though.

The jar inside jar is by design. Why it's not being picked up is something that would need investigation. Do you have anything on a remote file system?

**Comment by gerardolm** [comment]
> The jar inside jar is by design. Why it's not being picked up is something that would need investigation. Do you have anything on a remote file system?

Yes, I was taking a look at the com.thoughtworks.gocd.Boot and onejar.Handler classes. For some reason the jars-inside-the-jar are not handled propertly.

I'm doing this in a test server and all fs are local. /usr, /var and /home are on different devices, though.

**Comment by arvindsv** [comment]
No activity. Stale. Closing. The installers have also been rewritten since this time, I believe.
