### ISSUE TITLE
Adding config-repo with broken/incorrect material shows no error on the GoCD admin page/UX

### ISSUE THREAD

**Issue by bizmate** [gocd/gocd#4035]
##### Material fetching error not displayed
Bug Report

##### Summary

given I am a developer
I would like to see an error on the UX when I add a failing material reference in the server configuration
So i can rectify the material problem  

##### Environment
I have reproduced it in both 17.8 and 17.11

###### Basic environment details
* Go Server Version: | 17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1)
* JVM version: | 1.8.0_151
* OS Information: | Linux 4.4.0-1030-aws
* Usable space in artifacts repository: | 5.46 GB
* Database schema version: | 1708001
* Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

##### Steps to Reproduce
Add config repo
```xml
    <config-repos>
        <config-repo pluginId="yaml.config.plugin" id="repo3">
            <git url="ssh://git@gitlab.madeupservername.com:2222/group/BrokenUrlToRepo.git"  />
        </config-repo>
    </config-repos>
```

##### Expected Results
If the material is not working I would like to see an informative error, or at least an error on the UX

##### Actual Results
Nothing shown on the UX, I  need to inspect logs but it does not help end users who have no ssh access

##### Possible Fix
Show the error, in version 17.8 i managed to see it for 15 seconds once, i am unsure why it came up at that specific time, and then it would force disappear

##### Log snippets
```
2017-11-22 17:59:05,038 WARN  [103@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:112 - [Material Update] Modification check failed for material: URL: ssh://git@gitlab.madeupservername.com:2222/group/BrokenUrlToRepo.git, Branch: master
java.lang.RuntimeException: Failed to run git clone command STDERR: Cloning into '/var/lib/go-server/pipelines/flyweight/fe704047-3867-46af-9e16-f01c45c82f66'...
STDERR: ssh: Could not resolve hostname gitlab.madeupservername.com: Name or service not known
STDERR: fatal: Could not read from remote repository.
STDERR: 
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.
        at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:40)
        at com.thoughtworks.go.config.materials.git.GitMaterial.getGit(GitMaterial.java:213)
        at com.thoughtworks.go.config.materials.git.GitMaterial.latestModification(GitMaterial.java:117)
        at com.thoughtworks.go.server.service.materials.GitPoller.latestModification(GitPoller.java:32)
        at com.thoughtworks.go.server.service.materials.GitPoller.latestModification(GitPoller.java:28)
        at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:105)
        at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
        at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:55)
        at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:69)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:163)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:121)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:47)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:88)
        at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
        at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:85)
        at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:50)
        at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:30)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Failed to run git clone command
        at com.thoughtworks.go.util.ExceptionUtils.bombIfFailedToRunCommandLine(ExceptionUtils.java:50)
        at com.thoughtworks.go.config.materials.git.GitMaterial.git(GitMaterial.java:247)
        at com.thoughtworks.go.config.materials.git.GitMaterial.getGit(GitMaterial.java:211)
        ... 21 common frames omitted
2017-11-22 17:59:05,039 WARN  [90@MessageListener for ConfigMaterialUpdater] ConfigMaterialUpdater:78 - [Config Material Update] Cannot update configuration part because material update has failed. Reason: Failed to run git clone command STDERR: Cloning into '/var/lib/go-server/pipelines/flyweight/fe704047-3867-46af-9e16-f01c45c82f66'...
STDERR: ssh: Could not resolve hostname gitlab.madeupservername.com: Name or service not known
STDERR: fatal: Could not read from remote repository.
STDERR: 
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.. Cause: Failed to run git clone command
```

**Comment by jyotisingh** [comment]
@bizmate Just wondering if you happened to make any changes to cruise-config.xml using GoCD's UI or Full xml. Material update errors disappear until next update cycle after a config save. Could you please confirm

**Comment by bizmate** [comment]
I used the UI in this case. I noticed a pattern in the fact that the messages disappear but if the config has not changed there is no reason to hide the message

**Comment by varshavaradarajan** [comment]
This can be closed now that there is a config repo SPA to show the status and to test connection while adding a config repo. The modification check failure error appears in the server health messages as well.
