### ISSUE TITLE
randomly be unable to check the git repository status once in a few days

### ISSUE THREAD

**Issue by dreamlover** [gocd/gocd#4172]
##### Summary
I'm running gocd server in a docker container. Normally the pipeline works as expected, but it will randomly be unable to check the git repository status once in a few days. Consequently the pipeline won't start even triggered manually by click the start button in the web UI.

###### Basic environment details
* Go Version: `17.12.0`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.10.0-514.6.1.el7.x86_64`
* Browser vendor and version (if relevant): `Firefox 57.0.4(64-bit)`

##### Log snippets
```
git rev-parse --abbrev-ref HEAD
--- Environment ---
{GIT_ALLOW_PROTOCOL=http:https:ssh:git:file:rsync}
--- INPUT ----
--OUTPUT ---
HEAD
--- ERROR ---
STDERR: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
STDERR: Use '--' to separate paths from revisions, like this:
STDERR: 'git <command> [<revision>...] -- [<file>...]'
---
 
	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:40)
	at com.thoughtworks.go.config.materials.git.GitMaterial.getGit(GitMaterial.java:213)
	at com.thoughtworks.go.config.materials.git.GitMaterial.modificationsSince(GitMaterial.java:121)
	at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:37)
	at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:28)
	at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:109)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:56)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:142)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:134)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:101)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:98)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:50)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:30)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.thoughtworks.go.util.command.CommandLineException: Error performing command: --- Command ---
```
##### Code snippets/Screenshots
```
    Material update failed for material 'ssh://ay_cis@o.ayjiayou.com:30418/MPos.git' because: Error performing command: --- Command --- git rev-parse --abbrev-ref HEAD --- Environment --- {GIT_ALLOW_PROTOCOL=http:https:ssh:git:file:rsync} --- INPUT ---- --OUTPUT --- HEAD --- ERROR --- STDERR: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree. STDERR: Use '--' to separate paths from revisions, like this: STDERR: 'git <command> [<revision>...] -- [<file>...]' --- . Cause: Error performing command: --- Command --- git rev-parse --abbrev-ref HEAD --- Environment --- {GIT_ALLOW_PROTOCOL=http:https:ssh:git:file:rsync} --- INPUT ---- --OUTPUT --- HEAD --- ERROR --- STDERR: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree. STDERR: Use '--' to separate paths from revisions, like this: STDERR: 'git <command> [<revision>...] -- [<file>...]' --- 
```

**Comment by ketan** [comment]
can you provide the output of `git ls-remote YOUR_GIT_REPO_URL`?

**Comment by dreamlover** [comment]
```
[root@i MPos]# git ls-remote ssh://ay_cis@o.ayjiayou.com:30418/MPos.git
e352884c619115089520a25fadf1b8af775e163a	HEAD
d00b98e035ec84a30bdde31b68d0da195abdc6ba	refs/changes/24/124/1
e352884c619115089520a25fadf1b8af775e163a	refs/heads/master
```

**Comment by dreamlover** [comment]
I notice that the pipeline is building now!

**Comment by ketan** [comment]
There should not be a `HEAD` in the remote repository. Looks like someone likely made a bad push?

**Comment by dreamlover** [comment]
Why shouldn't there be a HEAD in the remote repository?

**Comment by dreamlover** [comment]
I checked that every of our repos has HEAD in the remote. Is there any misusage of our git server?

**Comment by jmanuelortiz** [comment]
Hi guys,

what was the solution for this at the end? I am facing this with some repos.

Regards

Manuel

**Comment by dreamlover** [comment]
To be honest, we changed to Jenkins...

**Comment by dreamlover** [comment]
> Hi guys,
> 
> what was the solution for this at the end? I am facing this with some repos.
> 
> Regards
> 
> Manuel

To be honest, we changed to Jenkins...

**Comment by sjjian** [comment]
hi, i reolve it by rerun gocd server docker.
