### ISSUE TITLE
[Feature request] Display warning if pipeline is not associated with any of the environment and all the agents are occupied

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#4194]
##### Issue Type

- Feature enhancement

##### Summary

If a pipeline is not assigned to any of the environment and all the agents are associated with environment/s, GoCD doesn't display any relevant warning message (if that pipeline is triggered) saying - there is no agent in free pool or pipeline needs to be associated with environment. It keeps on waiting for agent to get assigned.

###### Basic environment details

* Go Version: All

##### Steps to Reproduce

1. Create an environment and assign all the agents and pipelines (except one pipeline) 
2. Tigger pipeline
3. Pipeline is scheduled but waiting for agent to get assigned

##### Expected Results
Message shown in the warning section of dashboard saying pipeline_xyz is not assigned to any of the environment.

##### Actual Results
Warning message is logged in go-server.log file but nothing pointing to missing mapping between pipeline and environment or about agent.

##### Log snippets

```
2018-01-16 15:07:57,204 WARN  [qtp1123629720-30] HttpChannel:396 - /go/files/Clean_working_dir/11/defaultStage/1/defaultJob/cruise-output/console.log?startLineNumber=0
java.lang.IllegalStateException: Committed
        at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1242)
        at javax.servlet.ServletResponseWrapper.resetBuffer(ServletResponseWrapper.java:241)
        at org.eclipse.jetty.servlets.gzip.CompressedResponseWrapper.resetBuffer(CompressedResponseWrapper.java:272)
        at org.eclipse.jetty.servlets.gzip.CompressedResponseWrapper.sendError(CompressedResponseWrapper.java:286)
        at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:158)
        at org.springframework.security.context.HttpSessionContextIntegrationFilter$OnRedirectUpdateSessionResponseWrapper.sendError(HttpSessionContextIntegrationFilter.java:498)
        at com.thoughtworks.go.server.security.BasicAuthenticationFilter.handleException(BasicAuthenticationFilter.java:92)
        at com.thoughtworks.go.server.security.BasicAuthenticationFilter.doFilterHttp(BasicAuthenticationFilter.java:66)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
        at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
        at com.thoughtworks.go.server.security.OauthAuthenticationFilter.doFilterHttp(OauthAuthenticationFilter.java:61)
        at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
```
-->

**Comment by cholmes1111** [comment]
+1. Thanks for looking into this

**Comment by GaneshSPatil** [comment]
@maheshp @arvindsv -- can this be considered as part of analytics plugin?

**Comment by arvindsv** [comment]
@GaneshSPatil I think this should be done as a part of the default dashboard (warning that the job will be waiting forever). The plugin is more retrospective.

**Comment by arvindsv** [comment]
Also, this state can keep changing based on whether agents are available or not (quite dynamic).
