### ISSUE TITLE
Agent Error occurred during loop NullPointerException: Cannot invoke "org.apache.http.Header.getValue()" because "md5Header" is null

### ISSUE THREAD

**Issue by mario-fuentes** [gocd/gocd#4469]
##### Issue Type

- Bug Report

##### Summary

The GoCD Server inform that our two agents are idle but lot of task are pending waiting for an agent.  The agent docker log of both ends with a serie of NullPointerException, more than twenty continuous errors of the fellow type:

`
2018-03-01 11:55:55,365 [stdout] - 2018-03-01 11:55:55,364 ERROR [loopThread] AgentController:91 - [Agent Loop] Error occurred during loop: 

2018-03-01 11:55:55,365 [stdout] - java.lang.NullPointerException: null
`

##### Environment

[gocd-support.txt](https://github.com/gocd/gocd/files/1771224/gocd-support.txt)

###### Basic environment details

Go Server Version:	18.1.0 (5937-8a847b96ee8d38173f80178ed1285f0e53a970e0)
JVM version:	1.8.0_151
OS Information:	Linux 4.9.76-3.78.amzn1.x86_64
Usable space in artifacts repository:	2.72 GB
Database schema version:	1801007
Pipelines Count:	3

###### Additional Environment Details

We are using the official docker images.

**Comment by ketan** [comment]
Do you have the complete stacktrace on the agent? This error does not
contain enough information to diagnose the issue.

**Comment by mario-fuentes** [comment]
Hi Ketan, I know that the log isn't sufficient to diagnose, but our agents aren't running in debug mode.  I restarted the agent's containers and are working again.  If the issue persists, we should active the debug mode.

**Comment by ketan** [comment]
For now I'll close this issue, when you have more information, please post it here and we can reopen this issue.

**Comment by mario-fuentes** [comment]
Here more details

```
2018-03-01 13:56:32,068 [stdout] - 2018-03-01 13:56:32,067 ERROR [loopThread] AgentController:91 - [Agent Loop] Error occurred during loop: 
2018-03-01 13:56:32,068 [stdout] - java.lang.NullPointerException: null
2018-03-01 13:56:32,068 [stdout] - 	at com.thoughtworks.go.agent.service.AgentUpgradeService.validateMd5(AgentUpgradeService.java:97)
2018-03-01 13:56:32,068 [stdout] - 	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:80)
2018-03-01 13:56:32,068 [stdout] - 	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:69)
2018-03-01 13:56:32,068 [stdout] - 	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:83)
2018-03-01 13:56:32,068 [stdout] - 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
2018-03-01 13:56:32,068 [stdout] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-03-01 13:56:32,068 [stdout] - 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-03-01 13:56:32,068 [stdout] - 	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
2018-03-01 13:56:32,068 [stdout] - 	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
2018-03-01 13:56:32,068 [stdout] - 	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
2018-03-01 13:56:32,068 [stdout] - 	at java.util.TimerThread.mainLoop(Timer.java:555)
2018-03-01 13:56:32,068 [stdout] - 	at java.util.TimerThread.run(Timer.java:505)

```

**Comment by ketan** [comment]
Can you confirm how you're running your agent. This will happen when you simply run using `java -jar agent.jar` without specifying `-Dagent.binary.md5=.... -Dagent.plugins.md5=... -Dagent.tfs.md5=... -Dagent.launcher.md5=...`

**Comment by mario-fuentes** [comment]
I'm using the official GoCD Agent docker image, the agent is executed by the docker-entrypoint.sh.

Output for: ps -fe | grep java 
```
37 go         0:17 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Dgo.console.stdout=true -Djava.security.egd=file:/dev/./urandom -Dagent.plugins.md5=e8253de16575d8929a8fc27a1b0b40fa -Dagent.binary.md5=8b1c0a0b69473ab451c7afc2d307755d -Dagent.launcher.md5=01dee9234ca0d35e4a8a6c8e048217e8 -Dagent.tfs.md5=d755c775c5776400f7687233d33754e8 -jar agent.jar -serverUrl https://go-server:8154/go -sslVerificationMode NONE
```

**Comment by ketan** [comment]
Can you paste the output of the following. Also are your agents connecting through a reverse proxy?

```
$ curl -v https://your-go-server:8154/go/admin/latest-agent.status
```

**Comment by mario-fuentes** [comment]
The GoCD server and the agents are running inside a Docker Compose.

```
$ curl -v https://go-server:8154/go/admin/latest-agent.status
*   Trying 172.18.0.2...
* TCP_NODELAY set
* Connected to go-server (172.18.0.2) port 8154 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by mario-fuentes** [comment]
Exists any way to disable the auto-update feature into the agents?

**Comment by mario-fuentes** [comment]
Yesterday I upgraded my GoCD server and agents to 18.2.0, the NullPointerException continues but the agents are still working.

**Comment by ketan** [comment]
Could you provide the new stacktrace that you see with 18.2, along with the output of `ps aux | grep java`.

**Comment by ketan** [comment]
> Exists any way to disable the auto-update feature into the agents?

There is no way, the agent and server protocol changes slightly every release as new features are added, as such the agent needs to be a version that is compatible with the server. The server contains an agent jar binary that the agent bootstrapper will download and use.

> Yesterday I upgraded my GoCD server and agents to 18.2.0, the NullPointerException continues but the agents are still working.

The auto-update logic runs in a separate thread, so the normal operation of the agent will continue to run.

**Comment by mario-fuentes** [comment]
Into the Server
```
$ ps aux | grep java
   32 go        14:26 java -server -Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1g -XX:MaxMetaspaceSize=256m -Dgo.console.stdout=true -Duser.language=en -Djruby.rack.request.size.threshold.bytes=30000000 -Duser.country=US -Dcruise.config.dir=/go-working-dir/config -Dcruise.config.file=/go-working-dir/config/cruise-config.xml -Dcruise.server.port=8153 -Dcruise.server.ssl.port=8154 -jar /go-server/go.jar
```

Into the Agent
```
$ ps aux | grep java
   29 go         1:15 java -Dgocd.agent.log.dir=/go/logs -Dgo.console.stdout=true -jar /go-agent/agent-bootstrapper.jar -serverUrl https://go-server:8154/go
   54 go         2:15 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Dcruise.console.publish.interval=10 -Xms128m -Xmx256m -Dgo.console.stdout=true -Djava.security.egd=file:/dev/./urandom -Dagent.plugins.md5=5193778849e6c2c693b2f7ec53cd415f -Dagent.binary.md5=d7c76d9d7e91aae7f593491ceb7fcb40 -Dagent.launcher.md5=4c6579c8e7f9d18f4d6e4a3b5a4e1075 -Dagent.tfs.md5=8ff6cee33066099aaac2c28ea9982bf2 -jar agent.jar -serverUrl https://go-server:8154/go -sslVerificationMode NONE
```

Error stacktrace
```
2018-03-08 23:30:04,260 ERROR [loopThread] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
	at com.thoughtworks.go.agent.service.AgentUpgradeService.validateMd5(AgentUpgradeService.java:97)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:80)
	at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgrade(AgentUpgradeService.java:69)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:83)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

```

Latest Agent status
```
$ curl --insecure -v https://go-server:8154/go/admin/latest-agent.status

> GET /go/admin/latest-agent.status HTTP/1.1
> Host: go-server:8154
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 09 Mar 2018 18:13:03 GMT
< Set-Cookie: JSESSIONID=w0t677nloq9n1knf6kxlrdfsf;Path=/go;Expires=Fri, 23-Mar-2018 18:13:03 GMT;Secure;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Agent-Content-MD5: d7c76d9d7e91aae7f593491ceb7fcb40
< Agent-Launcher-Content-MD5: 4c6579c8e7f9d18f4d6e4a3b5a4e1075
< Agent-Plugins-Content-MD5: 5193778849e6c2c693b2f7ec53cd415f
< TFS-SDK-Content-MD5: 8ff6cee33066099aaac2c28ea9982bf2
< Cruise-Server-Ssl-Port: 8154
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-UA-Compatible: chrome=1
< Content-Length: 0
```

**Comment by chandru9279** [comment]
Bump - I am also facing this. @ketan 

```bash
[root@slave-vm10 data]# tail -f /var/log/go-agent/go-agent.log
2018-03-20 08:04:32,770 INFO  [loopThread] DefaultGoPublisher:89 - Stopping Transmission for Build [E2E/1060/cucumber/1/cucumber7/719]
2018-03-20 08:04:32,800 INFO  [loopThread] HttpService:138 - Got back 200 from server
2018-03-20 08:04:32,816 ERROR [loopThread] AgentController:91 - [Agent Loop] Error occurred during loop:
java.lang.NullPointerException: null
2018-03-20 08:34:32,842 ERROR [loopThread] AgentController:91 - [Agent Loop] Error occurred during loop:
java.lang.NullPointerException: null

[root@slave-vm10 data]# tail -f /var/log/go-agent/go-agent-stderr.log
2018-03-20 08:04:32,556 - [Fatal Error] :1:1: Content is not allowed in prolog.
2018-03-20 08:04:32,558 - [Fatal Error] :1:1: Content is not allowed in prolog.
2018-03-20 08:04:32,559 - [Fatal Error] :1:1: Content is not allowed in prolog.
2018-03-20 08:04:32,560 - [Fatal Error] :1:1: Content is not allowed in prolog.
```

**Comment by GaneshSPatil** [comment]
Hi @mario-fuentes @chandru9279 ,

The agent **Loop Thread** (triggered every _10 secs_) checks for agent upgrade, to know if the upgrade is required, the agent asks for the MD5 checksum of new agent.jar. Whereas, sometimes the expected MD5 information is not retrieved from the server, which results in `java.lang.NullPointerException`. To debug this issue further, we've added some extra logging as part of [this](https://github.com/gocd/gocd/pull/5212) PR.

Experimental build for GoCD server and agent [GoCD-v18.10.0-7575](https://hub.docker.com/r/gocdexperimental/gocd-server/tags/) contains additional logs which will help us debug this issue further. Can you try to reproduce the issue with the above mentioned experimental installer, enabling debug logging on the agent(s)? Please use a test (production-like) environment for experimental installers.

Thanks in advance.

**Comment by birchb1024** [comment]
I get this with GoCD Version 19.5.0 running the agent in Podman with Java openjdk 8
```
2019-10-02 00:56:50,961 ERROR [scheduler-3] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
        at com.thoughtworks.go.agent.service.AgentUpgradeService.validateMd5(AgentUpgradeService.java:112)
        at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgradeAndExtraProperties(AgentUpgradeService.java:85)
        at com.thoughtworks.go.agent.service.AgentUpgradeService.checkForUpgradeAndExtraProperties(AgentUpgradeService.java:73)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:83)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-10-02 01:27:03,259 ERROR [scheduler-1] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
```

repeated ad nauseum. . .

**Comment by matthiaskraaz** [comment]
With 19.11.0-10687:

```
...
2019-12-14 16:01:59,957 ERROR [scheduler-2] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
2019-12-14 16:32:11,525 ERROR [scheduler-1] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
2019-12-14 17:02:23,045 ERROR [scheduler-2] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
2019-12-14 17:32:34,389 ERROR [scheduler-2] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
2019-12-14 18:02:45,770 ERROR [scheduler-1] AgentController:91 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
...
```

**Comment by arvindsv** [comment]
@matthiaskraaz In the agent log file, do you see a stack trace anywhere? It can show up a few times before the logger decides to hide it because it is repetitive.

-----------------------------------------

@matthiaskraaz and @birchb1024: In #7452, I've brought back some DEBUG logs we used to have to try and reproduce this issue.

I'll provide you a link to an experimental installer which contains these changes as soon as it is ready. It would be useful if you could upgrade both the server and agent to it (in a test setup maybe) and see if this happens. If not, we will leave these logs in the 19.12.0 release as well. Maybe they will show up at a later time when you upgrade.

To enable these logs, you will need to:

1. Have a logger configuration file on the server (in `<config-dir>/logback-include.xml`) with content similar to:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<included>
  <logger name="com.thoughtworks.go.server.controller.AgentRegistrationController" level="DEBUG" />
</included>
```

2. Have a logger configuration file on the agent (in `<config-dir>/agent-logback-include.xml`) with content similar to:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<included>
  <logger name="com.thoughtworks.go.agent.service.AgentUpgradeService" level="DEBUG" />
</included>
```

**Comment by arvindsv** [comment]
@matthiaskraaz @birchb1024 Any installer newer than 19.12.0-10877 should have this logging change. You can get this by going to https://www.gocd.org/download/ and switching to the `Experimental` tab.

**Comment by arvindsv** [comment]
Closing as stale since there are no responses.

**Comment by JeroenOortwijn** [comment]
As described in PR #8771, I also ran into this issue.
Every 30 minutes it would log a NullPointerException.

I captured the traffic with Wireshark on the Go agent computer:
[Go agent capture.zip](https://github.com/gocd/gocd/files/5607115/Go.agent.capture.zip)

The Go agent is running on Windows 10 (IP address 10.0.4.65), the server on Ubuntu server 20.04 (IP address 10.0.4.83).

When there is a successful GET request, it looks like this:
```
GET /go/admin/latest-agent.status HTTP/1.1
Host: 10.0.4.83:8153
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.6 (Java/14.0.2)
Cookie: JSESSIONID=node016o7d7wnstvfg15gx4sx9o5kil186.node0
Accept-Encoding: gzip,deflate

HTTP/1.1 200 OK
Date: Fri, 27 Nov 2020 09:29:43 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Agent-Content-MD5: 0aac32f461a96bbb09ea184fb79d867c
Agent-Launcher-Content-MD5: e57a805e01a9bb52f7c28c3e71cbc8f6
Agent-Plugins-Content-MD5: 43071fb6ac29340a578dc98b8db2648d
TFS-SDK-Content-MD5: 41f9103cd19a45a5bcc05a691f950f3f
GoCD-Agent-Extra-Properties: 
Vary: Accept-Encoding, User-Agent
Content-Length: 0
```

But when the GET request is unsuccessful (md5Header is null), it looks like this:
```
GET /go/admin/latest-agent.status HTTP/1.1
Host: 10.0.4.83:8153
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.6 (Java/14.0.2)
Cookie: JSESSIONID=node016o7d7wnstvfg15gx4sx9o5kil186.node0
Accept-Encoding: gzip,deflate

HTTP/1.1 302 Found
Date: Fri, 27 Nov 2020 09:29:53 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Set-Cookie: JSESSIONID=node0zos8pvsv39u11qns0flqa2lb1189.node0; Path=/go; Expires=Fri, 11-Dec-2020 09:29:53 GMT; Max-Age=1209600; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Location: http://10.0.4.83:8153/go/auth/login
Content-Length: 0

GET /go/auth/login HTTP/1.1
Host: 10.0.4.83:8153
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.6 (Java/14.0.2)
Cookie: JSESSIONID=node0zos8pvsv39u11qns0flqa2lb1189.node0
Accept-Encoding: gzip,deflate

HTTP/1.1 200 OK
Date: Fri, 27 Nov 2020 09:29:53 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Cache-Control: max-age=0, private, must-revalidate
X-Runtime: 1
Content-Type: text/html;charset=utf-8
Vary: Accept-Encoding, User-Agent
Content-Encoding: gzip
Transfer-Encoding: chunked
```

So, the cause of an unsuccessful GET is that the server is redirecting us to the login page.

**Comment by maheshp** [comment]
@JeroenOortwijn can you enable debug logs as mentioned in https://github.com/gocd/gocd/issues/4469#issuecomment-566480095 and provide the same. We would need both the server and agent logs around the time you see this issue.

**Comment by JeroenOortwijn** [comment]
The agent log around the exception:
```
2020-11-27 11:29:55,169 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for itself, currentMD5:0aac32f461a96bbb09ea184fb79d867c, responseMD5:Agent-Content-MD5: 0aac32f461a96bbb09ea184fb79d867c, headerKey:Agent-Content-MD5
2020-11-27 11:29:55,169 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for launcher, currentMD5:e57a805e01a9bb52f7c28c3e71cbc8f6, responseMD5:Agent-Launcher-Content-MD5: e57a805e01a9bb52f7c28c3e71cbc8f6, headerKey:Agent-Launcher-Content-MD5
2020-11-27 11:29:55,169 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for plugins, currentMD5:43071fb6ac29340a578dc98b8db2648d, responseMD5:Agent-Plugins-Content-MD5: 43071fb6ac29340a578dc98b8db2648d, headerKey:Agent-Plugins-Content-MD5
2020-11-27 11:29:55,169 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for tfs-impl jar, currentMD5:41f9103cd19a45a5bcc05a691f950f3f, responseMD5:TFS-SDK-Content-MD5: 41f9103cd19a45a5bcc05a691f950f3f, headerKey:TFS-SDK-Content-MD5
2020-11-27 11:30:05,180 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for itself, currentMD5:0aac32f461a96bbb09ea184fb79d867c, responseMD5:Agent-Content-MD5: 0aac32f461a96bbb09ea184fb79d867c, headerKey:Agent-Content-MD5
2020-11-27 11:30:05,180 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for launcher, currentMD5:e57a805e01a9bb52f7c28c3e71cbc8f6, responseMD5:Agent-Launcher-Content-MD5: e57a805e01a9bb52f7c28c3e71cbc8f6, headerKey:Agent-Launcher-Content-MD5
2020-11-27 11:30:05,180 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for plugins, currentMD5:43071fb6ac29340a578dc98b8db2648d, responseMD5:Agent-Plugins-Content-MD5: 43071fb6ac29340a578dc98b8db2648d, headerKey:Agent-Plugins-Content-MD5
2020-11-27 11:30:05,180 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for tfs-impl jar, currentMD5:41f9103cd19a45a5bcc05a691f950f3f, responseMD5:TFS-SDK-Content-MD5: 41f9103cd19a45a5bcc05a691f950f3f, headerKey:TFS-SDK-Content-MD5
2020-11-27 11:30:15,193 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for itself, currentMD5:0aac32f461a96bbb09ea184fb79d867c, responseMD5:null, headerKey:Agent-Content-MD5
2020-11-27 11:30:15,193 DEBUG [scheduler-3] AgentUpgradeService:108 - [Agent Upgrade Validate MD5] Did not find Agent-Content-MD5 MD5 header in response HttpResponseProxy{HTTP/1.1 200 OK [Date: Fri, 27 Nov 2020 11:30:15 GMT, X-XSS-Protection: 1; mode=block, X-Content-Type-Options: nosniff, X-Frame-Options: SAMEORIGIN, X-UA-Compatible: chrome=1, Cache-Control: max-age=0, private, must-revalidate, X-Runtime: 1, Content-Type: text/html;charset=utf-8, Vary: Accept-Encoding, User-Agent, Transfer-Encoding: chunked] org.apache.http.client.entity.DecompressingEntity@71ebe784}.
2020-11-27 11:30:15,193 ERROR [scheduler-3] AgentController:92 - [Agent Loop] Error occurred during loop: 
java.lang.NullPointerException: null
2020-11-27 11:30:25,203 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for itself, currentMD5:0aac32f461a96bbb09ea184fb79d867c, responseMD5:Agent-Content-MD5: 0aac32f461a96bbb09ea184fb79d867c, headerKey:Agent-Content-MD5
2020-11-27 11:30:25,203 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for launcher, currentMD5:e57a805e01a9bb52f7c28c3e71cbc8f6, responseMD5:Agent-Launcher-Content-MD5: e57a805e01a9bb52f7c28c3e71cbc8f6, headerKey:Agent-Launcher-Content-MD5
2020-11-27 11:30:25,203 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for plugins, currentMD5:43071fb6ac29340a578dc98b8db2648d, responseMD5:Agent-Plugins-Content-MD5: 43071fb6ac29340a578dc98b8db2648d, headerKey:Agent-Plugins-Content-MD5
2020-11-27 11:30:25,203 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for tfs-impl jar, currentMD5:41f9103cd19a45a5bcc05a691f950f3f, responseMD5:TFS-SDK-Content-MD5: 41f9103cd19a45a5bcc05a691f950f3f, headerKey:TFS-SDK-Content-MD5
2020-11-27 11:30:35,219 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for itself, currentMD5:0aac32f461a96bbb09ea184fb79d867c, responseMD5:Agent-Content-MD5: 0aac32f461a96bbb09ea184fb79d867c, headerKey:Agent-Content-MD5
2020-11-27 11:30:35,219 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for launcher, currentMD5:e57a805e01a9bb52f7c28c3e71cbc8f6, responseMD5:Agent-Launcher-Content-MD5: e57a805e01a9bb52f7c28c3e71cbc8f6, headerKey:Agent-Launcher-Content-MD5
2020-11-27 11:30:35,219 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for plugins, currentMD5:43071fb6ac29340a578dc98b8db2648d, responseMD5:Agent-Plugins-Content-MD5: 43071fb6ac29340a578dc98b8db2648d, headerKey:Agent-Plugins-Content-MD5
2020-11-27 11:30:35,219 DEBUG [scheduler-3] AgentUpgradeService:106 - [Agent Upgrade Validate MD5] validating MD5 for tfs-impl jar, currentMD5:41f9103cd19a45a5bcc05a691f950f3f, responseMD5:TFS-SDK-Content-MD5: 41f9103cd19a45a5bcc05a691f950f3f, headerKey:TFS-SDK-Content-MD5
```
The exception stack trace is hidden, because the exception has been logged too many times already, but it is always the same (see PR #8771 for the stack trace).

The corresponding server log around the exception:
```
2020-11-27 11:29:55,169 DEBUG [qtp355070094-32] AgentRegistrationController:106 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:0aac32f461a96bbb09ea184fb79d867c], [Agent-Launcher-Content-MD5:e57a805e01a9bb52f7c28c3e71cbc8f6], [Agent-Plugins-Content-MD5:43071fb6ac29340a578dc98b8db2648d], [TFS-SDK-Content-MD5:41f9103cd19a45a5bcc05a691f950f3f]
2020-11-27 11:29:55,767 DEBUG [qtp355070094-32] AgentRegistrationController:106 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:0aac32f461a96bbb09ea184fb79d867c], [Agent-Launcher-Content-MD5:e57a805e01a9bb52f7c28c3e71cbc8f6], [Agent-Plugins-Content-MD5:43071fb6ac29340a578dc98b8db2648d], [TFS-SDK-Content-MD5:41f9103cd19a45a5bcc05a691f950f3f]
2020-11-27 11:30:05,180 DEBUG [qtp355070094-32] AgentRegistrationController:106 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:0aac32f461a96bbb09ea184fb79d867c], [Agent-Launcher-Content-MD5:e57a805e01a9bb52f7c28c3e71cbc8f6], [Agent-Plugins-Content-MD5:43071fb6ac29340a578dc98b8db2648d], [TFS-SDK-Content-MD5:41f9103cd19a45a5bcc05a691f950f3f]
2020-11-27 11:30:15,809 DEBUG [qtp355070094-32] AgentRegistrationController:106 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:0aac32f461a96bbb09ea184fb79d867c], [Agent-Launcher-Content-MD5:e57a805e01a9bb52f7c28c3e71cbc8f6], [Agent-Plugins-Content-MD5:43071fb6ac29340a578dc98b8db2648d], [TFS-SDK-Content-MD5:41f9103cd19a45a5bcc05a691f950f3f]
2020-11-27 11:30:25,204 DEBUG [qtp355070094-33] AgentRegistrationController:106 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:0aac32f461a96bbb09ea184fb79d867c], [Agent-Launcher-Content-MD5:e57a805e01a9bb52f7c28c3e71cbc8f6], [Agent-Plugins-Content-MD5:43071fb6ac29340a578dc98b8db2648d], [TFS-SDK-Content-MD5:41f9103cd19a45a5bcc05a691f950f3f]
2020-11-27 11:30:25,821 DEBUG [qtp355070094-33] AgentRegistrationController:106 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:0aac32f461a96bbb09ea184fb79d867c], [Agent-Launcher-Content-MD5:e57a805e01a9bb52f7c28c3e71cbc8f6], [Agent-Plugins-Content-MD5:43071fb6ac29340a578dc98b8db2648d], [TFS-SDK-Content-MD5:41f9103cd19a45a5bcc05a691f950f3f]
2020-11-27 11:30:35,219 DEBUG [qtp355070094-33] AgentRegistrationController:106 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:0aac32f461a96bbb09ea184fb79d867c], [Agent-Launcher-Content-MD5:e57a805e01a9bb52f7c28c3e71cbc8f6], [Agent-Plugins-Content-MD5:43071fb6ac29340a578dc98b8db2648d], [TFS-SDK-Content-MD5:41f9103cd19a45a5bcc05a691f950f3f]
2020-11-27 11:30:35,847 DEBUG [qtp355070094-32] AgentRegistrationController:106 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:0aac32f461a96bbb09ea184fb79d867c], [Agent-Launcher-Content-MD5:e57a805e01a9bb52f7c28c3e71cbc8f6], [Agent-Plugins-Content-MD5:43071fb6ac29340a578dc98b8db2648d], [TFS-SDK-Content-MD5:41f9103cd19a45a5bcc05a691f950f3f]
```

**Comment by birchb1024** [comment]
Thankyou
