### ISSUE TITLE
[New Dashboard and CCTray] Corner cases

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#4481]
##### Issue Type

- Bug Report

##### Summary

`NullPointerException` because of a pipeline not being in the config when the dashboard looks to update itself.

###### Basic environment details

* Go Version: `18.2.0 (6206-8c392dbb4d743e40ca9940f0d00eccdb5a08cb80)`
* JAVA Version: `1.8.0_144`

##### Steps to Reproduce

Unsure if these are the right steps:

###### Scenario 1:

1. Create a pipeline with a long-running job.
2. Start it.
3. Delete pipeline from config.
4. Once the job completes in the background, you’ll see an exception in the logs like the ones shown below.

###### Scenario 2:

1. Create a pipeline with a long-running job.
2. Start it.
3. Delete **that pipeline group** from config.
4. Once the job completes in the background, you’ll see an exception in the logs like the ones shown below.

##### Expected Results

The dashboard handles this case more gracefully. With a warning in the logs maybe, but not a stack trace.

##### Possible Fix

1. Make `GoConfigPipelinePermissionsAuthority` not use `goConfigService.findGroupByPipeline`. Have the group passed in.

2. Check earlier in the lifecycle for a missing group. Maybe in `GoDashboardService#updateCache`.

##### Log snippets

```
2018-03-02 09:52:40,236 WARN  [CCTray-Queue-Processor] MultiplexingQueueProcessor:68 - Failed to handle action in CCTray queue
java.lang.NullPointerException: null
        at com.thoughtworks.go.config.security.GoConfigPipelinePermissionsAuthority$1.visit(GoConfigPipelinePermissionsAuthority.java:65)
        at com.thoughtworks.go.domain.PipelineGroups.accept(PipelineGroups.java:115)
        at com.thoughtworks.go.config.security.GoConfigPipelinePermissionsAuthority.pipelinesInGroupsAndTheirPermissions(GoConfigPipelinePermissionsAuthority.java:58)
        at com.thoughtworks.go.config.security.GoConfigPipelinePermissionsAuthority.permissionsForPipeline(GoConfigPipelinePermissionsAuthority.java:46)
        at com.thoughtworks.go.domain.cctray.CcTrayConfigChangeHandler.call(CcTrayConfigChangeHandler.java:53)
        at com.thoughtworks.go.domain.cctray.CcTrayActivityListener$5$1.call(CcTrayActivityListener.java:152)
        at com.thoughtworks.go.server.messaging.MultiplexingQueueProcessor$1.run(MultiplexingQueueProcessor.java:63)
```

```
2018-03-02 09:52:40,239 WARN  [Dashboard-Queue-Processor] MultiplexingQueueProcessor:68 - Failed to handle action in Dashboard queue
java.lang.NullPointerException: null
        at com.thoughtworks.go.config.security.GoConfigPipelinePermissionsAuthority$1.visit(GoConfigPipelinePermissionsAuthority.java:65)
        at com.thoughtworks.go.domain.PipelineGroups.accept(PipelineGroups.java:115)
        at com.thoughtworks.go.config.security.GoConfigPipelinePermissionsAuthority.pipelinesInGroupsAndTheirPermissions(GoConfigPipelinePermissionsAuthority.java:58)
        at com.thoughtworks.go.config.security.GoConfigPipelinePermissionsAuthority.permissionsForPipeline(GoConfigPipelinePermissionsAuthority.java:46)
        at com.thoughtworks.go.server.dashboard.GoDashboardCurrentStateLoader.pipelineFor(GoDashboardCurrentStateLoader.java:126)
        at com.thoughtworks.go.server.service.GoDashboardService.updateCache(GoDashboardService.java:127)
        at com.thoughtworks.go.server.service.GoDashboardService.updateCacheForPipeline(GoDashboardService.java:81)
        at com.thoughtworks.go.server.dashboard.GoDashboardConfigChangeHandler.call(GoDashboardConfigChangeHandler.java:36)
        at com.thoughtworks.go.server.dashboard.GoDashboardActivityListener$3$1.call(GoDashboardActivityListener.java:137)
        at com.thoughtworks.go.server.messaging.MultiplexingQueueProcessor$1.run(MultiplexingQueueProcessor.java:63)
```

```
2018-03-02 09:53:06,034 WARN  [Dashboard-Queue-Processor] MultiplexingQueueProcessor:68 - Failed to handle action in Dashboard queue
java.lang.NullPointerException: null
        at com.thoughtworks.go.server.service.GoDashboardService.updateCacheForPipeline(GoDashboardService.java:72)
        at com.thoughtworks.go.server.dashboard.GoDashboardStageStatusChangeHandler.call(GoDashboardStageStatusChangeHandler.java:36)
        at com.thoughtworks.go.server.dashboard.GoDashboardActivityListener$5$1.call(GoDashboardActivityListener.java:175)
        at com.thoughtworks.go.server.messaging.MultiplexingQueueProcessor$1.run(MultiplexingQueueProcessor.java:63)
```

**Comment by tomzo** [comment]
I have just upgraded to `18.3.0` and I see quite a few of these null pointer exceptions when server is starting. For a few minutes it is polling config repos, so there are errors in configuration at the time. There are definitely no new jobs scheduled when this is happening but some are cancelled.

A part of logs:
```
2018-05-01 17:59:14,385 WARN  [Dashboard-Queue-Processor] MultiplexingQueueProcessor:68 - Failed to handle action in Dashboard queue
java.lang.NullPointerException: null
	at com.thoughtworks.go.server.service.GoDashboardService.updateCacheForPipeline(GoDashboardService.java:72)
	at com.thoughtworks.go.server.dashboard.GoDashboardStageStatusChangeHandler.call(GoDashboardStageStatusChangeHandler.java:36)
	at com.thoughtworks.go.server.dashboard.GoDashboardActivityListener$5$1.call(GoDashboardActivityListener.java:175)
	at com.thoughtworks.go.server.messaging.MultiplexingQueueProcessor$1.run(MultiplexingQueueProcessor.java:63)
2018-05-01 17:59:14,388 INFO  [93@MessageListener for ConfigMaterialUpdater] JobInstanceService:194 - cancelling job [JobInstance{stageId=81781, name='cpp-windows-pre-release', state=Scheduled, result=Unknown, agentUuid='null', stateTransitions=[com.thoughtworks.go.domain.JobStateTransition@599ea609[currentState=Scheduled,stateChangeTime=Mon Apr 30 18:26:07 UTC 2018,jobId=112235,stageId=81781,id=645975]], scheduledDate=Mon Apr 30 18:26:07 UTC 2018, timeProvider=com.thoughtworks.go.util.TimeProvider@33017a91, ignored=false, matcher=com.thoughtworks.go.domain.BuildOutputMatcher@74167974, identifier=JobIdentifier[dfit-random-trades.canary, 42, 8314bdf9, build, 1, cpp-windows-pre-release, 112235], plan=null, runOnAllAgents=false, runMultipleInstance=false}]
2018-05-01 17:59:14,489 INFO  [93@MessageListener for ConfigMaterialUpdater] BuildAssignmentService:284 - Successfully removed job plan [JobPlan identifier=JobIdentifier[dfit-random-trades.canary, 42, 8314bdf9, build, 1, cpp-windows-pre-release, 112235]resources=[vs2015] artifactConfigs=[com.thoughtworks.go.domain.ArtifactPlan@afe24e0e, com.thoughtworks.go.domain.ArtifactPlan@b0890437, com.thoughtworks.go.domain.ArtifactPlan@9bb171b3] generators=[]] that no longer exists in the config
2018-05-01 17:59:14,489 WARN  [Dashboard-Queue-Processor] MultiplexingQueueProcessor:68 - Failed to handle action in Dashboard queue
java.lang.NullPointerException: null
	at com.thoughtworks.go.server.service.GoDashboardService.updateCacheForPipeline(GoDashboardService.java:72)
	at com.thoughtworks.go.server.dashboard.GoDashboardStageStatusChangeHandler.call(GoDashboardStageStatusChangeHandler.java:36)
	at com.thoughtworks.go.server.dashboard.GoDashboardActivityListener$5$1.call(GoDashboardActivityListener.java:175)
	at com.thoughtworks.go.server.messaging.MultiplexingQueueProcessor$1.run(MultiplexingQueueProcessor.java:63)
```

**Comment by ketan** [comment]
@arvindsv — I've fixed the parts of the NPEs in the dashboard. Can you take a look at the cctray? The trick seems to be to use the null return value of `goConfigService.findGroupByPipeline(pipelineName)` to understand that the pipeline is removed.

**Comment by akshaydewan** [comment]
Is this fixed? I reproducing this for cctray, but didn't see any errors showing up in the logs.

**Comment by arvindsv** [comment]
@akshaydewan Maybe it is. I'll close it then, if it's no longer reproducible. I didn't see any code changes around this, but maybe a side effect. Anyway, this is not really priority. No one else seems to have come across it recently.
