### ISSUE TITLE
Go server fails to start when there is a special character in a environment variable

### ISSUE THREAD

**Issue by anishvenkat** [gocd/gocd#4639]
##### Issue Type

- Bug Report
##### Summary

Go server fails to start when there was a special character(Â) in an environment variable.

###### Basic environment details

* Go Version: 18.2.0
* JAVA Version: 1.8.0_102
* OS: Windows Server 2012 R2

###### Additional Environment Details

We have checked in the API support logs that the encoding was set to Cp1252.

###### Related ticket
35077 on Zendesk.

##### Expected Results
Go server starts normally

##### Actual Results
Go server fails to start

##### Log snippets

There was a warning regarding loading cruise-config.xml file from the disk. Below is the snippet for the same.
```
2018-04-09 08:40:35,682 WARN  [WrapperJarAppMain] CachedGoConfig:97 - Error loading cruise-config.xml from disk, keeping previous one
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1896)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:253)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1091)
	at com.thoughtworks.go.util.XmlUtils.buildXmlDocument(XmlUtils.java:57)
	at com.thoughtworks.go.util.XmlUtils.buildXmlDocument(XmlUtils.java:46)
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.parseInputStream(MagicalGoConfigXmlLoader.java:157)
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.deserializeConfig(MagicalGoConfigXmlLoader.java:100)
	at com.thoughtworks.go.config.GoFileConfigDataSource.forceLoad(GoFileConfigDataSource.java:181)
	at com.thoughtworks.go.config.GoFileConfigDataSource.load(GoFileConfigDataSource.java:157)
	at com.thoughtworks.go.config.CachedGoConfig.forceReload(CachedGoConfig.java:92)
	at com.thoughtworks.go.config.CachedGoConfig.loadConfigIfNull(CachedGoConfig.java:131)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:108)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:96)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gocd.Boot.run(Boot.java:104)
	at com.thoughtworks.gocd.Boot.main(Boot.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:427)
	at java.lang.Thread.run(Thread.java:745)
```
Error regaring startup of Go server

```
2018-04-09 08:40:36,291 ERROR [WrapperJarAppMain] GoServer:76 - ERROR: Failed to start Go server.
java.lang.RuntimeException: java.lang.RuntimeException: Peer (vm://go-server#1) disposed.
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:149)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:383)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:96)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gocd.Boot.run(Boot.java:104)
	at com.thoughtworks.gocd.Boot.main(Boot.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:427)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Peer (vm://go-server#1) disposed.
	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:36)
	at com.thoughtworks.go.server.messaging.activemq.ActiveMqMessagingService.addListener(ActiveMqMessagingService.java:95)
	at com.thoughtworks.go.server.messaging.GoMessageTopic.addListener(GoMessageTopic.java:39)
	at com.thoughtworks.go.server.service.PipelineScheduler.initialize(PipelineScheduler.java:80)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:126)
	... 43 common frames omitted
Caused by: javax.jms.JMSException: Peer (vm://go-server#1) disposed.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:62)
	at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1267)
	at org.apache.activemq.ActiveMQConnection.asyncSendPacket(ActiveMQConnection.java:1259)
	at org.apache.activemq.ActiveMQSession.<init>(ActiveMQSession.java:250)
	at org.apache.activemq.ActiveMQConnection.createSession(ActiveMQConnection.java:318)
	at com.thoughtworks.go.server.messaging.activemq.ActiveMqMessagingService.addListener(ActiveMqMessagingService.java:91)
	... 46 common frames omitted
Caused by: org.apache.activemq.transport.TransportDisposedIOException: Peer (vm://go-server#1) disposed.
	at org.apache.activemq.transport.vm.VMTransport.oneway(VMTransport.java:89)
	at org.apache.activemq.transport.MutexTransport.oneway(MutexTransport.java:40)
	at org.apache.activemq.transport.ResponseCorrelator.oneway(ResponseCorrelator.java:60)
	at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1265)
	... 50 common frames omitted
```

**Comment by ketan** [comment]
@adityasood — mind taking a look to see if this is still reproducible?

**Comment by adityasood** [comment]
@ketan this is still reproducible in 18.8.0 and 18.10.0.

**Comment by akshaydewan** [comment]
What are the steps to reproduce this? I tried a few things but wasn't able to reproduce it.

**Comment by adityasood** [comment]
@akshaydewan did you try this on a windows box with encodind set as cp1252?

**Comment by akshaydewan** [comment]
I tried it on MacOS and changed the file.encoding to cp1252. It's a Windows specific bug, right?

**Comment by adityasood** [comment]
@akshaydewan the report says it was tried on that and the ticket mentioned also has the same OS, I remember trying it on windows and never on mac.
