### ISSUE TITLE
500 page when rendering VSM

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4784]
##### Issue Type

- Bug Report

##### Summary

When visiting [this VSM](https://build.gocd.org/go/materials/value_stream_map/caef7f8c7e79ac4acdc4e41c1a0aafc7fbd2ef0ff8cf0a18371457b7c5aa0757/3b9e61c5f690336203eb37a86f2fca821d5a7fe2) page, I see a 500 page with this error in the log:

```
2018-05-25 06:18:27,490 ERROR [qtp777113684-3954142] Rails:-2 -
NameError (no method 'getValueStreamMap' for arguments (com.thoughtworks.go.config.CaseInsensitiveString,org.jruby.RubyString,com.thoughtworks.go.server.domain.Username,com.thoughtworks.go.server.service.result.HttpLocalizedOperationResult) on Java::ComThoughtworksGoServerService::ValueStreamMapService
  available overloads:
    (com.thoughtworks.go.config.CaseInsensitiveString,int,com.thoughtworks.go.server.domain.Username,com.thoughtworks.go.server.service.result.LocalizedOperationResult)
    (java.lang.String,java.lang.String,com.thoughtworks.go.server.domain.Username,com.thoughtworks.go.server.service.result.LocalizedOperationResult)):
  app/controllers/value_stream_map_controller.rb:56:in `generate_material_vsm_json'
  app/controllers/value_stream_map_controller.rb:37:in `show_material'
  app/controllers/value_stream_map_controller.rb:35:in `show_material'
  lib/jetty_weak_etag_middleware.rb:35:in `call'
  lib/catch_json_parse_errors.rb:23:in `call'
```

**Comment by ketan** [comment]
Closed via #4773
