### ISSUE TITLE
Reprovisioning a go-agent triggers a NullPointerException in the server when registering

### ISSUE THREAD

**Issue by cburgmer** [gocd/gocd#4860]
##### Issue Type

- Bug Report

##### Summary

Re-installed a go-agent will fail registration with the server, triggering a NullPointerException.

###### Basic environment details

* Go Server Version: `18.1.0 (5937-8a847b96ee8d38173f80178ed1285f0e53a970e0)`
* Go Agent Version: `18.1.0`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.9.91-40.57.amzn1.x86_64`

##### Steps to Reproduce

1. (optional) Disable and remove the agent on the agent page of the server
2. Re-install and start agent
3. Server shows that it has lost connection to the agent.

##### Actual Results
Go Agent logs show 503 error with an HTML page as result.

Go Server logs shows
```
2018-06-18 13:50:49,672 INFO  [qtp852687460-26] AgentRegistrationController:223 - [Agent Auto Registration] Auto registering agent with uuid eb130ac8-c54c-4d3a-98b2-95c3e8c6172b
2018-06-18 13:50:49,672 INFO  [qtp852687460-26] AgentRegistrationController:246 - [Agent Auto Registration] Auto registering agent with uuid eb130ac8-c54c-4d3a-98b2-95c3e8c6172b
2018-06-18 13:50:49,672 INFO  [qtp852687460-26] GoConfigDao:91 - Config update for entity request by com.thoughtworks.go.server.domain.Username@77415d84[displayName=agent_eb130ac8-c54c-4d3a-98b2-95c3e8c6172b_10.0.10.1_MY_AGENT_NAME,usern
ame=agent_eb130ac8-c54c-4d3a-98b2-95c3e8c6172b_10.0.10.1_MY_AGENT_NAME] is in queue - com.thoughtworks.go.config.update.AgentsUpdateCommand@1150b255
2018-06-18 13:50:49,673 INFO  [qtp852687460-26] GoConfigDao:94 - Config update for entity request by com.thoughtworks.go.server.domain.Username@77415d84[displayName=agent_eb130ac8-c54c-4d3a-98b2-95c3e8c6172b_10.0.10.1_MY_AGENT_NAME,usern
ame=agent_eb130ac8-c54c-4d3a-98b2-95c3e8c6172b_10.0.10.1_MY_AGENT_NAME] is being processed
2018-06-18 13:50:49,685 WARN  [qtp852687460-26] UpdateEnvironmentsCommand:45 - [Agent Auto Registration] Agent with uuid eb130ac8-c54c-4d3a-98b2-95c3e8c6172b could not be assigned to environment  as it does not exist.
2018-06-18 13:50:49,716 INFO  [qtp852687460-26] GoFileConfigDataSource:307 - [Configuration Changed] Saving updated configuration.
2018-06-18 13:50:51,228 ERROR [qtp852687460-26] GoConfigDao:100 - Config update for entity failed
java.lang.RuntimeException: failed to save : Duplicate unique value [eb130ac8-c54c-4d3a-98b2-95c3e8c6172b] declared for identity constraint of element "agents".
	at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingEntity(GoFileConfigDataSource.java:324)
	at com.thoughtworks.go.config.GoFileConfigDataSource.writeEntityWithLock(GoFileConfigDataSource.java:268)
	at com.thoughtworks.go.config.CachedGoConfig.writeEntityWithLock(CachedGoConfig.java:157)
	at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:98)
	at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:264)
	at com.thoughtworks.go.server.service.AgentConfigService.updateAgents(AgentConfigService.java:130)
	at com.thoughtworks.go.server.service.AgentConfigService.updateAgent(AgentConfigService.java:140)
	at com.thoughtworks.go.server.controller.AgentRegistrationController.agentRequest(AgentRegistrationController.java:253)
	at sun.reflect.GeneratedMethodAccessor725.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:359)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.web.FlashLoadingFilter.doFilter(FlashLoadingFilter.java:43)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.SessionFixationProtectionFilter.doFilterHttp(SessionFixationProtectionFilter.java:67)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.DenyGoCDAccessForArtifactsFilter.doFilterHttp(DenyGoCDAccessForArtifactsFilter.java:44)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.providers.anonymous.AnonymousProcessingFilter.doFilterHttp(AnonymousProcessingFilter.java:105)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.UserEnabledCheckFilter.doFilterHttp(UserEnabledCheckFilter.java:64)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.ReAuthenticationFilter.doFilterHttp(ReAuthenticationFilter.java:47)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:173)
	at com.thoughtworks.go.server.security.BasicAuthenticationFilter.doFilterHttp(BasicAuthenticationFilter.java:62)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.WebBasedAuthenticationFilter.doFilterHttp(WebBasedAuthenticationFilter.java:61)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.OauthAuthenticationFilter.doFilterHttp(OauthAuthenticationFilter.java:61)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.RemoveAdminPermissionFilter.doFilterHttp(RemoveAdminPermissionFilter.java:76)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.DisallowExternalReAuthenticationFilter.doFilterHttp(DisallowExternalReAuthenticationFilter.java:44)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
	at com.thoughtworks.go.server.security.GoLogoutFilter.doFilterHttp(GoLogoutFilter.java:48)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.ModeAwareFilter.doFilter(ModeAwareFilter.java:49)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:174)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.thoughtworks.go.server.web.BackupFilter.doFilter(BackupFilter.java:86)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
2018-06-18 13:50:51,228 INFO  [qtp852687460-26] GoConfigDao:104 - Entity update for request by com.thoughtworks.go.server.domain.Username@77415d84[displayName=agent_eb130ac8-c54c-4d3a-98b2-95c3e8c6172b_10.0.10.1_MY_AGENT_NAME,username=ag
ent_eb130ac8-c54c-4d3a-98b2-95c3e8c6172b_10.0.10.1_MY_AGENT_NAME] is completed
2018-06-18 13:50:51,229 ERROR [qtp852687460-26] AgentRegistrationController:280 - Error occurred during agent registration process:
com.thoughtworks.go.config.exceptions.GoConfigInvalidException: Updating agent failed: failed to save : Duplicate unique value [eb130ac8-c54c-4d3a-98b2-95c3e8c6172b] declared for identity constraint of element "agents".

	at com.thoughtworks.go.server.controller.AgentRegistrationController.agentRequest(AgentRegistrationController.java:261)
	at sun.reflect.GeneratedMethodAccessor725.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:359)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.web.FlashLoadingFilter.doFilter(FlashLoadingFilter.java:43)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.SessionFixationProtectionFilter.doFilterHttp(SessionFixationProtectionFilter.java:67)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.DenyGoCDAccessForArtifactsFilter.doFilterHttp(DenyGoCDAccessForArtifactsFilter.java:44)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.providers.anonymous.AnonymousProcessingFilter.doFilterHttp(AnonymousProcessingFilter.java:105)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.UserEnabledCheckFilter.doFilterHttp(UserEnabledCheckFilter.java:64)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.ReAuthenticationFilter.doFilterHttp(ReAuthenticationFilter.java:47)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.basicauth.BasicProcessingFilter.doFilterHttp(BasicProcessingFilter.java:173)
	at com.thoughtworks.go.server.security.BasicAuthenticationFilter.doFilterHttp(BasicAuthenticationFilter.java:62)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.AbstractProcessingFilter.doFilterHttp(AbstractProcessingFilter.java:271)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.WebBasedAuthenticationFilter.doFilterHttp(WebBasedAuthenticationFilter.java:61)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.OauthAuthenticationFilter.doFilterHttp(OauthAuthenticationFilter.java:61)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.RemoveAdminPermissionFilter.doFilterHttp(RemoveAdminPermissionFilter.java:76)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.DisallowExternalReAuthenticationFilter.doFilterHttp(DisallowExternalReAuthenticationFilter.java:44)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
	at com.thoughtworks.go.server.security.GoLogoutFilter.doFilterHttp(GoLogoutFilter.java:48)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.web.i18n.LocaleResolver.doFilter(LocaleResolver.java:41)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at com.thoughtworks.go.server.security.ModeAwareFilter.doFilter(ModeAwareFilter.java:49)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:371)
	at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:174)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.thoughtworks.go.server.web.BackupFilter.doFilter(BackupFilter.java:86)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
2018-06-18 13:50:51,229 ERROR [qtp852687460-26] BasicAuthenticationFilter:64 - org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
```

**Comment by arvindsv** [comment]
@cburgmer We should make the agent show a better message than NullPointerException, but it *looks like* it is happening because the server is failing to register the agent, because another agent with the same UUID exists.

Are you trying to clone an agent? If so, you'll need to remove the config/ directory (or at least the guid file in there). This [doc page](https://docs.gocd.org/current/faq/agent_guid_issue.html) talks about it a bit more.

Do you think that is what's happening in this case?

**Comment by arvindsv** [comment]
Ugh. Sorry. I see you mentioned "Steps to reproduce". I'll think about it.

**Comment by cburgmer** [comment]
I currently feel I can't share our setup process verbatim, because of typical IP concerns. I can however try to answer more detailed what is done on provisioning. From a first view it seems rather straightforward:

1. Install .deb file
2. Provide basic config
3. Remove /var/lib/go-agent/config/agent.jks
4. Write `agent.auto.register.key` and `agent.auto.register.resources` in /var/lib/go-agent/config/autoregister.properties

The workaround for now seems to be to disable and remove the agent from the list of agents, and wait for the autoconnect to re-establish connection a few seconds later.

Agree on the "better error" in the case it's actually a user error.

If it seems like the same UUID is being re-used for the new process, may I ask how this is constructed?

**Comment by arvindsv** [comment]
@cburgmer The UUID is in a file called guid.txt. Right next to the agent.jks file.

In step 3, can you try to remove the whole config/ directory? The config/ directory has `agent.jks`, `guid.txt` and `token`. Try starting with an empty config/ directory, with only the `autoregister.properties` file.

Without the `guid.txt` and `token` files, there should be no hint of the fact that this agent was a valid agent at a previous time.

**Comment by cburgmer** [comment]
I've changed the provisioning, and it does not break things for now. However I cannot reproduce the auto registration in the logs for now, so I can't definitely say it fixes the issue. (I can't see any AgentRegistrationController in the server log, nor does the agent log produce new entries.)

**Comment by arvindsv** [comment]
@cburgmer So, are you saying it is auto-registering, but doesn't show up in any logs? Or, does it not auto-register at all?

**Comment by cburgmer** [comment]
The former, auto-registring, no logs. I did try twice. This might me be doing something different today, or our logs not behaving correctly.

**Comment by cburgmer** [comment]
We just realised, that the fix for this issue described here, actually broke the deletion of the `config/` dir, so instead of partially deleting it (as before) we just kept the exact directory copy around. This somehow made this issue disappear just failed today when we rolled out a new GoCD version with new certificates (the old `agent.jks` stuck around and didn't work with the newest certificates from 18.6).

Obviously we would prefer immutable infra, but we currently have a few agents that still retain old state that just gets overridden by ansible provisioning. My expectation would be that installing a new .deb for the agent should make sure that it can work with old config, so maybe we could change this issue into something along the lines of dealing with old config, especially the one that the GoCD agent autowires (e.g. `agent.jks`). Currently our workaround is, as suggested by you, to nuke the `config/` dir.

**Comment by arvindsv** [comment]
@cburgmer If an existing `config/` directory is present, and the server knows about that agent, I don't see why reinstalling the agent and changing nothing else makes it break. If that's what you're seeing, I agree that it shouldn't. You shouldn't have to remove the agent from the server and delete `config/` unless you want to.

**Comment by arvindsv** [comment]
> ... when we rolled out a new GoCD version with new certificates ...

I see. Maybe this is all because of that. If you change the server certificates, the agent will continue to use the known/old `agent.jks` and that's by design, so that a man-in-the-middle attack is less likely to succeed.

I suspect I'm not understanding your scenario completely, if that's not it. :)
