### ISSUE TITLE
Template read-only view throws error when external artifacts is configured

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#4903]
##### Issue Type

- Bug Report

##### Summary

Templates readonly view throws error when  external artifact is configured

###### Basic environment details

* Go Version: `18.7.0 (6990-a4e86591253b2b689af07cf6c98d9babb6d41b5b)`
* Docker registry external artifact plugin - `0.0.1-41`

##### Steps to Reproduce

1. Create a template with External publish artifacts configured
2. Assoiciate the template with a pipeline
3. Goto pipeline edit page and click on the magnify glass button near template name for readonly view of the template
4. Application returns 500 error and below exception in the server logs,

```
2018-07-03 10:50:21,498 ERROR [qtp1205555397-29] Rails:-2 -
ActionView::Template::Error (undefined method `getSource' for #<Java::ComThoughtworksGoConfig::PluggableArtifactConfig:0x24d78dcb>):
    204:             <% scope[:job].artifactConfigs().each do |artifact_config| %>
    205:                 <tr>
    206:                     <td class="name_value_cell">
    207:                         <%= artifact_config.getSource() %>
    208:                     </td>
    209:                     <td class="name_value_cell">
    210:                         <%= artifact_config.getDestination() %>
  app/views/config_view/templates/show.html.erb:207:in `_app_views_config_view_templates_show_html_erb__264450968_130044'
  app/views/config_view/templates/show.html.erb:204:in `_app_views_config_view_templates_show_html_erb__264450968_130044'
  app/views/config_view/templates/show.html.erb:140:in `_app_views_config_view_templates_show_html_erb__264450968_130044'
  app/views/config_view/templates/show.html.erb:22:in `_app_views_config_view_templates_show_html_erb__264450968_130044'
  lib/jetty_weak_etag_middleware.rb:35:in `call'
  lib/catch_json_parse_errors.rb:23:in `call'
```

##### Expected Results

Template read-only view should be displayed

**Comment by rajiesh** [comment]
Verified on 18.7.0 (7107-ca37138fb0de89afb2f607cb57de22478550f8ac)
