### ISSUE TITLE
Linux version 18.6.0 fails to upgrade version 16.2.1 Windows configuration

### ISSUE THREAD

**Issue by denis-troller** [gocd/gocd#4939]
##### Issue Type

- Bug Report

##### Summary

Restoring a backup taken from a Windows 16.2.1 GoCD server on a fresh 18.6.0 Ubuntu GoCD install leads to a failure to upgrade the configuration and to start the server.

###### Basic environment details

* Go Version: 18.6.0-6883
* JAVA Version:  openjdk version 1.8.0_171
* OS: Ubuntu Linux 16.04

##### Steps to Reproduce

1. Perform a backup of a v16.2.1 GoCD server running under Windows 7
2. Perform the installation of GoCD on ubuntu according to the documentation using apt
3. copy backup/config-dir/ contents to /etc/go/
4. copy backup/db/ contents to /var/lib/go-server/db/h2db/
5. copy backup/config-repo/ contents to /var/lib/db/config.git
6. update all new files and directories to have go:go ownership
7. start server using sudo /etc/init.d/go-server start

##### Expected Results

The server should migrate the configuration and start.

##### Actual Results

The server fails to start (see logs).

##### Possible Fix

No idea

##### Log snippets

```
2018-07-10 23:05:53,187 INFO  [main] ConfigCipherUpdater:71 - Found unsafe cipher 64d04c1676ce2085 on server, Go will make an attempt to rekey
2018-07-10 23:05:53,195 INFO  [main] ConfigCipherUpdater:73 - Old cipher was successfully backed up to /etc/go/cipher.original.2018-07-10-23-05-53
2018-07-10 23:05:53,204 INFO  [main] ConfigCipherUpdater:75 - Old config was successfully backed up to /etc/go/cruise-config.xml.original.2018-07-10-23-05-53
2018-07-10 23:05:53,212 INFO  [main] CipherProvider:64 - Cipher not found. Creating a new cipher file
2018-07-10 23:05:53,356 ERROR [main] ConfigCipherUpdater:114 - Re-keying of cipher failed with error: [Input byte array has incorrect ending byte at 24]
java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 24
	at java.util.Base64$Decoder.decode0(Base64.java:742)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.thoughtworks.go.security.GoCipher.decipher(GoCipher.java:64)
	at com.thoughtworks.go.config.ConfigCipherUpdater.reEncryptUsingNewKey(ConfigCipherUpdater.java:128)
	at com.thoughtworks.go.config.ConfigCipherUpdater.migrate(ConfigCipherUpdater.java:97)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:105)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1515)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1477)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:273)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:126)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gocd.Boot.run(Boot.java:111)
	at com.thoughtworks.gocd.Boot.main(Boot.java:57)
018-07-10 23:05:53,380 ERROR [Thread-78] PluginSettingsMetadataLoader:64 - Failed to fetch plugin settings metadata for plugin cd.go.authentication.ldap. Maybe the plugin does not implement plugin settings and view?
2018-07-10 23:05:53,380 ERROR [Thread-78] PluginSettingsMetadataLoader:65 - Plugin: cd.go.authentication.ldap - Metadata load info: [{extension='authorization', configuration='null', view='null', error='Interaction with plugin with id 'cd.go.authentication.ldap' implementing 'authorization' extension failed while requesting for 'go.plugin-settings.get-configuration'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-configuration is not supported by plugin.']'}]
2018-07-10 23:05:53,411 INFO  [main] GoConfigMigration:209 - Upgrading config file from version 78 to version 108
2018-07-10 23:05:54,032 ERROR [Thread-78] PluginSettingsMetadataLoader:64 - Failed to fetch plugin settings metadata for plugin yum. Maybe the plugin does not implement plugin settings and view?
2018-07-10 23:05:54,032 ERROR [Thread-78] PluginSettingsMetadataLoader:65 - Plugin: yum - Metadata load info: [{extension='package-repository', configuration='null', view='null', error='Interaction with plugin with id 'yum' implementing 'package-repository' extension failed while requesting for 'go.plugin-settings.get-configuration'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '400' and the following response: 'Invalid request name go.plugin-settings.get-configuration']'}]
2018-07-10 23:05:54,080 ERROR [Thread-78] PluginInfoBuilder:55 - Failed to fetch Plugin Settings metadata for plugin yum. Maybe the plugin does not implement plugin settings and view?
2018-07-10 23:05:54,278 ERROR [Thread-78] PluginSettingsMetadataLoader:64 - Failed to fetch plugin settings metadata for plugin cd.go.authentication.passwordfile. Maybe the plugin does not implement plugin settings and view?
2018-07-10 23:05:54,279 ERROR [Thread-78] PluginSettingsMetadataLoader:65 - Plugin: cd.go.authentication.passwordfile - Metadata load info: [{extension='authorization', configuration='null', view='null', error='Interaction with plugin with id 'cd.go.authentication.passwordfile' implementing 'authorization' extension failed while requesting for 'go.plugin-settings.get-configuration'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-configuration is not supported by plugin.']'}]
2018-07-10 23:05:54,658 INFO  [main] GoConfigMigration:217 - Finished upgrading config file
2018-07-10 23:05:54,658 INFO  [main] GoConfigMigrator:101 - [Config Save] Starting Config Save post upgrade using FullConfigSaveNormalFlow
2018-07-10 23:05:54,958 WARN  [main] GoConfigMigrator:93 - Error upgrading config file, trying to upgrade using the versioned config file.
2018-07-10 23:05:54,977 INFO  [main] GoConfigMigration:195 - Config file is backed up, location: /etc/go/cruise-config.xml.invalid.2018-07-10-23-05-54
2018-07-10 23:05:54,987 WARN  [main] GoConfigMigrator:132 - Go encountered an invalid configuration file while starting up. The invalid configuration file has been renamed to ‘/etc/go/cruise-config.xml.invalid.2018-07-10-23-05-54’ and a new configuration file has been automatically created using the last good configuration. Cause: 'Encrypted value for property with key 'Password' is invalid. This usually happens when the cipher text is modified to have an invalid value.'
2018-07-10 23:05:54,990 INFO  [main] GoConfigMigration:209 - Upgrading config file from version 78 to version 108
2018-07-10 23:05:55,469 INFO  [main] GoConfigMigration:217 - Finished upgrading config file
2018-07-10 23:05:55,469 INFO  [main] GoConfigMigrator:101 - [Config Save] Starting Config Save post upgrade using FullConfigSaveNormalFlow
2018-07-10 23:05:55,602 WARN  [main] GoConfigMigrator:121 - The versioned config file could be invalid or migrating the versioned config resulted in an invalid configuration
2018-07-10 23:05:55,603 ERROR [main] GoConfigMigrator:80 - There are errors in the Cruise config file.  Please read the error message and correct the errors.
Once fixed, please restart Cruise.
Error: Encrypted value for property with key 'Password' is invalid. This usually happens when the cipher text is modified to have an invalid value.
2018-07-10 23:05:55,604 INFO  [main] GoFileConfigDataSource:148 - Config file changed at 1531256754000
2018-07-10 23:05:55,604 INFO  [main] GoFileConfigDataSource:149 - Reloading config file: /etc/go/cruise-config.xml
2018-07-10 23:05:55,644 WARN  [main] CachedGoConfig:97 - Error loading cruise-config.xml from disk, keeping previous one
com.thoughtworks.go.util.XsdValidationException: Value '78' of attribute 'schemaVersion' of element 'cruise' is not valid with respect to the corresponding attribute use. Attribute 'schemaVersion' has a fixed value of '108'.
	at com.thoughtworks.go.util.XmlUtils.buildXmlDocument(XmlUtils.java:59)
	at com.thoughtworks.go.util.XmlUtils.buildXmlDocument(XmlUtils.java:46)
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.parseInputStream(MagicalGoConfigXmlLoader.java:156)
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.deserializeConfig(MagicalGoConfigXmlLoader.java:99)
	at com.thoughtworks.go.config.GoFileConfigDataSource.forceLoad(GoFileConfigDataSource.java:177)
	at com.thoughtworks.go.config.GoFileConfigDataSource.load(GoFileConfigDataSource.java:153)
	at com.thoughtworks.go.config.CachedGoConfig.forceReload(CachedGoConfig.java:92)
	at com.thoughtworks.go.config.CachedGoConfig.loadConfigIfNull(CachedGoConfig.java:131)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:109)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1515)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1477)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:273)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:126)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gocd.Boot.run(Boot.java:111)
	at com.thoughtworks.gocd.Boot.main(Boot.java:57)

```

**Comment by arvindsv** [comment]
This could be due to different line endings between Windows and Linux. @denis-troller Is this still blocking you?

**Comment by denis-troller** [comment]
Thanks @arvindsv.

This is still blocking me. I wanted to upgrade GoCD and migrate to a Linux VM at the same time but I a now stuck to 16.2 as a result. I tried the same with the oldest version available (17.5.0) and, if the messages are a bit different because Go does not attempt to do anyhting beyond failing on the cipher, it seems to fail with the same problem.

On the line-endings front, I don't think this is it. the Cipher file does not contain any line ending on the windows side.
I tried 
- original files -> the error is as logged
- modify the cipher file with nano with an additional LF -> same error

Any clue ?

**Comment by denis-troller** [comment]
Well, I got it working finally by thinking a bit more about it.
I deleted /etc/go/cipher and edited the whole cruise-config.xml file to remove encrypted passwords and replace them with non encrypted versions. After that Go finally accepted to start and load the whole pipeline definition.

At least this is a work-around IF you happen to know all the passwords in the configuration...

**Comment by ketan** [comment]
> Steps to Reproduce
> 1. Perform a backup of a v16.2.1 GoCD server running under Windows 7
> 2. Perform the installation of GoCD on ubuntu according to the documentation using apt
> 3. copy backup/config-dir/ contents to /etc/go/
> 4. copy backup/db/ contents to /var/lib/go-server/db/h2db/
> 5. copy backup/config-repo/ contents to /var/lib/db/config.git
> 6. update all new files and directories to have go:go ownership
> 7. start server using sudo /etc/init.d/go-server start

I just want to make sure I understand this properly:
- When installing on ubuntu — did you install the latest version (18.6), if not version 18.6, then what version of go-server did you install on ubuntu
- When restoring the config dir, did you make sure to restore the `cruise-config.xml` and `cipher` files
- When performing the restore, did you ensure that the go-server was not running

If the answer to these questions is yes — We suspect that there are possibly some encrypted values in the config that can possibly not be encrypted (likely because of a typo). We'd like to help verify that this is not the case. Would you be willing to share a copy the config dir backup for us to look at? Please send it to `support [at] thoughtworks.com` with a link to this issue and we'll see what we can do.

Thanks

**Comment by denis-troller** [comment]
@ketan : Yes, you understand correctly. I backed up a v16.2.1 server running on windows and used the backed-up files to restore, as per the steps listed in the GoCD documentation, on a v 18.6.0 server on ubuntu, before starting the server.

As stated above, I finally managed to get it to load my cruise-config by, after restoring all the files but befroe starting the server:
- manually editing the file and replacing all encryptedPassword attributes with pasword attributes with their original value (luckily I know all of them).
- Deleting the cipher file 
- starting the server

I will email a copy of the config-dir archive to you for further investigation.

Thanks for your time.

**Comment by ketan** [comment]
There are a few of reasons why this failed:

- one of the `encryptedPassword` attributes ends with a `===`. This is technically an invalid base64 encoded string. However the library we were using to decode commons-codec suffered from [this bug](https://issues.apache.org/jira/browse/CODEC-134) so it was never caught.

- Somewhere around 17.2, we made a [this change](https://github.com/gocd/gocd/commit/58ec5b6989bdfe65f69ec1210d8be83c237d56fe#diff-09fc9cc2bbe55c445f3750cbea964a8aR58) which basically uses the JVM provided base64 library.

- The jvm provided base64 library is a lot more standards compliant — and so it throws up with an exception when it fails decoding that particular string.

- Here is a sample program to demonstrate the issue:

```java
    public static void main(String[] args) {
        String encryptedPassword = "C5CYMIHWQUUZMKUGZHGEOSJSQDE4L===";
        byte[] bytes = org.apache.commons.codec.binary.Base64.decodeBase64(encryptedPassword);
        java.util.Base64.getDecoder().decode(encryptedPassword);
    }
```

The error thrown is:

```
Exception in thread "main" java.lang.IllegalArgumentException: Last unit does not have enough valid bits
	at java.util.Base64$Decoder.decode0(Base64.java:734)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.thoughtworks.go.server.DevelopmentServer.main(DevelopmentServer.java:47)
```

**Comment by ketan** [comment]
It's possible that the bad encrypted password was a result of a typo. It should be possible to see when and who changed the particular line by running a `git blame cruise-config.xml` command on the [config.git rep](https://api.gocd.org/current/#clone-the-configuration-repository).

For now, I'm going to mark this issue as closed. But if you have any further questions, I'm happy to answer.
