### ISSUE TITLE
Error executing request 'go.plugin-settings.get-configuration' while the Plugin shouldn't need to respond to this request

### ISSUE THREAD

**Issue by Diogomrol** [gocd/gocd#4994]
##### Issue Type
- Documentation Report
- Bug?

##### Summary

I'm currently developing an Artifact plugin and I'm getting an error logged when loading the plugin:

Error while executing request go.plugin-settings.get-configuration
java.lang.NullPointerException: null

If I missed nothing I guess that the documentation doesn't mention that I need to implement a response to this request.

Am I right? Is this some kind of bug / documentation issue? Or did I miss something?

Thanks in advance.

Cheers,
Diogo

**Comment by akshaydewan** [comment]
Hi Diogo,

I believe the log message you're seeing is normal, and the plugin should continue to load after that. I checked the Docker Registry Artifact plugin and the Debian Repository Poller plugin. Neither of them implement the `get-configuration` request, and I see the same log message. But the plugins continue to load and work as expected.

But the log message does act as a red-herring and may confuse plugin developers. I'm thinking of changing the severity to `INFO` or `WARN` instead of `ERROR`. @bdpiparva WDYT?

**Comment by ketan** [comment]
> I'm thinking of changing the severity to INFO or WARN instead of ERROR.

Along with a message disclaimer to the effect "not all plugins are required to implement this message/this error may be safe to ignore".

**Comment by Diogomrol** [comment]
Hi,

I thought so, that this would be something not mandatory to be implemented.

I will ignore that error then.

But I do agree with you: showing it like an error causes some confusion. Could the error message be improved somehow? :)

Thanks for your help!

**Comment by ketan** [comment]
@adityasood @rahulpargaonkar — could one of you test and close this?

**Comment by rahulpargaonkar** [comment]
I have tested the issue with latest go-server version i.e go-server-18.8.0-7365 & docker-registry-artifact-plugin-1.0.0-47. Now the Warning messages is logged instead of error Message:

```
2018-08-29 16:26:32,611 WARN  [Thread-78] PluginSettingsMetadataLoader:64 - Failed to fetch plugin settings metadata for plugin cd.go.artifact.docker.registry. Maybe the plugin does not implement plugin settings and view?
2018-08-29 16:26:32,611 WARN  [Thread-78] PluginSettingsMetadataLoader:65 - Plugin: cd.go.artifact.docker.registry - Metadata load info: [{extension='artifact', configuration='null', view='null', error='Interaction with plugin with id 'cd.go.artifact.docker.registry' implementing 'artifact' extension failed while requesting for 'go.plugin-settings.get-configuration'. Reason: [java.lang.NullPointerException]'}]
2018-08-29 16:26:32,611 WARN  [Thread-78] PluginSettingsMetadataLoader:66 - Not all plugins are required to implement the request above. This error may be safe to ignore.
```

**Comment by manojtr** [comment]
I still see this

Version: 19.11,  using offical docker image from gocd


```
jvm 1    | 2019-12-12 11:55:27,139 ERROR [Thread-80] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:127 [plugin-cd.go.contrib.elasticagent.kubernetes] - Failed to handle request go.plugin-settings.get-configuration
jvm 1    | java.lang.NullPointerException: null
jvm 1    | 	at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:62)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
jvm 1    | 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
jvm 1    | 	at com.thoughtworks.go.plugin.access.common.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:56)
jvm 1    | 	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.lambda$findSettingsAndViewOfAllExtensionsIn$2(PluginSettingsMetadataLoader.java:84)
jvm 1    | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
jvm 1    | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
jvm 1    | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
jvm 1    | 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
jvm 1    | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
jvm 1    | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
jvm 1    | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
jvm 1    | 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
jvm 1    | 	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.findSettingsAndViewOfAllExtensionsIn(PluginSettingsMetadataLoader.java:89)
jvm 1    | 	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:59)
jvm 1    | 	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:49)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.PluginLoader.lambda$doPostBundleInstallActivities$0(PluginLoader.java:114)
jvm 1    | 	at org.apache.commons.collections4.IteratorUtils.forEach(IteratorUtils.java:1224)
jvm 1    | 	at org.apache.commons.collections4.IterableUtils.forEach(IterableUtils.java:585)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.PluginLoader.lambda$doPostBundleInstallActivities$1(PluginLoader.java:114)
jvm 1    | 	at org.apache.commons.collections4.IteratorUtils.forEach(IteratorUtils.java:1224)
jvm 1    | 	at org.apache.commons.collections4.IterableUtils.forEach(IterableUtils.java:585)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.PluginLoader.doPostBundleInstallActivities(PluginLoader.java:113)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.PluginLoader.loadPlugin(PluginLoader.java:71)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:162)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:105)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:69)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.lambda$pluginJarAdded$0(DefaultPluginJarLocationMonitor.java:237)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:258)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:237)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.monitor.PluginChangeNotifier.lambda$notify$0(PluginChangeNotifier.java:34)
jvm 1    | 	at java.base/java.lang.Iterable.forEach(Unknown Source)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.monitor.PluginChangeNotifier.notify(PluginChangeNotifier.java:31)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:204)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:192)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:177)
```

**Comment by manojtr** [comment]
another one
```
jvm 1    | 2019-12-12 11:55:17,161 ERROR [Thread-80] p.c.g.a.l.c.g.a.l.LdapPlugin:127 [plugin-cd.go.authentication.ldap] - Error while executing request go.plugin-settings.get-configuration
jvm 1    | com.thoughtworks.go.plugin.api.exceptions.UnhandledRequestTypeException: This is an invalid request type :go.plugin-settings.get-configuration
```

**Comment by sbussard** [comment]
I agree with this sentiment, can we do anything but ignore these errors? 
Elastic agents (k8s pods) are not launching for me and I'm trying to figure out why. Having a bunch of errors is a huge distraction
