### ISSUE TITLE
Using SSO proxy with basic auth causes CSRF errors in the GUI

### ISSUE THREAD

**Issue by sandro-h** [gocd/gocd#4997]
##### Issue Type

- Bug Report

##### Summary

We have a reverse proxy in front of GoCD (and other apps) that provides Single Sign-On. In the case of GoCD, the proxy does this by simply appending a basic auth Authorization header to the requests forwarded to the GoCD server.

In previous versions this worked fine, but since upgrading from 18.3 to 18.6 we are experiencing issues when performing changes in the GUI.
We receive "The change you wanted was rejected." errors when editing the config xml or any pipeline, for example.
The server log (see below) shows that the CSRF token cannot be validated.

After some digging, I'm fairly certain this is due to a change in session management which will recreate the session when the Authorization header is set, even if there is still a valid ongoing session (see Possible Fix section).

###### Basic environment details

* Go Version: 18.6.0 (6883-1013a67ccf0cda9c87e6361286708b584be42338)
* JAVA Version: 1.8.0_111
* OS: Linux 3.10.0-514.6.1.el7.x86_64
* Browser vendor and version (if relevant): Firefox 61, Chrome 67 

##### Steps to Reproduce

In lieu of a full reverse proxy setup, we can reproduce the behavior of GoCD resetting the session using curl:

```
# Create a session using basic auth and store the cookie
curl "<host>:8154/go/pipelines" -k -v -o /dev/null -c cookies.txt -u $USER 

# Use the session cookie WITHOUT basic auth
curl "<host>:8154/go/pipelines" -k -v -o /dev/null -b cookies.txt
-> the session is maintained

# Use the session cookie AND basic auth
curl "<host>:8154/go/pipelines" -k -v -o /dev/null -b cookies.txt -u $USER
```

##### Expected Results

The session from the cookie is maintained even if the Authorization header is set.

##### Actual Results

The server creates a new session and returns a Set-Cookie header with a new session cookie.
This invalidates the CSRF token stored in the old session.

##### Possible Fix

I'm fairly certain this change in behavior is due to this change in the AbstractBasicAuthenticationFilter: https://github.com/gocd/gocd/commit/bf001a4fbe0c93cbdb359fc8bc37dd36a550c7c8#diff-a4fb18faf26d223eb093b3cf955a474b

I don't know if there was a good reason to remove the ```if (SessionUtils.hasAuthenticationToken(request))``` check, though.

##### Log snippets

```
2018-07-20 13:41:31,751 WARN  [qtp1260134048-8971819] Rails:-2 - Can't verify CSRF token authenticity
2018-07-20 13:41:31,754 ERROR [qtp1260134048-8971819] Rails:-1 - 
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  lib/jetty_weak_etag_middleware.rb:35:in `call'
  lib/catch_json_parse_errors.rb:23:in `call'
```

**Comment by arvindsv** [comment]
@bdpiparva When you have the time, can you take a look at this?

**Comment by bdpiparva** [comment]
@sandro-h -- Yes, you are right about the behavioral change around authentication. To understand the issue more please can you provide us more information about how your SSO is implemented?

**Comment by sandro-h** [comment]
Hi @bdpiparva,

Thanks for getting back on this.  
The SSO is implemented via a reverse proxy. You log into the SSO portal with your credentials, and the proxy will generally send a proprietary signed token to the backend applications to authenticate the user.
For applications that don't support this token, the proxy can also use basic authentication. So for every request it forwards to GoCD, for example, it will append the *Authorization* HTTP header with the user's credentials.
It's also able to manage (session) cookies that are returned from the backend application and attach these to the forwarded requests as well. I've been told by our SSO support that configuring it in a way that it does *not* send the Authorization header if it already has a valid session token from GoCD is not straight-forward, unfortunately.

So far we haven't encountered this session recreation problem in any of the other applications where we use basic authentication forwarding, so that's why I was wondering in my original post if there is a specific reason for the change.
Hope that helps to elaborate on the problem.

**Comment by maheshp** [comment]
https://github.com/gocd/gocd/pull/5067 fixes this issue.

**Comment by ketan** [comment]
@sandro-h — do you have a testbed where you can provide us feedback on this build https://build.gocd.org/go/tab/build/detail/installers/1078/dist/1/dist#tab-artifacts ? To login just click on the "guest" icon on the login page.

We plan to cut a release early next week, so if you can confirm that this works for you before that, we may be able to put additional fixes in.

**Comment by sandro-h** [comment]
Hi @ketan,

We tried the build in our test environment and can confirm that the CSRF errors no long appear.
Thanks very much for the fix!
