### ISSUE TITLE
Changing artifact location(custom path) from server configuration page doesn't validate the path on save

### ISSUE THREAD

**Issue by anishtesting** [gocd/gocd#5038]
##### Issue Type
- Bug

##### Summary

When we try to update the artifact location from the server configuration page, we do not validate if the "go" user has permissions in the path defined. 

Post the change of the artifact location, one has to restart Go server for this change to take effect. If the "go" user doesn't have permissions to the path assigned, the server restart fails.

###### Basic environment details

* Go Version: 18.7.0
* JAVA Version: 1.8.0_181-8u18
* OS: Ubuntu 16.04.4 LTS

##### Steps to Reproduce

1. Navigate to the server configuration page from the GoCD UI.
2. Add a custom location for the artifacts directory. Say - /root/artifacts.
3. Save the page. We don't validate if the "go" user has permissions to this directory. Only a warning is shown in the GoCD dashboard that this change needs a server restart.
4. Restart Go server and you will see that the server doesn't come up. Log shows that the it cannot create the artifact directory. Log snippet below.

##### Expected Results
Go server should validate the path.

##### Actual Results
We show a warning saying that the change in the artifacts directory location will not take effect until the Go Server is restarted. Post restart, the server errors out.

##### Possible Fix
Maybe run a validation on the path defined on save.

##### Log snippets
```
java.lang.RuntimeException: java.lang.RuntimeException: Unable to create artifacts directory at /root/artifacts/
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:167)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:53)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1515)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1477)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:150)
	at com.thoughtworks.go.server.Jetty9Server.startHandlers(Jetty9Server.java:182)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:132)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:72)
	at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
	at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.gocd.Boot.run(Boot.java:111)
	at com.thoughtworks.gocd.Boot.main(Boot.java:57)
Caused by: java.lang.RuntimeException: Unable to create artifacts directory at /root/test
	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:28)
	at com.thoughtworks.go.server.service.GoConfigService.initialize(GoConfigService.java:143)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:116)
	... 36 common frames omitted
2018-08-17 06:10:31,360 ERROR [main] GoServer:76 - ERROR: Failed to start GoCD server.
```

**Comment by arvindsv** [comment]
Talked to @anishtesting. It's a bug, but no one else has found it in a while. So, it's probably not a common operation. If it's simple to fix, we should. If not, we can do it later or leave it as a known issue.

**Comment by adityasood** [comment]
@arvindsv we mark this as known and close this out?

**Comment by arvindsv** [comment]
@adityasood Yes, closing as known.
