### ISSUE TITLE
go-server-18.8.0 generates java.lang.NoSuchMethodError: org.bouncycastle.asn1.x509.SubjectKeyIdentifier.<init>(Lorg/bouncycastle/asn1/x509/SubjectPublicKeyInfo;)V

### ISSUE THREAD

**Issue by taringamberini** [gocd/gocd#5137]
##### Summary

go-server-18.8.0 doesn't start.

##### Environment

Windows 10 64bit

###### Basic environment details

```plain
c:\java\go\go-server-18.8.0>set
...
GO_AGENT_JAVA_HOME=C:\java\jdk1.8.0_111\jre
GO_SERVER_JAVA_HOME=C:\java\jdk1.8.0_111\jre
...
```

##### Steps to Reproduce

~~1. download server from https://www.gocd.org/download/#windows~~
~~2. doubleclick to install the server~~
1. download from https://www.gocd.org/download/#zip
2. run start-server.bat

##### Expected Results

The server should start.

##### Actual Results

The server doesn't start.

See logs line below.

##### Log snippets

```plain
[Wed Sep 05 15:33:34 CEST 2018]   Working directory    : c:\java\go\go-server-18.8.0
[Wed Sep 05 15:33:34 CEST 2018]   Application arguments: []
[Wed Sep 05 15:33:34 CEST 2018]            GoCD Version: 18.8.0-7433
Could not find file `c:\java\go\go-server-18.8.0\config\logback.xml'. Attempting to load from classpath.
Using classpath resource `jar:onejar:lib/server-launcher-18.8.0-7433-main.jar!/config/logback.xml'.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.thoughtworks.gocd.Boot.run(Boot.java:111)
        at com.thoughtworks.gocd.Boot.main(Boot.java:57)
Caused by: java.lang.NoSuchMethodError: org.bouncycastle.asn1.x509.SubjectKeyIdentifier.<init>(Lorg/bouncycastle/asn1/x509/SubjectPublicKeyInfo;)V
        at org.bouncycastle.x509.extension.SubjectKeyIdentifierStructure.fromPublicKey(Unknown Source)
        at org.bouncycastle.x509.extension.SubjectKeyIdentifierStructure.<init>(Unknown Source)
        at com.thoughtworks.go.security.PKCS12BagAttributeSetter.setLocalKeyId(PKCS12BagAttributeSetter.java:54)
        at com.thoughtworks.go.security.X509CertificateGenerator.storeX509Certificate(X509CertificateGenerator.java:82)
        at com.thoughtworks.go.security.X509CertificateGenerator.createAndStoreX509Certificates(X509CertificateGenerator.java:70)
        at com.thoughtworks.go.server.util.GoSslSocketConnector.ensureX509Certificates(GoSslSocketConnector.java:98)
        at com.thoughtworks.go.server.util.GoSslSocketConnector.sslConnector(GoSslSocketConnector.java:56)
        at com.thoughtworks.go.server.util.GoSslSocketConnector.<init>(GoSslSocketConnector.java:52)
        at com.thoughtworks.go.server.Jetty9Server.sslConnector(Jetty9Server.java:204)
        at com.thoughtworks.go.server.Jetty9Server.configure(Jetty9Server.java:83)
        at com.thoughtworks.go.server.GoServer.configureServer(GoServer.java:84)
        at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:71)
        at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
        at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:45)
        ... 6 more
```

##### Any other info

The same thing happens if I install the windows service version
~~https://www.gocd.org/download/#zip~~
https://www.gocd.org/download/#windows

Thanks in advance,
Tarin

**Comment by taringamberini** [comment]
The bug doesn't manifest itself if I install the server choosing the installation option "use bundled jre".

I saw in the bundled jre `C:\java\go\server\jre\release`:
```
JAVA_VERSION="1.8.0_102"
OS_NAME="Windows"
OS_VERSION="5.2"
OS_ARCH="amd64"
SOURCE=" .:daafd7d3a76a corba:56b133772ec1 deploy:de4043049895 hotspot:ac29c9c1193a hotspot/make/closed:c65fdf789fd7 hotspot/src/closed:60c728d85221 hotspot/test/closed:1e18c2279cc4 install:6f5ea1d3b6a0 jaxp:1f032000ff4b jaxws:81f2d81a48d7 jdk:48c99b423839 jdk/make/closed:e4e4e633f6e0 jdk/src/closed:e49a105b44cf jdk/test/closed:410f3c278e89 langtools:0549bf2f507d nashorn:0948e61a3722 pubs:6b7e6c06ce51 sponsors:b2b1e386c6b3"
BUILD_TYPE="commercial"
```

Instead the bug manifest itself if I install the server choosing the installation option "custom (or local) jre" and typing my local `C:\java\jdk1.8.0_111\jre`. In the `C:\java\jdk1.8.0_111\release`:
```
JAVA_VERSION="1.8.0_111"
OS_NAME="Windows"
OS_VERSION="5.2"
OS_ARCH="amd64"
SOURCE=" .:07c7b5880ac3 corba:7898951ff63c deploy:e06026011e5b hotspot:05a6a5823aa5 hotspot/make/closed:1cc269cccf44 hotspot/src/closed:075d5fd610df hotspot/test/closed:1d9823c1ccd9 install:2ed3b409ecf2 jaxp:f1d0b6e81070 jaxws:1439cb8c6e86 jdk:ab26fe28f9ed jdk/make/closed:865eb1cff2a8 jdk/src/closed:3467b700cdc2 jdk/test/closed:39129eac756b langtools:0e2e745ed6d7 nashorn:97770cfdb942 pubs:8a989345f000 sponsors:8a0f220b2552"
BUILD_TYPE="commercial"
```

So I guess the bug is related to the JAVA_VERSION.

Best regards,
Tarin

**Comment by arvindsv** [comment]
Might have something to do with the change "Restrict JARs signed with weak algorithms and keys" in [JRE 8u111](http://www.oracle.com/technetwork/java/javase/8u111-relnotes-3124969.html). I use it with 8u172 on a Mac, though and it works.

Also, we're making changes to make GoCD work with Java 9, 10 and beyond. See #3136. So, maybe this is not a big problem? As long as it works with 8u102, which is bundled. Someone will need to look at it.

**Comment by taringamberini** [comment]
> So, maybe this is not a big problem?

Yes, it isn't. Now I'm using the bundled jre and it works as expected.

Maybe this issue could be closed with a "won't fix".

Kind regards,
Tarin

**Comment by arvindsv** [comment]
@ketan Thoughts? Wont-fix, or investigate? /cc @rajiesh @adityasood

**Comment by ketan** [comment]
I'd want to investigate this when there's time available. But I'm tempted to fix as wont-fix. Esp because we're soon to upgrade java/jruby/bouncycastle in time for 18.10.
