### ISSUE TITLE
The change you wanted was rejected (on Chrome 69/70)

### ISSUE THREAD

**Issue by abdulg** [gocd/gocd#5296]
##### Issue Type

- Bug Report

##### Summary

Since updating to 18.10.0-7703 users who were able to make changes to pipelines now get the error 'The change you wanted was rejected'. As before the upgrade these users are authenticated via GitHub.

The error only occurs with Chrome (69 and 70). Firefox 62 works fine.

##### Environment

```plain
      "GO_SERVER_LOG_DIR": "/var/log/go-server",
      "HOME": "/var/go",
      "LANG": "en_US.UTF-8",
      "LANGUAGE": "en_CA:en",
      "LC_ALL": "en_US.UTF-8",
      "LOGNAME": "go",
      "MAIL": "/var/mail/go",
      "OLDPWD": "/var/go",
      "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin",
      "PWD": "/var/lib/go-server",
      "SHELL": "/bin/bash",
      "SHLVL": "1",
      "USER": "go",
      "XDG_DATA_DIRS": "/usr/local/share:/usr/share:/var/lib/snapd/desktop",
      "XDG_RUNTIME_DIR": "/run/user/999",
      "XDG_SESSION_ID": "c1"
```

###### Basic environment details

* Go Version: `18.10.0 (7703-42d1cbe661161b5400289ead86c0447c84af8c0a)`
* JAVA Version: `1.8.0_181`
* OS: `Linux 4.15.0-1023-aws`
* Browser vendor and version (if relevant): `Chrome 69 or 70`

###### Additional Environment Details

The problem does not occur with Firefox 62

##### Steps to Reproduce

1.  Login in via GitHub on Chrome
2.  Select the gear icon to edit a pipeline (for which this user has permission to edit)
3. Select Save (no need to make changes)
4. Pop up error dialog will appear

##### Expected Results

Save should be successful

##### Actual Results

Dialog: The change you wanted was rejected [Maybe you tried to change something you didn't have access to]
##### Log snippets

```
2018-10-19 10:50:11,402 WARN  [qtp1392425346-30] Rails:-1 - HTTP Origin header (https://gocd.eventmobi.com) didn't match request.base_url (http://127.0.0.1:8153)
2018-10-19 10:50:11,406 ERROR [qtp1392425346-30] Rails:-1 -   
2018-10-19 10:50:11,406 ERROR [qtp1392425346-30] Rails:-1 - ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
2018-10-19 10:50:11,407 ERROR [qtp1392425346-30] Rails:-1 -   
2018-10-19 10:50:11,407 ERROR [qtp1392425346-30] Rails:-1 - gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:34:in `block in Callbacks'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
org/jruby/RubyArray.java:1801:in `each'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:38:in `block in process_action'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134:in `process'
gems/jruby/2.5.0/gems/actionview-5.2.1/lib/action_view/rendering.rb:32:in `process'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:191:in `dispatch'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_controller/metal.rb:252:in `dispatch'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
org/jruby/RubyArray.java:1801:in `each'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `serve'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
gems/jruby/2.5.0/gems/versionist-1.7.0/lib/versionist/middleware.rb:39:in `_call'
gems/jruby/2.5.0/gems/versionist-1.7.0/lib/versionist/middleware.rb:17:in `call'
gems/jruby/2.5.0/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15:in `call'
gems/jruby/2.5.0/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
gems/jruby/2.5.0/gems/rack-2.0.5/lib/rack/conditional_get.rb:38:in `call'
gems/jruby/2.5.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
uri:classloader:/jruby/rack/session_store.rb:79:in `context'
gems/jruby/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:38:in `call_app'
gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:28:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
gems/jruby/2.5.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
gems/jruby/2.5.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
gems/jruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
gems/jruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'
gems/jruby/2.5.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
gems/jruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:524:in `call'
uri:classloader:/rack/handler/servlet.rb:22:in `call'
```

##### Any other info

We tried the following with Chrome:
1. Clear cookies [still did not work]
2. Use incognito and login to GitHub/GoCD again [still did not work]
3. Use Chrome on another machine that had only logged in as admin, and login as a GitHub user [still did not work, the built in `admin` user does work]

**Comment by abdulg** [comment]
> 
> 
> @abdulg Do you have a reverse proxy setup? [On gitter](https://gitter.im/gocd/gocd?at=5bc97dd41e23486b93e2421f) someone has a similar issue.

I do and I will try the recommendations and update my findings. That will be only next week though.

**Comment by abdulg** [comment]
The reverse proxy changes fixed the issue (I was using nginx). Thanks.

**Comment by nitingadekar** [comment]
I removed the proxy to get rid of the issue, Can someone share exact changes to be made in proxy to get this working?
