### ISSUE TITLE
Placeholder for issues in Config-repo API

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5430]
##### Issue Type
- Bug Report

##### Summary

Following two issues existed in the Config-repo API and need to be looked at/ fixed as part of an upcoming release. This issue contains a part of issues reported #5394 

* Invalid material type returns 500 server error,
Submit a create config repo request as below,

```
{
    "id": "repo2",
    "plugin_id": "json.config.plugin",
    "material": {
      "type": "GIT",
      "attributes": {
        "url": "http://github.com/test-project",
        "auto_update": true,
        "branch": "master"
      }
    }
  }
```

API returns 500 server error. Error in logs,

```
2018-11-14 16:24:13,091 ERROR [qtp84739718-14] GeneralError:54 -
java.lang.IllegalArgumentException: Unsupported material type: GIT
	at com.thoughtworks.go.apiv1.configrepos.representers.MaterialRepresenter.fromJSON(MaterialRepresenter.java:114)
	at com.thoughtworks.go.apiv1.configrepos.representers.ConfigRepoConfigRepresenterV1.fromJSON(ConfigRepoConfigRepresenterV1.java:37)
	at com.thoughtworks.go.apiv1.configrepos.ConfigReposControllerV1.buildEntityFromRequestBody(ConfigReposControllerV1.java:163)
	at com.thoughtworks.go.apiv1.configrepos.ConfigReposControllerV1.createRepo(ConfigReposControllerV1.java:117)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
	at com.thoughtworks.go.spark.SparkPreFilter.doFilter(SparkPreFilter.java:53)
```
* Plugin id is not validated(looks like this issue always existed with the API)
Submit a create or update config repo API call with below request,

```
{
    "id": "repo1",
    "plugin_id": "foo.bar",
    "material": {
      "type": "git",
      "attributes": {
        "url": "http://github.com/test-project",
        "auto_update": true,
        "branch": "master"
      }
    }
  }
```
Repo created successfully in config xml

**Comment by akshaydewan** [comment]
Not specifying plugin id seems to assume `gocd-xml` as the plugin id:

```
curl 'http://localhost:8153/go/api/admin/config_repos' \
	-H 'Content-Type: application/json; charset=UTF-8' \
	-H 'Accept: application/vnd.go.cd.v1+json' \
	-u admin:badger \
	-d '{"material":{"attributes":{},"type":"git"}}'


{
  "message" : "Validations failed for config-repo '93155129-8fde-4cc2-ae54-4665a50c892d'. Error(s): [Validation failed.]. Please correct and resubmit.",
  "data" : {
    "id" : "93155129-8fde-4cc2-ae54-4665a50c892d",
    "plugin_id" : "gocd-xml",
    "material" : {
      "errors" : {
        "url" : [ "URL cannot be blank" ]
      },
      "type" : "git",
      "attributes" : {
        "name" : null,
        "auto_update" : true,
        "url" : null,
        "branch" : "master"
      }
    },
    "configuration" : [ ]
  }
}
```

**Comment by rajiesh** [comment]
Regarding the issue mentioned by @akshaydewan about plugin_id getting defaulted to `gocd-xml` when not provided in the create request, here is a suggestion for handling it,

1. Create/Udpate request do not provide plugin_id - Response code should be 422 with error as `Plugin_id cannot be blank`
2. Create/Update request provide plugin_id which is not installed on the server or any invalid value - Response code should be 422 with error as `Invalid value for plugin_id. Please check the server for valid plugin_id`

cc: @maheshp
