### ISSUE TITLE
Improve error message when agent is unable to get work

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5483]
##### Issue Type

- Feature enhancement

##### Summary

When an agent gets a 403 response from the server for a variety of reasons, end users get confused as to the root cause of the error. This can happen for a variety of reasons:

- agent has been deleted from the configuration
- agent is pending approval
- possible reverse proxy situation

**Comment by ketan** [comment]
Error now says:

```
2018-11-30 20:43:38,372 ERROR [scheduler-2] AgentHTTPClientController:100 - Error occurred when agent tried to ping server:
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://build.gocd.org/go/remoting/remoteBuildRepository]; nested exception i
s org.apache.http.client.ClientProtocolException: The server returned status code 403. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
   - There is possibly a reverse proxy (or load balancer) that is terminating SSL. Hint: use port 8154 of the GoCD server. See https://docs.gocd.org/current/installation/configur
e-reverse-proxy.html#agents-and-reverse-proxies for details.
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:226)
        at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
```
