### ISSUE TITLE
Deleting a config repo causes PipelineNotFoundException in the background

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#5508]
##### Issue Type
- Bug Report

##### Summary
1. Create a config repo from the SPA
2. Wait for it to get parsed and show up on the dashboard
3. Delete the config repo from the SPA
4. Check Go server logs. For the deleted pipelines, we repeatedly see:
```
java.lang.RuntimeException: com.thoughtworks.go.config.PipelineNotFoundException: Pipeline 'yaml-example' not found.
	at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:48)
	at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:25)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.thoughtworks.go.config.PipelineNotFoundException: Pipeline 'yaml-example' not found.
	at com.thoughtworks.go.config.BasicCruiseConfig.pipelineConfigByName(BasicCruiseConfig.java:615)
	at com.thoughtworks.go.server.service.GoConfigService.pipelineConfigNamed(GoConfigService.java:252)
	at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:110)
	at com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:44)
	... 4 common frames omitted
```

**Comment by akshaydewan** [comment]
Some more info: This happens only when deleting from the SPA. Deleting from the config-xml works fine without any exception.

`PipelineScheduler.onConfigChange` is called when removing the config repo from the XML, but it's not invoked when deleting via the SPA (which uses `DeleteConfigRepoCommand`)

**Comment by maheshp** [comment]
> I thought there was some kind of onEntityChange callback that should be subscribed to. Just a thought, don't respond. :)

Yeah, looks like PipelineScheduler is just a ConfigChangedListener - https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/PipelineScheduler.java#L45

Update to the ConfigRepo through the API would notify just the EntityConfigChangedListeners.

**Comment by rajiesh** [comment]
Verified on 18.12.0 (8139-005f4fd80bafd2efd1d413537368156303f6ef6e)
