### ISSUE TITLE
Pipeline and stage run 'Latest' counters have stopped working

### ISSUE THREAD

**Issue by d-led** [gocd/gocd#5607]
##### Bug

- Bug Report
- Feature proposal

##### Summary

- Since 18.something (to my memory), the UI links of the form `/go/pipelines/<pipeline_name>/Latest/<stage_name>/Latest` stopped working and return a 404. 
- The artifact URLs still contain the route of the form `/go/files/<pipeline>/Latest/<stage>/Latest/<job>/<artifact>`. This should continue to work 😄 

###### Basic environment details

* Go Version: `18.12`

##### Steps to Reproduce

1. Open a pipeline view: e.g. `/go/pipelines/<pipeline>/777/default/1`
2. Replace the numbers with `Latest`
3. observe 404

##### Expected Results

- latest pipeline/stage run view is shown

##### Actual Results

- 404

##### Possible Fix

- (re-)add a route, calculating the latest counters for the view

**Comment by arvindsv** [comment]
Also, see [conversation in gitter](https://gitter.im/gocd/gocd?at=5c1babab6aabd13a34bdb911).

**Comment by arvindsv** [comment]
Moved to 19.1 so that we can investigate and make a decision about either bringing it back and documenting it properly, or marking it as WONT-FIX.

**Comment by ankitsri11** [comment]
@d-led I tried on both GoCD 17.1.0 and 18.1.0 versions and couldn't see any of the below URL working. 

```
/go/pipelines/<pipeline_name>/Latest/<stage_name>/Latest
/go/pipelines/<pipeline_name>/Latest/<stage_name>/1
/go/pipelines/<pipeline_name>/1/<stage_name>/Latest
```

Would it be possible for you to share the exact GoCD version where you saw it working? Thanks

**Comment by d-led** [comment]
@ankitsri11 I've just started `18.2.0 (6228-fbb379a451871b29aa47aef907a78dc64379233f)`from the [demo repo](https://github.com/d-led/gocd_docker_compose_example/tree/4027936c7c615042d6c5743dee0ad814510efcac/static_config) (`docker-compose up`) and it works:

http://localhost:8153/go/tab/build/detail/gocd-rpi-unicorn-hat-monitor/Latest/test/Latest/unit

![screen shot 2018-12-27 at 08 56 29](https://user-images.githubusercontent.com/1716584/50471587-ac8a8300-09b5-11e9-8721-5868e786fcd1.png)

**Comment by d-led** [comment]
`18.7.0 (7121-75d1247f58ab8bcde3c5b43392a87347979f82c5)` works too

**Comment by d-led** [comment]
`18.12.0 (8222-e6778f1cc84bf91e323d337c876046167da36985)` doesn't work

**Comment by ankitsri11** [comment]
@d-led thanks for the update. I was able to replicate and looks like it stopped working from 18.11.0.

I get below error while accessing the job detail page with the latest counter.

<img width="1161" alt="screenshot 2018-12-28 at 12 55 40" src="https://user-images.githubusercontent.com/6838313/50527863-f9e31f00-0a9f-11e9-8215-24ac44ed2e44.png">

Error in the logs:

`2018-12-28 12:53:16,994 ERROR [qtp2070529722-17] JobController:176 - Job detail page error:
java.lang.RuntimeException: Expected numeric pipelineCounter, but received 'latest' for [samp/latest/defaultStage/latest/defaultJob]
        at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:30)
        at com.thoughtworks.go.server.controller.JobController.jobDetail(JobController.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:181)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:420)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)`

**Comment by ankitsri11** [comment]
Looks like the changes were made here: https://github.com/gocd/gocd/commit/dcf69b053bbc3ba7729fc3a29c515ff76a4ac960#diff-f5bcf3c6bab7d8b6e2c6620a418bb1e2

Part of this PR: https://github.com/gocd/gocd/pull/5256

**Comment by d-led** [comment]
it seems that the commit actually didn't mean to break, but rather improve the code

**Comment by d-led** [comment]
it worked for things like sending an email to someone saying "look at the latest pipeline run" 😃

**Comment by arvindsv** [comment]
Any thoughts, @akshaydewan ?

**Comment by d-led** [comment]
`latest` would be great as a permalink to the latest run's artifacts, custom tabs and logs

**Comment by arvindsv** [comment]
@akshaydewan Yes. No arbitrary labels.

**Comment by rajiesh** [comment]
Verified on 19.1.0 (8445-eb004d2a8df97734b224df38f04b2501c65ddd63)
