### ISSUE TITLE
go-server fails to poll and checkout from a hg repository with
authentication using latest version of hg (version greater than
2.0.1)

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#57]
Description
-----------

While the steps indicate use of a private bitbucket repo, the bug basically happens when Go is used with any hg repo using a client version \>=2.0.1

#### Steps to reproduce

- Setup a hg repo with basic authentication enabled. You may also use a private mercurial hg repository in bitbucket with security enabled

- Try configuring a hg material for a pipeline by giving right credentials. Click check connection to make sure configuration is correct.

- Now save the pipeline and un pause it

#### Expected result

The pipeline should trigger fine and should go green

#### **Current result**

PIpeline does not get triggered. Material update fails with an error:
>>Failed to run hg pull command: ERROR: warning: bitbucket.org certificate with >>fingerprint 45:ad:ae:1a:cf:0e:73:47:06:07:e0:88:f5:cc:10:e5:fa:1c:f7:99 not verified >>(check hostfingerprints or web.cacerts config setting) ERROR: abort: http >>authorization required.

This issue occurs with hg client version 2.0.1 or higher.
This is because Mercurial from 2.0.1 onwards does not preserve credentials when doing a clone and as a consequence all subsequent calls (hg pull) to the main repo fails (http://mercurial.selenic.com/wiki/WhatsNew\#Mercurial\_2.0.1\_.282011-12-01.29)

**Comment by agoyal-git** [comment]
Works fine on 15.1.0(1470-8daae3aaaeaef8)

**Comment by arvindsv** [comment]
I think there's a problem with this. When you use this config:

```
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="75">
  <server artifactsdir="artifacts" commandRepositoryLocation="default" />
  <pipelines group="defaultGroup">
    <pipeline name="Test">
      <materials>
        <hg url="repo" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
</cruise>
```
and setup a local repo like this:

```
$ ls
LICENSE  config.properties  default.cruise-server  go.jar  init.cruise-server  server.cmd  server.sh  start-server.bat  stop-server.bat  stop-server.sh
$ (hg init repo; cd repo; touch a-file; hg add a-file; hg ci --user abc -m "Initial commit")
$ ls repo/
a-file
```

it fails to run the pipeline. The error in the logs is:

```
2015-03-19 17:44:13,156  WARN [87@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:121 - [Material Update] Modification check failed for material: URL: repo
java.lang.RuntimeException: Failed to run hg pull command: 
STDERR: abort: repository /Users/my-user/go-server-15.1.0/pipelines/flyweight/13839216-0709-4a0a-b39b-191aad6060d0/repo not found!
	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:28)
	at com.thoughtworks.go.util.ExceptionUtils.bombIf(ExceptionUtils.java:56)
	at com.thoughtworks.go.util.ExceptionUtils.bombUnless(ExceptionUtils.java:61)
	at com.thoughtworks.go.domain.materials.mercurial.HgCommand.findRecentModifications(HgCommand.java:116)
	at com.thoughtworks.go.domain.materials.mercurial.HgCommand.latestOneModificationAsModifications(HgCommand.java:98)
	at com.thoughtworks.go.config.materials.mercurial.HgMaterial.latestModification(HgMaterial.java:90)
	at com.thoughtworks.go.server.service.materials.HgPoller.latestModification(HgPoller.java:31)
	at com.thoughtworks.go.server.service.materials.HgPoller.latestModification(HgPoller.java:27)
	at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:106)
	at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:72)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:178)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:134)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:47)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:95)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:92)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:695)
```

**Comment by arikagoyal** [comment]
I realized that this issue comes because you have specified relative path to the repo. If you give absolute path, it works fine. Could you confirm? Saw this issue for supported hg version 1.9 as well. Its probably an existing issue. Maybe we should create a separate issue for this and close this one.

**Comment by arvindsv** [comment]
This was working in Jan, I checked on commit: ec32d51085853b8db00589dccf886359de00f616.

**Comment by arikagoyal** [comment]
Supporting relative repo path does not help too much as it would eventually fail on the agent. Unlikely that anyone would have this kind of setup in their environment. Hence this issue is a "won't fix"
