### ISSUE TITLE
Config repo does not work with Mercurial branch

### ISSUE THREAD

**Issue by aayjaychan** [gocd/gocd#5749]
##### Issue Type

- Bug Report

##### Summary

When using config repo with Mercurial, branch name cannot be appended to the URL, otherwise GoCD will not apply the config.

The [relevant section](https://docs.gocd.org/current/configuration/configuration_reference.html#config-repo-hg) of the configuration reference mentioned that two #s have to be used, but neither one or two # works.

###### Basic environment details

* Docker Image digest: `sha256:d3bc5c93d11797cc35aa0405090d15d6032fa15c1c9540c99a3ae30a3a3f0642`
* Go Version: `18.12.0 (8222-e6778f1cc84bf91e323d337c876046167da36985)`
* JAVA Version: `1.8.0_181`
* OS: `Linux 4.15.0-43-generic`

##### Steps to Reproduce

1. Add an hg YAML config repo with branch information at the end of the URL, either through Config Repositories page or by editing XML directly.

##### Expected Results

Pipelines in the config repo appear on dashboard.

##### Actual Results

No pipeline defined in the config repo appears on dashboard.

When # is used, the error message is:
```
2+ errors :: Error when processing params for '***/Core.Draft#default' used in field 'url', # must be followed by a parameter pattern or escaped by another #;; Error when processing params for '***/Core.Draft#default' used in field 'url', # must be followed by a parameter pattern or escaped by another #;; - Config-Repo: ***/Core.Draft##default at 6483394f24e60b3aee9775578761972ab5a3b411
```

When ## is used, the error message is:
```
Failed to run hg clone command STDERR: abort: unknown revision '#default'!
```

##### Log snippets

When # is used:
```
2019-01-22 12:23:53,213 INFO  [133@MessageListener for ConfigMaterialUpdateListener] GoConfigDao:112 - Config update request com.thoughtworks.go.config.GoPartialConfig$GoPartialUpdateCommand@7299b92b by anonymous is being processed
2019-01-22 12:23:53,350 WARN  [133@MessageListener for ConfigMaterialUpdateListener] GoFileConfigDataSource:344 - Merged config update operation failed on LATEST 12 partials. Falling back to using LAST VALID 11 partials. Exception message was: 2+ errors :: Error when processing params for '***/Core.Draft#default' used in field 'url', # must be followed by a parameter pattern or escaped by another #;; Error when processing params for '***/Core.Draft#default' used in field 'url', # must be followed by a parameter pattern or escaped by another #;;
com.thoughtworks.go.config.exceptions.GoConfigInvalidMergeException: 2+ errors :: Error when processing params for '***/Core.Draft#default' used in field 'url', # must be followed by a parameter pattern or escaped by another #;; Error when processing params for '***/Core.Draft#default' used in field 'url', # must be followed by a parameter pattern or escaped by another #;;
        at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:143)
        at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:117)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:75)
        at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:561)
        at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:493)
        at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:477)
        at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:338)
        at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:151)
        at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:119)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:288)
        at com.thoughtworks.go.config.GoPartialConfig.updateConfig(GoPartialConfig.java:126)
        at com.thoughtworks.go.config.GoPartialConfig.onSuccessPartialConfig(GoPartialConfig.java:86)
        at com.thoughtworks.go.config.GoRepoConfigDataSource.notifySuccessListeners(GoRepoConfigDataSource.java:173)
        at com.thoughtworks.go.config.GoRepoConfigDataSource.onCheckoutComplete(GoRepoConfigDataSource.java:146)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.updateConfigurationFromCheckout(ConfigMaterialUpdateListener.java:100)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.onMessage(ConfigMaterialUpdateListener.java:81)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.onMessage(ConfigMaterialUpdateListener.java:36)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
2019-01-22 12:23:53,454 WARN  [133@MessageListener for ConfigMaterialUpdateListener] GoFileConfigDataSource:350 - Merged config update operation failed using fallback LAST VALID 12 partials. Exception message was: 2+ errors :: Error when processing params for '***/Core.Draft#default' used in field 'url', # must be followed by a parameter pattern or escaped by another #;; Error when processing params for '***/Core.Draft#default' used in field 'url', # must be followed by a parameter pattern or escaped by another #;;
```

When ## is used:
```
2019-01-22 12:29:54,522 INFO  [qtp815992954-25] GoConfigDao:92 - Config update for entity request by com.thoughtworks.go.server.domain.Username@5c128ec[***] is being processed
2019-01-22 12:29:54,578 INFO  [qtp815992954-25] GoFileConfigDataSource:302 - [Configuration Changed] Saving updated configuration.
2019-01-22 12:29:54,696 INFO  [qtp815992954-25] MagicalGoConfigXmlWriter:84 - [Serializing Config] Generating config partial.
2019-01-22 12:29:54,924 INFO  [qtp815992954-25] CachedGoConfig:164 - About to notify com.thoughtworks.go.config.remote.ConfigRepoConfig config listeners
2019-01-22 12:29:54,927 INFO  [qtp815992954-25] CachedGoConfig:179 - Finished notifying com.thoughtworks.go.config.remote.ConfigRepoConfig config listeners
2019-01-22 12:29:54,928 INFO  [qtp815992954-25] GoConfigDao:102 - Entity update for request by com.thoughtworks.go.server.domain.Username@5c128ec[***] is completed
2019-01-22 12:29:54,981 ERROR [qtp815992954-36] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
2019-01-22 12:29:56,275 ERROR [qtp815992954-36] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
2019-01-22 12:30:29,826 WARN  [122@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:112 - [Material Update] Modification check failed for material: URL: ***/Core.Draft##default
java.lang.RuntimeException: Failed to run hg clone command STDERR: abort: unknown revision '#default'!
        at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:42)
        at com.thoughtworks.go.config.materials.mercurial.HgMaterial.getHg(HgMaterial.java:116)
        at com.thoughtworks.go.config.materials.mercurial.HgMaterial.latestModification(HgMaterial.java:86)
        at com.thoughtworks.go.server.service.materials.HgPoller.latestModification(HgPoller.java:31)
        at com.thoughtworks.go.server.service.materials.HgPoller.latestModification(HgPoller.java:27)
        at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:115)
        at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
        at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:55)
        at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:69)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:163)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:121)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:47)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:88)
        at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$executeWithExceptionHandling$2(TransactionTemplate.java:44)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:41)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:85)
        at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:64)
        at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:33)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Failed to run hg clone command
        at com.thoughtworks.go.util.ExceptionUtils.bombIfFailedToRunCommandLine(ExceptionUtils.java:52)
        at com.thoughtworks.go.config.materials.mercurial.HgMaterial.hg(HgMaterial.java:207)
        at com.thoughtworks.go.config.materials.mercurial.HgMaterial.getHg(HgMaterial.java:114)
        ... 21 common frames omitted
2019-01-22 12:30:29,834 WARN  [134@MessageListener for ConfigMaterialUpdateListener] ConfigMaterialUpdateListener:72 - [Config Material Update] Cannot update configuration part because material update has failed. Reason: Failed to run hg clone command STDERR: abort: unknown revision '#default'!. Cause: Failed to run hg clone command
2019-01-22 12:30:40,753 ERROR [qtp815992954-26] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type

```
##### Code snippets/Screenshots

When # is used:
![image](https://user-images.githubusercontent.com/12904352/51533935-3b889f00-1e7f-11e9-8449-cf5d4cd4a267.png)

![image](https://user-images.githubusercontent.com/12904352/51534067-aafe8e80-1e7f-11e9-9544-763d5676f1fe.png)

When ## is used:
![image](https://user-images.githubusercontent.com/12904352/51532754-ee56fe00-1e7b-11e9-8b47-9e9ebf3e3389.png)

![image](https://user-images.githubusercontent.com/12904352/51533401-b355ca00-1e7d-11e9-816c-06df0fde47b4.png)

**Comment by ankitsri11** [comment]
I was able to replicate the issue with the local mercurial repository for both regular pipeline and config-repo. 

```
mercurial $ hg branches
release                        3:82a9f916e3be
release1                       2:d733dc7d139b
default                        0:c76675e22e7d (inactive)
```

I was able to add pipeline with no check connection error for material. But soon after I saw below error and it stopped polling for changes. However, force trigger did pick the changes and triggered the pipeline. 

```
Modification check failed for material: URL: /tmp/gocd/mercurial##release122 Jan, 2019 at 12:53:12 Local Time
Failed to run hg clone command STDERR: abort: unknown revision '#release1'!
```

Material config:

```
 "materials" : [ {
    "type" : "hg",
    "attributes" : {
      "url" : "/tmp/gocd/mercurial##release",
      "destination" : null,
      "filter" : null,
      "invert_filter" : false,
      "name" : null,
      "auto_update" : true
    }
```

Errors in the go-server.log file:

```
2019-01-22 12:53:12,293 WARN  [125@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:112 - [Material Update] Modification check failed for material: URL: /tmp/gocd/mercurial##release1
java.lang.RuntimeException: Failed to run hg clone command STDERR: abort: unknown revision '#release1'!
        at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:42)
        at com.thoughtworks.go.config.materials.mercurial.HgMaterial.getHg(HgMaterial.java:116)
        at com.thoughtworks.go.config.materials.mercurial.HgMaterial.latestModification(HgMaterial.java:86)
        at com.thoughtworks.go.server.service.materials.HgPoller.latestModification(HgPoller.java:31)
        at com.thoughtworks.go.server.service.materials.HgPoller.latestModification(HgPoller.java:27)
        at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:115)
        at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
        at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:55)
        at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:69)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:163)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:121)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:47)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:88)
        at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$executeWithExceptionHandling$2(TransactionTemplate.java:44)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:41)
        at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:85)
        at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:64)
        at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:33)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Failed to run hg clone command
        at com.thoughtworks.go.util.ExceptionUtils.bombIfFailedToRunCommandLine(ExceptionUtils.java:52)
        at com.thoughtworks.go.config.materials.mercurial.HgMaterial.hg(HgMaterial.java:207)
        at com.thoughtworks.go.config.materials.mercurial.HgMaterial.getHg(HgMaterial.java:114)
        ... 21 common frames omitted
2019-01-22 12:53:12,295 WARN  [111@MessageListener for ConfigMaterialUpdateListener] ConfigMaterialUpdateListener:71 - [Config Material Update] Cannot update configuration part because material update has failed. Reason: Failed to run hg clone command STDERR: abort: unknown revision '#release1'!. Cause: Failed to run hg clone command
2019-01-22 12:53:24,319 ERROR [qtp2070529722-33] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
2019-01-22 12:53:34,335 ERROR [qtp2070529722-24] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
2019-01-22 12:53:44,211 ERROR [qtp2070529722-21] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
```

**Comment by ankitsri11** [comment]
@aayjaychan I cleared up everything and tried adding config-repo with a single hash `#` and it worked. 

It looks like only one hash `#` is required for the config-repo whereas double hash `##` for the GoCD pipeline material configuration.

Here is my config-repo configuration.

 ```
 <config-repos>
    <config-repo pluginId="json.config.plugin" id="blah">
      <hg url="/tmp/gocd/mercurial#release1" />
    </config-repo>
  </config-repos>
```
![screenshot 2019-01-22 at 13 36 02](https://user-images.githubusercontent.com/6838313/51566913-b2577500-1e4a-11e9-8752-4d86711285ab.png)

Here is the pipeline configuration stored under config-repo with a mercurial material (double hash for the branch):

```
{
  "format_version": 1,
  "name": "build_test",
  "environment_variables": [
    {
      "name": "TEST_NUM"
    }
  ],
  "group": "Pipeline_as_Code",
  "materials": [
    {
      "url": "/tmp/gocd/mercurial##release",
      "filter": {
        "ignore": [],
        "whitelist": []
      },
      "auto_update": true,
      "type": "hg"
    }
  ],
  "stages": [
    {
      "name": "build_test_build_stage",
      "fetch_materials": true,
      "never_cleanup_artifacts": false,
      "clean_working_directory": false,
      "environment_variables": [],
      "jobs": [
        {
          "name": "build_test_job",
          "environment_variables": [],
          "tabs": [],
          "resources": [],
          "artifacts": [],
          "properties": [],
          "run_instance_count": null,
          "timeout": 0,
          "tasks": [
            {
              "type": "exec",
              "command": "ls"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by ankitsri11** [comment]
@aayjaychan I tried **configrepo** material type (https://github.com/tomzo/gocd-json-config-plugin#configrepo) inside the config-repo pipeline and got a similar error as that of yours. 

```
There was an error parsing this configuration repository:
INVALID MERGED CONFIGURATION
Number of errors: 1+
1. Error when processing params for '/tmp/gocd/mercurial#release1' used in field 'url', # must be followed by a parameter pattern or escaped by another #;; 
- For Config Repo: /tmp/gocd/mercurial##release1 at 1d69b1deef3db1da28cd96fbf42b401f44deb240
```

This is all because of the special-ness of `#` in the config, where it is used for param replacement. Related: - https://github.com/gocd/gocd/issues/854

I would suggest not to use **configrepo** material type until the behavior is changed. You can try setting up as mentioned in my previous response.

**Comment by arvindsv** [comment]
Since there's a workaround, closing this issue till we know anything more - or decide this case should be handled.
