### ISSUE TITLE
Go-CD fails to render it's configuration via yaml.config.plugin after upgrading from 18.12.0 to 19.1

### ISSUE THREAD

**Issue by jfoboss** [gocd/gocd#5793]
##### Issue Type
- Bug Report

##### Summary

Go-CD fails to render valid configuration via yaml.config.plugin after upgrading from 18.12.0 to 19.1.

##### Environment
* CentOS 7 (x86_64)
* OpenJDK 1.8

###### Basic environment details

* Go Version: `18.12.0 & 19.1`
* JAVA Version: `1.8.0_191`
* OS: `Linux 4.15.0-20-generic`

###### Additional Environment Details

Working environment:
```
{
  "Timestamp": "2019-01-30T08:34:20Z",
  "Go Server Information": {
    "Version": "18.12.0 (8222-e6778f1cc84bf91e323d337c876046167da36985)"
  },
  "Config Statistics": {
    "Valid Config": {
      "Number of pipelines": 101,
      "Number of agents": 19,
      "Number of environments": 33,
      "Number of unique materials": 197,
      "Number of schedulable materials": 199
    },
  "OS Information": {
    "OS Name": "Linux",
    "OS Version": "4.15.0-20-generic",
    "System Architecture": "amd64",
    "Available Processors": 24,
    "Average System Load": 2.02
  },
  "Runtime Information": {
    "Name": "8800@inf-gocd",
    "Uptime": 907013,
    "Uptime (in Time Format)": "[About 0 hours, 15 minutes, 7 seconds]",
    "Spec Name": "Java Virtual Machine Specification",
    "Spec Vendor": "Oracle Corporation",
    "Spec Version": "1.8",
    "System Properties": {
      "cruise.config.dir": "/etc/go",
      "cruise.config.file": "/etc/go/cruise-config.xml",
      "cruise.server.port": "8153",
      "cruise.server.ssl.port": "8154",
      "file.encoding": "UTF-8",
      "file.encoding.pkg": "sun.io",
      "java.class.path": "/usr/share/go-server/go.jar",
      "java.class.version": "52.0",
      "java.endorsed.dirs": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/endorsed",
      "java.ext.dirs": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/ext:/usr/java/packages/lib/ext",
      "java.home": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre",
      "java.io.tmpdir": "/tmp",
      "java.library.path": "/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib",
      "java.protocol.handler.pkgs": "com.thoughtworks.gocd",
      "java.runtime.name": "OpenJDK Runtime Environment",
      "java.runtime.version": "1.8.0_191-b12",
      "java.security.egd": "file:/dev/./urandom",
      "java.specification.name": "Java Platform API Specification",
      "java.specification.vendor": "Oracle Corporation",
      "java.specification.version": "1.8",
      "java.vendor": "Oracle Corporation",
      "java.vendor.url": "http://java.oracle.com/",
      "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
      "java.version": "1.8.0_191",
      "java.vm.info": "mixed mode",
      "java.vm.name": "OpenJDK 64-Bit Server VM",
      "java.vm.specification.name": "Java Virtual Machine Specification",
      "java.vm.specification.vendor": "Oracle Corporation",
      "java.vm.specification.version": "1.8",
      "java.vm.vendor": "Oracle Corporation",
      "java.vm.version": "25.191-b12",
      "jdk.tls.ephemeralDHKeySize": "matched",
      "os.arch": "amd64",
      "os.name": "Linux",
      "os.version": "4.15.0-20-generic",
      "path.separator": ":",
      "rails.use.compressed.js": "true",
      "sun.arch.data.model": "64",
    },
```

##### Steps to Reproduce

1. `yum ugrade -y`
2. sadly look at broken go pipelines in web interface of go-server 19.1
3. `yum downgrade go-server && yum versionlock go-server`
4. look at working go-cd 18.12

##### Expected Results
Go-CD is upgraded successfully without config rendering errors

##### Actual Results
Go-CD fails to render config which is valid for 18.12

##### Log snippets
```
2019-01-30 08:12:41,240 INFO  [152@MessageListener for ConfigMaterialUpdateListener] GoConfigDao:108 - Config update request by anonymous is in queue - com.thoughtworks.go.config.update.PartialConfigUpdateCommand@7437867c
2019-01-30 08:12:41,242 INFO  [152@MessageListener for ConfigMaterialUpdateListener] GoConfigDao:111 - Config update request com.thoughtworks.go.config.update.PartialConfigUpdateCommand@7437867c by anonymous is being processed
2019-01-30 08:12:41,269 INFO  [151@MessageListener for ConfigMaterialUpdateListener] GoConfigDao:108 - Config update request by anonymous is in queue - com.thoughtworks.go.config.update.PartialConfigUpdateCommand@1f2150aa
2019-01-30 08:12:41,507 WARN  [152@MessageListener for ConfigMaterialUpdateListener] GoFileConfigDataSource:342 - Merged config update operation failed on LATEST 1 partials. Falling back to using LAST VALID 0 partials. Exception message was: Number of errors: 6+
1. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
2. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
3. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
4. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
5. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
6. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;

com.thoughtworks.go.config.exceptions.GoConfigInvalidMergeException: Number of errors: 6+
1. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
2. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
3. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
4. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
5. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;
6. Encrypted value for variable named 'ARTIFACTORY_PASSWORD' is invalid. This usually happens when the cipher text is modified to have an invalid value.;;

        at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:141)
        at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:128)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:75)
        at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:559)
        at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:491)
        at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:475)
        at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:336)
        at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:161)
        at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:118)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:291)
        at com.thoughtworks.go.config.GoPartialConfig.updateConfig(GoPartialConfig.java:102)
        at com.thoughtworks.go.config.GoPartialConfig.onSuccessPartialConfig(GoPartialConfig.java:84)
        at com.thoughtworks.go.config.GoRepoConfigDataSource.notifySuccessListeners(GoRepoConfigDataSource.java:173)
        at com.thoughtworks.go.config.GoRepoConfigDataSource.onCheckoutComplete(GoRepoConfigDataSource.java:146)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.updateConfigurationFromCheckout(ConfigMaterialUpdateListener.java:103)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.onMessage(ConfigMaterialUpdateListener.java:80)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.onMessage(ConfigMaterialUpdateListener.java:38)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
2019-01-30 08:12:41,659 WARN  [152@MessageListener for ConfigMaterialUpdateListener] GoFileConfigDataSource:348 - Merged config update operation failed using fallback LAST VALID 1 partials. Exception message was: Number of errors: 6+

```

**Comment by ketan** [comment]
When you upgraded, did you replace the `cipher` or `cipher.aes` files in the config directory? Removing the cipher files will prevent the encrypted values from being decrypted.

**Comment by ketan** [comment]
Sorry about what I'd said earlier. Support for DES based passwords was removed as of 19.1. See https://www.gocd.org/releases/#19-1-0. It had been deprecated for a few releases.

I'd recommend re-encrypting the passwords (using the encryption API) and update the values in the configuration repository.
