### ISSUE TITLE
Upgrade from 18.12.0 to 19.1.0 fails with Column "STAGES.CANCELLEDBY" not found

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#5795]
##### Issue Type

- Bug Report

##### Summary

When upgrading my go.cd server with large H2 database it fails with querying the database when or after `Retriving Active Pipelines from Database...`

```
### Error querying database.  Cause: org.h2.jdbc.JdbcSQLException: Column "STAGES.CANCELLEDBY" not found; SQL statement:
SELECT
        pipelines.id as pipelineId, pipelines.name as pipelineName, buildCauseType, label, buildCauseMessage,
        pipelines.counter as pipelineCounter, pipelines.label as pipelineLabel, pipelines.naturalOrder as naturalOrder,
        pipelines.comment as pipelineComment, stages.name as stageName,stages.counter as stageCounter, stages.id as stageId, stages.approvedBy as approvedBy, stages.cancelledBy as cancelledBy,
        stages.approvalType as approvalType, stages.result as stageResult, stages.latestRun, stages.rerunOfCounter,
        builds.id as buildId, builds.name as buildName, builds.state as buildState, builds.result as buildResult,
        builds.scheduledDate as scheduledDate, stages.orderId as orderId
        FROM pipelines
        INNER JOIN stages ON stages.pipelineId = pipelines.id AND
         
        stages.latestRun = true
     
        INNER JOIN builds ON builds.stageId = stages.id AND builds.ignored != true
     
        INNER JOIN (
            SELECT stages.pipelineId AS id
            FROM stages
            WHERE stages.state = 'Building' AND latestRun = true
        UNION
            SELECT max(pipelines.id) AS id
                FROM pipelines
                GROUP BY pipelines.name
        ) pipelines_to_show ON pipelines.id = pipelines_to_show.id
        ORDER BY pipelines.id DESC, stages.orderId ASC [42122-168]
### The error may exist in com/thoughtworks/go/server/dao/maps/Pipeline.xml
### The error may involve Pipeline.allActivePipelines
### The error occurred while executing a query
```

###### Basic environment details

* Go Version: `19.1.0-8469`
* JAVA Version: `open jdk 8`
* OS: `alpine:3.6`

**Comment by JorritSalverda** [comment]
At least rolling back to 18.12.0 works without issues. It could be that the db migration scripts didn't successfully finish when upgrading. Is there any way to ensure they run again when doing another upgrade attempt? Or will the always re-run until successfully finished?

**Comment by varshavaradarajan** [comment]
@JorritSalverda - no, it won't rerun because of a bug in dbdeploy- https://github.com/gocd/gocd/issues/2223. 

Do you use the postgreSQL addon? If so, was that updated with the gocd server? 

There could also be some setup problems which leads to that. Can you please check the go server logs and cruise.trace.db (if using h2)  at the time you started the 19.1.0 gocd server? This will help in understanding why the migration failed in the first place. 

Does the go server log show 1901001 (this is the one that introduces the cancelledBy column) as `to be applied` when the dbdeploy migration starts?

**Comment by JorritSalverda** [comment]
Unfortunately the logs from that first upgrade are no longer available - I run go.cd in a Kubernetes without log shipping and the old pod logs are gone by now - but it got killed by the liveness check after 20 minutes, when it was still working on changing indexes.

If i re-run the upgrade now it logs the following for the database migration:

```
************************************************************************
2019-01-31 08:39:07,712 INFO  [main] DbDeployMigration:60 - ************************************************************************
Reading change scripts from directory /var/lib/go-server/db/h2deltas...
dbdeploy v2.11
2019-01-31 08:39:07,789 INFO  [main] H2EventListener:31 - Initializing database: jdbc:h2:db/h2db/cruise
Creating index SYS:SYS_ID 0%
2019-01-31 08:39:15,260 INFO  [main] H2EventListener:83 - Creating index SYS:SYS_ID 0%
Creating index SYS:SYS_ID 0%
2019-01-31 08:39:15,262 INFO  [main] H2EventListener:83 - Creating index SYS:SYS_ID 0%
2019-01-31 08:39:15,819 INFO  [main] H2EventListener:35 - Database is opened
2019-01-31 08:39:15,848 INFO  [main] H2EventListener:31 - Initializing database: jdbc:h2:db/h2db/cruise
Changes currently applied to database:
  1..90, 221001, 230001..230009, 240001, 240002, 300001..300011, 1202001..1202003, 1203002..1203005, 1301001, 1302001, 1303001..1303004, 1304001, 1401001, 1403001, 1403002, 1501001..1501003, 1502001, 1503001, 1503002, 1606001, 1606002, 1607001, 1610001, 1701001, 1702001, 1704001..1704003, 1708001, 1801001..1801007, 1802001, 1802002, 1804001, 1805001, 1807001, 1807002, 1808001, 1808002, 1901001
Scripts available:
  1..90, 221001, 230001..230009, 240001, 240002, 300001..300011, 1202001..1202003, 1203002..1203005, 1301001, 1302001, 1303001..1303004, 1304001, 1401001, 1403001, 1403002, 1501001..1501003, 1502001, 1503001, 1503002, 1606001, 1606002, 1607001, 1610001, 1701001, 1702001, 1704001..1704003, 1708001, 1801001..1801007, 1802001, 1802002, 1804001, 1805001, 1807001, 1807002, 1808001, 1808002, 1901001
To be applied:
  (none)
2019-01-31 08:39:15,881 INFO  [main] H2EventListener:31 - Initializing database: jdbc:h2:db/h2db/cruise
Database upgrade completed successfully.
2019-01-31 08:39:15,888 INFO  [main] DbDeployMigration:71 - Database upgrade completed.
2019-01-31 08:39:15,890 INFO  [main] H2EventListener:78 - Closing database
2019-01-31 08:39:16,214 INFO  [main] H2Database:124 - [db] Using connection configuration jdbc:h2:db/h2db/cruise;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;CACHE_SIZE=131072;TRACE_LEVEL_FILE=1;TRACE_MAX_FILE_SIZE=16;DATABASE_EVENT_LISTENER='com.thoughtworks.go.server.util.H2EventListener' [User: sa]
2019-01-31 08:39:16,215 INFO  [main] H2Database:114 - Creating data source with url=jdbc:h2:db/h2db/cruise;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;CACHE_SIZE=131072;TRACE_LEVEL_FILE=1;TRACE_MAX_FILE_SIZE=16;DATABASE_EVENT_LISTENER='com.thoughtworks.go.server.util.H2EventListener'
```

Acting like all is fine, but then again it fails on the missing `STAGES.CANCELLEDBY` column. Is there any way i can forcibly re-run the migration scripts with DbDeploy again? By updating a database record to act like nothing has been applied so far? Or manually run the deltas myself against the H2 database?

By the way, I use the file-based H2 database and don't have the paid Postgresql add-on.

If I look for the deltas for release 1901 I can only find `/var/lib/go-server/db/h2deltas/1901001_add_cancelled_by_to_stages_table.sql`, but that seems to be the missing column indeed.

```
ALTER TABLE stages ADD COLUMN cancelledBy varchar(255);

--//@UNDO

ALTER TABLE stages DROP COLUMN cancelledBy;
```

**Comment by ketan** [comment]
I'd suggest doing this right now, to avoid any further issues with your db:

1. shutdown your gocd server
2. Sync the database file to your local computer
3. Download the following jar http://central.maven.org/maven2/com/h2database/h2/1.3.168/h2-1.3.168.jar
4. Run via `java -cp h2-1.3.168.jar org.h2.tools.Shell`. Provide the following when asked
    - url: `jdbc:h2:/path/to/cruise` do not append the `.db` extension
    - username: `sa`
    - password: (blank)
5. At the sql prompt, execute `select * from changelog order by CHANGE_NUMBER desc limit 10;`.

I currently suspect that the changelog table might have a `START_DT` value but no `COMPLETE_DT` value corresponding to the entry for `1901001_add_cancelled_by_to_stages_table.sql`. If that is the case, it indicates that the transaction to perform the migration started off, but did not finish.

If this is the case, you should run the sql snippet above `ALTER TABLE stages ADD COLUMN cancelledBy varchar(255);` and update the `COMPLETE_DT` to the current timestamp by executing: 

```sql
update changelog set COMPLETE_DT=current_timestamp() where CHANGE_NUMBER=1901001`;
```

**Comment by ketan** [comment]
I should add that if the state of the table is not what I describe, please attach the output of `select * from changelog` to this issue.

**Comment by JorritSalverda** [comment]
Ah sorry, I missed your comment about how to fix it.

**Comment by ketan** [comment]
> Given that the COMPLETE_DT is null you would expect dbdeploy to re-run. But perhaps since this particular delta is not idempotent that's not wise to do.

That's a known bug with dbdeploy, with the workaround I mentioned.

> Shall I just delete that last record and re-start?

That would work fine. Since there's just one SQL to execute. Depending on the size of your stages table, it may take some time. So make sure the instance is not terminated like the last time.

**Comment by JorritSalverda** [comment]
I now have an hour before the instance gets terminated. Running the `ALTER TABLE stages ADD COLUMN cancelledBy varchar(255);` command now and hopefully it completes within that time.

**Comment by JorritSalverda** [comment]
Although the server now starts fine after having completed the steps I can't start any builds, it seems the database has been corrupted in all the attempts to upgrade:

```
SQL []; Referential integrity constraint violation: "STAGES_COPY_4_0_FK_BUILDS_STAGES: PUBLIC.BUILDS FOREIGN KEY(STAGEID) REFERENCES PUBLIC.STAGES_COPY_4_0(ID) (581026)"; SQL statement:
INSERT INTO builds (name, scheduledDate, state, result, agentUuid, stageId, runOnAllAgents, runMultipleInstance, originalJobId, rerun)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23506-168]; nested exception is org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "STAGES_COPY_4_0_FK_BUILDS_STAGES: PUBLIC.BUILDS FOREIGN KEY(STAGEID) REFERENCES PUBLIC.STAGES_COPY_4_0(ID) (581026)"; SQL statement:
INSERT INTO builds (name, scheduledDate, state, result, agentUuid, stageId, runOnAllAgents, runMultipleInstance, originalJobId, rerun)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23506-168]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:242)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy30.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at com.thoughtworks.go.server.transaction.SqlMapClientTemplate.insert(SqlMapClientTemplate.java:74)
	at com.thoughtworks.go.server.dao.JobInstanceSqlMapDao.lambda$save$0(JobInstanceSqlMapDao.java:213)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$execute$1(TransactionTemplate.java:32)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:29)
	at com.thoughtworks.go.server.dao.JobInstanceSqlMapDao.save(JobInstanceSqlMapDao.java:211)
	at com.thoughtworks.go.server.service.JobInstanceService.save(JobInstanceService.java:214)
	at com.thoughtworks.go.server.service.StageService.persistJobs(StageService.java:274)
	at com.thoughtworks.go.server.service.StageService.lambda$save$0(StageService.java:236)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$execute$1(TransactionTemplate.java:32)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:29)
	at com.thoughtworks.go.server.service.StageService.save(StageService.java:233)
	at com.thoughtworks.go.server.service.PipelineService.lambda$save$0(PipelineService.java:98)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$execute$1(TransactionTemplate.java:32)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:29)
	at com.thoughtworks.go.server.service.PipelineService.save(PipelineService.java:89)
	at com.thoughtworks.go.server.service.PipelineScheduleQueue.lambda$createPipeline$0(PipelineScheduleQueue.java:138)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$execute$1(TransactionTemplate.java:32)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:29)
	at com.thoughtworks.go.server.service.PipelineScheduleQueue.createPipeline(PipelineScheduleQueue.java:129)
	at com.thoughtworks.go.server.service.ScheduleService.schedulePipeline(ScheduleService.java:175)
	at com.thoughtworks.go.server.service.ScheduleService.autoSchedulePipelinesFromRequestBuffer(ScheduleService.java:157)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at com.thoughtworks.go.server.service.ModeAwareRunnable.run(ModeAwareRunnable.java:51)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "STAGES_COPY_4_0_FK_BUILDS_STAGES: PUBLIC.BUILDS FOREIGN KEY(STAGEID) REFERENCES PUBLIC.STAGES_COPY_4_0(ID) (581026)"; SQL statement:
INSERT INTO builds (name, scheduledDate, state, result, agentUuid, stageId, runOnAllAgents, runMultipleInstance, originalJobId, rerun)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23506-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:361)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:303)
	at org.h2.table.Table.fireConstraints(Table.java:871)
	at org.h2.table.Table.fireAfterRow(Table.java:888)
	at org.h2.command.dml.Insert.insertRows(Insert.java:126)
	at org.h2.command.dml.Insert.update(Insert.java:84)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:194)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 40 common frames omitted
```

Any (simple) way to fix this?

**Comment by JorritSalverda** [comment]
The highest ID in the STAGES_COPY_4_0 table is 580784. This is indeed less than the value 581027 that's tried to be inserted into the builds table. Where does the insert statement get this stageid value from to begin with?

**Comment by ketan** [comment]
`STAGES_COPY_4_0` isn't supposed to be a table. What tables does the sql statement `show tables;`  list?

**Comment by JorritSalverda** [comment]
On a side note I wonder whether tables are properly indexed on their id (primary key I guess).

If i run `select * from STAGES_COPY_4_0 limit 10;` it only takes 62ms, but if I run `select * from STAGES_COPY_4_0 order by id desc limit 10;` it takes 9922ms.

And even worse `select * from builds limit 10;` takes just 37ms, while `select * from builds order by id desc limit 10;` takes and incredible 264822ms.

**Comment by ketan** [comment]
Looking at H2's source, it seems to create a temp table, when an `alter table` sql runs. I suspect that that's where the error is coming from. I'm not entirely sure, why the temp table is being used by any of the sql statements being executed.

I'd suggest using the recovery tool: http://www.h2database.com/html/advanced.html#using_recover_tool to recover and rebuild the DB.

**Comment by JorritSalverda** [comment]
I have the following tables:
```
sql> show tables;
TABLE_NAME                     | TABLE_SCHEMA
AGENTS                         | PUBLIC
ARTIFACTPLANS                  | PUBLIC
ARTIFACTPROPERTIESGENERATOR    | PUBLIC
BUILDS                         | PUBLIC
BUILDSTATETRANSITIONS          | PUBLIC
CHANGELOG                      | PUBLIC
DATASHARINGSETTINGS            | PUBLIC
ENVIRONMENTVARIABLES           | PUBLIC
JOBAGENTMETADATA               | PUBLIC
MATERIALS                      | PUBLIC
MODIFICATIONS                  | PUBLIC
MODIFIEDFILES                  | PUBLIC
NOTIFICATIONFILTERS            | PUBLIC
PIPELINELABELCOUNTS            | PUBLIC
PIPELINEMATERIALREVISIONS      | PUBLIC
PIPELINES                      | PUBLIC
PIPELINESELECTIONS             | PUBLIC
PIPELINESTATES                 | PUBLIC
PLUGINS                        | PUBLIC
PROPERTIES                     | PUBLIC
RESOURCES                      | PUBLIC
SERVERBACKUPS                  | PUBLIC
STAGEARTIFACTCLEANUPPROHIBITED | PUBLIC
STAGES                         | PUBLIC
STAGES_COPY_4_0                | PUBLIC
USAGEDATAREPORTING             | PUBLIC
USERS                          | PUBLIC
VERSIONINFOS                   | PUBLIC
_BUILDS                        | PUBLIC
_STAGES                        | PUBLIC
```

I'll have a look at the recovery tool.

**Comment by JorritSalverda** [comment]
Unfortunately I couldn't get recovery to work; it created the sql file, but applying it to the existing db failed on the existing user. With a file of 2GB I couldn't edit it to remove that particular statement. Running the script on a fresh database failed as well. So I decided to wipe the database and accept the loss of history. This isn't too big of a deal, only losing the counters per pipeline is problematic for some of them.

Nevertheless, thanks for helping out. And I'll make sure to automate backing up the database before upgrading go.cd :S

**Comment by JorritSalverda** [comment]
It would have been nice if the counters per pipeline got backed up outside of the database as well ;)

**Comment by ketan** [comment]
> Unfortunately I couldn't get recovery to work; it created the sql file, but applying it to the existing db failed on the existing user

You'd want to restore on a new DB file, not the same DB file.

**Comment by ketan** [comment]
And after you restore, perhaps remove the last record in the changelog table, if it exists in the new DB.

**Comment by krnaveen14** [comment]
>    * url: `jdbc:h2:/path/to/cruise` do not append the `.db` extension

Also do not append the `.h2` extension. Just the `jdbc:h2:/var/lib/go-server/db/h2db/cruise`

**Comment by csyszf** [comment]
> Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "STAGES_COPY_4_0_FK_BUILDS_STAGES: PUBLIC.BUILDS FOREIGN KEY(STAGEID) REFERENCES PUBLIC.STAGES_COPY_4_0(ID) (581027)"; SQL statement:
INSERT INTO builds (name, scheduledDate, state, result, agentUuid, stageId, runOnAllAgents, runMultipleInstance, originalJobId, rerun)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23506-168]

Anyone who ran into this problem can try to remove the `STAGES_COPY_*` foreign key constraint on table `BUILDS` and table `BUILDSTATETRANSITIONS`
