### ISSUE TITLE
Go error: Could not find modification 12258 in []

### ISSUE THREAD

**Issue by rohanpoddar** [gocd/gocd#588]
We created a pipeline and ran it. It ran the first time. However, after this, we consistently get an error on go-server.log. The stacktrace is.

```
2014-09-25 17:05:13,549  INFO [2005349873@qtp-75424399-7] PipelineScheduler:140 - [Pipeline Schedule] [Accepted] Manual trigger of pipeline 'Bahmni_artifacts_release' accepted for user ci-admin
2014-09-25 17:05:13,552  INFO [2005349873@qtp-75424399-7] PipelineScheduler:144 - [Pipeline Schedule] [Processed] Manual trigger of pipeline 'Bahmni_artifacts_release' processed with result 'com.thoughtworks.go.serverhealth.ServerHealthState@7d5189b4[healthStateLevel=OK,type=<HealthStateType DATABASE_DISK_FULL LogScope[GLOBAL, scope=GLOBAL]>,message=,description=,expiryTime=<null>,timestamp=Thu Sep 25 17:05:13 IST 2014]'
2014-09-25 17:05:13,559 ERROR [58@MessageListener for MaterialUpdateStatusNotifier] BuildCauseProducerService:243 - Error while scheduling pipeline: Bahmni_artifacts_release
java.lang.RuntimeException: Could not find modification 12258 in []
    at com.thoughtworks.go.domain.materials.Modifications.since(Modifications.java:101)
    at com.thoughtworks.go.server.persistence.MaterialRepository.findModificationsSince(MaterialRepository.java:721)
    at com.thoughtworks.go.server.materials.MaterialChecker.findRevisionsSince(MaterialChecker.java:68)
    at com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:200)
    at com.thoughtworks.go.server.scheduling.BuildCauseProducerService$WaitForPipelineMaterialUpdate.onMaterialUpdate(BuildCauseProducerService.java:322)
    at com.thoughtworks.go.server.materials.MaterialUpdateStatusNotifier.onMessage(MaterialUpdateStatusNotifier.java:54)
    at com.thoughtworks.go.server.materials.MaterialUpdateStatusNotifier.onMessage(MaterialUpdateStatusNotifier.java:28)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by arvindsv** [comment]
Closing as stale.
