### ISSUE TITLE
Tasks not assigned to agents, NPE in logs

### ISSUE THREAD

**Issue by tdegueur** [gocd/gocd#5889]
##### Issue Type

- Bug Report

##### Summary

Tasks are not seem assigned to any agent despite them being configured, launched, and appearing as "Idle" in the Agents tab.

Logs (pasted below) show a stacktrace mentioning a file called "/go/admin/latest-agent.status" which does not seem to exist. Is it supposed to be generated by the server at startup?

###### Basic environment details

* Go Version: 18.7.0
* JAVA Version: 1.8.0_171
* OS: Linux 4.9.0-0.bpo.6-amd64
* Browser vendor and version (if relevant): Not Internet Explorer 7 D:

###### Additional Environment Details

Server and Agents are running in Docker containers.

The full content of /api/support exceeds the maximum length of Github issues, which parts would be helpful?

##### Steps to Reproduce

Not available.

##### Log snippets

```
2019-02-21 10:45:49,272 WARN  [qtp1991294891-18] HttpChannel:568 - /go/admin/latest-agent.status
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.web.FlashLoadingFilter.doFilterInternal(FlashLoadingFilter.java:39)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.DenyIfRefererIsNotFilesFilter.doFilterInternal(DenyIfRefererIsNotFilesFilter.java:53)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.AllowAllAccessFilter.doFilterInternal(AllowAllAccessFilter.java:34)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractUserEnabledCheckFilter.doFilterInternal(AbstractUserEnabledCheckFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.ThreadLocalUserFilter.doFilterInternal(ThreadLocalUserFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractBasicAuthenticationFilter.filterWhenSecurityEnabled(AbstractBasicAuthenticationFilter.java:81)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractBasicAuthenticationFilter.doFilterInternal(AbstractBasicAuthenticationFilter.java:65)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.AssumeAnonymousUserFilter.doFilterInternal(AssumeAnonymousUserFilter.java:65)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractReAuthenticationFilter.doFilterInternal(AbstractReAuthenticationFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.InvalidateAuthenticationOnSecurityConfigChangeFilter.doFilterInternal(InvalidateAuthenticationOnSecurityConfigChangeFilter.java:101)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.RememberLastRequestUrlFilter.doFilterInternal(RememberLastRequestUrlFilter.java:41)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.thoughtworks.go.server.newsecurity.filters.AlwaysCreateSessionFilter.doFilterInternal(AlwaysCreateSessionFilter.java:41)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.AbstractSessionReduceIdleTimeoutFilter.doFilterInternal(AbstractSessionReduceIdleTimeoutFilter.java:45)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at com.thoughtworks.go.server.newsecurity.filters.ModeAwareFilter.doFilter(ModeAwareFilter.java:53)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at com.thoughtworks.go.server.newsecurity.filterchains.MainFilterChain.doFilter(MainFilterChain.java:76)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at com.thoughtworks.go.server.web.BackupFilter.doFilter(BackupFilter.java:86)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:36)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
```

**Comment by arvindsv** [comment]
@tdegueur This seems like a duplicate of #4469. Won't close it yet, since that one is unresolved too.

1. /cc @GaneshSPatil might be interested. I'm sure we can provide you some changes to `logback-include.xml` to show more logs.

2. You mentioned using Docker. Would you be able to provide more details so that we can reproduce this?

Thank you.

**Comment by tdegueur** [comment]
@arvindsv Thanks for the response, here are the versions we are using for the docker images:

```
FROM gocd/gocd-server:v18.7.0
FROM gocd/gocd-agent-debian-8:v18.7.0
```

I'm not sure which details can be helpful, did you have something specific in mind?

I figured out how to attach files on Github, here is the content of /api/support:
[gocd-support.txt](https://github.com/gocd/gocd/files/2900803/gocd-support.txt)

Cheers.

**Comment by arvindsv** [comment]
@tdegueur Are you sure you're using the 18.7.0 image for the GoCD server? From the support output you attached, it says:

```json
"Go Server Information": {
  "Version": "18.1.0 (5937-8a847b96ee8d38173f80178ed1285f0e53a970e0)"
}
```

Maybe once that is confirmed, we can look at other parts of this. Thanks.

**Comment by tdegueur** [comment]
@arvindsv Support output on the currently running server says 18.7.0, I must've attached an older file, sorry about that.

Correct file:
[gocd-support.txt](https://github.com/gocd/gocd/files/2904986/gocd-support.txt)

**Comment by ankitsri11** [comment]
@tdegueur can you share the output of below curl command.
```
$ curl -v https://your-go-server:8154/go/admin/latest-agent.status
```
Also, let us know if you are connecting agents through a reverse proxy.

**Comment by tdegueur** [comment]
```
*   Trying XXX.XXX.XXX.XXX...
* TCP_NODELAY set
* Connected to my-go-server (XXX.XXX.XXX.XXX) port 8154 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Would the certificate be the cause of the problem?

**Comment by arvindsv** [comment]
@tdegueur It might not be a problem. It might be the self-signed cert which GoCD server creates. Can you run it with `curl -k` to get curl to ignore the certificate for now?

**Comment by tdegueur** [comment]
@arvindsv Output with -k:

```
*   Trying 91.134.230.101...
* TCP_NODELAY set
* Connected to cd01.gael-systems.com (91.134.230.101) port 8154 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=059b301daa63; OU=Cruise server webserver certificate
*  start date: Jan  1 00:00:00 1970 GMT
*  expire date: Feb 20 16:41:50 2029 GMT
*  issuer: CN=059b301daa63; OU=Cruise server webserver certificate
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /go/admin/latest-agent.status HTTP/1.1
> Host: cd01.gael-systems.com:8154
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 27 Feb 2019 10:52:17 GMT
< Set-Cookie: JSESSIONID=node0ezla43fbdu9t1kcu2r16qdc1k1145810.node0;Path=/go;Expires=Wed, 13-Mar-2019 10:52:17 GMT;Max-Age=1209600;Secure;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Agent-Content-MD5: da4bc474e0bc2280f116b7c1dfcc14f8
< Agent-Launcher-Content-MD5: 23030f242c86829e05d25eb370252970
< Agent-Plugins-Content-MD5: 2e5e1261888571b39e046f0bf6184fe7
< TFS-SDK-Content-MD5: d7dedab203be64a6822e91d35e0c98d0
< Cruise-Server-Ssl-Port: 8154
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-UA-Compatible: chrome=1
< Vary: Accept-Encoding, User-Agent
< Content-Length: 0
< 
* Connection #0 to host cd01.gael-systems.com left intact
```

**Comment by arvindsv** [comment]
Hello! Let's take a step back. Here's what I tried:

```
$ docker run -d -p 8153:8153 -p 8154:8154 gocd/gocd-server:v18.7.0
Unable to find image 'gocd/gocd-server:v18.7.0' locally
v18.7.0: Pulling from gocd/gocd-server
911c6d0c7995: Pull complete
e7e3cbf95172: Pull complete
f653fcea23e7: Pull complete
ba3c9de073f9: Pull complete
c423e0a0f6ab: Pull complete
ff5e3a43fd26: Pull complete
Digest: sha256:58b078643785f38dae8c33e658af395a106df792205c5dee36be10d2ba2185ac
Status: Downloaded newer image for gocd/gocd-server:v18.7.0
edf4cb66c599618d8bd094f9ea42dbde97884ba17664fb9c3bebfc20fee81d15
```

Server is running:

```
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED              STATUS              PORTS                              NAMES
edf4cb66c599        gocd/gocd-server:v18.7.0   "/docker-entrypoint.…"   About a minute ago   Up About a minute   0.0.0.0:8153-8154->8153-8154/tcp   compassionate_jennings
```

Brought up an agent:

```
$ docker run -d -e GO_SERVER_URL=https://$(docker inspect --format='{{(index (index .NetworkSettings.IPAddress))}}' compassionate_jennings):8154/go gocd/gocd-agent-debian-8:v18.7.0
Unable to find image 'gocd/gocd-agent-debian-8:v18.7.0' locally
v18.7.0: Pulling from gocd/gocd-agent-debian-8
d660b1f15b9b: Pull complete
dfa5e04c04cf: Pull complete
e2606b9823f7: Pull complete
1212ccb87414: Pull complete
d8ed81e42c85: Pull complete
feac2d62b1cc: Pull complete
e1c998a31ecd: Pull complete
09035f80e066: Pull complete
Digest: sha256:bde5f50bbc2800d9d8dbdd53d1be485d878186620dc59176a5f7e9d314857e4b
Status: Downloaded newer image for gocd/gocd-agent-debian-8:v18.7.0
ade9b6f0efac3411a7fd685bcd7fb30751ce9f28ff314de0c2d41d47fbfcf9fb
```

Then:

1. I went to: http://localhost:8153/go/agents

2. Enabled that agent.

3. Started a pipeline.

It worked.


curl shows output similar to yours:

```
$ curl -k -v 'https://localhost:8154/go/admin/latest-agent.status'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8154 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=edf4cb66c599; OU=Cruise server webserver certificate
*  start date: Jan  1 00:00:00 1970 GMT
*  expire date: Feb 28 03:41:55 2029 GMT
*  issuer: CN=edf4cb66c599; OU=Cruise server webserver certificate
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /go/admin/latest-agent.status HTTP/1.1
> Host: localhost:8154
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 28 Feb 2019 04:04:58 GMT
< Set-Cookie: JSESSIONID=node012i89dvhf0jez1cbm4f81rixsv49.node0;Path=/go;Expires=Thu, 14-Mar-2019 04:04:58 GMT;Max-Age=1209600;Secure;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Agent-Content-MD5: da4bc474e0bc2280f116b7c1dfcc14f8
< Agent-Launcher-Content-MD5: 23030f242c86829e05d25eb370252970
< Agent-Plugins-Content-MD5: 32dbaeb9471da65b711c2cab4eb94eaa
< TFS-SDK-Content-MD5: d7dedab203be64a6822e91d35e0c98d0
< Cruise-Server-Ssl-Port: 8154
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-UA-Compatible: chrome=1
< Vary: Accept-Encoding, User-Agent
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

Can you try this and tell us what happens? If that works, then the problem is elsewhere.

**Comment by tdegueur** [comment]
Hi, I followed your instructions and it worked just fine with a fresh server and agent.

**Comment by arvindsv** [comment]
@tdegueur Ok, that's good. What changes have you made to the image? You said you based your images on the GoCD docker images (`FROM gocd/gocd-server:v18.7.0`). What is different from the instructions I sent and your case?

**Comment by tdegueur** [comment]
I need to investigate with the original admin, this may take a while. Keep you posted.

**Comment by nhuquan** [comment]
@arvindsv 
This is the complete content of the Dockerfile

```docker
FROM gocd/gocd-server:v18.7.0

COPY plugin/* /godata/plugins/external/
COPY config/* /home/go/

RUN chmod 777 /godata/plugins/external/*
RUN chmod 777 /home/go/*

ENV CONFIG_GIT_REPO=${secret_valuedo_not_expose_on_the_internet}
ENV CONFIG_GIT_BRANCH=master

EXPOSE 8153
EXPOSE 8154
```

I have 3 custom jar plugins in the `plugin` folder: 

* github-pr-poller-1.4.0-RC.jar
* github-pr-status-1.4.jar
* gocd-maven-plugin-0.1.1.jar 

Hope this help.

**Comment by ankitsri11** [comment]
@tdegueur @nhuquan 

I tried to spin a server with all the mentioned plugins and referring to a config git repo.

```
docker run -d -p8153:8153 -p8154:8154 \
  -e GOCD_PLUGIN_INSTALL_github-pr-poller=https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/download/v1.4.0-RC2/github-pr-poller-1.4.0-RC2.jar \
  -e GOCD_PLUGIN_INSTALL_github-pr-status=https://github.com/gocd-contrib/gocd-build-status-notifier/releases/download/1.5/github-pr-status-1.5.jar \
  -e GOCD_PLUGIN_INSTALL_gocd-maven-plugin=https://github.com/1and1/go-maven-poller/releases/download/v1.2.1/go-maven-poller.jar \
  -e CONFIG_GIT_REPO=https://github.com/ankitsri11/gocd-config.git \
  -e CONFIG_GIT_BRANCH=master \
  gocd/gocd-server:v18.7.0
```
Server is running:

```
~ » docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED              STATUS              PORTS                              NAMES
8829a7cda547        gocd/gocd-server:v18.7.0   "/docker-entrypoint.…"   About a minute ago   Up About a minute   0.0.0.0:8153-8154->8153-8154/tcp   sad_ellis
```

Brought up an agent:

`~ » docker run -d -e GO_SERVER_URL=https://$(docker inspect --format='{{(index (index .NetworkSettings.IPAddress))}}' sad_ellis):8154/go gocd/gocd-agent-debian-8:v18.7.0`

Then, I followed below:

I went to: http://localhost:8153/go/agents and enabled that agent.
Triggered the pipeline which was part of config git repo and it worked.

Can you let me know how the agent is brought up? We might be missing something there.

Also, can you try running your server using the docker command which I tried. You can update the CONFIG_GIT_REPO variable pointing to yours.

**Comment by ketan** [comment]
Reopening for @rajiesh or @adityasood to test.

**Comment by tdegueur** [comment]
Hi @ankitsri11 @arvindsv ,

Sorry for the delayed response, it's hard to find time sometimes. The problem seems to have solved itself after updating our CONFIG_GIT_REPO, which means we can start using our pipeline again. This doesn't explain why the problem occurred in the first place, however.

Thank you so much for the support, please let me know if you need more information in case you want to keep investigating.

Cheers.

**Comment by arvindsv** [comment]
@tdegueur Good to know! Sometimes, when we don't know the root cause, it tends to come back. :) If it does, feel free to comment / open an issue. Thanks.
