### ISSUE TITLE
Bug: Add Stage in the UI Fails

### ISSUE THREAD

**Issue by AndrewBurian** [gocd/gocd#6022]
##### Issue Type

Bug Report

##### Summary

When attempting to create a new stage in an existing pipeline, GoCD returns an error when creating the stage.

###### Basic environment details

* Go Version: `19.2.0 (8641-db17f5840f9d1c6838add93af050b812bbdf5c68)`
* JAVA Version: `1.8.0_212`
* OS: `Linux 4.9.0-8-amd64`
* Browser vendor and version (if relevant): `Chome Version 72.0.3626.121`

##### Steps to Reproduce

1. Create GoCD pipeline, setup save
2. Edit pipeline
3. Stages > Add New
4. Submit stage

##### Expected Results
New stage added to the pipeline with a default task

##### Actual Results
Throws an error

##### Possible Fix
Parsing error? UI and backend disagreement?

##### Log snippets

UI Issued Request:
```
utf8=%E2%9C%93&authenticity_token=redacted&config_md5=f73cd8c3df78bc0a3b2dbf0ba44a41fa&current_tab=stages&stage%5Bname%5D=publish&stage%5Bapproval%5D%5Btype%5D=success&stage%5Bjobs%5D%5B%5D%5Bname%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5BtaskOptions%5D=ant&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Bant%5D%5BbuildFile%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Bant%5D%5Btarget%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Bant%5D%5BworkingDirectory%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Bnant%5D%5BbuildFile%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Bnant%5D%5Btarget%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Bnant%5D%5BworkingDirectory%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Bnant%5D%5BnantPath%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Brake%5D%5BbuildFile%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Brake%5D%5Btarget%5D=&stage%5Bjobs%5D%5B%5D%5Btasks%5D%5Brake%5D%5BworkingDirectory%5D=
```

go-server.log
```
2019-03-25 19:22:18,560 ERROR [qtp1860513229-23] GoConfigDao:120 - Config update failed.
java.lang.RuntimeException: Name is a required field
at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:42)
        at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:360)
        at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:161)
        at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:118)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:291)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfigFromUI(GoConfigService.java:342)
...
Caused by: com.thoughtworks.go.config.exceptions.GoConfigInvalidException: Name is a required field
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:139)
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:128)
	at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:75)
	at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:559)
	at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:491)
	at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:475)
	at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:336)
	... 488 common frames omitted
```

##### Code snippets/Screenshots
![Screen Shot 2019-03-25 at 12 13 47 PM](https://user-images.githubusercontent.com/4976968/54947678-202a2680-4ef8-11e9-9fcf-ee14827a43b3.png)

##### Any other info

Can be worked around by editing the server XML config directly

**Comment by GaneshSPatil** [comment]
@AndrewBurian -- I tried reproducing the above-mentioned scenario.

The save fails for **_`job name`_** being the required field. If we scroll below, the job name field shows the error.

<img width="1286" alt="Screen Shot 2019-03-26 at 9 00 10 AM" src="https://user-images.githubusercontent.com/15275847/54969785-99338780-4fa5-11e9-921c-292618774f28.png">

After specifying the job configurations, the create new stage completes successfully.

Do let us know if this helps you resolve the issue.

**Comment by AndrewBurian** [comment]
Hey! Apologies for this, the bug was in fact that I couldn't scroll down below what I had in the screen shot, and couldn't even see that there was a default task there that was unpopulated.

Poked around and one of my browser extensions seemed to disagree with the page. Disabled it for the GoCD page and it works like a charm now.

Cheers!
