### ISSUE TITLE
Elastic Agents Profiles API allows creating profiles when plugin is absent

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6087]
##### Issue Type

- Bug Report

##### Summary

Elastic agent profiles API allows users to create or update an elastic agent profile when plugin is absent.
This will cause the elastic agent profiles configurations to not be validated as the plugin is missing resulting in possibly invalid configurations.

###### Basic environment details

* Go Version: `GoCD Version: 19.3.0 (8785-34d4f423859709a883d3403b1d6c47ac4c5516be).`

###### Additional Environment Details

Intially, Elastic Agents Profiles API wasn't allowing creation or updates to elastic agent profiles in case of plugin absense.
Later, to support artifact stores, we've made changes to `PluginProfilesService` as part of [`7f86768ef69554960e7727c6285ff21db87d95e2`](https://github.com/gocd/gocd/commit/7f86768ef69554960e7727c6285ff21db87d95e2) commit, which caused this to go through.

older stacktrace it was failing for:
```
2019-04-05 11:13:40,084 ERROR [156@MessageListener for ServerPingListener] JMSMessageListenerAdapter:77 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener@5bece3c
com.thoughtworks.go.plugin.access.PluginNotFoundException: Did not find 'elastic-agent' plugin with id 'cd.go.contrib.elastic-agent.docker'. Looks like plugin is missing
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:40)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.serverPing(ElasticAgentExtension.java:80)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.serverPing(ElasticAgentPluginRegistry.java:50)
	at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:32)
	at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:22)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:748)
```

##### Expected Results
Elastic Agent Profiles creation shouldn't be allowed when plugin is absent.

##### Actual Results
Elastic Agent Profiles creation is allowed when plugin is absent.

---

#### NOTE:

As these changes were made to `PluginProfilesService`, all the commands and services consuming this service will be affected by this bug.

List of APIs having the similar bug:
- [x] Artifacts
- [x] Cluster Profiles
- [x] Elastic Agent Profile
- [x] Secret Configs
- [x] Security Auth Configs

\cc: @bdpiparva @maheshp

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/6088

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
