### ISSUE TITLE
[Bug] - Shouldn't allow to save pipeline config with empty template

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6468]
> Migrated from [Trello Card 133](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;7lrlBvKY)

Basically, we should not allow the user to submit the form when there are no templates and they enabled `Use Template`.

Perhaps we should even show the message as a warning box (yellow?) instead of the informational light blue box.

Either way, we should show a validation error that no template is selected (or something like that) prevents the user from submitting the form.

## Attachments

* ![Screenshot 2019-06-10 at 15.16.28.png](https://raw.githubusercontent.com/gocd/gocd/c65082a0b39ec9e0e5fa5565b0e7a2421487e15d/.github/trello-attachments/bd10562403e40fd8e36ecc962f605e1ec12e45d23da728bbbebab4d704413a6a/Screenshot_2019-06-10_at_15.16.28.png)

**Comment by marques-work** [comment]
@ibnc Note that you should set the `forceOpen` attribute on the `<AdvancedSettings/>` component if an error is present so that the panel is force-expanded to reveal the validation error.

**Comment by ankitsri11** [comment]
For the new workflow, it works fine. Verified on GoCD Version: 19.6.0 (9359-ea6a0afe0b8a34c617a47b70bde258a383797b1c). 

![Screenshot 2019-06-26 at 13 51 31](https://user-images.githubusercontent.com/6838313/60214019-89804500-9819-11e9-8564-defec8684dd3.png)

@marques-work @ibnc However, for the old workflow, it is still broken. See below:

Error in the go-server.log file:

```
2019-06-26 13:52:48,371 ERROR [qtp208645117-33] Rails:-2 - Exception:
NoMethodError: undefined method `getJobs' for nil:NilClass
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/app/controllers/admin/pipelines_controller.rb:103:in `block in create'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/app/controllers/admin_controller.rb:116:in `save'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/app/controllers/admin_controller.rb:40:in `save_page'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/app/controllers/admin/pipelines_controller.rb:98:in `create'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/abstract_controller/base.rb:194:in `process_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/abstract_controller/base.rb:134:in `process'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionview-5.2.2.1/lib/action_view/rendering.rb:32:in `process'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_controller/metal.rb:191:in `dispatch'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_controller/metal.rb:252:in `dispatch'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
        /private/tmp/go-server-19.6.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/actionpack-5.2.2.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
        org/jruby/RubyArray.java:1801:in `each'
```

![Screenshot 2019-06-26 at 13 52 59](https://user-images.githubusercontent.com/6838313/60214206-e2e87400-9819-11e9-8e8e-0bf4b296646b.png)

**Comment by marques-work** [comment]
@ankitsri11 I'll take a look at this. @ibnc is busy with an important spike ATM.

**Comment by ankitsri11** [comment]
@marques-work it seems to have fixed for the old workflow but the message is ambiguous. 


![Screenshot 2019-07-03 at 14 17 44](https://user-images.githubusercontent.com/6838313/60625700-6adff800-9d9d-11e9-888a-3dad19c4b716.png)

It should say something like (same as that of new workflow):

`There are no templates configured or you are unauthorized to view the existing templates. Add one via the templates page.
`

**Comment by marques-work** [comment]
@ankitsri11 This is fixed now (when the build goes through)

![image](https://user-images.githubusercontent.com/723642/60629939-bc43b380-9dac-11e9-91f1-2e36149bbf3e.png)

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.6.0 (9430-01a6f3f4d8d57c166d0b038d143c23ef304ce8c0)
