### ISSUE TITLE
New Agent Token-based authentication fails with HTTP header mismatch

### ISSUE THREAD

**Issue by alexfrancavilla** [gocd/gocd#6647]
##### Issue Type
- Bug Report

##### Summary
The new token based authentication seems to fail on my setup. I have upgraded the Go server to 19.6.0 (no environment variable `GO_USE_TOKEN_AUTH` is set, since the changelog states that this is now active by default). Afterwards I have set up a fresh new agent running on a Mac Mini (10.14.5 Mojave), using the new osx installer zip. Configured the server URL in `wrapper-config/wrapper-properties.conf` and then started the agent in foreground using `bin/go-agent console`.

The agent fails with: `Missing required headers 'Content-MD5' in response.` but I can validate that the URL is returning the correct header. See below for my attempt to validate that the server is working correctly.

##### Environment

Here is the full support api log, too big to be included in this issue: https://gist.github.com/alexfrancavilla/7798c1486abdbf0711de67438deba1dc

###### Basic environment details

Go server running on Kubernetes using the official Helm chart. No fancy configurations set, the web interface is reachable through an Ingress which in turn goes through an AWS ELB. But I believe this setup is mostly irrelevant, the only important thing is that the Ingress controller works like a reverse proxy.

* Go Version: `19.6.0 (9515-4b674c10941b6c27d7ec2a28dd946518d9211b7a)`
* JAVA Version: `12.0.1`
* OS: `Linux 4.9.0-9-amd64`
* Chart version: `gocd-1.14.0`
* Kubernetes version: `1.12.10`
* Ingress Controller: `Traefik v1.7.12`

##### Steps to Reproduce

1. Deploy Go server and put a reverse proxy in front of it
2. Deploy Go agent on mac OS, pointing to the reverse proxy url

##### Expected Results
The agent can talk to the server, downloading the agent jar and announcing itself as a new agent.

##### Actual Results
Agent doesn't announce itself, instead repeats the following error message:
```plain
2019-07-22 16:11:07,506 ERROR [WrapperJarAppMain] ServerBinaryDownloader:82 - Couldn't update admin/agent. Sleeping for 1m. Error:
org.apache.http.client.ClientProtocolException: Problem accessing GoCD Server at https://ci.<REDACTED>.com/go/admin/agent
Missing required headers 'Content-MD5' in response.

        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.handleInvalidResponse(ServerBinaryDownloader.java:145)
        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.download(ServerBinaryDownloader.java:120)
        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:77)
        at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:95)
        at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
        at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
        at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:78)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:59)
        at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.thoughtworks.gocd.Boot.run(Boot.java:89)
        at com.thoughtworks.gocd.Boot.main(Boot.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Though from the exact same host, I can validate that the header is indeed there:
```plain
$ curl -sSl -D - https://ci.<REDACTED>.com/go/admin/agent -o /dev/null
HTTP/2 200
content-md5: f24d7111cfa5ddd517ae2a6601979868
content-type: application/octet-stream
cruise-server-ssl-port: 8154
date: Mon, 22 Jul 2019 14:43:48 GMT
expires: Thu, 01 Jan 1970 00:00:00 GMT
gocd-agent-extra-properties:
set-cookie: JSESSIONID=node01ogr338rhqn3r17fjgm9rg3qax1853.node0;Path=/go;Expires=Mon, 05-Aug-2019 14:43:48 GMT;Max-Age=1209600;Secure;HttpOnly
vary: Accept-Encoding
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-ua-compatible: chrome=1
x-xss-protection: 1; mode=block
```

Additionally I have checked if the resulting binary matches the MD5 sum, and it does:
```plain
$ curl -O https://ci.<REDACTED>.com/go/admin/agent
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.4M    0 20.4M    0     0  12.8M      0 --:--:--  0:00:01 --:--:-- 12.8M

$ md5 agent
MD5 (agent) = f24d7111cfa5ddd517ae2a6601979868
```

The only real difference I noticed is that the header's from the reverse proxy are lowercased and the error message is mentioning the header in capitalized form. I wasn't able to check this as well for time reasons, and according to [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) this should, at least in theory, be no issue: 
>Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

**Comment by ketan** [comment]
Do you mind creating the file `config/agent-launcher-logback-include.xml` in your agent working directory, and starting the agent process? Be sure to remove the following files from the agent working dir:

- agent-launcher.jar
- agent-plugins.zip
- agent.jar
- tfs-impl.jar

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- config/agent-launcher-logback-include.xml -->
<included>
  <logger name="org.apache.http.headers" level="DEBUG" />
</included>

```

**Comment by ketan** [comment]
You should see a bunch of log statements in `logs/go-agent-launcher.log` that dump any headers that the agent process sees. Please paste those log statements here.

Here is what I see in my log file, you should probably see something similar.

```
2019-07-23 04:52:39,582 DEBUG [WrapperJarAppMain] headers:133 - http-outgoing-1 >> HEAD /go/admin/agent HTTP/1.1
2019-07-23 04:52:39,583 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-1 >> Host: build.gocd.org:8154
2019-07-23 04:52:39,583 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-1 >> Connection: Keep-Alive
2019-07-23 04:52:39,583 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-1 >> User-Agent: Apache-HttpClient/4.5.6 (Java/12.0.1)
2019-07-23 04:52:39,583 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-1 >> Accept-Encoding: gzip,deflate
2019-07-23 04:52:39,642 DEBUG [WrapperJarAppMain] headers:122 - http-outgoing-1 << HTTP/1.1 200 OK
2019-07-23 04:52:39,643 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Date: Tue, 23 Jul 2019 08:52:39 GMT
2019-07-23 04:52:39,643 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << X-XSS-Protection: 1; mode=block
2019-07-23 04:52:39,643 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << X-Content-Type-Options: nosniff
2019-07-23 04:52:39,643 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << X-Frame-Options: SAMEORIGIN
2019-07-23 04:52:39,644 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << X-UA-Compatible: chrome=1
2019-07-23 04:52:39,644 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Set-Cookie: JSESSIONID=node01sib3f26so1141a5lfkgsn629q325.node0;Path=/go;Expires=Tue, 06-Aug-2019 08:52:39 GMT;Max-Age=1209600;Secure;HttpOnly
2019-07-23 04:52:39,644 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Expires: Thu, 01 Jan 1970 00:00:00 GMT
2019-07-23 04:52:39,645 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Content-MD5: b3c4b0124c47256b1915543c0b424c4e
2019-07-23 04:52:39,645 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Cruise-Server-Ssl-Port: 8154
2019-07-23 04:52:39,645 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << GoCD-Agent-Extra-Properties:
2019-07-23 04:52:39,646 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Vary: Accept-Encoding, User-Agent
2019-07-23 04:52:39,646 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Content-Length: 0
2019-07-23 04:52:39,648 INFO  [WrapperJarAppMain] ServerBinaryDownloader:108 - Downloading agent.jar
2019-07-23 04:52:39,839 DEBUG [WrapperJarAppMain] headers:133 - http-outgoing-2 >> GET /go/admin/agent HTTP/1.1
2019-07-23 04:52:39,839 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-2 >> Host: build.gocd.org:8154
2019-07-23 04:52:39,840 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-2 >> Connection: Keep-Alive
2019-07-23 04:52:39,840 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-2 >> User-Agent: Apache-HttpClient/4.5.6 (Java/12.0.1)
2019-07-23 04:52:39,840 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-2 >> Accept-Encoding: gzip,deflate
2019-07-23 04:52:39,959 DEBUG [WrapperJarAppMain] headers:122 - http-outgoing-2 << HTTP/1.1 200 OK
2019-07-23 04:52:39,960 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Date: Tue, 23 Jul 2019 08:52:39 GMT
2019-07-23 04:52:39,960 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << X-XSS-Protection: 1; mode=block
2019-07-23 04:52:39,960 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << X-Content-Type-Options: nosniff
2019-07-23 04:52:39,961 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << X-Frame-Options: SAMEORIGIN
2019-07-23 04:52:39,961 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << X-UA-Compatible: chrome=1
2019-07-23 04:52:39,961 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Set-Cookie: JSESSIONID=node017mhoj867a4c013mhhsqbvhsqk326.node0;Path=/go;Expires=Tue, 06-Aug-2019 08:52:39 GMT;Max-Age=1209600;Secure;HttpOnly
2019-07-23 04:52:39,962 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Expires: Thu, 01 Jan 1970 00:00:00 GMT
2019-07-23 04:52:39,962 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Content-MD5: b3c4b0124c47256b1915543c0b424c4e
2019-07-23 04:52:39,962 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Cruise-Server-Ssl-Port: 8154
2019-07-23 04:52:39,962 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << GoCD-Agent-Extra-Properties:
2019-07-23 04:52:39,963 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Content-Type: application/octet-stream
2019-07-23 04:52:39,963 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Transfer-Encoding: chunked
2019-07-23 04:52:39,965 INFO  [WrapperJarAppMain] ServerBinaryDownloader:115 - Got server response
2019-07-23 04:52:52,053 INFO  [WrapperJarAppMain] ServerBinaryDownloader:123 - Piped the stream to admin/agent
```

**Comment by alexfrancavilla** [comment]
Hi @ketan, thanks for taking a look. Your requested logs:

<details><summary>go-agent-launcher.log</summary>

```
2019-07-24 10:24:00,429 INFO  [TouchLoopThread-1] Lockfile:101 - Using lock file: /Users/ci/go-agent-19.6.0/.agent-bootstrapper.running
2019-07-24 10:24:00,981 INFO  [WrapperJarAppMain] ServerBinaryDownloader:108 - Downloading agent.jar
2019-07-24 10:24:01,089 INFO  [WrapperJarAppMain] ServerBinaryDownloader:115 - Got server response
2019-07-24 10:24:01,091 ERROR [WrapperJarAppMain] ServerBinaryDownloader:82 - Couldn't update admin/agent. Sleeping for 1m. Error:
org.apache.http.client.ClientProtocolException: Problem accessing GoCD Server at https://ci.<REDACTED>.com/go/admin/agent
Missing required headers 'Content-MD5' in response.

	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.handleInvalidResponse(ServerBinaryDownloader.java:145)
	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.download(ServerBinaryDownloader.java:120)
	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:77)
    <...>
2019-07-24 10:25:57,937 INFO  [TouchLoopThread-1] Lockfile:101 - Using lock file: /Users/ci/go-agent-19.6.0/.agent-bootstrapper.running
2019-07-24 10:25:58,237 DEBUG [WrapperJarAppMain] headers:133 - http-outgoing-0 >> HEAD /go/admin/agent-launcher.jar HTTP/1.1
2019-07-24 10:25:58,238 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-0 >> Host: ci.<REDACTED>.com
2019-07-24 10:25:58,238 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-0 >> Connection: Keep-Alive
2019-07-24 10:25:58,238 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.6 (Java/11.0.1)
2019-07-24 10:25:58,239 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-0 >> Accept-Encoding: gzip,deflate
2019-07-24 10:25:58,265 DEBUG [WrapperJarAppMain] headers:122 - http-outgoing-0 << HTTP/1.1 200 OK
2019-07-24 10:25:58,265 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << Content-Length: 0
2019-07-24 10:25:58,265 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << Content-Md5: 66ec93e59afaff1655c4ade7fd33e530
2019-07-24 10:25:58,265 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << Cruise-Server-Ssl-Port: 8154
2019-07-24 10:25:58,266 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << Date: Wed, 24 Jul 2019 08:25:58 GMT
2019-07-24 10:25:58,266 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << Expires: Thu, 01 Jan 1970 00:00:00 GMT
2019-07-24 10:25:58,266 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << Gocd-Agent-Extra-Properties:
2019-07-24 10:25:58,266 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << Set-Cookie: JSESSIONID=node013okglhppemak1llyxm3mpp40h21931.node0;Path=/go;Expires=Wed, 07-Aug-2019 08:25:58 GMT;Max-Age=1209600;Secure;HttpOnly
2019-07-24 10:25:58,266 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << Vary: Accept-Encoding
2019-07-24 10:25:58,266 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << X-Content-Type-Options: nosniff
2019-07-24 10:25:58,267 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << X-Frame-Options: SAMEORIGIN
2019-07-24 10:25:58,267 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << X-Ua-Compatible: chrome=1
2019-07-24 10:25:58,267 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-0 << X-Xss-Protection: 1; mode=block
2019-07-24 10:25:58,369 DEBUG [WrapperJarAppMain] headers:133 - http-outgoing-1 >> HEAD /go/admin/agent HTTP/1.1
2019-07-24 10:25:58,369 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-1 >> Host: ci.<REDACTED>.com
2019-07-24 10:25:58,369 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-1 >> Connection: Keep-Alive
2019-07-24 10:25:58,370 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-1 >> User-Agent: Apache-HttpClient/4.5.6 (Java/11.0.1)
2019-07-24 10:25:58,370 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-1 >> Accept-Encoding: gzip,deflate
2019-07-24 10:25:58,394 DEBUG [WrapperJarAppMain] headers:122 - http-outgoing-1 << HTTP/1.1 200 OK
2019-07-24 10:25:58,395 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Content-Length: 0
2019-07-24 10:25:58,395 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Content-Md5: f24d7111cfa5ddd517ae2a6601979868
2019-07-24 10:25:58,395 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Cruise-Server-Ssl-Port: 8154
2019-07-24 10:25:58,396 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Date: Wed, 24 Jul 2019 08:25:58 GMT
2019-07-24 10:25:58,396 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Expires: Thu, 01 Jan 1970 00:00:00 GMT
2019-07-24 10:25:58,396 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Gocd-Agent-Extra-Properties:
2019-07-24 10:25:58,396 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Set-Cookie: JSESSIONID=node015g10zdxluibv1rs2qyi56r4m121932.node0;Path=/go;Expires=Wed, 07-Aug-2019 08:25:58 GMT;Max-Age=1209600;Secure;HttpOnly
2019-07-24 10:25:58,396 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Vary: Accept-Encoding
2019-07-24 10:25:58,396 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << Vary: Accept-Encoding, User-Agent
2019-07-24 10:25:58,396 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << X-Content-Type-Options: nosniff
2019-07-24 10:25:58,397 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << X-Frame-Options: SAMEORIGIN
2019-07-24 10:25:58,397 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << X-Ua-Compatible: chrome=1
2019-07-24 10:25:58,397 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-1 << X-Xss-Protection: 1; mode=block
2019-07-24 10:25:58,398 INFO  [WrapperJarAppMain] ServerBinaryDownloader:108 - Downloading agent.jar
2019-07-24 10:25:58,480 DEBUG [WrapperJarAppMain] headers:133 - http-outgoing-2 >> GET /go/admin/agent HTTP/1.1
2019-07-24 10:25:58,480 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-2 >> Host: ci.<REDACTED>.com
2019-07-24 10:25:58,480 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-2 >> Connection: Keep-Alive
2019-07-24 10:25:58,480 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-2 >> User-Agent: Apache-HttpClient/4.5.6 (Java/11.0.1)
2019-07-24 10:25:58,481 DEBUG [WrapperJarAppMain] headers:136 - http-outgoing-2 >> Accept-Encoding: gzip,deflate
2019-07-24 10:25:58,511 DEBUG [WrapperJarAppMain] headers:122 - http-outgoing-2 << HTTP/1.1 200 OK
2019-07-24 10:25:58,511 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Content-Encoding: gzip
2019-07-24 10:25:58,511 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Content-Md5: f24d7111cfa5ddd517ae2a6601979868
2019-07-24 10:25:58,512 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Content-Type: application/octet-stream
2019-07-24 10:25:58,512 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Cruise-Server-Ssl-Port: 8154
2019-07-24 10:25:58,512 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Date: Wed, 24 Jul 2019 08:25:58 GMT
2019-07-24 10:25:58,512 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Expires: Thu, 01 Jan 1970 00:00:00 GMT
2019-07-24 10:25:58,512 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Gocd-Agent-Extra-Properties:
2019-07-24 10:25:58,513 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Set-Cookie: JSESSIONID=node0dadk30o6e8rn1600tl5n0f18221933.node0;Path=/go;Expires=Wed, 07-Aug-2019 08:25:58 GMT;Max-Age=1209600;Secure;HttpOnly
2019-07-24 10:25:58,513 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Vary: Accept-Encoding
2019-07-24 10:25:58,513 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << X-Content-Type-Options: nosniff
2019-07-24 10:25:58,513 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << X-Frame-Options: SAMEORIGIN
2019-07-24 10:25:58,513 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << X-Ua-Compatible: chrome=1
2019-07-24 10:25:58,513 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << X-Xss-Protection: 1; mode=block
2019-07-24 10:25:58,513 DEBUG [WrapperJarAppMain] headers:125 - http-outgoing-2 << Transfer-Encoding: chunked
2019-07-24 10:25:58,515 INFO  [WrapperJarAppMain] ServerBinaryDownloader:115 - Got server response
2019-07-24 10:25:58,516 ERROR [WrapperJarAppMain] ServerBinaryDownloader:82 - Couldn't update admin/agent. Sleeping for 1m. Error:
org.apache.http.client.ClientProtocolException: Problem accessing GoCD Server at https://ci.<REDACTED>.com/go/admin/agent
Missing required headers 'Content-MD5' in response.

	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.handleInvalidResponse(ServerBinaryDownloader.java:145)
	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.download(ServerBinaryDownloader.java:120)
	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:77)
    <...>
```
</details>

From these I have noticed that the logs receive a `Content-Md5` header and the exception mentions `Content-MD5`. Maybe this could be an indicator?

**Comment by ketan** [comment]
Thanks, for the logs. This seems to confirm that the header is coming back properly. FYI: My fear was that the reverse proxy may be doing something funny based on the user-agent.

We're basically calling [`response.getFirstHeader(MD5_HEADER)`](https://github.com/gocd/gocd/blob/250f072a5e0186b85a1788fe08e2cb49e887a4c5/agent-common/src/main/java/com/thoughtworks/go/agent/launcher/ServerBinaryDownloader.java#L141) to ascertain that any reverse proxies are not doing anything funny (we've seen this happen in the past with certain misconfigured reverse proxies).

The implementation of [`getFirstHeader`](https://github.com/apache/httpcomponents-core/blob/4.4.4/httpcore/src/main/java/org/apache/http/message/HeaderGroup.java#L202-L213) has always been compliance with the RFC spec, where it does a case-insensitive string comparison, at this point, you may likely just have to debug the code in an IDE, or if this is a publicly facing server, I may be able to debug it at my end. Let me know how you'd like to proceed.

Out of curiosity, what is the locale on your agent machine (`java -XshowSettings:all`)?

**Comment by alexfrancavilla** [comment]
Thanks for digging into it @ketan. I'm kinda hitting a roadblock with this as I have nearly 0 experience in the Java ecosystem especially when it comes to debugging components of an app. I think I can make it work to provide you access to the instance (e.g. make it publicly facing), is there an easy way to pass you the details via PM or so?

In the mean time I will deploy the agent to different macos/linux hosts, trying to narrow it down further.

Regarding the locale, is this what you were looking for?
```
$ java -XshowSettings:all

<...>

Locale settings:
    default locale = English (United States)
    default display locale = English (United States)
    default format locale = English (United States)
```

**Comment by yuhenabc** [comment]
The error is:
``` text
org.apache.http.client.ClientProtocolException: Problem accessing GoCD Server at http://go.vb.com/go/admin/agent
Missing required headers 'Content-MD5' in response.
```
But when I curl the url:
``` text
# curl -I http://go.vb.com/go/admin/agent
HTTP/1.1 200 OK
Content-Length: 0
Content-Md5: eabe138e3f243e9613ac370aab80a47c
Date: Tue, 05 Apr 2022 01:18:33 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Gocd-Agent-Extra-Properties: 
Set-Cookie: JSESSIONID=node01r0u67rl1yj971ctvn017te76u34.node0; Path=/go; Expires=Tue, 19-Apr-2022 01:18:33 GMT; Max-Age=1209600; HttpOnly
Vary: Accept-Encoding, User-Agent
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Ua-Compatible: chrome=1
X-Xss-Protection: 1; mode=block
```
the difference is  the words `Content-MD5` vs `Content-Md5`，waitting the author to resolve this problom in then next version.

**Comment by yuhenabc** [comment]
In http, header `Content-Md5` is equal to `Content-MD5`，even `content-md5`，so I think then go-agent was not treat then as the same.

**Comment by chadlwilson** [comment]
Hi @yuhenabc - As Ketan mentions [above](https://github.com/gocd/gocd/issues/6647#issuecomment-514560037), the headers are queried case-insensitive so the case is likely not the problem here; the code doesn't care about the case of the header.

For us to look at your issue any deeper (the original issue does seem unresolved unfortunately), we'd probably need to see the raw logs from the agent using the instructions Ketan's mentioned at https://github.com/gocd/gocd/issues/6647#issuecomment-514118814 and also to understand your deployment environment, GoCD version etc so we can narrow it down.
