### ISSUE TITLE
Error in Go Server startup (uninitialized constant ActiveSupport::SecureRandom)

### ISSUE THREAD

**Issue by gajwani** [gocd/gocd#701]
We were rebooting our server, when we noticed that this happened during startup:

```
2014-11-10 12:06:39,029 ERROR [367035308@qtp-1077245673-197] Rails:? -
ActionView::TemplateError (uninitialized constant ActiveSupport::SecureRandom) on line #97 of app/views/pipelines/index.json.erb:
94:            scope[:trigger_with_option_label] = l.string('TRIGGER_WITH_OPTIONS')
95:         -%>\n        <% _scope = {:pipeline_model=> scope[:pipeline_model], :label=>"#{scope[:trigger_label]}"}; -%><% _scope[:pipeline] = _scope[:pipeline_model].getLatestPipelineInstance() -%>\n<%= json_escape((pipeline_operations_blocking_form_remote_tag(:url => api_pipeline_action_path(:pipeline_name => _scope[:pipeline].getName(), :action => "schedule"),
96:                     :html => {
97:                         :onsubmit => "PipelineOperations.onTrigger(this, '#{_scope[:pipeline].getName()}', '#{api_pipeline_action_path(:pipeline_name => _scope[:pipeline].getName(), :action => "schedule")}'); return false;"
98:                     }))) -%>\n    <div class='operate trigger_wrapper'>\n        <%= json_escape((submit_button(_scope[:label], {:type=> 'image', :disabled => !_scope[:pipeline_model].canForce(), :id => "deploy-#{_scope[:pipeline].getName()}"}))) -%>\n    </div>\n<%= json_escape((end_form_tag)) -%>\n\n        <% _scope = {:pipeline => scope[:pipeline_model].getLatestPipelineInstance(),
99:                                                                                                  :label => "#{scope[:trigger_with_option_label]}",
100:                                                                                                  :can_trigger => scope[:pipeline_model].canForce(),

    (eval):2:in `form_authenticity_token'
    app/helpers/application_helper.rb:265:in `form_tag'
    app/helpers/application_helper.rb:229:in `pipeline_operations_form_remote_tag'
    app/helpers/application_helper.rb:221:in `pipeline_operations_blocking_form_remote_tag'
    app/views/pipelines/index.json.erb:97
    app/views/pipelines/index.json.erb:58
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-complete-1.5.0.jar!/builtin/java/java.lang.rb:19:in `each_with_index'
    app/views/pipelines/index.json.erb:56
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-complete-1.5.0.jar!/builtin/java/java.util.rb:21:in `call'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-complete-1.5.0.jar!/builtin/java/java.util.rb:21:in `each'
    app/views/pipelines/index.json.erb:54
    app/controllers/application_controller.rb:230:in `render_with_error_render_check'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/action_controller/session/java_servlet_store.rb:49:in `call'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/rack/adapter/rails.rb:36:in `serve_rails'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/rack/adapter/rails.rb:52:in `call'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/jruby/rack/rails.rb:149:in `call'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/rack/handler/servlet.rb:19:in `call'
    :1


On line #97 of app/views/pipelines/index.json.erb

    94:            scope[:trigger_with_option_label] = l.string('TRIGGER_WITH_OPTIONS')
    95:         -%>\n        <% _scope = {:pipeline_model=> scope[:pipeline_model], :label=>"#{scope[:trigger_label]}"}; -%><% _scope[:pipeline] = _scope[:pipeline_model].getLatestPipelineInstance() -%>\n<%= json_escape((pipeline_operations_blocking_form_remote_tag(:url => api_pipeline_action_path(:pipeline_name => _scope[:pipeline].getName(), :action => "schedule"),
    96:                     :html => {
    97:                         :onsubmit => "PipelineOperations.onTrigger(this, '#{_scope[:pipeline].getName()}', '#{api_pipeline_action_path(:pipeline_name => _scope[:pipeline].getName(), :action => "schedule")}'); return false;"
    98:                     }))) -%>\n    <div class='operate trigger_wrapper'>\n        <%= json_escape((submit_button(_scope[:label], {:type=> 'image', :disabled => !_scope[:pipeline_model].canForce(), :id => "deploy-#{_scope[:pipeline].getName()}"}))) -%>\n    </div>\n<%= json_escape((end_form_tag)) -%>\n\n        <% _scope = {:pipeline => scope[:pipeline_model].getLatestPipelineInstance(),
    99:                                                                                                  :label => "#{scope[:trigger_with_option_label]}",
    100:                                                                                                  :can_trigger => scope[:pipeline_model].canForce(),

    (eval):2:in `form_authenticity_token'
    app/helpers/application_helper.rb:265:in `form_tag'
    app/helpers/application_helper.rb:229:in `pipeline_operations_form_remote_tag'
    app/helpers/application_helper.rb:221:in `pipeline_operations_blocking_form_remote_tag'
    app/views/pipelines/index.json.erb:97
    app/views/pipelines/index.json.erb:58
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-complete-1.5.0.jar!/builtin/java/java.lang.rb:19:in `each_with_index'
    app/views/pipelines/index.json.erb:56
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-complete-1.5.0.jar!/builtin/java/java.util.rb:21:in `call'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-complete-1.5.0.jar!/builtin/java/java.util.rb:21:in `each'
    app/views/pipelines/index.json.erb:54
    app/controllers/application_controller.rb:230:in `render_with_error_render_check'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/action_controller/session/java_servlet_store.rb:49:in `call'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/rack/adapter/rails.rb:36:in `serve_rails'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/rack/adapter/rails.rb:52:in `call'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/jruby/rack/rails.rb:149:in `call'
    file:/var/vcap/store/gocd/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-0.9.6.jar!/rack/handler/servlet.rb:19:in `call'
    :1
```

We surmise that this is a startup race condition - someone tried to login before the SecureRandom module had been loaded into the JRuby/Java Runtime. We're not entirely sure, but it could be something that needs to be sorted.

Our GoCD version: 14.2.0(377-d8a2866d6af85e)

**Comment by arvindsv** [comment]
Closing. Old. Hasn't been reported again.
