### ISSUE TITLE
migration error from one kubernetes cluster to another

### ISSUE THREAD

**Issue by sherwinwangs** [gocd/gocd#7156]
##### Issue Type
- Bug Report

##### Summary
I've deploy gocd-server in kubernetes cluster with elastic agent,but when I tried to migrate to another kubernetes cluster I Got authorized error. 
I've got the same error in same kubernetes cluster when I run kubectl delete -f with the YAML file and apply to the cluster with the same YAML file.

##### Environment
Running gocd-server with elastic agent.

###### Basic environment details
OS: amazon linux
Kubernetes: 1.14.4

###### Additional Environment Details
None

##### Steps to Reproduce
1. setup gocd-server with elastic agent in kubernetes with RBAC
2. delete the RBAC Configuration, Deployment, Service, etc..
3. apply the same YAML file to the kubernetes cluster.
4. wait until service finish init and starting,then watch the gocd-server logs.

##### Expected Results
gocd-server can be success authroized with the service account token with kubernetes 

##### Actual Results
as the error log described:Failed to handle request cd.go.elastic-agent.server-ping
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.24.0.1/api/v1/namespaces/see/pods. Message: Unauthorized! 

##### Log snippets
log file: plugin-cd.go.contrib.elasticagent.kubernetes.log
log content:
```
2019-10-30 06:24:05,137 INFO  [Thread-81] KubernetesPlugin:72 - [Migrate Config] Request for Config Migration Started...
2019-10-30 06:24:05,150 INFO  [Thread-81] KubernetesPlugin:72 - [Migrate Config] No Plugin Settings are configured. Skipping Config Migration...
2019-10-30 06:24:40,260 ERROR [165@MessageListener for ServerPingListener] KubernetesPlugin:127 - Failed to handle request cd.go.elastic-agent.server-ping
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.24.0.1/api/v1/namespaces/see/pods. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
        at cd.go.contrib.elasticagent.KubernetesAgentInstances.refreshAll(KubernetesAgentInstances.java:150)
        at cd.go.contrib.elasticagent.KubernetesPlugin.refreshInstancesForCluster(KubernetesPlugin.java:134)
        at cd.go.contrib.elasticagent.KubernetesPlugin.refreshInstancesForAllClusters(KubernetesPlugin.java:124)
        at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:92)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:149)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
        at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.serverPing(ElasticAgentExtensionV5.java:152)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.serverPing(ElasticAgentExtension.java:64)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.serverPing(ElasticAgentPluginRegistry.java:52)
        at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:31)
        at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:84)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:64)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by arvindsv** [comment]
Hello. Are you using persistent volumes? What service token is configured in plugin settings? Is it the correct one (for the new cluster)?

**Comment by newbee9527** [comment]
@arvindsv The problem can be roughly described as follows: GoCD deployed in k8s, using NFS to persist the configuration file and pipeline information of GoCD, and need to migrate GoCD to another k8s for data retention. Use serviceaccount, the error message is shown above @sherwinwangs

**Comment by arvindsv** [comment]
@newbee9527 You should probably take a look at the security token then, in the cluster configuration. It's probably using that of the old one.

For instance, if you use the helm chart, it will [get the token](https://github.com/helm/charts/blob/8a5a143bad43e211ba0b8377ce08807b62378232/stable/gocd/templates/configmap.yaml#L15-L16) for the service account and then [configure the cluster to use that token](https://github.com/helm/charts/blob/8a5a143bad43e211ba0b8377ce08807b62378232/stable/gocd/templates/configmap.yaml#L41-L65).

**Comment by GaneshSPatil** [comment]
@newbee9527 @arvindsv -- The error `io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.24.0.1/api/v1/namespaces/see/pods. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.` happens when the specified service token does not have enough permissions or it has been revoked. In this particular case, the service token can not list the pod.

@newbee9527 -- can you try executing `kubectl auth can-i` commands for the permissions mentioned [here](https://github.com/gocd/kubernetes-elastic-agents/blob/master/install.md#configuration) for the new cluster.

eg: `kubectl auth can-i list pods --as=system:serviceaccount:default:default -n default`

**Comment by GaneshSPatil** [comment]
Hi @sherwinwangs -- Following up to check whether you're still facing the issue with GoCD Kubernetes elastic agent plugin? Do you need any further assistance with this issue?

**Comment by GaneshSPatil** [comment]
No Update, Marking Stale.

Closing...
