### ISSUE TITLE
Server throwing exception when retrieving environment variable from Vault

### ISSUE THREAD

**Issue by smithhannahm** [gocd/gocd#7157]
##### Issue Type

- Bug Report

##### Summary

When an environment variable is using the Vault plugin to retrieve a secret, the pipeline is never picked up by the agent, and the pipeline just hangs. There is a NumberFormatException that is produced in the server logs.

##### Environment

Go Server 19.9.0 in the official docker image, running in an on-premise Kubernetes, installed via the stable helm chart. Kubernetes Elastic Agent plugin (3.2.0-187) and Vault Secret Manager Plugin (1.0.0-23) are installed. 

A Secret config is specified for a Vault instance running in a different Kubernetes cluster, behind a registered domain address. An approle is configured for authentication, with an appropriate policy. 

The default `getting_started_pipeline` has been modified to include an environment variable that's value is specified by the secret management. 

###### Basic environment details

* Go Version: 19.9.0 (10194-34fca8f7682a65ef5fbd6726d51fd52b0c041bc6)
* JAVA Version: 12.0.1
* OS: Linux 4.14.128-rancher

###### Additional Environment Details

Vault version 1.1.2

##### Steps to Reproduce

1. Vault Secret config set up, using an approle authentication method
2. Default pipeline altered to include an environment variable, whose value is `{{SECRET:[sandbox][access_key]}}`
3. Kick off manual run of pipeline

##### Expected Results
The pipeline runs without issue, as no substantial changes have been made. (Simply adding an environment variable that isn't a secret doesn't affect the pipeline run at all).

##### Actual Results
The agent is provisioned and registered, but never picks up the pipeline. Instead server logs show a `java.lang.RuntimeException: java.lang.NumberFormatException: empty String` exception, repeating every 10 seconds.

Vault plugin logs show that Vault validation was successful.

##### Log snippets

```
2019-10-30 16:30:24,755 INFO  [ThreadPoolTaskScheduler-5] ScheduleService:161 - [Pipeline Schedule] Scheduling pipeline getting_started_pipeline with build cause [ManualForcedBuildCause: Forced by anonymous]
2019-10-30 16:30:24,777 INFO  [ThreadPoolTaskScheduler-5] PipelineRepository:82 - Start updating pipeline timeline
2019-10-30 16:30:24,781 INFO  [ThreadPoolTaskScheduler-5] PipelineRepository:88 - Pipeline timeline updated
2019-10-30 16:30:37,115 INFO  [qtp335383297-30] AgentRegistrationController:263 - [Agent Auto Registration] Auto registering agent with uuid bc607247-642b-45b2-a8fb-38315bef9f68
2019-10-30 16:30:39,741 INFO  [qtp335383297-31] BuildRepositoryRemoteImpl:122 - [Agent Cookie] Agent [Agent [gocd-agent-a8f7a085-5fab-4d13-968e-0b3168e6ca70, 10.42.2.2, bc607247-642b-45b2-a8fb-38315bef9f68]] at location [/go] asked for a new cookie, assigned [e93f5e98-51a3-4a12-a013-173c4e8236a3]
2019-10-30 16:30:39,772 ERROR [109@MessageListener for WorkFinder] JMSMessageListenerAdapter:88 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@32719e35
java.lang.RuntimeException: java.lang.NumberFormatException: empty String
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:309)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:149)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
        at com.thoughtworks.go.plugin.access.secrets.v1.SecretsExtensionV1.lookupSecrets(SecretsExtensionV1.java:101)
        at com.thoughtworks.go.plugin.access.secrets.SecretsExtension.lookupSecrets(SecretsExtension.java:79)
        at com.thoughtworks.go.server.service.SecretParamResolver.lambda$lookupAndUpdateSecretParamsValue$0(SecretParamResolver.java:89)
        at java.base/java.util.HashMap.forEach(Unknown Source)
        at com.thoughtworks.go.server.service.SecretParamResolver.resolve(SecretParamResolver.java:80)
        at com.thoughtworks.go.server.service.SecretParamResolver.resolve(SecretParamResolver.java:66)
        at com.thoughtworks.go.server.service.BuildAssignmentService.lambda$createWork$2(BuildAssignmentService.java:297)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$execute$1(TransactionTemplate.java:31)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:28)
        at com.thoughtworks.go.server.service.BuildAssignmentService.lambda$createWork$3(BuildAssignmentService.java:287)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.transactionSurrounding(TransactionTemplate.java:60)
        at com.thoughtworks.go.server.service.BuildAssignmentService.createWork(BuildAssignmentService.java:271)
        at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:180)
        at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:159)
        at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:60)
        at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:32)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:84)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:64)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: empty String
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at cd.go.plugin.base.GsonTransformer.fromJson(GsonTransformer.java:30)
        at com.thoughtworks.gocd.secretmanager.vault.SecretConfigLookupExecutor.parseRequest(SecretConfigLookupExecutor.java:69)
        at com.thoughtworks.gocd.secretmanager.vault.SecretConfigLookupExecutor.parseRequest(SecretConfigLookupExecutor.java:33)
        at cd.go.plugin.base.executors.secrets.LookupExecutor.execute(LookupExecutor.java:27)
        at cd.go.plugin.base.dispatcher.RequestDispatcher.lambda$dispatch$0(RequestDispatcher.java:41)
        at java.base/java.util.Optional.map(Unknown Source)
        at cd.go.plugin.base.dispatcher.RequestDispatcher.dispatch(RequestDispatcher.java:41)
        at com.thoughtworks.gocd.secretmanager.vault.VaultPlugin.handle(VaultPlugin.java:59)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
        ... 23 common frames omitted
Caused by: java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
        at java.base/java.lang.Double.parseDouble(Unknown Source)
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
        ... 42 common frames omitted
```

##### Any other info

Experimentation with the Vault path/key combination makes me believe that it is actually retrieving the secret, but running into an exception when it tries to insert the secret into the environment. Invalid paths return a 400 exception in the Vault logs, while valid paths return no such exception on Vault's side, only the above exception in the server logs.

**Comment by kritika-singh3** [comment]
Hi @smithhannahm, thanks for reporting. We have fixed the issue and created a stable release for the [plugin](https://github.com/gocd/gocd-vault-secret-plugin/releases/tag/v1.0.1-25). Please use the same and let us know if it fixed your problem.

**Comment by smithhannahm** [comment]
Yes, I updated the plugin and have gotten it working correctly. Thank you!
