### ISSUE TITLE
Bug: Agent Loses Contact - Connection Pool Shutdown

### ISSUE THREAD

**Issue by abbotware** [gocd/gocd#7407]
##### Issue Type

- Bug Report

##### Summary

Agent loses contact after some time.  

I have 2 identical agents (VM clones) one of them has this problem , the other doesn't.   This only started happening when I upgraded 

###### Basic environment details

    Go Version: 19.11.0
    JAVA Version: 13.0.1
    OS: Windows Server 2019 10.0

##### Steps to Reproduce

Not sire

##### Expected Results
Agent should stay alive

##### Actual Results
Agent loses contact and needs to be manually restarted

##### Log snippets

```
[scheduler-2] AgentHTTPClientController:103 - Error occurred when agent tried to ping server: 
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://10.10.10.50:8154/go/remoting/remoteBuildRepository]; nested exception is java.lang.IllegalStateException: Connection pool shut down
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:226)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy10.ping(Unknown Source)
	at com.thoughtworks.go.agent.AgentHTTPClientController.ping(AgentHTTPClientController.java:98)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:191)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:267)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.thoughtworks.go.agent.common.ssl.GoAgentServerHttpClient.execute(GoAgentServerHttpClient.java:54)
	at com.thoughtworks.go.agent.GoHttpClientHttpInvokerRequestExecutor.doExecuteRequest(GoHttpClientHttpInvokerRequestExecutor.java:78)
	at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:137)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:202)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:184)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:150)
	... 15 common frames omitted
```

**Comment by arvindsv** [comment]
Strange. I don't think I've seen this before. Do you have a proxy in between anywhere? What is the version of the GoCD server this agent is connecting to? Are there any relevant logs on the GoCD server?

The closest potential issue I could find is this: https://stackoverflow.com/questions/25889925/apache-poolinghttpclientconnectionmanager-throwing-illegal-state-exception

... but it doesn't match because I think we already use httpclient 4.5.6. That's why I'm considering something to do with the environment (setup) since you mention this happens only with one agent out of two identical agents.

**Comment by abbotware** [comment]
No proxy - the go server and about 5 agents (2 windows, 3 linux) are all contain on a single virtual network on a single vm farm.  I only noticed this going form go 19.7 to 19.10... and also on 19.11.

Id be more than happy to post the log files - please advise me on which ones I should capture.    I always see a lot of files and am not sure which ones are relevant.

I have worked around the problem - It seems that the agent service dies at some point - I set it up to restart on automatically on failure (windows services settings) and for the time being I am not 'seeing' the problem, but it may still be happening.
