### ISSUE TITLE
Revert following changes as part of 20.1.0 release

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7546]
##### Revert following Changes before `v20.1.0` release:
- [x] https://github.com/gocd/gocd/commit/b012df65bcac5bdf53909b8152cbfa17d2a633a6
- [x] https://github.com/gocd/gocd/pull/7562

The above-mentioned commit has been added to debug the flaky `JobRerunScheduleServiceTest > shouldUpdateServerHealthStateWhenCantSchedule`. 

This commit needs to be removed before the release to avoid printing stack traces to the error console.

**Comment by GaneshSPatil** [comment]
Here is the stack trace of the flaky test failure:

```
 java.lang.NullPointerException
	at com.thoughtworks.go.server.service.ScheduleService.internalRerun(ScheduleService.java:210)
	at com.thoughtworks.go.server.service.ScheduleService.lockAndRerunStage(ScheduleService.java:322)
	at com.thoughtworks.go.server.service.ScheduleService.rerunJobs(ScheduleService.java:344)
	at com.thoughtworks.go.server.service.JobRerunScheduleServiceTest.assertScheduleFailure(JobRerunScheduleServiceTest.java:345)
	at com.thoughtworks.go.server.service.JobRerunScheduleServiceTest.shouldUpdateServerHealthStateWhenCantSchedule(JobRerunScheduleServiceTest.java:201)
```

This is failing on [this](https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/ScheduleService.java#L210) line, where, `result.getServerHealthState()` is returning null.

However, after taking a deeper look at the test, it looks like [this](https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/ScheduleService.java#L209) `if` condition should not have executed as we've mocked `schedulingChecker.canRerunStage` method [here](https://github.com/gocd/gocd/blob/master/server/src/test-fast/java/com/thoughtworks/go/server/service/JobRerunScheduleServiceTest.java#L358) to return `true`.

Print some additional information as part of https://github.com/gocd/gocd/pull/7562 to debug this issue further. Initial suspicion is with the arguments, the difference in the arguments causing this method to return false!

**Comment by GaneshSPatil** [comment]
Additional information to debug this flaky test can be found at https://build.gocd.org/go/tab/build/detail/build-windows/4474/build-non-server/1/FastTests-runInstance-3 Job's console log.

```
Pipeline Identifier:Pipeline[name=mingle, counter=0, label=${COUNT}]

Stage Identifier:StageIdentifier[mingle, 1, LABEL-1, build, 1]

[schedulingCheckerService.canSchedule(
    com.thoughtworks.go.server.service.result.ServerHealthStateOperationResult@101a259b
;, schedulingCheckerService.shouldAllowSchedulingStage(
   com.thoughtworks.go.domain.Pipeline@1f,
   "build"
);, schedulingCheckerService.canRerunStage(
    Pipeline[name=mingle, counter=0, label=${COUNT}],
    "build",
    "bob-e44d4c03-a01e-4d81-921a-7a36da8626a3",
    com.thoughtworks.go.server.service.result.ServerHealthStateOperationResult@190a5e6c
]

canRerunStage: true
```

`schedulingCheckerService.canRerunStage` method was called with different arguments than with what it has been mocked. It should've been called with `anonymous` user instead of `bob-e44d4c03-a01e-4d81-921a-7a36da8626a3`.

This test fails only when APIControllerTests run before this test. As API controller tests performs `loginAsRandomUser`.

---

To reproduce this failure locally, add 
`SessionUtils.setCurrentUser(new GoUserPrinciple("bob-e44d4c03-a01e-4d81-921a-7a36da8626a3", "bob-e44d4c03-a01e-4d81-921a-7a36da8626a3", GoAuthority.ROLE_ANONYMOUS.asAuthority()));`
line [beforeEach](https://github.com/gocd/gocd/blob/master/server/src/test-fast/java/com/thoughtworks/go/server/service/JobRerunScheduleServiceTest.java#L69-L93) method.

**Comment by GaneshSPatil** [comment]
Done as part of https://github.com/gocd/gocd/pull/7563
