### ISSUE TITLE
Error upgrading GoCD agent with invalid agent-launcher loaded in class path

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#7569]
##### Issue Type

- Bug Report

##### Summary
```
sudo service go-agent console

Running go-agent...
wrapper  | The "wrapper.app.parameter.100" property was redefined on line #49 of configuration file: /usr/share/go-agent/wrapper-config/wrapper-properties.conf
wrapper  |   Old Value wrapper.app.parameter.100=-serverUrl
wrapper  |   New Value wrapper.app.parameter.100=-serverUrl
wrapper  | The "wrapper.app.parameter.101" property was redefined on line #50 of configuration file: /usr/share/go-agent/wrapper-config/wrapper-properties.conf
wrapper  |   Old Value wrapper.app.parameter.101=https://localhost:8154/go
wrapper  |   New Value wrapper.app.parameter.101=https://172.28.153.94:8154/go
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Standard Edition 64-bit 3.5.41
wrapper  |   Copyright (C) 1999-2019 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |   Licensed to ThoughtWorks for GoCD Agent On Linux
wrapper  |  
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | [Mon Jan 06 21:16:53 UTC 2020] Starting process:  
jvm 1    | [Mon Jan 06 21:16:53 UTC 2020]   Working directory    : /var/lib/go-agent
jvm 1    | [Mon Jan 06 21:16:53 UTC 2020]   Application arguments: [-serverUrl, https://172.28.153.94:8154/go]
jvm 1    | [Mon Jan 06 21:16:53 UTC 2020]            GoCD Version: 19.12.0-10888
jvm 1    | [Mon Jan 06 21:16:53 UTC 2020]            Java Version: 13.0.1
jvm 1    | [Mon Jan 06 21:16:53 UTC 2020]        Operating System: Linux(4.14.154-99.181.amzn1.x86_64)
jvm 1    | Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:onejar:lib/agent-bootstrapper-19.12.0-10888-classes.jar!/config/agent-bootstrapper-logback.xml'.
jvm 1    | SLF4J: Class path contains multiple SLF4J bindings.
jvm 1    | SLF4J: Found binding in [jar:onejar:lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: Found binding in [jar:file:/var/lib/go-agent/data/deps-9c739471f62c5995-agent-launcher.jar/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
jvm 1    | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
jvm 1    | Could not find file `config/agent-launcher-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:file:/var/lib/go-agent/data/deps-9c739471f62c5995-agent-launcher.jar/agent-launcher-18.1.0-5937-classes.jar!/config/agent-launcher-logback.xml'.
jvm 1    | java.lang.reflect.InvocationTargetException
jvm 1    | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | at com.thoughtworks.gocd.Boot.run(Boot.java:90)
jvm 1    | at com.thoughtworks.gocd.Boot.main(Boot.java:56)
jvm 1    | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
jvm 1    | at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
jvm 1    | at com.thoughtworks.go.agent.launcher.DownloadableFile.matchChecksum(DownloadableFile.java:72)
jvm 1    | at com.thoughtworks.go.agent.launcher.DownloadableFile.isChecksumEquals(DownloadableFile.java:79)
jvm 1    | at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:73)
jvm 1    | at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:90)
jvm 1    | at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
jvm 1    | at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
jvm 1    | at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
jvm 1    | at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:76)
jvm 1    | at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:57)
jvm 1    | at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
jvm 1    | at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:57)
jvm 1    | ... 12 more
jvm 1    | Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
jvm 1    | at java.base/java.net.URLClassLoader.findClass(Unknown Source)
jvm 1    | at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jvm 1    | at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
jvm 1    | ... 23 more
wrapper  | <-- Wrapper Stopped
```

**Comment by arvindsv** [comment]
I was able to reproduce this. Looks like it should be safe to remove the old agent-launcher.jar every time during an upgrade. This happened when upgrading from 18.1 to 19.12, because the old launcher was now invalid, with new Java version.
