### ISSUE TITLE
LDAP authentication doesn't work after upgrade

### ISSUE THREAD

**Issue by abhinav-chittora** [gocd/gocd#7614]
##### Issue Type
- Bug Report
##### Summary

Not able to login via LDAP credentials. I have upgrade gocd version from 17.x to 19.x (latest available) and after that LDAP credentials stopped working. 

##### Environment
```plain
"Go Server Information": {
    "Version": "19.12.0 (10888-29b0f854605987c8edab9dced4814b62dc751a11)"
  }
```

```plain
{
        "id": "cd.go.authentication.ldap",
        "type": [
          "authorization"
        ],
        "version": "2.0.1-90",
        "bundled_plugin": true,
        "status": {
          "state": "ACTIVE",
          "messages": [],
          "rootCauseIfInvalid": null
        }
      }
```

###### Basic environment details

* Go Version: `19.12.0 (10888-29b0f854605987c8edab9dced4814b62dc751a11).`
* JAVA Version: `13.0.1`
* OS: `Linux 3.10.0-1062.9.1.el7.x86_64`
* Browser vendor and version (if relevant): `NA`

##### Steps to Reproduce
1. Upgrade from 17.x to 19.x
2. 
3. 
4. 

##### Expected Results
LDAP credentials should be working. 

##### Actual Results
It doesn't accept LDAP credentials. 

##### Log snippets

```
2020-01-16 00:52:01,674 INFO  [Thread-80] LdapPlugin:72 - Loading plugin null version 2.0.1-90
2020-01-16 00:52:01,860 ERROR [Thread-80] LdapPlugin:127 - Error while executing request go.plugin-settings.get-configuration
com.thoughtworks.go.plugin.api.exceptions.UnhandledRequestTypeException: This is an invalid request type :go.plugin-settings.get-configuration
        at cd.go.plugin.base.dispatcher.RequestDispatcher.lambda$dispatch$1(RequestDispatcher.java:42)
        at java.base/java.util.Optional.orElseThrow(Unknown Source)
        at cd.go.plugin.base.dispatcher.RequestDispatcher.dispatch(RequestDispatcher.java:42)
        at cd.go.authentication.ldap.LdapPlugin.handle(LdapPlugin.java:68)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
        at com.thoughtworks.go.plugin.access.common.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:56)
        at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.lambda$findSettingsAndViewOfAllExtensionsIn$2(PluginSettingsMetadataLoader.java:84)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.findSettingsAndViewOfAllExtensionsIn(PluginSettingsMetadataLoader.java:89)
        at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:59)
        at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:49)
        at com.thoughtworks.go.plugin.infra.PluginLoader.lambda$doPostBundleInstallActivities$0(PluginLoader.java:114)
        at org.apache.commons.collections4.IteratorUtils.forEach(IteratorUtils.java:1224)
        at org.apache.commons.collections4.IterableUtils.forEach(IterableUtils.java:585)
        at com.thoughtworks.go.plugin.infra.PluginLoader.lambda$doPostBundleInstallActivities$1(PluginLoader.java:114)
        at org.apache.commons.collections4.IteratorUtils.forEach(IteratorUtils.java:1224)
        at org.apache.commons.collections4.IterableUtils.forEach(IterableUtils.java:585)
        at com.thoughtworks.go.plugin.infra.PluginLoader.doPostBundleInstallActivities(PluginLoader.java:113)
        at com.thoughtworks.go.plugin.infra.PluginLoader.loadPlugin(PluginLoader.java:71)
        at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:162)
        at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:105)
        at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:69)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.lambda$pluginJarAdded$0(DefaultPluginJarLocationMonitor.java:237)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:258)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:237)
        at com.thoughtworks.go.plugin.infra.monitor.PluginChangeNotifier.lambda$notify$0(PluginChangeNotifier.java:34)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at com.thoughtworks.go.plugin.infra.monitor.PluginChangeNotifier.notify(PluginChangeNotifier.java:31)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:204)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:191)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:177)
```

**Comment by adityasood** [comment]
@abhinav-chittora the error snippet you have shared has an error about a capability (plugin-settings) that the LDAP plugin does not implement and it is safe to ignore this.

Can you enable debug logs for your setup, restart your GoCD server, try logging in and share the debug logs here?

To enable debug logs, based on your OS you can find instructions [here](https://github.com/gocd/gocd-ldap-authentication-plugin#troubleshooting)

**Comment by adityasood** [comment]
@abhinav-chittora a quick update and something to note. With plugin version 2.0.1-90 we have changed the underlying library for the bundled plugin from JNDI to ApacheDs LDAP client for the authentication. A must change would be to now specify a fully qualified ManagerDN instead of just username.

Please ensure your configuration is updated before you verify the plugin.

You can troubleshoot this using ldapsearch tool and use the below query

```
ldapsearch -x -H ldap://ldap-hostname:389/ -b "<search-base>" -D "Manager_DN" -W "userPrincipalName =USERNAME"
```
