### ISSUE TITLE
Server upgrade to v19.12.0 fails when pipeline label template contains package material name

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7654]
##### Issue Type

- Bug Report

##### Summary

Upgrading server to `v19.12.0` fails when the pipeline label template contains package material name specified in format `${PACKAGE:REPO}`

###### Basic environment details

* Go Version: `v19.12.0`

##### Steps to Reproduce

1. Install GoCD Server `v19.11.0`
2.  Install any Package Repository Plugin. (Say `go-npm-poller`)
3. Define a Package Repository by visiting `go/admin/package_repositories/new` (Say `npm`)
4. Define a package material using `npm` repository. (Say `my-package`)
5. Define the pipeline label using package material name as `${npm:my-package}`
6. Verify configurations.
7. Upgrade GoCD Server to `v19.12.0`.
8. The server start fails with error `Error: You have defined a label template in pipeline 'up42' that refers to a material called 'npm:my-package', but no material with this name is defined.`

##### Expected Results
GoCD Server `v19.12.0` should start with configurations which were previously valid.

##### Actual Results
The server start up fails with error: `Error: You have defined a label template in pipeline 'up42' that refers to a material called 'npm:my-package', but no material with this name is defined.`

##### Possible Fix
Add an xml migration to migrate the labeltemplate from `${npm:my-package}` to `${npm_my-package}`

##### Additional Information

<details><summary>Use the following cruise-config.xml to reproduce this issue:</summary>
<p>

```xml
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="135">
  <server agentAutoRegisterKey="323040d4-f2e4-4b8a-8394-7a2d122054d1" webhookSecret="3d5cd2f5-7fe7-43c0-ba34-7e01678ba8b6" commandRepositoryLocation="default" serverId="60f5f682-5248-4ba9-bb35-72c92841bd75" tokenGenerationKey="8c3c8dc9-08bf-4cd7-ac80-cecb3e7ae86c">
    <security>
      <authConfigs>
        <authConfig id="9cad79b0-4d9e-4a62-829c-eb4d9488062f" pluginId="cd.go.authentication.passwordfile">
          <property>
            <key>PasswordFilePath</key>
            <value>config/password.properties</value>
          </property>
        </authConfig>
      </authConfigs>
      <roles>
        <role name="xyz" />
      </roles>
      <admins>
        <user>jez</user>
        <user>admin</user>
      </admins>
    </security>
    <backup emailOnSuccess="true" emailOnFailure="true" />
    <artifacts>
      <artifactsDir>artifacts</artifactsDir>
    </artifacts>
  </server>
  <repositories>
    <repository id="0c24bd20-2b24-4fba-9410-aea494d29bf5" name="npm">
      <pluginConfiguration id="npm" version="1" />
      <configuration>
        <property>
          <key>REPO_URL</key>
          <value>http://npmjs.com/</value>
        </property>
      </configuration>
      <packages>
        <package id="07951410-c70e-4a91-be53-8968cf0c07bc" name="my-package">
          <configuration>
            <property>
              <key>PACKAGE_ID</key>
              <value>v1.0.0</value>
            </property>
          </configuration>
        </package>
      </packages>
    </repository>
  </repositories>
  <pipelines group="first">
    <authorization>
      <view>
        <user>operate</user>
      </view>
      <admins>
        <user>operate</user>
      </admins>
    </authorization>
    <pipeline name="up42" labeltemplate="${npm:my-package}">
      <materials>
        <package ref="07951410-c70e-4a91-be53-8968cf0c07bc" />
      </materials>
      <stage name="up42_stage">
        <jobs>
          <job name="up42_job">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
</cruise>
```

</p>
</details>

<details><summary>Refer the following stack trace failure during upgrade</summary>
<p>

```
com.thoughtworks.go.config.exceptions.GoConfigInvalidException: You have defined a label template in pipeline 'up42' that refers to a material called 'npm:my-package', but no material with this name is defined.
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:137)
	at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:126)
	at com.thoughtworks.go.config.FullConfigSaveFlow.preprocessAndValidate(FullConfigSaveFlow.java:97)
	at com.thoughtworks.go.config.FullConfigSaveNormalFlow.execute(FullConfigSaveNormalFlow.java:59)
	at com.thoughtworks.go.config.GoConfigMigrator.upgradeConfigFile(GoConfigMigrator.java:110)
	at com.thoughtworks.go.config.GoConfigMigrator.upgrade(GoConfigMigrator.java:96)
	at com.thoughtworks.go.config.GoConfigMigrator.migrate(GoConfigMigrator.java:87)
	at com.thoughtworks.go.config.CachedGoConfig.upgradeConfig(CachedGoConfig.java:148)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:116)
	at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:51)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:959)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:924)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:510)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:153)
	at com.thoughtworks.go.server.Jetty9Server.startHandlers(Jetty9Server.java:183)
	at com.thoughtworks.go.server.Jetty9Server.start(Jetty9Server.java:133)
	at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:67)
	at com.thoughtworks.go.server.DevelopmentServer.main(DevelopmentServer.java:67)
There are errors in the Cruise config file.  Please read the error message and correct the errors.
Once fixed, please restart GoCD.
Error: You have defined a label template in pipeline 'up42' that refers to a material called 'npm:my-package', but no material with this name is defined.
```

</p>
</details>

### Cause of failure and Workaround

As part of GoCD release `v19.12.0`, We've fixed the issue https://github.com/gocd/gocd/issues/7345 where and invalid export configurations were generated for pipelines having package repository materials. To fix this issue, we've changed the package material name representation from `repo:package` to `repo_package`, as `:` is not supported in GoCD material name.

The above mentioned changes causes `repo:package` material name being invalid in GoCD `v19.12.0`, causing server startup to fail.

As a workaround to this, users are required to modify the `cruise-config.xml` manually and change the pipeline template name from `${repo:package}` to `${repo_package}`.

**Comment by GaneshSPatil** [comment]
## Issue 2: After 19.12.0 Upgrade, Package Repositories can possibly result into duplicate material name

##### Issue Type

- Bug Report

##### Summary

Upgrading GoCD server to `v19.12.0` can possibly result into duplicate material names for different package repositories.

As part of GoCD `v19.12.0`, the material name representation for package repository materials has been changed from `repo:package` to `repo_package`.
Following example demonstrates the conflicting name scenario:

* Repo: `npm`          Package: `my_package`
* Repo: `npm_my`   Package: `package`

| REPO              |     PACKAGE    | Material Name in `v19.11.0` | Material Name in `v19.12.0` |
| ------------- |---------------| --------------------------- |-----------------------------|
| npm                | my_package    | `npm:my_package`              | `npm_my_package`               |
| npm_my        | package            | `npm_my:package`              | `npm_my_package`               |


**Note:** There is no unique name validations in GoCD for SCM and Package Repository Materials (Issue: https://github.com/gocd/gocd/issues/1883), hence the above mentioned configuration is valid.

#### Whereas, the above mentioned configurations can have unintended behavior for Pipeline Label specified as material name.


###### Basic environment details

* Go Version: `v19.12.0`

##### Steps to Reproduce

1. Install GoCD Server `v19.11.0`
2.  Install any Package Repository Plugin. (Say `go-npm-poller`)
3. Define `npm` Package Repository by visiting `go/admin/package_repositories/new`
4. Define `npm_my` Package Repository by visiting `go/admin/package_repositories/new`
5. Define a pipeline.
6. Define a `my_package` package material using `npm` repository. (`npm:my_package`)
7. Define a `package` package material using `npm_my` repository.(`npm_my:package`)
8. Define the pipeline label using the second package material name as `${npm_my:package}`
9. Trigger the pipeline to verify appropriate pipeline label is set.
10. Upgrade GoCD Server to `v19.12.0`.
11. The server start fails with error `Error: You have defined a label template in pipeline 'up42' that refers to a material called 'npm_my:package', but no material with this name is defined.`
12. Change package from `${npm_my:package}` to `${npm_my_package}`
13. Restart GoCD Server.
14. Trigger the pipeline. The pipeline will be triggered with the first material (repo: `npm`, package: `my_package`) as it is the first material matching the label template `${npm_my_package}`


##### Additional Information

<details><summary>Use the following cruise-config.xml to reproduce this issue:</summary>
<p>

```xml
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="134">
  <server agentAutoRegisterKey="323040d4-f2e4-4b8a-8394-7a2d122054d1" webhookSecret="3d5cd2f5-7fe7-43c0-ba34-7e01678ba8b6" commandRepositoryLocation="default" serverId="60f5f682-5248-4ba9-bb35-72c92841bd75" tokenGenerationKey="8c3c8dc9-08bf-4cd7-ac80-cecb3e7ae86c">
    <security>
      <authConfigs>
        <authConfig id="9cad79b0-4d9e-4a62-829c-eb4d9488062f" pluginId="cd.go.authentication.passwordfile">
          <property>
            <key>PasswordFilePath</key>
            <value>config/password.properties</value>
          </property>
        </authConfig>
      </authConfigs>
      <roles>
        <role name="xyz" />
      </roles>
      <admins>
        <user>jez</user>
        <user>admin</user>
      </admins>
    </security>
    <backup emailOnSuccess="true" emailOnFailure="true" />
    <artifacts>
      <artifactsDir>artifacts</artifactsDir>
    </artifacts>
  </server>
  <repositories>
    <repository id="010e815e-0ae0-480f-ab10-5254851e3c4a" name="npm">
      <pluginConfiguration id="npm" version="1" />
      <configuration>
        <property>
          <key>REPO_URL</key>
          <value>http://registry.npmjs.org</value>
        </property>
        <property>
          <key>USERNAME</key>
          <value>admin</value>
        </property>
        <property>
          <key>PASSWORD</key>
          <value>password</value>
        </property>
      </configuration>
      <packages>
        <package id="c523dd70-be48-4d35-acf8-7518d16a50cf" name="my_package">
          <configuration>
            <property>
              <key>PACKAGE_ID</key>
              <value>underscore</value>
            </property>
          </configuration>
        </package>
      </packages>
    </repository>
    <repository id="576cd16d-138d-4356-8b1c-e6c7a86238b6" name="npm_my">
      <pluginConfiguration id="npm" version="1" />
      <configuration>
        <property>
          <key>REPO_URL</key>
          <value>http://registry.npmjs.org</value>
        </property>
      </configuration>
      <packages>
        <package id="d6e166e0-13e9-4624-8c51-730facea4ec0" name="package">
          <configuration>
            <property>
              <key>PACKAGE_ID</key>
              <value>gocd</value>
            </property>
          </configuration>
        </package>
      </packages>
    </repository>
  </repositories>
  <pipelines group="defaultGroup">
    <pipeline name="pipeline" labeltemplate="${npm_my_package}">
      <materials>
        <package ref="c523dd70-be48-4d35-acf8-7518d16a50cf" />
        <package ref="d6e166e0-13e9-4624-8c51-730facea4ec0" />
      </materials>
      <stage name="stage">
        <jobs>
          <job name="job">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
</cruise>
```

</p>
</details>

##### Problem with Plugin exported Environment Variables:

**For all versions of GoCD, with the above-mentioned Package and Repository names, invalid plugin environment variables are exported.**

Most of the Package Repository plugins makes Package and Repository Name information available as Environment Variables of the Job in the following format:
```
GO_PACKAGE_<REPO-NAME>_<PACKAGE-NAME>_LABEL
GO_REPO_<REPO-NAME>_<PACKAGE-NAME>_REPO_URL
GO_PACKAGE_<REPO-NAME>_<PACKAGE-NAME>_PACKAGE_ID
GO_PACKAGE_<REPO-NAME>_<PACKAGE-NAME>_LOCATION
GO_PACKAGE_<REPO-NAME>_<PACKAGE-NAME>_VERSION
```

As the combination of multiple Repo Name and Package Name with underscore (`_`) can result into the same value, the above-mentioned Environment Variables will not have expected values.


### Workaround

As a workaround to this issue, users are recommended to use hypens (`-`) for Package and Repository names, instead of underscores (`_`).

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/7659 in GoCD release v20.1.0
