### ISSUE TITLE
Modification check failed for material:  special characters are not allowed

### ISSUE THREAD

**Issue by gmaclinuxer** [gocd/gocd#7752]
##### Issue Type

Bug Report

##### Summary

This is the detail error log
```
2020-02-19 00:00:27,356 WARN  [132@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:127 - [Material Update] Modification check failed for material: URL: , Branch: master
    2 org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
    3     at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67)
    4     at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:45)
    5     at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
    6     at com.thoughtworks.go.domain.materials.git.GitModificationParser.parse(GitModificationParser.java:34)
    7     at com.thoughtworks.go.domain.materials.git.GitCommand.gitLog(GitCommand.java:133)
    8     at com.thoughtworks.go.domain.materials.git.GitCommand.modificationsSince(GitCommand.java:116)
    9     at com.thoughtworks.go.config.materials.git.GitMaterial.modificationsSince(GitMaterial.java:135)
   10     at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:35)
   11     at com.thoughtworks.go.server.service.materials.GitPoller.modificationsSince(GitPoller.java:26)
   12     at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:128)
   13     at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:56)
   14     at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:157)
   15     at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:149)
   16     at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:108)
   17     at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:23)
   18     at com.thoughtworks.go.server.transaction.TransactionTemplate.lambda$executeWithExceptionHandling$2(TransactionTemplate.java:43)
   19     at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
   20     at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:40)
   21     at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:105)
   22     at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:64)
   23     at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:32)
   24     at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
   25     at com.thoughtworks.go.server.messaging.activemq.J
```

The commit message has some special chars like `^M` and `^A`，which come from a git commit on windows system

```

commit 858ec1a86643436bad730cb6a3d213d6fbc546ab
Date:   Fri Feb 14 13:50:05 2020 +0800

    Merge branch 'km' of xxxxx
    
     Conflicts:
    	itsm/km/constants.py
    	itsm/km/models/classification.py
```

###### Basic environment details

```
304 INFO   | jvm 1    | 2020/02/19 17:03:41 | [Wed Feb 19 17:03:41 CST 2020]   Working directory    : /var/lib/go-server
305 INFO   | jvm 1    | 2020/02/19 17:03:41 | [Wed Feb 19 17:03:41 CST 2020]   Application arguments: []
306 INFO   | jvm 1    | 2020/02/19 17:03:41 | [Wed Feb 19 17:03:41 CST 2020]            GoCD Version: 20.1.0-11114
307 INFO   | jvm 1    | 2020/02/19 17:03:41 | [Wed Feb 19 17:03:41 CST 2020]            Java Version: 13.0.1
308 INFO   | jvm 1    | 2020/02/19 17:03:41 | [Wed Feb 19 17:03:41 CST 2020]        Operating System: Linux(3.10.0-693.el7.x86_64)
```
##### Steps to Reproduce

1. Create a pipeline with a git material
2. Add a few commit
3. Make a new commit that starts contains special chars or pull a branch on windows system and create auto conflict merge commit message like 
```
    Merge branch 'develop' of xxx into xxx
    
     Conflicts:
    	itsm/km/constants.py
    	itsm/km/models/classification.py
```
4. See gocd error

##### Expected Result

Normally notice the modification and build the pipeline

##### Actual Results

GoCD errors and no longer pulls any further changes from the material/repository.

Error notify is: `special characters are not allowed`

![image](https://user-images.githubusercontent.com/14108137/74825068-3cbb2280-5344-11ea-8ca6-ab91d201b950.png)

**Comment by arvindsv** [comment]
Adding a note here to verify that this is fixed in 20.2.0, by https://github.com/gocd/gocd/pull/7714 and also to verify that carriage return and line feed characters don't cause problems.

**Comment by arvindsv** [comment]
Here are a couple of scenarios we should check:

Scenario 1: Fails in 20.1.0 and in latest experimental build of 20.2.0 (as of now):
```
echo -e 'Hello \a There' >commit-message.txt
date >>abc.txt
git commit -F commit-message.txt abc.txt
```

Scenario 1: Succeeds in both 20.1.0 and in latest experimental build of 20.2.0 (as of now):
```
echo -n -e 'Hello There\r\nAnother Line\nHow about just CR?\r' >commit-message.txt
date >>abc.txt
git commit -F commit-message.txt abc.txt
```

**Comment by marques-work** [comment]
@arvindsv I think I have something working using an XML escaper (yaml accepts XML entity escapes; JSON escaping escapes too many things (e.g., `\n` that break the parser).

**Comment by marques-work** [comment]
Seems to parse just fine:

```bash
printf 'hello \x01 \a there.\n' > commit.txt
date >> blah.txt
git commit -F commit.txt -- blah.txt
```

**Comment by marques-work** [comment]
Instead of escaping, we decided to just revert to the pre-yaml implementation

**Comment by felipedss** [comment]
did this work for anyone?
