### ISSUE TITLE
Placeholder issue for removal of default SSL support

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#7766]
##### Issue Type

- Bug Report

##### Summary

All issues related to this PR - https://github.com/gocd/gocd/pull/7669 - will be captured in this issue

- [x] GoCD Server upgrade fails. More details in this [comment](https://github.com/gocd/gocd/issues/7766#issuecomment-589595794)
- [x] Setting the system property `-Dgo.server.enable.tls=true` does not enable default TLS. Expected the default TLS with self signed certificates to be created and server listen on 8154 port
- [x] GoCD agent wrapper-properties.conf file still has default `-serverUrl` parameter set to `https://localhost:8154/go`. Due to this the agent connection on first start will fail. Since we have removed the support for 8154, it should be ideally removed from agent properties too. IMO  better approach will be not to set the `-serverUrl` property make it mandatory for the user to specify on agent startup

**Comment by rajiesh** [comment]
An upgrade from stable version `20.1.0-11114` to build `20.2.0-11230` fails with below error in `go-server-wrapper.log` file,

```
STATUS | wrapper  | 2020/02/20 09:20:57 | Launching a JVM...
INFO   | jvm 1    | 2020/02/20 09:20:57 | WrapperManager: Initializing...
INFO   | jvm 1    | 2020/02/20 09:20:57 | [Thu Feb 20 09:20:57 UTC 2020] Starting process:
INFO   | jvm 1    | 2020/02/20 09:20:57 | [Thu Feb 20 09:20:57 UTC 2020]   Working directory    : /var/lib/go-server
INFO   | jvm 1    | 2020/02/20 09:20:57 | [Thu Feb 20 09:20:57 UTC 2020]   Application arguments: []
INFO   | jvm 1    | 2020/02/20 09:20:57 | [Thu Feb 20 09:20:57 UTC 2020]            GoCD Version: 20.2.0-11230
INFO   | jvm 1    | 2020/02/20 09:20:57 | [Thu Feb 20 09:20:57 UTC 2020]            Java Version: 13.0.1
INFO   | jvm 1    | 2020/02/20 09:20:57 | [Thu Feb 20 09:20:57 UTC 2020]        Operating System: Linux(4.19.76-linuxkit)
INFO   | jvm 1    | 2020/02/20 09:20:58 | Could not find file `/etc/go/logback.xml'. Attempting to load from classpath.
INFO   | jvm 1    | 2020/02/20 09:20:58 | Using classpath resource `jar:onejar:lib/server-launcher-20.2.0-11230-main.jar!/config/logback.xml'.
INFO   | jvm 1    | 2020/02/20 09:21:00 | WARNING: An illegal reflective access operation has occurred
INFO   | jvm 1    | 2020/02/20 09:21:00 | WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (onejar:lib/bcprov-jdk15on-1.59.jar) to constructor sun.security.provider.Sun()
INFO   | jvm 1    | 2020/02/20 09:21:00 | WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
INFO   | jvm 1    | 2020/02/20 09:21:00 | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
INFO   | jvm 1    | 2020/02/20 09:21:00 | WARNING: All illegal access operations will be denied in a future release
INFO   | jvm 1    | 2020/02/20 09:21:00 | java.lang.reflect.InvocationTargetException
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at com.thoughtworks.gocd.Boot.run(Boot.java:90)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at com.thoughtworks.gocd.Boot.main(Boot.java:56)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 | Caused by: java.lang.NoClassDefFoundError: com/thoughtworks/go/CurrentGoCDVersion
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at com.thoughtworks.go.server.Jetty9Server.configure(Jetty9Server.java:82)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at com.thoughtworks.go.server.GoServer.configureServer(GoServer.java:79)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:66)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at com.thoughtworks.go.server.GoServer.go(GoServer.java:59)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:42)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       ... 12 more
INFO   | jvm 1    | 2020/02/20 09:21:00 | Caused by: java.lang.ClassNotFoundException: com.thoughtworks.go.CurrentGoCDVersion
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/java.net.URLClassLoader.findClass(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2020/02/20 09:21:00 |       ... 17 more
STATUS | wrapper  | 2020/02/20 09:21:02 | <-- Wrapper Stopped
```

**Comment by ketan** [comment]
>  Setting the system property `-Dgo.server.enable.tls=true` does not enable default TLS. Expected the default TLS with self signed certificates to be created and server listen on 8154 port

This is intentional. Presence of self-signed certs, implies an upgrade. A fresh installation with `-Dgo.server.enable.tls=true` will not work as expected.

**Comment by rajiesh** [comment]
Verified on 20.2.0 (11289-c2cec4753bc4845894bb88ba70528721f23f2f9d)
