### ISSUE TITLE
Error uploading artifacts

### ISSUE THREAD

**Issue by aliensojurner** [gocd/gocd#8253]
##### Issue Type

Bug report

##### Summary

Whenever we run a build after setting up a reverse proxy, only some of the final artifacts are actually uploaded. I would think  that if any failed then all would fail but there are large and small files that upload properly and other large and small files fail to upload. It's giving a 404 error on some files while other files upload just fine. File size does not seem to be an issue. 
###### Basic environment details

* Go Version: `20.1`
* JAVA Version: `13`
* OS: `Windows server 2012R2`

##### Steps to Reproduce

We run a build and once the build is successful it starts to upload all the artifacts including the installer files. 
It uploads the individual executables and other files but when it gets to the installers themselves it fails to find them in the place they have always been at. 

##### Expected Results
All artifacts should upload back to the Go Server
##### Actual Results
Most upload and then others fail even though all files are present on the agent to be uploaded to the buildserver
Here you can see a file that uploads properly - 2020-06-22 09:51:15,492 INFO  [scheduler-1] HttpService:71 - Uploading file [C:\Program Files (x86)\Go Agent\data\cruise-11e646de-948d-4dd7-9e1a-bc1b13c1a64d\d0585926-1da7-44aa-b5a6-dd4d36ab4e0d\install_files.zip.zip] to url [https://go.exposure.software/go/remoting/files/productname/318/build/1/windows64/?attempt=1&buildId=414790]
2020-06-22 09:51:16,049 INFO  [scheduler-1] HttpService:129 - Got back 201 from server

##### Log snippets
[](url)

```
long log lines go here
```
-->

##### Code snippets/Screenshots

If you would like to share any code/screenshots please add it here.
Do mask any confidential information which you don't want to be shared.
Remember to surround them in 3 backticks like this —

```
java.lang.RuntimeException: Failed to upload C:\Program Files (x86)\Go Agent\pipelines\productname\AlienInstaller\win\build\Release\installer_win.  HTTP return code is 404
	at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:29)
	at com.thoughtworks.go.publishers.GoArtifactsManipulator.publish(GoArtifactsManipulator.java:105)
	at com.thoughtworks.go.work.DefaultGoPublisher.upload(DefaultGoPublisher.java:68)
	at com.thoughtworks.go.domain.ArtifactPlan.uploadArtifactFile(ArtifactPlan.java:169)
	at com.thoughtworks.go.domain.ArtifactPlan.publishBuildArtifact(ArtifactPlan.java:143)
	at com.thoughtworks.go.domain.ArtifactPlan.publishBuiltInArtifacts(ArtifactPlan.java:131)
	at com.thoughtworks.go.remote.work.artifact.ArtifactsPublisher.publishArtifacts(ArtifactsPublisher.java:75)
	at com.thoughtworks.go.remote.work.BuildWork.completeJob(BuildWork.java:197)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:129)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:79)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveWork(AgentHTTPClientController.java:147)
	at com.thoughtworks.go.agent.AgentHTTPClientController.work(AgentHTTPClientController.java:119)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:84)
	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)```

**Comment by maheshp** [comment]
We would need more information to understand this, can you please share the entire log statements  from ```go-agent.log``` and ```go-server.log``` when the upload fails?
