### ISSUE TITLE
Error fetching artifact

### ISSUE THREAD

**Issue by hakito** [gocd/gocd#8347]
##### Issue Type
- Bug Report

##### Summary

The agent fails to download _bigger_ artifacts. It seems it's because the server thinks the agent is idle. But the agent isn't.

```
##|15:42:53.890 [go] Start to build ToolSuite-4.1/4.1.0.351/Tests/1/IntegrationTests on WinXBuild1 [C:\Go\InteractiveSession]
!!|15:42:53.937 [go] Task: fetch artifact [SapUtil.IntegrationTests] => [] from [ToolSuite-4.1/Build/Build]
&1|15:42:53.937 [go] Fetching artifact [SapUtil.IntegrationTests] from [ToolSuite-4.1/4.1.0.351/Build/latest/Build]
&2|15:45:44.800 [go] Could not fetch artifact http://sibm1.sux.local:8153/go/remoting/files/ToolSuite-4.1/351/Build/latest/Build/SapUtil.IntegrationTests.zip. Pausing 20 seconds to retry. Error was : Caught an exception 'Premature end of Content-Length delimited message body (expected: 24101845; received: 12812288'
```

The received size might differ
```
&2|15:31:21.903 [go] Could not fetch artifact http://sibm1.sux.local:8153/go/remoting/files/ToolSuite-4.1/351/Build/latest/Build/SapUtil.IntegrationTests.zip. Pausing 12 seconds to retry. Error was : Caught an exception 'Premature end of Content-Length delimited message body (expected: 24101845; received: 8585216'
```

##### Environment

``` 
 "Go Server Information": {
    "Version": "20.5.0 (11820-1c9b12ac8aa216a2c062fbec4cba18d9cfb8b404)"
  },
```

###### Basic environment details

* Go Version: 20.5.0 (11820-1c9b12ac8aa216a2c062fbec4cba18d9cfb8b404)
* JAVA Version: 13.0.2
* OS: Windows Server 2019 10.0

###### Additional Environment Details

Agent runs in a Windows Hyper-V container.

##### Expected Results
Artifacts Fetched

##### Actual Results
Exception

##### Possible Fix

Download the zip file at once before unpacking the files.

##### Log snippets
Server Log
```
G:\Server\artifacts\cache\artifacts\pipelines\ToolSuite-4.1\353\Build\1\Build\SapUtil.IntegrationTests.zip. ShouldZip? = false
2020-07-17 07:16:04,772 WARN  [qtp188316009-30] HttpChannel:587 - handleException /go/remoting/files/ToolSuite-4.1/353/Build/latest/Build/SapUtil.IntegrationTests.zip java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
```

Agent Log
```
2020-07-16 15:45:44,675 INFO  [scheduler-1] DirHandler:60 - [Agent Fetch Artifact] Downloading a directory from 'SapUtil.IntegrationTests' to 'C:\Go\InteractiveSession\pipelines\ToolSuite-4.1'. Handling the entry: 'SapUtil.IntegrationTests/net462/System.Globalization.dll'
2020-07-16 15:45:44,784 ERROR [scheduler-1] ZipUtil:159 - Failed to unzip file [SapUtil.IntegrationTests/net462/System.Globalization.Extensions.dll] to directory [C:\Go\InteractiveSession\pipelines\ToolSuite-4.1]
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 24101845; received: 12812288
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:183)
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:243)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:195)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at com.thoughtworks.go.util.ZipUtil.extractTo(ZipUtil.java:141)
	at com.thoughtworks.go.util.ZipUtil.unzip(ZipUtil.java:119)
	at com.thoughtworks.go.domain.DirHandler.handle(DirHandler.java:62)
	at com.thoughtworks.go.util.HttpService.download(HttpService.java:102)
	at com.thoughtworks.go.domain.DownloadAction.download(DownloadAction.java:73)
	at com.thoughtworks.go.domain.DownloadAction.perform(DownloadAction.java:47)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.pullArtifact(FetchArtifactBuilder.java:65)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.downloadArtifact(FetchArtifactBuilder.java:56)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.fetch(FetchArtifactBuilder.java:51)
	at com.thoughtworks.go.publishers.GoArtifactsManipulator.fetch(GoArtifactsManipulator.java:168)
	at com.thoughtworks.go.work.DefaultGoPublisher.fetch(DefaultGoPublisher.java:72)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.build(FetchArtifactBuilder.java:46)
	at com.thoughtworks.go.remote.work.Builders.build(Builders.java:73)
	at com.thoughtworks.go.remote.work.BuildWork.execute(BuildWork.java:208)
	at com.thoughtworks.go.remote.work.BuildWork.buildJob(BuildWork.java:181)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:129)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:79)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveWork(AgentHTTPClientController.java:149)
	at com.thoughtworks.go.agent.AgentHTTPClientController.work(AgentHTTPClientController.java:121)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2020-07-16 15:45:44,784 ERROR [scheduler-1] HttpService:109 - Error while downloading [http://sibm1.sux.local:8153/go/remoting/files/ToolSuite-4.1/351/Build/latest/Build/SapUtil.IntegrationTests.zip]
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 24101845; received: 12812288
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:183)
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:243)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:195)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at com.thoughtworks.go.util.ZipUtil.extractTo(ZipUtil.java:141)
	at com.thoughtworks.go.util.ZipUtil.unzip(ZipUtil.java:119)
	at com.thoughtworks.go.domain.DirHandler.handle(DirHandler.java:62)
	at com.thoughtworks.go.util.HttpService.download(HttpService.java:102)
	at com.thoughtworks.go.domain.DownloadAction.download(DownloadAction.java:73)
	at com.thoughtworks.go.domain.DownloadAction.perform(DownloadAction.java:47)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.pullArtifact(FetchArtifactBuilder.java:65)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.downloadArtifact(FetchArtifactBuilder.java:56)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.fetch(FetchArtifactBuilder.java:51)
	at com.thoughtworks.go.publishers.GoArtifactsManipulator.fetch(GoArtifactsManipulator.java:168)
	at com.thoughtworks.go.work.DefaultGoPublisher.fetch(DefaultGoPublisher.java:72)
	at com.thoughtworks.go.domain.builder.FetchArtifactBuilder.build(FetchArtifactBuilder.java:46)
	at com.thoughtworks.go.remote.work.Builders.build(Builders.java:73)
	at com.thoughtworks.go.remote.work.BuildWork.execute(BuildWork.java:208)
	at com.thoughtworks.go.remote.work.BuildWork.buildJob(BuildWork.java:181)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:129)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:79)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveWork(AgentHTTPClientController.java:149)
	at com.thoughtworks.go.agent.AgentHTTPClientController.work(AgentHTTPClientController.java:121)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by arvindsv** [comment]
Strange:

```
&1|15:42:53.937 [go] Fetching artifact [SapUtil.IntegrationTests] from [ToolSuite-4.1/4.1.0.351/Build/latest/Build]
&2|15:45:44.800 [go] Could not fetch artifact http://sibm1.sux.local:8153/go/remoting/files/ToolSuite-4.1/351/Build/latest/Build/SapUtil.IntegrationTests.zip. Pausing 20 seconds to retry. Error was : Caught an exception 'Premature end of Content-Length delimited message body (expected: 24101845; received: 12812288'
```

It seems like it took nearly 2 minutes before it failed, to download just 24MB. You might need to go deeper into the network or maybe the VM is getting swapped out or something. I've seen agents regularly download 100s of MBs without any problems. 

You might also want to try bringing up an agent locally (local to the server) and see if this happens there as well. If it does, maybe it's nothing to do with the network.
