### ISSUE TITLE
Dashboard/UI is slow post upgrade to 20.5

### ISSUE THREAD

**Issue by m4ver1k** [gocd/gocd#8421]
##### Summary

We were running gocd 19.5 and recently upgraded to 20.5,

Procedure followed:
- Upgraded to 20.4
- Ran database-migrator 
- Upgraded to 20.5

`Post this the dashboard/UI of gocd is slow`
API calls to server eg: https://gocdhost/go/pipelineHistory.json?pipelineName=<pipeline-name>&start=0 takes 20+sec and in some cases more than a minute to load.

##### Environment
We are running gocd on Kubernetes. 

```plain

"Config Statistics": {
"Valid Config": {
"Number of pipelines": 476,
"Number of environments": 0,
"Number of agents": 1,
"Number of unique materials": 294,
"Number of schedulable materials": 297
},
"Security": {
"Plugins": [
{
"Google oauth authorization plugin": true
},
{
"Password File Authentication Plugin for GoCD": true
},
{
"LDAP Authentication Plugin for GoCD": false
}
],
"Enabled": true
}
},
"Config file locations": {
"loc.config.dir": "/go-working-dir/config",
"loc.log.root.0": "/go-working-dir/logs",
"loc.log.basename.0": "go-server.log",
"loc.log.root.2": "/go-working-dir/logs",
"loc.log.basename.2": "plugin-cd.go.artifact.docker.registry.log",
"loc.log.root.4": "/go-working-dir/logs",
"loc.log.basename.4": "plugin-cd.go.authentication.ldap.log",
"loc.log.root.6": "/go-working-dir/logs",
"loc.log.basename.6": "plugin-cd.go.authentication.passwordfile.log",
"loc.log.root.8": "/go-working-dir/logs",
"loc.log.basename.8": "plugin-cd.go.authorization.google.log",
"loc.log.root.10": "/go-working-dir/logs",
"loc.log.basename.10": "plugin-cd.go.contrib.elasticagent.kubernetes.log"
},
"OS Information": {
"OS Name": "Linux",
"OS Version": "4.14.171+",
"System Architecture": "amd64",
"Available Processors": 1,
"Average System Load": 0.46
},
"Runtime Information": {
"Name": "137@gocd-backend-server-779464f777-wmrhs",
"Uptime": 11298274,
"Uptime (in Time Format)": "[About 3 hours, 8 minutes, 18 seconds]",
"Spec Name": "Java Virtual Machine Specification",
"Spec Vendor": "Oracle Corporation",
"Spec Version": "13",
"Input Arguments": [
"-Xms512m",
"-Xmx1024m",
"-XX:MaxMetaspaceSize=400m",
"-Duser.language=en",
"-Duser.country=US",
"-Djruby.rack.request.size.threshold.bytes=30000000",
"-Xms1024m",
"-Xmx3072m",
"-Dgo.console.stdout=true",
"-Djava.library.path=wrapper",
"-Dwrapper.key=AghS3rp_vDrUPeo-eDeQMq_H1evz27DN",
"-Dwrapper.port=32000",
"-Dwrapper.jvm.port.min=31000",
"-Dwrapper.jvm.port.max=31999",
"-Dwrapper.pid=124",
"-Dwrapper.version=3.5.41-st",
"-Dwrapper.native_library=wrapper",
"-Dwrapper.arch=x86",
"-Dwrapper.cpu.timeout=10",
"-Dwrapper.jvmid=1",
"-Dwrapper.lang.domain=wrapper",
"-Dwrapper.lang.folder=../lang"
],
"System Properties": {
"file.encoding": "UTF-8",
"file.separator": "/",
"go.console.stdout": "true",
"java.class.path": "wrapper/wrapper.jar:lib/go.jar",
"java.class.version": "57.0",
"java.home": "/gocd-jre",
"java.io.tmpdir": "/tmp",
"java.library.path": "wrapper",
"java.protocol.handler.pkgs": "com.thoughtworks.gocd",
"java.runtime.name": "OpenJDK Runtime Environment",
"java.runtime.version": "13.0.2+8",
"java.specification.name": "Java Platform API Specification",
"java.specification.vendor": "Oracle Corporation",
"java.specification.version": "13",
"java.vendor": "AdoptOpenJDK",
"java.vendor.url": "https://adoptopenjdk.net/",
"java.vendor.url.bug": "https://github.com/AdoptOpenJDK/openjdk-support/issues",
"java.vendor.version": "AdoptOpenJDK",
"java.version": "13.0.2",
"java.version.date": "2020-01-14",
"java.vm.compressedOopsMode": "Zero based",
"java.vm.info": "mixed mode, sharing",
"java.vm.name": "OpenJDK 64-Bit Server VM",
"java.vm.specification.name": "Java Virtual Machine Specification",
"java.vm.specification.vendor": "Oracle Corporation",
"java.vm.specification.version": "13",
"java.vm.vendor": "AdoptOpenJDK",
"java.vm.version": "13.0.2+8",
"jdk.debug": "release",
"jdk.tls.ephemeralDHKeySize": "matched",
"jetty.base": "/go-working-dir",
"jetty.git.hash": "a304fd9f351f337e7c0e2a7c28878dd536149c6c",
"jetty.home": "/go-working-dir",
"jetty.xml.file.name": "jetty.xml",
"jruby.compile.invokedynamic": "false",
"jruby.ji.objectProxyCache": "false",
"jruby.management.enabled": "true",
"jruby.rack.request.size.threshold.bytes": "30000000",
"line.separator": "\n",
"net.sf.ehcache.skipUpdateCheck": "true",
"os.arch": "amd64",
"os.name": "Linux",
"os.version": "4.14.171+",
"path.separator": ":",
"rails.use.compressed.js": "true",
"sun.arch.data.model": "64",
"sun.boot.library.path": "/gocd-jre/lib",
"sun.cpu.endian": "little",
"sun.io.unicode.encoding": "UnicodeLittle",
"sun.java.command": "org.tanukisoftware.wrapper.WrapperJarApp lib/go.jar",
"sun.java.launcher": "SUN_STANDARD",
"sun.jnu.encoding": "UTF-8",
"sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
"user.country": "US",
"user.dir": "/go-working-dir",
"user.home": "/home/go",
"user.language": "en",
"user.name": "go",
"user.timezone": "GMT",
"wrapper.arch": "x86",
"wrapper.cpu.timeout": "10",
"wrapper.java.pid": "137",
"wrapper.jvm.port.max": "31999",
"wrapper.jvm.port.min": "31000",
"wrapper.jvmid": "1",
"wrapper.key": "AghS3rp_vDrUPeo-eDeQMq_H1evz27DN",
"wrapper.lang.domain": "wrapper",
"wrapper.lang.folder": "../lang",
"wrapper.native_library": "wrapper",
"wrapper.pid": "124",
"wrapper.port": "32000",
"wrapper.version": "3.5.41-st"
},
"Cache Information": {
"com.thoughtworks.go.server.cache.GoCacheFactory": {
"goCache": {
"Cache configuration information": {
"Name": "goCache",
"Maximum Elements in Memory": 100000,
"Maximum Elements on Disk": 0,
"Memory Store Eviction Policy": "LRU",
"Clean or Flush": true,
"Eternal": true,
"Time To Idle Seconds": 0,
"time To Live Seconds": 0,
"Persistence Configuration Strategy": "NONE",
"Persistence Configuration Synchronous writes": false,
"Disk Spool Buffer Size in MB": 30,
"Disk Access Stripes": 1,
"Disk Expiry Thread Interval Seconds": 120,
"Logging Enabled": false,
"Terracotta Configuration": null,
"Cache Writer Configuration": {
"writeMode": "WRITE_THROUGH",
"notifyListenersOnException": false,
"minWriteDelay": 1,
"maxWriteDelay": 1,
"rateLimitPerSecond": 0,
"writeCoalescing": false,
"writeBatching": false,
"writeBatchSize": 1,
"retryAttempts": 0,
"retryAttemptDelaySeconds": 1,
"writeBehindConcurrency": 1,
"writeBehindMaxQueueSize": 0,
"cacheWriterFactoryConfiguration": null
},
```

###### Basic environment details

* Go Version: `GoCD Version: 20.5.0 (11820-1c9b12ac8aa216a2c062fbec4cba18d9cfb8b404).`
* JAVA Version: `13.0.2`
* OS: `Linux 4.14.171+`
* Browser vendor and version (if relevant): `Chrome Version 84.0.4147.105 (Official Build) (64-bit)`

###### Additional Environment Details
- Running on K8S
- Supplied JVM Opts to helm and increased Xms1G and Xmx3G (but in running process default values and the one we supplied shows up, though right one wins is what most JVMs does)

**Comment by maheshp** [comment]
@m4ver1k  to verify if this is an issue, I brought up a GoCD serve on 19.2.0 using a backup of one of our large GoCD instance. This instance has 4000+ pipelines and the db has around 1711173 records for pipeline runs.
 
Ran few benchmarks against dashboard and pipeline history.

Post that, I migrated the db and upgraded to GoCD 20.6.0. Ran the same set of benchmarks on this server as well. 
The results were comparable and did not find much of a difference. Also, analyzed the sql queries used for fetching the pipeline history, again the time taken between the db's were mostly same.

This looks like an issue specific to your environment. With current information provided by you it will be tough to understand the reason for slow page loads. Has anything changed in your environment between the upgrades and did you migrate to PostgreSQL or are you still using H2?

**Comment by m4ver1k** [comment]
Nothing much have changed and still using H2

**Comment by maheshp** [comment]
> We are in 20.5.0, is there any changes in 20.6.0 that would have fixed these ?

There has been no changes around these pages and API's recently. You might want to consider enabling [web request logging](https://docs.gocd.org/current/advanced_usage/logging.html) to record the time taken for these requests.

The support log provided by you lists the `"Available Processors": 1,`. From the given information I cannot say that having 1 processor is a bottleneck but it seems less considering the number of pipelines and materials you have. I would consider increasing the processors to check if it helps.

We have seen H2 being a constraint once the number of pipelines, materials etc grows. At some point you might want to consider moving to PostgreSQL as well.

**Comment by m4ver1k** [comment]
thanks @maheshp again for the quick response,

the following config snippet is from our old gocd instance

```"Timestamp": "2020-08-12T14:41:39Z",
"Go Server Information": {
"Version": "19.5.0 (9272-496bf8b95e603c1f3980ae59042bc559eecbbbc0)"
},
"Config Statistics": {
"Valid Config": {
"Number of pipelines": 477,
"Number of agents": 1,
"Number of environments": 0,
"Number of unique materials": 295,
"Number of schedulable materials": 299
},
"Security": {
"Plugins": [
{
"Google oauth authorization plugin": true
},
{
"Password File Authentication Plugin for GoCD": true
},
{
"LDAP Authentication Plugin for GoCD": false
}
],
"Enabled": true
}
},
"Config file locations": {
"loc.config.dir": "/go-working-dir/config",
"loc.log.root.0": "/go-working-dir/logs",
"loc.log.basename.0": "go-server.log",
"loc.log.root.2": "/go-working-dir/logs",
"loc.log.basename.2": "plugin-cd.go.artifact.docker.registry.log",
"loc.log.root.4": "/go-working-dir/logs",
"loc.log.basename.4": "plugin-cd.go.authentication.ldap.log",
"loc.log.root.6": "/go-working-dir/logs",
"loc.log.basename.6": "plugin-cd.go.authentication.passwordfile.log",
"loc.log.root.8": "/go-working-dir/logs",
"loc.log.basename.8": "plugin-cd.go.authorization.google.log",
"loc.log.root.10": "/go-working-dir/logs",
"loc.log.basename.10": "plugin-cd.go.contrib.elasticagent.kubernetes.log"
},
"OS Information": {
"OS Name": "Linux",
"OS Version": "4.14.127+",
"System Architecture": "amd64",
"Available Processors": 1,
"Average System Load": 4.0068359375
}
```

This also had the same number of processor and was running H2, so trying to understand if migration could have caused anything.
In this old instance the dashboard was quite fast. 

The new instance is running on a K8S Node with : `4cpu 8GB` but we have not set any resource request on the deployment will try that with 2 cpus and enable web request logging and get back.

**Comment by ketan** [comment]
The version of H2 (and the underlying h2 filestore) has changed in 19.5. See https://docs.gocd.org/20.5.0/installation/upgrade_to_gocd_20.5.0.html

**Comment by adarshk-rapido** [comment]
@ketan thanks for response, we decided to move to `postgres` so was trying to use the migrator tool to migrate from 20.5 H2 to 20.5 Postgres (hope this is possible).

Getting these error while running the migrator and not proceeding beyond 6%.


`/data/godata/db/h2db/gocd-database-migrator-1.0.0 # sh ./bin/gocd-database-migrator   --insert   --progress   --source-db-url='jdbc:h2:/data/godata/db/h2db/cruise'   --source-db-user='sa'   --source
-db-password=''   --target-db-url='jdbc:postgresql://DB_HOST:5432/gocd_db' --target-db-user='gocd_user'   --target-db-password='password'`

```
INFO: No `--source-db-driver-class` is specified. Setting `--source-db-driver-class='org.h2.Driver'`.
INFO: No `--target-db-driver-class` specified. Setting `--target-db-driver-class='org.postgresql.Driver'`.
2020-08-28 21:56:12,559 INFO  [main] DbSync:76 - Using dialect H2 for source database.
2020-08-28 21:56:12,945 INFO  [main] DbSync:77 - Using dialect POSTGRES for target database.
2020-08-28 21:56:13,481 INFO  [main] DbSync:106 - Initializing database skeleton on target database.
2020-08-28 21:56:16,926 INFO  [main] DbSync:108 - Done initializing database skeleton on target database.
2020-08-28 21:56:16,928 INFO  [main] DbSync:112 - Initializing database views.
2020-08-28 21:56:17,235 INFO  [main] DbSync:114 - Done initializing database views.
2020-08-28 21:56:17,238 INFO  [main] DbSync:119 - Copying database records.
2020-08-28 21:56:17,265 INFO  [main] DbSync:189 - Found tables:
2020-08-28 21:56:17,266 INFO  [main] DbSync:192 -   MODIFIEDFILES: 189894 records
2020-08-28 21:56:17,267 INFO  [main] DbSync:192 -   ACCESSTOKEN: 2 records
2020-08-28 21:56:17,267 INFO  [main] DbSync:192 -   DATASHARINGSETTINGS: 1 records
2020-08-28 21:56:17,267 INFO  [main] DbSync:192 -   PIPELINELABELCOUNTS: 452 records
2020-08-28 21:56:17,267 INFO  [main] DbSync:192 -   PIPELINESTATES: 402 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   USAGEDATAREPORTING: 1 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   ARTIFACTPLANS: 138 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   STAGES: 34196 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   SERVERBACKUPS: 213 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   VERSIONINFOS: 1 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   RESOURCES: 58 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   NOTIFICATIONFILTERS: 0 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   BUILDS: 38802 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   PIPELINES: 17419 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   PIPELINEMATERIALREVISIONS: 18105 records
2020-08-28 21:56:17,270 INFO  [main] DbSync:192 -   MODIFICATIONS: 58786 records
2020-08-28 21:56:17,271 INFO  [main] DbSync:192 -   PIPELINESELECTIONS: 15 records
2020-08-28 21:56:17,271 INFO  [main] DbSync:192 -   PLUGINS: 0 records
2020-08-28 21:56:17,271 INFO  [main] DbSync:192 -   JOBAGENTMETADATA: 49 records
2020-08-28 21:56:17,271 INFO  [main] DbSync:192 -   BUILDSTATETRANSITIONS: 229324 records
2020-08-28 21:56:17,272 INFO  [main] DbSync:192 -   ENVIRONMENTVARIABLES: 31 records
2020-08-28 21:56:17,272 INFO  [main] DbSync:192 -   DATABASECHANGELOG: 107 records
2020-08-28 21:56:17,272 INFO  [main] DbSync:192 -   AGENTS: 38405 records
2020-08-28 21:56:17,273 INFO  [main] DbSync:192 -   DATABASECHANGELOGLOCK: 1 records
2020-08-28 21:56:17,273 INFO  [main] DbSync:192 -   STAGEARTIFACTCLEANUPPROHIBITED: 942 records
2020-08-28 21:56:17,273 INFO  [main] DbSync:192 -   USERS: 76 records
2020-08-28 21:56:17,274 INFO  [main] DbSync:192 -   MATERIALS: 339 records
record copy progress   0% [>                                                                                                                         ]      0/627759 record (0:00:00 / ?) ? record/s2020-08-28 21:56:18,299 ERROR [pool-2-thread-4] DbSync:203 - null
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "pool-2-thread-4" java.lang.RuntimeException: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:204)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	... 3 more
record copy progress   0% [>                                                                                                               ]   1363/627759 record (0:00:09 / 1:12:04) 151.4 record/s2020-08-28 21:56:27,367 ERROR [pool-2-thread-5] DbSync:203 - null
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "pool-2-thread-5" java.lang.RuntimeException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:204)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	... 3 more
record copy progress   6% [======>                                                                                                         ]  38244/627759 record (0:04:22 / 1:07:20) 146.0 record/s
```

**Comment by m4ver1k** [comment]
@ketan thanks for response, we decided to move to `postgres` so was trying to use the migrator tool to migrate from 20.5 H2 to 20.5 Postgres (hope this is possible).

Getting these error while running the migrator and not proceeding beyond 6%.

@maheshp ^^

`/data/godata/db/h2db/gocd-database-migrator-1.0.0 # sh ./bin/gocd-database-migrator   --insert   --progress   --source-db-url='jdbc:h2:/data/godata/db/h2db/cruise'   --source-db-user='sa'   --source
-db-password=''   --target-db-url='jdbc:postgresql://DB_HOST:5432/gocd_db' --target-db-user='gocd_user'   --target-db-password='password'`

```
INFO: No `--source-db-driver-class` is specified. Setting `--source-db-driver-class='org.h2.Driver'`.
INFO: No `--target-db-driver-class` specified. Setting `--target-db-driver-class='org.postgresql.Driver'`.
2020-08-28 21:56:12,559 INFO  [main] DbSync:76 - Using dialect H2 for source database.
2020-08-28 21:56:12,945 INFO  [main] DbSync:77 - Using dialect POSTGRES for target database.
2020-08-28 21:56:13,481 INFO  [main] DbSync:106 - Initializing database skeleton on target database.
2020-08-28 21:56:16,926 INFO  [main] DbSync:108 - Done initializing database skeleton on target database.
2020-08-28 21:56:16,928 INFO  [main] DbSync:112 - Initializing database views.
2020-08-28 21:56:17,235 INFO  [main] DbSync:114 - Done initializing database views.
2020-08-28 21:56:17,238 INFO  [main] DbSync:119 - Copying database records.
2020-08-28 21:56:17,265 INFO  [main] DbSync:189 - Found tables:
2020-08-28 21:56:17,266 INFO  [main] DbSync:192 -   MODIFIEDFILES: 189894 records
2020-08-28 21:56:17,267 INFO  [main] DbSync:192 -   ACCESSTOKEN: 2 records
2020-08-28 21:56:17,267 INFO  [main] DbSync:192 -   DATASHARINGSETTINGS: 1 records
2020-08-28 21:56:17,267 INFO  [main] DbSync:192 -   PIPELINELABELCOUNTS: 452 records
2020-08-28 21:56:17,267 INFO  [main] DbSync:192 -   PIPELINESTATES: 402 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   USAGEDATAREPORTING: 1 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   ARTIFACTPLANS: 138 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   STAGES: 34196 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   SERVERBACKUPS: 213 records
2020-08-28 21:56:17,268 INFO  [main] DbSync:192 -   VERSIONINFOS: 1 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   RESOURCES: 58 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   NOTIFICATIONFILTERS: 0 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   BUILDS: 38802 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   PIPELINES: 17419 records
2020-08-28 21:56:17,269 INFO  [main] DbSync:192 -   PIPELINEMATERIALREVISIONS: 18105 records
2020-08-28 21:56:17,270 INFO  [main] DbSync:192 -   MODIFICATIONS: 58786 records
2020-08-28 21:56:17,271 INFO  [main] DbSync:192 -   PIPELINESELECTIONS: 15 records
2020-08-28 21:56:17,271 INFO  [main] DbSync:192 -   PLUGINS: 0 records
2020-08-28 21:56:17,271 INFO  [main] DbSync:192 -   JOBAGENTMETADATA: 49 records
2020-08-28 21:56:17,271 INFO  [main] DbSync:192 -   BUILDSTATETRANSITIONS: 229324 records
2020-08-28 21:56:17,272 INFO  [main] DbSync:192 -   ENVIRONMENTVARIABLES: 31 records
2020-08-28 21:56:17,272 INFO  [main] DbSync:192 -   DATABASECHANGELOG: 107 records
2020-08-28 21:56:17,272 INFO  [main] DbSync:192 -   AGENTS: 38405 records
2020-08-28 21:56:17,273 INFO  [main] DbSync:192 -   DATABASECHANGELOGLOCK: 1 records
2020-08-28 21:56:17,273 INFO  [main] DbSync:192 -   STAGEARTIFACTCLEANUPPROHIBITED: 942 records
2020-08-28 21:56:17,273 INFO  [main] DbSync:192 -   USERS: 76 records
2020-08-28 21:56:17,274 INFO  [main] DbSync:192 -   MATERIALS: 339 records
record copy progress   0% [>                                                                                                                         ]      0/627759 record (0:00:00 / ?) ? record/s2020-08-28 21:56:18,299 ERROR [pool-2-thread-4] DbSync:203 - null
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "pool-2-thread-4" java.lang.RuntimeException: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:204)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	... 3 more
record copy progress   0% [>                                                                                                               ]   1363/627759 record (0:00:09 / 1:12:04) 151.4 record/s2020-08-28 21:56:27,367 ERROR [pool-2-thread-5] DbSync:203 - null
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "pool-2-thread-5" java.lang.RuntimeException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:204)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	... 3 more
record copy progress   6% [======>                                                                                                         ]  38244/627759 record (0:04:22 / 1:07:20) 146.0 record/s
```

**Comment by maheshp** [comment]
@m4ver1k sorry for the delayed response. It's hard to say what could be going wrong from the stacktrace provided by you. Would you be comfortable sharing the H2 db with us, so that we can try to understand this better.

**Comment by adarshk-rapido** [comment]
@maheshp please let me know how to share the file.

**Comment by ketan** [comment]
You can upload the DB file to a known location on google
drive/onedrive/dropbox and share a link with support@thoughtworks.com with
a link to this issue number.

- Ketan

**Comment by maheshp** [comment]
In its current form the [GoCD db migration tool](https://github.com/gocd/gocd-database-migrator/) does not support syncing data between databases after the initial migration of a GoCD database on `v20.4.0` or `below` to a`v20.5.0` compliant database. @m4ver1k had to make changes to tool get the sync working. 

Closing the ticket for now.

**Comment by m4ver1k** [comment]
thanks for the help once again @maheshp and @ketan
