### ISSUE TITLE
Agents going Lost Contact after a while and warnings in the server about remoteBuildRepository

### ISSUE THREAD

**Issue by Diogomrol** [gocd/gocd#8427]
##### Issue Type

- Bug Report

##### Summary

We migrated our Go Server to a new server with a PostgreSQL database (without migrating any data), and we created agents with a fresh installation of GoCD Agent. Both server and agents are on 20.5.0 version.

Important detail: we have a "pre-production" version of our server, where we did the same migration, and had no issues.

##### Environment

Using an EC2 instance + RDS with a LB.

###### Basic environment details

* Go Version: 20.5.0 (11820-1c9b12ac8aa216a2c062fbec4cba18d9cfb8b404)
* JAVA Version: 13.0.2
* OS: Linux 3.10.0-1127.18.2.el7.x86_64

##### Issue and logs

After a while, we observe that all agents go "Lost Contact". Eventually if we restart the server everything starts working well for a couple of hours.

By checking the logs, we see this on the Agents:

```
2020-08-04 18:15:22,327 ERROR [scheduler-1] AgentHTTPClientController:105 - Error occurred when agent tried to ping server: 
org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://<server_url>:443/go/remoting/remoteBuildRepository]; nested exception is org.apache.http.client.ClientProtocolException: The server returned status code 403. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
   - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/20.5.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.convertHttpInvokerAccessException(HttpInvokerClientInterceptor.java:226)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy10.ping(Unknown Source)
	at com.thoughtworks.go.agent.AgentHTTPClientController.ping(AgentHTTPClientController.java:100)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.client.ClientProtocolException: The server returned status code 403. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
   - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/20.5.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
	at com.thoughtworks.go.agent.GoHttpClientHttpInvokerRequestExecutor.validateResponse(GoHttpClientHttpInvokerRequestExecutor.java:100)
	at com.thoughtworks.go.agent.GoHttpClientHttpInvokerRequestExecutor.doExecuteRequest(GoHttpClientHttpInvokerRequestExecutor.java:66)
	at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:137)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:202)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:184)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:150)
```

After checking the server logs, we also see this error:

![image](https://user-images.githubusercontent.com/9485620/89392792-e713e000-d701-11ea-86b3-4fde89859fee.png)

Any idea on what can be causing this? Any help is appreciated.

Thanks a lot,
Diogo

**Comment by Diogomrol** [comment]
Some more details about the environment:

EC2 has 4 cpus and 16gb of memory

And we are using -Xmx8g to launch the server.

**Comment by arvindsv** [comment]
When I've seen this happen, it's been due to a wrongly configured load balancer. Is your load balancer terminating TLS? I hope it's not connected to two GoCD servers, because that won't work.

To rule out load balancers being a problem, I'd set up a local agent and see if it loses contact as well at that time.

Since the right forum for this is the mailing list, and since this is not _yet_ known to be a GoCD issue, I'll close it for now. We can continue the conversation, and I can reopen it if we identify a GoCD problem. It'll likely get more eyeballs if sent to the mailing list.

**Comment by arvindsv** [comment]
I'm reopening this, since there hasn't been a resolution / any further discussion on the mailing list topic you opened. Maybe someone else here will have an idea.

The `ArrayIndexOutOfBoundsException` is weird. When you see it happening you might need to increase the debug level across the server to get better logging.

**Comment by maheshp** [comment]
@Diogomrol before loosing contact do you know if the agents have actually run any job?

We might need more information to understand this issue, for the agent which is in lost contact will you be able to send all the agent logs and the server log corresponding to the time when the agent starts seeing errors during server ping.
Please send the logs to support(at)thoughtworks.com

**Comment by Diogomrol** [comment]
@maheshp the agents are indeed able to execute jobs before this happens.

After a few days of this we notice that the agents are able to be up for like 8 hours, running jobs normally, and suddenly all of them (talking about more than 100 agents) go LostContact at exactly the same instant.

I will try to collect some more logs, but this looks an issue related with the server given the fact that all the agents loose contact, as I said, at exactly the same time.

**Comment by Diogomrol** [comment]
@arvindsv and @maheshp in what concerns logs, what we get when this happens on both the server and agent is exactly what I have posted when I opened the issue here.

We get a bunch of that warns.

**Comment by Diogomrol** [comment]
And forgot to mention @arvindsv, as you asked before, we have tried to setup a local agent on server's machine to rule out load balancer issues, but that agent also gets lost contact.

**Comment by maheshp** [comment]
@Diogomrol thanks for the information. I am taking a look at it, will get back once I have some answers.

**Comment by maheshp** [comment]
Fixed as part of - https://github.com/gocd/gocd/pull/8473
