### ISSUE TITLE
Fail to perform any GoCD updates due to invalid config repository configuration

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8463]
[Please refer to the YAML configuration provided in the Steps to Reproduce point 1]

#### 1. Confusion between GoCD Parameters and YAML Comment.
  - A GoCD parameter should be used within quotes in YAML definition. Example:
    ```yaml
        arguments:
            - "#{COMMAND_TO_EXECUTE}"
    ```
  - A Yaml comment should be used only as #my_comment. Example:
    ```yaml
        arguments:
            - "#{COMMAND_TO_EXECUTE}"  #this is an argument specified as a pipeline parameter
    ```
    In the given configuration, the argument is specified as `- #{COMMAND_TO_EXECUTE}` instead of `- "#{COMMAND_TO_EXECUTE}"` making it read as comment and evaluated to `-` (causing null argument).

#### 3. Missing GoCD full config save safety check to allow config updates regardless of validity of config repository.

---

##### Issue Type

- Bug Report

##### Summary

An invalid config repository blocks all the GoCD config saves.

###### Basic environment details

* Go Version: `20.6.0` (This error only occurs on GoCD Release v20.6.0, works fine with other releases)

##### Steps to Reproduce

1. Create a config repository with following Yaml Configuration.
<details>
  <summary>`config-repo-pipeline.gocd.yaml`</summary>
  
```yaml
COMMAND_TO_EXECUTE: ls
format_version: 3
pipelines:
  config-repo-pipeline:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/gocd/gocd
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:OF+lIfTm57i3ZJm8uALG1g==:2VDyBzAfH8NGqoJF2QXXmA==
    stages:
    - first-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          first-job:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - #{COMMAND_TO_EXECUTE}
                command: docker
                run_if: passed
    parameters:
      COMMAND_TO_EXECUTE: ls
```
</details>

2. Upon successful parse, no message is shown on the config repository page.
<img width="1045" alt="Screen Shot 2020-08-14 at 4 41 51 PM" src="https://user-images.githubusercontent.com/15275847/90243809-2dc5b080-de4d-11ea-9dbc-11ad1e0cde0f.png">

3. When any any of the GoCD entities are updated from GoCD UI, all the updates fail with the following stack trace:
<details>
  <summary>Error Stack Trace</summary>
  
```
2020-08-12 05:24:36,386 ERROR [qtp1380852585-43] GoConfigDao:96 - Config update for entity failed
java.lang.NullPointerException: null
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$XmlFieldWithValue.valueString(MagicalGoConfigXmlWriter.java:209)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$ValueXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:395)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:147)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$CollectionXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:349)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$ImplicitCollectionXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:307)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:147)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$CollectionXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:349)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$ExplicitCollectionXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:371)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:147)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$CollectionXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:349)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$ExplicitCollectionXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:371)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:147)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$CollectionXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:349)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter$ExplicitCollectionXmlFieldWithValue.populate(MagicalGoConfigXmlWriter.java:371)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.toXmlPartial(MagicalGoConfigXmlWriter.java:117)
        at com.thoughtworks.go.server.service.EntityHashes.serializeDomainEntity(EntityHashes.java:107)
        at com.thoughtworks.go.server.service.EntityHashes.digestDomainConfigEntity(EntityHashes.java:99)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.thoughtworks.go.server.service.EntityHashes.digestMany(EntityHashes.java:95)
        at com.thoughtworks.go.server.service.EntityHashes.digestPartial(EntityHashes.java:72)
        at com.thoughtworks.go.config.PartialConfigHelper.hash(PartialConfigHelper.java:102)
        at com.thoughtworks.go.config.PartialConfigHelper.identity(PartialConfigHelper.java:66)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.thoughtworks.go.config.PartialConfigHelper.identities(PartialConfigHelper.java:61)
        at com.thoughtworks.go.config.PartialConfigHelper.isEquivalent(PartialConfigHelper.java:56)
        at com.thoughtworks.go.config.GoFileConfigDataSource.areKnownPartialsSameAsValidPartials(GoFileConfigDataSource.java:477)
        at com.thoughtworks.go.config.GoFileConfigDataSource.writeEntityWithLock(GoFileConfigDataSource.java:299)
        at com.thoughtworks.go.config.CachedGoConfig.writeEntityWithLock(CachedGoConfig.java:159)
        at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:94)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:307)
        at com.thoughtworks.go.server.service.ElasticProfileService.update(ElasticProfileService.java:156)
        at com.thoughtworks.go.server.service.ElasticProfileService.update(ElasticProfileService.java:72)
        at com.thoughtworks.go.apiv2.elasticprofile.ElasticProfileControllerV2.update(ElasticProfileControllerV2.java:157)
```
</details>

4. When cruise-config.xml is updated from the `cruise-config.xml` tab, the update fails with no error message.
<img width="1408" alt="Screen Shot 2020-08-14 at 4 42 16 PM" src="https://user-images.githubusercontent.com/15275847/90243792-23a3b200-de4d-11ea-802e-7c114aba1df2.png">

##### Expected Results
An invalid config repository should not affect GoCD config updates.

##### Actual Results
An invalid config repository block GoCD config updates.

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.7.0 (12096-ccdde50c002926ff21e74930e5f4ee7f2d298b1b)
