### ISSUE TITLE
Zip File agent requires java 13, not 11

### ISSUE THREAD

**Issue by dkowis** [gocd/gocd#9182]
##### Issue Type

* Bug Report

##### Summary

The [zip file agent](https://www.gocd.org/download/#zip) seems to have class files that are java 13, not java 11.

```plain
go-agent/go-agent-21.2.0 > ./bin/go-agent console
Running go-agent...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Standard Edition 64-bit 3.5.41
wrapper  |   Copyright (C) 1999-2019 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |   Licensed to ThoughtWorks for GoCD Agent
wrapper  |
wrapper  | The value of wrapper.java.command does not appear to be a java binary.
wrapper  | The use of scripts is not supported. Trying to continue, but some features may not work correctly..
wrapper  | The value of wrapper.java.command does not appear to be a java binary.
wrapper  | The use of scripts is not supported. Trying to continue, but some features may not work correctly..
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | Running GoCD requires Java version >= 11. You are currently running with Java version 1.8. GoCD will now exit!
wrapper  | <-- Wrapper Stopped
go-agent/go-agent-21.2.0 > jenv shell 11
go-agent/go-agent-21.2.0 > ./bin/go-agent console
Running go-agent...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Standard Edition 64-bit 3.5.41
wrapper  |   Copyright (C) 1999-2019 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |   Licensed to ThoughtWorks for GoCD Agent
wrapper  |
wrapper  | The value of wrapper.java.command does not appear to be a java binary.
wrapper  | The use of scripts is not supported. Trying to continue, but some features may not work correctly..
wrapper  | The value of wrapper.java.command does not appear to be a java binary.
wrapper  | The use of scripts is not supported. Trying to continue, but some features may not work correctly..
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | [Mon Mar 29 12:07:30 CDT 2021] Starting process:
jvm 1    | [Mon Mar 29 12:07:30 CDT 2021]   Working directory    : /home/dkowis/temp/go-agent/go-agent-21.2.0
jvm 1    | [Mon Mar 29 12:07:30 CDT 2021]   Application arguments: [-serverUrl, http://localhost:8153/go]
jvm 1    | [Mon Mar 29 12:07:30 CDT 2021]            GoCD Version: 21.2.0-12498
jvm 1    | [Mon Mar 29 12:07:30 CDT 2021]            Java Version: 11.0.8
jvm 1    | [Mon Mar 29 12:07:30 CDT 2021]        Operating System: Linux(5.8.0-7642-generic)
jvm 1    | WrapperJarApp:
jvm 1    | WrapperJarApp Error: Encountered an error running main:
jvm 1    | WrapperJarApp Error: java.lang.UnsupportedClassVersionError: com/thoughtworks/go/agent/bootstrapper/AgentBootstrapper has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0
jvm 1    | WrapperJarApp Error: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
jvm 1    | WrapperJarApp Error: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
jvm 1    | WrapperJarApp Error: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
jvm 1    | WrapperJarApp Error: 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
jvm 1    | WrapperJarApp Error: 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
jvm 1    | WrapperJarApp Error: 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
jvm 1    | WrapperJarApp Error: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
jvm 1    | WrapperJarApp Error: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
jvm 1    | WrapperJarApp Error: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
jvm 1    | WrapperJarApp Error: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
jvm 1    | WrapperJarApp Error: 	at com.thoughtworks.gocd.Boot.run(Boot.java:89)
jvm 1    | WrapperJarApp Error: 	at com.thoughtworks.gocd.Boot.main(Boot.java:56)
jvm 1    | WrapperJarApp Error: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | WrapperJarApp Error: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jvm 1    | WrapperJarApp Error: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    | WrapperJarApp Error: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
jvm 1    | WrapperJarApp Error: 	at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
jvm 1    | WrapperJarApp Error: 	at java.base/java.lang.Thread.run(Thread.java:834)
wrapper  | <-- Wrapper Stopped
go-agent/go-agent-21.2.0 > java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

###### Basic environment details

* Go Version: `21.2.0-12498`
* JAVA Version: 11.0.8
* OS: `Linux`

##### Steps to Reproduce

1.  Download and extract the zip file
2. `./bin/go-agent console`
3. :boom: 
4. 

##### Expected Results
I should have a go-agent fired up.

##### Actual Results
I get ugly class version errors :(

##### Possible Fix
(on the latest release tag:)
https://github.com/gocd/gocd/blob/16e1ac6956cd5177a99dc3fe33503661881c354f/build.gradle#L161-L164
need to be set to java 11, or the documentation needs to be updated to indicate needs at least java 13

**Comment by maheshp** [comment]
@dkowis the [System Requirements](https://docs.gocd.org/current/installation/system_requirements.html) documentation has been updated to reflect the required JRE version.

All GoCD installers except for the Zip installer comes bundled with the latest version of JRE. This is based on the [announcement](https://www.gocd.org/2019/05/21/official-stance-on-java/) made earlier.

I will close this issue for now.

**Comment by dkowis** [comment]
Thanks for clarifying, sorry I missed that in the blog post!

**Comment by maheshp** [comment]
No problem :)

**Comment by belka-ew** [comment]
The download page still says: "Requires Java Runtime Environment (JRE) version 11 (for releases 19.9.0 and higher)"

**Comment by arvindsv** [comment]
Thank you for finding that! It should be updated now.
