### ISSUE TITLE
Unable to Rerun selected/ failed jobs from UI

### ISSUE THREAD

**Issue by NehaAgarwal2598** [gocd/gocd#9197]
##### Issue Type

- Bug Report

##### Summary

Unable to Rerun selected/ failed jobs from UI

###### Basic environment details

* Go Version: `20.4.0 (11749-5553066d29d315951efa5ead0c087374df6338b9).`
* JAVA Version: `13.0.2`
* OS: `Linux 3.10.0-1160.6.1.el7.x86_64`
* Browser vendor and version (if relevant): `Chrome 87`

##### Steps to Reproduce

1. Go To the pipeline History page.
2. Go to Stage details page for the selected stage.
2. Click on Jobs tab.
3. Select a Job
4. Click on RERUN SELECTED

##### Expected Results
The selected job should rerun

##### Actual Results
The job doesn't run.
<img width="623" alt="Screenshot 2021-04-05 at 5 39 57 PM" src="https://user-images.githubusercontent.com/38171738/113572561-133b8400-9636-11eb-93b8-0f8ff422ee72.png">

##### Log snippets

```
 2021-04-05 11:33:59,595 WARN  [qtp28140798-99708184] Rails:-1 - HTTP Origin header (https://gocd-example.****.com) didn't match request.base_url (http://gocd-example.com)
jvm 1    | 2021-04-05 11:33:59,598 ERROR [qtp28140798-99708184] Rails:-1 -
jvm 1    | 2021-04-05 11:33:59,599 ERROR [qtp28140798-99708184] Rails:-1 - ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
jvm 1    | 2021-04-05 11:33:59,599 ERROR [qtp28140798-99708184] Rails:-1 -
jvm 1    | 2021-04-05 11:33:59,599 ERROR [qtp28140798-99708184] Rails:-1 - gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:34:in `block in Callbacks'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
jvm 1    | org/jruby/RubyArray.java:1801:in `each'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:513:in `invoke_before'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:38:in `block in process_action'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
jvm 1    | gems/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
jvm 1    | gems/jruby/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:134:in `process'
jvm 1    | gems/jruby/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:32:in `process'
```

**Comment by arvindsv** [comment]
Seems like either a proxy configuration issue or setting the correct site URL and secure site URL in the server configuration.
