### ISSUE TITLE
[SPPU] Give clear log message in case external plugin fails to
load due to same jar name

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#93]
## Description:

Let the bundled plugin and external plugin have the same jar name. Inthis case only bundled plugin gets loaded and not external plugin. But in logs it gives this error message which is not very clear (it
makes sense when external plugin failed to load due to same plugin id ) -

```
 2013-09-22 19:43:54,047 WARN [Thread-67]
 DefaultPluginJarLocationMonitor:276 - Plugin listener failed
  java.lang.RuntimeException: Found bundled plugin with ID: [yum], external plugin could not be loaded
  at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.validateIfExternalPluginRemovingBundledPlugin(DefaultPluginJarChangeListener.java:94)
  at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:53)
  at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor\$PluginLocationMonitorThread\$DoOnAllListeners\$1.execute(DefaultPluginJarLocationMonitor.java:243)
  at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor\$PluginLocationMonitorThread\$DoOnAllListeners.doOnAll(DefaultPluginJarLocationMonitor.java:274)
  at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor\$PluginLocationMonitorThread\$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:241)
  at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor\$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:172)
  at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor\$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:163)
  at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor\$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:149)
```

**Comment by arvindsv** [comment]
No activity. Stale. Closing.
