### ISSUE TITLE
Issue with zip and osx agent installers

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#931]
1) Start the server zip installer
2) Start the agent zip installer. It throws following error -

./agent.sh: line 96: /var/log/./.-bootstrapper.log: Permission denied
./agent.sh: line 97: /var/log/./.-bootstrapper.log: Permission denied
./agent.sh: line 98: /var/log/./.-bootstrapper.log: Permission denied
logFile Environment Variable= /var/log/./.-bootstrapper.log
Logging to /var/log/./.-bootstrapper.log
2015-03-04 13:05:15,996 [main     ] WARN  go.agent.bootstrapper.BootstrapperLoggingHelper:60 - Unable to initialize log4j file-appender: /var/log/./.-bootstrapper.log
java.io.FileNotFoundException: /var/log/./.-bootstrapper.log (Permission denied)
	at java.io.FileOutputStream.openAppend(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:192)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.FileAppender.<init>(FileAppender.java:108)
	at org.apache.log4j.FileAppender.<init>(FileAppender.java:119)
	at com.thoughtworks.go.agent.bootstrapper.BootstrapperLoggingHelper.setupDefaultLog4j(BootstrapperLoggingHelper.java:54)
	at com.thoughtworks.go.agent.bootstrapper.BootstrapperLoggingHelper.initLog4j(BootstrapperLoggingHelper.java:42)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
2015-03-04 13:05:15,999 [main     ] WARN  go.agent.bootstrapper.BootstrapperLoggingHelper:61 - Using console-appender instead
2015-03-04 13:05:16,068 [main     ] INFO  agent.common.util.JarUtil:68 - Attempting to load Go-Agent-Launcher-Class from c1ed3dd2-b545-4577-92c6-ab7d28c1dd48agent-launcher.jar File: 
2015-03-04 13:05:16,071 [main     ] INFO  agent.common.util.JarUtil:77 - manifestLibDirKey: Go-Agent-Launcher-Lib-Dir: libs
2015-03-04 13:05:16,102 [main     ] INFO  agent.common.util.JarUtil:83 - manifestClassKey: Go-Agent-Launcher-Class: com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl
2015-03-04 13:05:16,104 [main     ] INFO  agent.common.util.ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLauncher using com.simontuffs.onejar.JarClassLoader
2015-03-04 13:05:16,132 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:72 - Attempting create and start launcher...
0 [main] ERROR com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl  - Launch encountered an unknown exception
java.lang.RuntimeException: java.io.FileNotFoundException: /var/log/./go-agent-launcher.log (Permission denied)
	at com.thoughtworks.go.agent.common.util.LoggingHelper.createFileAppender(LoggingHelper.java:70)
	at com.thoughtworks.go.agent.common.util.LoggingHelper.configureLoggerIfNoneExists(LoggingHelper.java:60)
	at com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:66)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:74)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.io.FileNotFoundException: /var/log/./go-agent-launcher.log (Permission denied)
	at java.io.FileOutputStream.openAppend(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:192)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:165)
	at org.apache.log4j.FileAppender.<init>(FileAppender.java:108)
	at org.apache.log4j.RollingFileAppender.<init>(RollingFileAppender.java:69)
	at com.thoughtworks.go.agent.common.util.LoggingHelper.createFileAppender(LoggingHelper.java:68)
	... 10 more
2015-03-04 13:05:16,149 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:76 - Launcher returned with code -273(0xFFFFFEEF)
2015-03-04 13:05:16,170 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:116 - Destroying launcher creator
2015-03-04 13:05:17,192 [main     ] INFO  go.agent.bootstrapper.DefaultAgentLauncherCreatorImpl:90 - Attempt No: 1 to cleanup launcher temp files
2015-03-04 13:05:17,194 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:99 - Waiting for 10000 ms before re-launch....
2015-03-04 13:05:27,201 [main     ] INFO  agent.common.util.JarUtil:68 - Attempting to load Go-Agent-Launcher-Class from fad44578-af9b-48b6-9c61-b1067dbe2219agent-launcher.jar File: 
2015-03-04 13:05:27,202 [main     ] INFO  agent.common.util.JarUtil:77 - manifestLibDirKey: Go-Agent-Launcher-Lib-Dir: libs
2015-03-04 13:05:27,229 [main     ] INFO  agent.common.util.JarUtil:83 - manifestClassKey: Go-Agent-Launcher-Class: com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl
2015-03-04 13:05:27,231 [main     ] INFO  agent.common.util.ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLauncher using com.simontuffs.onejar.JarClassLoader
2015-03-04 13:05:27,257 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:72 - Attempting create and start launcher...
1 [main] ERROR com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl  - Launch encountered an unknown exception
java.lang.RuntimeException: java.io.FileNotFoundException: /var/log/./go-agent-launcher.log (Permission denied)
	at com.thoughtworks.go.agent.common.util.LoggingHelper.createFileAppender(LoggingHelper.java:70)
	at com.thoughtworks.go.agent.common.util.LoggingHelper.configureLoggerIfNoneExists(LoggingHelper.java:60)
	at com.thoughtworks.cruise.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:66)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:74)
	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.io.FileNotFoundException: /var/log/./go-agent-launcher.log (Permission denied)
	at java.io.FileOutputStream.openAppend(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:192)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:165)
	at org.apache.log4j.FileAppender.<init>(FileAppender.java:108)
	at org.apache.log4j.RollingFileAppender.<init>(RollingFileAppender.java:69)
	at com.thoughtworks.go.agent.common.util.LoggingHelper.createFileAppender(LoggingHelper.java:68)
	... 10 more
2015-03-04 13:05:27,274 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:76 - Launcher returned with code -273(0xFFFFFEEF)
2015-03-04 13:05:27,292 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:116 - Destroying launcher creator
2015-03-04 13:05:28,314 [main     ] INFO  go.agent.bootstrapper.DefaultAgentLauncherCreatorImpl:90 - Attempt No: 1 to cleanup launcher temp files
2015-03-04 13:05:28,315 [main     ] INFO  go.agent.bootstrapper.AgentBootstrapper:99 - Waiting for 10000 ms before re-launch....

**Comment by arvindsv** [comment]
Want to fix all of these with #796, which I am working on. Let's re-verify this when that is done.

**Comment by mdaliejaz** [comment]
As part of #700 the service name is required for the logs. So if the agent is started with the command `sh agent.sh`, it works as it gets the service name as *agent.sh*.
```
mdaliej@INmdaliej:~/Projects/go/gocd/target/go-agent-15.1.0$ sh agent.sh
agent.sh                                   // echo $SERVICE_NAME
logFile Environment Variable= /Users/mdaliej/Projects/go/gocd/target/go-agent-15.1.0/agent.sh-bootstrapper.log
Logging to /Users/mdaliej/Projects/go/gocd/target/go-agent-15.1.0/agent.sh-bootstrapper.log
0 [TouchLoopThread-3] INFO com.thoughtworks.go.agent.launcher.Lockfile  - Using lock file: /Users/mdaliej/Projects/go/gocd/target/go-agent-15.1.0/.agent-bootstrapper.running
```
But if the agent is started with command `./agent.sh` after providing the execute permission, it fails to start with the aforementioned error, since the service name is set to '*.*'
```
mdaliej@INmdaliej:~/Projects/go/gocd/target/go-agent-15.1.0$ ./agent.sh
.                                                 // echo $SERVICE_NAME
./agent.sh: line 114: /var/log/./.-bootstrapper.log: Permission denied
./agent.sh: line 115: /var/log/./.-bootstrapper.log: Permission denied
./agent.sh: line 116: /var/log/./.-bootstrapper.log: Permission denied
logFile Environment Variable= /var/log/./.-bootstrapper.log
Logging to /var/log/./.-bootstrapper.log
2015-03-04 11:36:53,465 [main     ] WARN  go.agent.bootstrapper.BootstrapperLoggingHelper:60 - Unable to initialize log4j file-appender: /var/log/./.-bootstrapper.log
java.io.FileNotFoundException: /var/log/./.-bootstrapper.log (Permission denied)
```

**Comment by arvindsv** [comment]
I meant the OSX bit. For the zip installer, we should fix it. Wondering if we should set SERVICE_NAME to go-agent, if the SERVICE_NAME contains "agent". Hmm. Tough. If there are multiple instances, and it is used in that case, what do we do?

**Comment by mdaliejaz** [comment]
> I meant the OSX bit. For the zip installer, we should fix it. Wondering if we should set SERVICE_NAME to go-agent, if the SERVICE_NAME contains "agent". Hmm. Tough. If there are multiple instances, and it is used in that case, what do we do?

SERVICE_NAME is '.' in this (bug) case :-|
What if we have SERVICE_NAME as *'go-agent'* by default and append (or change) the default based on some other parameter (not sure what parameter!).
Worst case, users have to manually specify the service name for newer (multiple) instances.

**Comment by arvindsv** [comment]
I've defaulted it to go-agent. Users shouldn't have to specify a service name. The service name is now passed into agent.sh, from /etc/init.d/go-agent-1, where it is decided based on the name of the script being "go-agent-1".

**Comment by arvindsv** [comment]
I've verified it on debian, and using agent.sh directly from /usr/share/go-agent on that same box. But, not using the zip "installer". I built the installers using:

```
docker run -i -t -v `pwd`/installers-built:/installers -e REPO=https://github.com/arvindsv/gocd.git -e COMMIT=931_fix_service_name_issue gocd-build-installer:14.4.0 deb rpm zip
```

**Comment by arvindsv** [comment]
I tried with the zip installer as well, and it works.

**Comment by arikagoyal** [comment]
Works fine on 15.1.0(1594-db70c652aa3804)
