### ISSUE TITLE
Agent lost contact after upgrading to 21.2.0

### ISSUE THREAD

**Issue by kandap** [gocd/gocd#9347]
I have upgraded Go server to 21.2.0 from 20.x. Upgrade successful but agent lost contact. From the logs, I can see that

```
WARN: FATAL: ERROR: GO_JAVA_HOME is set to an invalid directory: /opt/xyz/java/jdk-11.0.5 
Please set the GO_JAVA_HOME variable in your environment to match the location of your Java installation. pam_unix(su-l:session): session closed for user go

```
```
echo $JAVA_HOME
/opt/xyz/java/jdk-11.0.5

echo $GO_JAVA_HOME
/opt/xyz/java/jdk-11.0.5

readlink -f $(which java)
/opt/xyz/java/jdk-11.0.5/bin/java

cat /etc/default/go-agent-1
GO_SERVER_URL=https://gocd2.dev.xyz.com.au/go
AGENT_WORK_DIR=/opt/xyz/go/go-agent-1
GO_JAVA_HOME=/opt/xyz/java/jdk-11.0.5
AGENT_MEM='8192m'
AGENT_MAX_MEM='8192m'
```

Logs:

 ```
tail -f go-agent-1-bootstrapper.out.log
[Tue May 25 14:37:18 AEST 2021] Starting process:
[Tue May 25 14:37:18 AEST 2021]   Working directory    : /opt/xyz/go/go-agent-1
[Tue May 25 14:37:18 AEST 2021]   Application arguments: [-serverUrl, https://gocd2.dev.adp.xyz.com.au/go]
[Tue May 25 14:37:18 AEST 2021]            GoCD Version: 18.10.0-7703
Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
Using classpath resource `jar:onejar:lib/agent-bootstrapper-18.10.0-7703-classes.jar!/config/agent-bootstrapper-logback.xml'.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.thoughtworks.gocd.Boot.run(Boot.java:111)
        at com.thoughtworks.gocd.Boot.main(Boot.java:57)
**Caused by: java.lang.UnsupportedClassVersionError: com/thoughtworks/go/agent/launcher/AgentLauncherImpl has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0**
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at com.thoughtworks.go.agent.bootstrapper.DefaultAgentLauncherCreatorImpl.loadClass(DefaultAgentLauncherCreatorImpl.java:68)
        at com.thoughtworks.go.agent.bootstrapper.DefaultAgentLauncherCreatorImpl.createLauncher(DefaultAgentLauncherCreatorImpl.java:58)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:76)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:60)
        at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:60)
        ... 6 more

```

**Comment by arvindsv** [comment]
It looks like you have a very old agent installation (18.10.0-7703), but the bigger issue seems to be that your server is upgraded to use a newer version of Java and the agent is on an older version of Java. Not sure about 18.10.0, but most newer GoCD agents come with the correct version of JRE bundled.

Since this is an environment/setup issue, I'll close it. The best place to get help with issues such as this is the [GoCD mailing list](https://groups.google.com/forum/#!forum/go-cd).

**Comment by kandap** [comment]
Hi Aravind, 
Thanks for getting back to me. Firstly apologies to contact here instead of google groups. Google groups is blocked in our organisation and hence unable to reach out to group for help.  We have upgraded the agent to 21.2.0 as well.  

Go-server -> up and running. 
Go-agent -> go-agent service is up and running but the agent is still in lost contact at server side.
                     we restarted both server and agent and no luck. 
                     I also have another question reg go-agent-1, 2 3.. are these still applicable to new veriosn 21.2.0?
                     When I run "service go-agent-1" we are still getting java version , home path error. Not sure if agent-1, 2, 3 are still valid in 21.2.0. 

In the /var/log/go-agent/go-agent-launcher.log, we see the below error. Your help will be highly appreciated as we have several PROD instances are runnign using 18.x versions and we need to upgrade them to 21.2.0 asap. so we are trying an upgrade in DEV and facing with these issues. Thank you. 

```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 51 common frames omitted
2021-05-26 13:58:56,480 ERROR [WrapperJarAppMain] ServerBinaryDownloader:88 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error:
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
        at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.fetchUpdateCheckHeaders(ServerBinaryDownloader.java:104)
        at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:80)
        at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:88)
        at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
        at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
        at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:76)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:57)
        at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
        at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:57)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.thoughtworks.gocd.Boot.run(Boot.java:90)
        at com.thoughtworks.gocd.Boot.main(Boot.java:56)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at java.base/sun.security.validator.Validator.validate(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 46 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 51 common frames omitted

```
