### ISSUE TITLE
server stops resonding with java.nio.channels.ClosedSelectorException

### ISSUE THREAD

**Issue by mmb** [gocd/gocd#937]
Sometimes our GoCD server stops responding on the front-end (port 8153). The logs are filled with errors like this:

```
2015-03-06 10:25:17,047 ERROR [980961982@qtp-1710387865-19 - Acceptor0 SelectChannelConnector@0.0.0.0:8153] log:87 - EXCEPTION
java.nio.channels.ClosedSelectorException
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:84)
        at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:106)
        at org.mortbay.io.nio.SelectorManager$SelectSet.doSelect(SelectorManager.java:630)
        at org.mortbay.io.nio.SelectorManager.doSelect(SelectorManager.java:191)
        at org.mortbay.jetty.nio.SelectChannelConnector.accept(SelectChannelConnector.java:124)
        at org.mortbay.jetty.AbstractConnector$Acceptor.run(AbstractConnector.java:707)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
2015-03-06 10:25:17,048 ERROR [980961982@qtp-1710387865-19 - Acceptor0 SelectChannelConnector@0.0.0.0:8153] log:87 - EXCEPTION
java.nio.channels.ClosedSelectorException
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:84)
        at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:106)
        at org.mortbay.io.nio.SelectorManager$SelectSet.doSelect(SelectorManager.java:630)
        at org.mortbay.io.nio.SelectorManager.doSelect(SelectorManager.java:191)
        at org.mortbay.jetty.nio.SelectChannelConnector.accept(SelectChannelConnector.java:124)
        at org.mortbay.jetty.AbstractConnector$Acceptor.run(AbstractConnector.java:707)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
2015-03-06 10:25:17,048 ERROR [980961982@qtp-1710387865-19 - Acceptor0 SelectChannelConnector@0.0.0.0:8153] log:87 - EXCEPTION
java.nio.channels.ClosedSelectorException
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:84)
        at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:106)
        at org.mortbay.io.nio.SelectorManager$SelectSet.doSelect(SelectorManager.java:630)
        at org.mortbay.io.nio.SelectorManager.doSelect(SelectorManager.java:191)
        at org.mortbay.jetty.nio.SelectChannelConnector.accept(SelectChannelConnector.java:124)
        at org.mortbay.jetty.AbstractConnector$Acceptor.run(AbstractConnector.java:707)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

Restarting the server makes the problem go away.

**Comment by srinivasupadhya** [comment]
looks related - http://jira.codehaus.org/browse/JETTY-1418
hopefully https://github.com/gocd/gocd/issues/400 should fix this?

**Comment by arvindsv** [comment]
Jetty has been upgraded. Shouldn't be happening.
