### ISSUE TITLE
Repoquery error while polling

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#95]
## Description

The following error seems to happen when Go Server is running as jar. And user logs off.
Things seem to become normal again after user logs in again.

``` gmail_default""="" style="" color:="" rgb(34,="" 34,="" 34);="" font-family:="" arial,="" sans-serif;="" font-size:="" 13px;""=""
java.lang.RuntimeException: Error while querying repository with path 'file:///home/srinivas/Documents/repos/yum-repo-2' and package spec 'go-agent*'. Error Message: error: rpmdb: Thread/process 17311/140715759941376 failed: Thread died in Berkeley DB library

error: db5 error(-30973) from dbenv->failchk: DB_RUNRECOVERY: Fatal error, run database recovery

error: cannot open Packages index using db5 -  (-30973)

error: cannot open Packages database in /home/srinivas/.rpmdb

Traceback (most recent call last):

  File "/usr/bin/repoquery", line 867, in <module>

    main(sys.argv)

  File "/usr/bin/repoquery", line 779, in main

    repoq.doConfigSetup(debuglevel=initnoise, init_plugins=opts.plugins)

  File "/usr/lib/pymodules/python2.7/yum/__init__.py", line 199, in doConfigSetup

    return self.conf

  File "/usr/lib/pymodules/python2.7/yum/__init__.py", line 723, in <lambda>

    conf = property(fget=lambda self: self._getConfig(),

  File "/usr/lib/pymodules/python2.7/yum/__init__.py", line 249, in _getConfig

    startupconf = config.readStartupConfig(fn, root)

  File "/usr/lib/pymodules/python2.7/yum/config.py", line 807, in readStartupConfig

    startupconf.releasever = _getsysver(startupconf.installroot, startupconf.distroverpkg)

  File "/usr/lib/pymodules/python2.7/yum/config.py", line 914, in _getsysver

    idx = ts.dbMatch('provides', distroverpkg)

_rpm.error: rpmdb open failed

at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:259)

at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:193)

at com.thoughtworks.go.plugin.infra.DefaultPluginManager.doOn(DefaultPluginManager.java:64)

at com.thoughtworks.cruise.server.service.materials.PackageMaterialPoller.getModifications(PackageMaterialPoller.java:65)

at com.thoughtworks.cruise.server.service.materials.PackageMaterialPoller.modificationsSince(PackageMaterialPoller.java:61)

at com.thoughtworks.cruise.server.service.materials.PackageMaterialPoller.modificationsSince(PackageMaterialPoller.java:28)

at com.thoughtworks.cruise.server.service.MaterialService.modificationsSince(MaterialService.java:95)

at com.thoughtworks.cruise.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:36)

at com.thoughtworks.cruise.server.materials.PackageMaterialUpdater.insertLatestOrNewModifications(PackageMaterialUpdater.java:45)

at com.thoughtworks.cruise.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:134)

at com.thoughtworks.cruise.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:126)

at com.thoughtworks.cruise.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:90)

at com.thoughtworks.cruise.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:8)

at com.thoughtworks.cruise.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:37)

at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)

at com.thoughtworks.cruise.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:33)

at com.thoughtworks.cruise.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:87)

at com.thoughtworks.cruise.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:27)

at com.thoughtworks.cruise.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:12)

at com.thoughtworks.cruise.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:49)

at com.thoughtworks.cruise.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:34)

at java.lang.Thread.run(Thread.java:722)

Caused by: java.lang.RuntimeException: Error while querying repository with path 'file:///home/srinivas/Documents/repos/yum-repo-2' and package spec 'go-agent*'. Error Message: error: rpmdb: Thread/process 17311/140715759941376 failed: Thread died in Berkeley DB library

error: db5 error(-30973) from dbenv->failchk: DB_RUNRECOVERY: Fatal error, run database recovery

error: cannot open Packages index using db5 -  (-30973)

error: cannot open Packages database in /home/srinivas/.rpmdb

Traceback (most recent call last):

  File "/usr/bin/repoquery", line 867, in <module>

    main(sys.argv)

  File "/usr/bin/repoquery", line 779, in main

    repoq.doConfigSetup(debuglevel=initnoise, init_plugins=opts.plugins)

  File "/usr/lib/pymodules/python2.7/yum/__init__.py", line 199, in doConfigSetup

    return self.conf

  File "/usr/lib/pymodules/python2.7/yum/__init__.py", line 723, in <lambda>

    conf = property(fget=lambda self: self._getConfig(),

  File "/usr/lib/pymodules/python2.7/yum/__init__.py", line 249, in _getConfig

    startupconf = config.readStartupConfig(fn, root)

  File "/usr/lib/pymodules/python2.7/yum/config.py", line 807, in readStartupConfig

    startupconf.releasever = _getsysver(startupconf.installroot, startupconf.distroverpkg)

  File "/usr/lib/pymodules/python2.7/yum/config.py", line 914, in _getsysver

    idx = ts.dbMatch('provides', distroverpkg)

_rpm.error: rpmdb open failed

at com.tw.go.plugin.material.artifactrepository.yum.exec.command.RepoQueryCommand.execute(Unknown Source)

at com.tw.go.plugin.material.artifactrepository.yum.exec.YumRepositoryPoller.executeRepoQuery(Unknown Source)

at com.tw.go.plugin.material.artifactrepository.yum.exec.YumRepositoryPoller.getLatestRevision(Unknown Source)

at com.tw.go.plugin.material.artifactrepository.yum.exec.YumRepositoryPoller.latestModificationSince(Unknown Source)

at com.thoughtworks.cruise.server.service.materials.PackageMaterialPoller$2.execute(PackageMaterialPoller.java:58)

at com.thoughtworks.cruise.server.service.materials.PackageMaterialPoller$2.execute(PackageMaterialPoller.java:50)

at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:257)

... 21 more
```

**Comment by arvindsv** [comment]
repoquery itself has to be replaced with dnf. Closing this.
