### ISSUE TITLE
SCM extension point - UI issues

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#975]
1) The server side validation errors show up twice on UI

![scm-validation-errors](https://cloud.githubusercontent.com/assets/6175869/6777184/17953e54-d16d-11e4-8f2b-96bccb4c105c.png)

2) Sometimes the edit of material opens a different screen like follows -

![scm-edit-material-error](https://cloud.githubusercontent.com/assets/6175869/6796624/9e50538e-d21c-11e4-9610-2180b6f5deb2.png)

Stack trace -

```
2015-03-24 11:48:22,465  WARN [1214265572@qtp-963992883-8] Rails:? - Could not load 'material', rendering failure /var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/app/controllers/admin_controller.rb:41:in `inject'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/app/controllers/admin_controller.rb:41:in `assert_loaded'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/app/controllers/admin_controller.rb:66:in `assert_load'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/app/controllers/admin/materials/pluggable_scm_controller.rb:60:in `edit'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/base.rb:189:in `process_action'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/callbacks.rb:18:in `process_action'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:496:in `_run__172116320__process_action__callbacks'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/lib/go-server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/rails.new/vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/callbacks.rb:17:in `process_action'
2015-03-24 11:48:22,490 FATAL [1214265572@qtp-963992883-8] Rails:? -
AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
  app/controllers/admin/materials/pluggable_scm_controller.rb:62:in `edit'
```

**Comment by srinivasupadhya** [comment]
1 is pending.
