### ISSUE TITLE
stacktrace from go-server logs

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#998]
```
015-03-30 21:19:04,330  WARN [47230934@qtp-1055945557-131] Stage:395 - Expected stage [StageIdentifier[acceptance, 354, 15.1.0.402-6c6e0f388f6e2ab932f2c6f3c1cfbc0cfce0d54a, twist-priority, 1]] to have no state, but was Failed
java.lang.Exception
        at com.thoughtworks.go.domain.Stage.building(Stage.java:395)
        at com.thoughtworks.go.server.service.StageService$3.doInTransaction(StageService.java:220)
        at com.thoughtworks.go.server.transaction.TransactionTemplate$2.doInTransaction(TransactionTemplate.java:39)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
        at com.thoughtworks.go.server.service.StageService.save(StageService.java:218)
        at com.thoughtworks.go.server.service.ScheduleService$1.doInTransaction(ScheduleService.java:259)
        at com.thoughtworks.go.server.transaction.TransactionTemplate$2.doInTransaction(TransactionTemplate.java:39)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
        at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
        at com.thoughtworks.go.server.service.ScheduleService.scheduleStage(ScheduleService.java:240)
        at com.thoughtworks.go.server.service.ScheduleService.internalRerun(ScheduleService.java:236)
        at com.thoughtworks.go.server.service.ScheduleService.lockAndRerunStage(ScheduleService.java:305)
        at com.thoughtworks.go.server.service.ScheduleService.rerunJobs(ScheduleService.java:324)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:485)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:340)
...
```

**Comment by arvindsv** [comment]
Is this related to #1000?

**Comment by arvindsv** [comment]
Closing. Have no more info.
