### ISSUE TITLE
pipeline label resolution failure

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#999]
causes pipeline schedule failures

```
java.lang.IllegalArgumentException: named capturing group is missing trailing '}'
    at java.util.regex.Matcher.appendReplacement(Matcher.java:792)
    at com.thoughtworks.go.domain.label.PipelineLabel.replaceRevisionsInLabel(PipelineLabel.java:52)
    at com.thoughtworks.go.domain.label.PipelineLabel.updateLabel(PipelineLabel.java:79)
    at com.thoughtworks.go.domain.Pipeline.updateLabel(Pipeline.java:156)
    at com.thoughtworks.go.domain.Pipeline.updateCounter(Pipeline.java:150)
    at com.thoughtworks.go.server.service.PipelineService.updateCounter(PipelineService.java:118)
    at com.thoughtworks.go.server.service.PipelineService.access$000(PipelineService.java:45)
    at com.thoughtworks.go.server.service.PipelineService$1.doInTransaction(PipelineService.java:101)
    at com.thoughtworks.go.server.transaction.TransactionTemplate$2.doInTransaction(TransactionTemplate.java:39)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
    at com.thoughtworks.go.server.service.PipelineService.save(PipelineService.java:96)
    at com.thoughtworks.go.server.service.PipelineScheduleQueue$1.doInTransaction(PipelineScheduleQueue.java:141)
    at com.thoughtworks.go.server.transaction.TransactionTemplate$2.doInTransaction(TransactionTemplate.java:39)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
    at com.thoughtworks.go.server.service.PipelineScheduleQueue.createPipeline(PipelineScheduleQueue.java:129)
    at com.thoughtworks.go.server.service.ScheduleService.schedulePipeline(ScheduleService.java:197)
    at com.thoughtworks.go.server.service.ScheduleService.autoSchedulePipelinesFromRequestBuffer(ScheduleService.java:178)
    at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
    at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
    at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
    at com.thoughtworks.go.timer.ModeAwareMethodInvokingTimerTaskFactoryBean$1.run(ModeAwareMethodInvokingTimerTaskFactoryBean.java:43)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```

**Comment by arvindsv** [comment]
Are these related to #1000?
